### ISSUE TITLE
Semantic information for Database.denotations

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1015]
Follow up of #822. Currently it's possible to resolve a few names in Database.sugars but not in Database.denotations. It would be nice if for example it was possible to attribute references in Denotation.info

**Comment by xeno-by** [comment]
One thing that I'd like to implement here is making `Denotation.info` strings parseable. For that, we'll need to introduce `Type.Method` that can express dependent method types. This is going to be a new AST node that will need a `checkParent` check that makes sure that it doesn't appear in normal programs.

**Comment by olafurpg** [comment]
Related https://github.com/scalacenter/scalafix/issues/254 scalafix ExplicitReturnTypes uses Denotation.info to insert the explicit types, in some cases the types are not fully qualified causing the rewrite to insert false names (e.g., Long when java.lang.Long should be inserted)
