### ISSUE TITLE
Prepare changelog for v2.0

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1020]

**Comment by olafurpg** [comment]
I started working on this here https://github.com/scalameta/scalameta/compare/master...olafurpg:changelog-2.0?expand=1

**Comment by ShaneDelmore** [comment]
@olafurpg Line 33 of https://github.com/scalameta/scalameta/compare/master...olafurpg:changelog-2.0?expand=1#diff-f6d2964a2f939f972e8216efe4919ecdR33
/s/compiaton/compilation

**Comment by olafurpg** [comment]
Thanks @ShaneDelmore. Fixed.

In addition to the changelog, I took the liberty to update our landing page with more up-to-date information https://github.com/scalameta/scalameta/compare/master...olafurpg:website?expand=1

**Comment by ShaneDelmore** [comment]
@olafurpg Looks good. Caught one more typo in the latest version, /s/instead querying/instead of querying

**Comment by olafurpg** [comment]
Fixed in https://github.com/scalameta/scalameta/pull/1081
