### ISSUE TITLE
Issues running scalahost on community build

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1026]
```

[warn] failed to generate semanticdb for /home/geirsson/megarepos/scala-java8-compat/src/test/scala/scala/compat/java8/FunctionConvertersTest.scala:
[warn] java.lang.RuntimeException: ambiguous mend src/test/scala/scala/compat/java8/FunctionConvertersTest.scala@19103..19103  src/test/scala/scala/compat/java8/FunctionConvertersTest.scala@19080..19103 test_LongBinaryOperator
[warn]  at scala.sys.package$.error(package.scala:27)
[warn]  at scala.meta.internal.semantic.AttributesOps$XtensionCompilationUnitAttributes$$anonfun$toAttributes$1$traverser$3$.indexName(AttributesOps.scala:65)




    Jul 12, 2017 10:19:59 PM com.google.protobuf.CodedOutputStream inefficientWriteStringNoTag
WARNING: Converting ill-formed UTF-16. Your Protocol Buffer will not round trip correctly!
com.google.protobuf.Utf8$UnpairedSurrogateException: Unpaired surrogate at index 6 of 9
        at com.google.protobuf.Utf8$UnsafeProcessor.encodeUtf8(Utf8.java:1227)
        at com.google.protobuf.Utf8.encode(Utf8.java:304)

```

**Comment by xeno-by** [comment]
1) What's the SHA of the commit that you take `FunctionConvertersTest.scala` from?
2) Where does this error come from?

**Comment by olafurpg** [comment]
1. Here is the link : https://github.com/scala/scala-java8-compat/blob/2030bfab679932355964b92e49324c6b384bc6d0/src/test/scala/scala/compat/java8/FunctionConvertersTest.scala
2. the warning is emitted by protobuf-java without escalating an exception, the logs don't show which file is causing this. I propose we wait and see if a repro pops up later.

**Comment by xeno-by** [comment]
Is this still relevant?

**Comment by olafurpg** [comment]
I didn't notice those issues when I ran the last time to build this corpus here https://drive.google.com/open?id=0B5BBsTPBxGcMemRsMjBpUDNYM1E I may have missed it though, I should persist the sbt logs for separate analysis of errors. We're good to close this for now.

**Comment by jameskoch** [comment]
I hit this upgrading a large codebase w/ scala 2.11.11, scalafix 0.9.4 and scalameta 4.1.6.

Caused by this awful procedure syntax:

```
object Test {
  def foo{}
}
```

Not lack of space between method name and body.
