### ISSUE TITLE
PlatformPathIO.js should work in the browser

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1031]
I upgraded to meta v2 in metadoc and hit on this issue

```
TypeError: Cannot read property 'sep' of undefined
    at $c_s_meta_internal_io_PlatformPathIO$.fileSeparatorChar__C (metadoc-js-fastopt-bundle.js:21618)
    at $c_s_meta_internal_io_PathIO$.fromUnix__T__T (metadoc-js-fastopt-bundle.js:21533)
```

The problem is that PlatformPathIO assumes a Node.js environment. In this case, we should fallback to `/`, but more generally we should maybe add some tests reading semanticdb bytes in a non-nodejs environment if that's possible

**Comment by jonas** [comment]
It would be nice to also get rid of this cludge: https://github.com/scalameta/metadoc/blob/a8e82c1c78f68503dea627da6ea5e1c9ece50d2b/metadoc-js/src/main/scala/scala/meta/internal/io/JSIO.scala

**Comment by olafurpg** [comment]
Yes, do you have an idea how to gracefully fallback in browser?

**Comment by olafurpg** [comment]
`@JSImport` seems to support a fallback name https://github.com/scala-js/scala-js/blob/06ddd281863c96183cf2037cc66bcd942bb90aed/library/src/main/scala/scala/scalajs/js/annotation/JSImport.scala#L68 I'm gonna experiment with implementing the node classes for the browser as fallback

**Comment by jonas** [comment]
It sounds weird that would force projects that want use Scala meta in the browser to disable modules altogether.

I experimented a bit with loading the required node modules on demand. Would that be a valid solution also? I'm also curious why jsshell was chosen for providing the CWD over https://nodejs.org/api/process.html#process_process_cwd which is a core API.

**Comment by olafurpg** [comment]
> I experimented a bit with loading the required node modules on demand. Would that be a valid solution also? 

That is totally valid. Would you be able to send a PR? I'm not happy with the solution in this PR.

>  jsshell was chosen for providing the CWD 

I've been meaning to move to CWD in the core api, it was the first facade I did and a few SO answers said there was no way to get CWD in the node api and I know 0 about js so I thought I needed a library.

**Comment by jonas** [comment]
Yes, I'd be happy to send a PR. And will also add some JS IO tests
