### ISSUE TITLE
Parser fails when inline keyword starts template

### ISSUE THREAD

**Issue by fommil** [scalameta/scalameta#1038]
copy/paste from https://github.com/scalameta/scalafmt/issues/999

in this exact version of our project https://github.com/fommil/stalagmite/tree/552944186524c72ef74a997a4e21c8ff6a6509d4

`sbt fmt` outputs

```
[warn] /home/fommil/Projects/stalagmite/src/main/scala/fommil/stalagmite/DataImpl.scala:158: error: ; expected but def found
[warn] inline def apply(defn: Any): Any = meta {
[warn]          ^
```

on valid code https://github.com/fommil/stalagmite/blob/552944186524c72ef74a997a4e21c8ff6a6509d4/src/main/scala/fommil/stalagmite/DataImpl.scala#L158

**Comment by DavidDudson** [comment]
I went to upgrade elysium the other day and encountered this. I was hunting around scalameta/paradise thinking the regression was there. Looks like it’s not. What version of meta was the last one that parsed inline code correctly?

**Comment by olafurpg** [comment]
The issue only appears when `inline` is the first statement in the enclosing template

```scala
@ import $ivy.`org.scalameta::scalameta:2.0.0-M1`, scala.meta._
@ dialects.Paradise212("""object a {
    val x = 2
    inline def foo = 2
  }
  """).parse[Source].get
res4: Source = Source(...) // OK
@ dialects.Paradise212("""object a {
    inline def foo = 2
  }
  """).parse[Source].get
<input>:2: error: ; expected but def found
inline def foo = 2
         ^
```

**Comment by vovapolu** [comment]
Is it a bug in parser or what? Adding a dummy statement is quite controversial solution :)

**Comment by olafurpg** [comment]
Yes this is a bug in the parser, the dummy statement is a workaround for this bug

**Comment by DavidDudson** [comment]
Does this affect quasiquotes as well?? Or just the parser? (On my phone so I cannot check)

**Comment by olafurpg** [comment]
Yes, quasiquotes use the same parser.

**Comment by DavidDudson** [comment]
It’s definitely the bug stopping the elysium upgrade then. I generate inline defs with quasiquotes.

**Comment by gabro** [comment]
Tracking this here: https://github.com/scalameta/scalameta/issues/1776
