### ISSUE TITLE
Composing macro annotations and then accessing the generated companion object fails at runtime with NoClassDefFoundError

### ISSUE THREAD

**Issue by zliu41** [scalameta/scalameta#1046]
Suppose I have an annotation, `@first`, which adds a companion object to a trait:

```scala
class first extends scala.annotation.StaticAnnotation {
  inline def apply(defn: Any): Any = meta {
    val q"..$mods trait $tname { ..$stats }" = defn
    q"""..$mods trait $tname {
      ..$stats
    }
    object ${Term.Name(tname.value)}
    """
  }
}
```

And another annotation, `@second`, that is a no-op:

```scala
class second extends scala.annotation.StaticAnnotation {
  inline def apply(defn: Any): Any = meta {
    defn match {
      case Term.Block(Seq(cls, companion)) =>
        q"""
           $cls
           $companion
         """
    }
  }
}
```

Composing the two annotations and attempting to access the companion object:

```scala
@first
@second
trait Hello

object Main extends App {
  println(Hello)
}
```

compiles, but fails at runtime:

```Exception in thread "main" java.lang.NoClassDefFoundError: foo/Hello$```

If I make the trait wrapped in an object instead of a top-level trait:

```scala
object Wrapper {
  @first
  @second
  trait Hello
}
```

Then it works:

```foo.Wrapper$Hello$@5649fd9b```

I'm using scalameta 1.8.0, paradise 3.0.0-M9, scala 2.11.11.

**Comment by xeno-by** [comment]
Resubmitted as https://github.com/scalameta/paradise/issues/227.

**Comment by exoego** [comment]
https://github.com/scalameta/paradise is archived and issues seems removed.
Could someone know the status of this issue ?
