### ISSUE TITLE
Unified compilation scope.

### ISSUE THREAD

**Issue by cuzfrog** [scalameta/scalameta#1048]
Currently, a given single `object` will be instantiated every time per annotation, like:
```scala
private object MacroUtil {
  println(this.toString)
  ...
}

final class AnnotationA extends StaticAnnotation {
  inline def apply(defn: Any): Any = meta {
    MacroUtil(...)
  }
}

final class AnnotationB extends StaticAnnotation {
  inline def apply(defn: Any): Any = meta {
    MacroUtil(...)
  }
}
```
`MacroUtil` will be created twice during compilation:
```
com.github.cuzfrog.scmd.MacroUtil$@6e022c0b
com.github.cuzfrog.scmd.MacroUtil$@48d79fed
```

This makes communication between two annotated classes hard. Vintage macros could share same object scope: https://stackoverflow.com/questions/30143900/communicate-between-two-macros.

**Comment by xeno-by** [comment]
Resubmitted as https://github.com/scalameta/paradise/issues/225.
