### ISSUE TITLE
Macro expansion doesn't insert backticks around non-alphabetical Term.Name

### ISSUE THREAD

**Issue by vovapolu** [scalameta/scalameta#1049]
This annotation 
```scala
class annotation extends scala.annotation.StaticAnnotation {
  inline def apply(defn: Any): Any = meta {
    Term.Block(Seq(q"""class A {
        def func(${Term.Name("bad_arg[]")}: Int) = 1
      }
   """))
  }
}
``` 
produces the compilation error 
```code
[error] <macro>:2: ':' expected but '[' found.
[error]   class A { def func(bad_arg[]: Int) = 1 }
[error]                             ^
```
Although when I test macro expansion by parsing the scala code and then comparing it with generated `Tree`, it works almost correctly (pretty-printer doesn't print backticks sometimes).

**Comment by gabro** [comment]
I not entirely sure, but this seems a rather easy fix to apply here: https://github.com/scalameta/scalameta/blob/master/scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala#L122

**Comment by xeno-by** [comment]
Resubmitted as https://github.com/scalameta/paradise/issues/224.
