### ISSUE TITLE
Import scala.collection.immutable._ explicitly is necessary for Term.Param

### ISSUE THREAD

**Issue by a-nigredo** [scalameta/scalameta#1053]
In order to create Term.Param user has to import scala.collection.immutable._ explicitly to macro annotation file.
Step to reproduce:
Try to create  Term.Param e.g.
` Term.Param(Seq(Mod.Implicit()), Term.Name("name"), None, None)`
Scalac complains:
`[error]  found   : Seq[scala.meta.Type.Name]`
` [error]  required: scala.collection.immutable.Seq[scala.meta.Type.Name]`

**Comment by xeno-by** [comment]
This is fixed in 2.0.0-M1, where all collections are actually lists.
