### ISSUE TITLE
No source root found with macro annotations and scoverage

### ISSUE THREAD

**Issue by etorreborre** [scalameta/scalameta#1060]
Where macro annotations are used scoverage reports:
```scala
No source root found for '/home/.../<macro>'
```

The current workaround is to add the following sbt setting:
```
coverageExcludedFiles := ".*macro.*"
```

**Comment by DavidDudson** [comment]
Thus is a scalameta/paradise issue.

https://github.com/scalameta/paradise/issues/56

**Comment by etorreborre** [comment]
Thanks for the cleanup @DavidDudson
