### ISSUE TITLE
Naming for the generic portion of scalameta

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1064]
2.0.0-M2 factors out semanticdb handling into a new project that we tentatively call `langmeta` with the maven group name `org.langmeta` and the package name `lang.meta`. Let's discuss and finalize the naming before the final release of 2.0.0.

**Comment by olafurpg** [comment]
I personally prefer the name `langmeta` over `lang.meta`. Other than that, I like `org.langmeta` as the group name. You should buy the domain asap @xeno-by 😸

**Comment by xeno-by** [comment]
Domain bought. Let's discuss naming on Thursday.

**Comment by xeno-by** [comment]
Sonatype issue: https://issues.sonatype.org/browse/OSSRH-34039

**Comment by xeno-by** [comment]
I agree with `org.langmeta`. @olafurpg, can you please modify the build to publish to `org.langmeta` and the langmeta projects to use the new namespace?

**Comment by olafurpg** [comment]
I've moved lang.meta to org.langmeta in #1094 . `scalafix replace:lang.meta/org.langmeta` did most of the work, the only case where it failed was for the `lang.meta` package object itself since it did not rename the `lang` package to `org`, which is understandable.

**Comment by olafurpg** [comment]
Fixed in #1094
