### ISSUE TITLE
Get rid of megaCache

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1068]
- https://github.com/lucidsoftware/neo-sbt-scalafmt/blob/e79e0fc76c8d6416b891f23597ce4c7528bed5e1/scalafmt-impl/src/shared/main/scala/com/lucidchart/scalafmt/impl/Scalafmtter.scala#L24
- #778 
- `Input.read; Files.write(Input); Input.read // stale!`

It would be really nice to get rid of this global mutable cache.

**Comment by olafurpg** [comment]
I propose we leave this out of the v2.0 milestone to unblock a release.

**Comment by xeno-by** [comment]
👍

**Comment by olafurpg** [comment]
I have a proposal for how to solve this without breaking existing code, instead of always using the global megaCache, https://github.com/scalameta/scalameta/blob/1af15eb96c30c437d1b4aa57aca1740a36ed44a4/scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala#L13

we can make it a parameter to `ScalametaTokenizer`. We could then make it easier for applications to construct parsers/tokenizers with custom megaCache. For example, in the case of scalafmt/scalafix, it would be little trouble for me change from `InputLike.parse[T]` to a slightly more verbose syntax that uses custom megaCache. Something in this direction would be enough to solve my problems.

**Comment by netvl** [comment]
Copied from gitter (per @olafurpg request):

> I'm currently playing with scalameta and encountered quite a strange thing.
> 
> ```scala
> scala> res31.syntax
> res42: String = override val key: String = "teradata"
> 
> scala> res31.structure
> res43: String = Defn.Def(List(Mod.Override()), Term.Name("key"), Nil, Nil, Some(Type.Name("String")), Lit.String("teradata"))
> 
> scala> Defn.Def(List(Mod.Override()), Term.Name("key"), Nil, Nil, Some(Type.Name("String")), Lit.String("teradata"))
> res44: scala.meta.Defn.Def = override def key: String = "teradata"
> 
> scala> res31
> res45: scala.meta.Stat = override val key: String = "teradata"
> ```
> 
> The next to last expression is that I just copied res43 and pasted it to repl. How is it possible that a statement is printed as val (and it is actually loaded from a file where it is a val), but its structure says it's a def?

> this is really strange - apparently I cannot reproduce it anymore! it now shows correct structure if I execute exactly the same code in sbt's consoleProject repl.
> 
> The thing is, initially the file with the aforementioned val did indeed contain override def instead of override val. However, I changed it to val, and even restarted the repl before trying to parse the files again, and got these strange results. But now I also restarted the SBT process. Maybe there is some jvm-global cache which results into this?
