### ISSUE TITLE
Repl examples on the website are weird

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1071]
<img width="828" alt="screen shot 2017-08-17 at 15 43 37" src="https://user-images.githubusercontent.com/1408093/29415379-2a14af38-8363-11e7-84d9-555e172ad39b.png">

http://scalameta.org/

Reported by @a-nigredo on Gitter.

**Comment by xeno-by** [comment]
Fixed by republishing manually, making sure I use 2.11.11.
