### ISSUE TITLE
semanticdb-scalac + scalamacros/paradise break Scaladoc generation

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1072]
At the following commit
https://github.com/scalacenter/scalafix/pull/291/commits/9798839741cb4c6180ea191c94f2738e12dbf88d
I have the scalahost compiler plugin enabled in the scalafix repo

- `coreJVM/compile` is OK
- `coreJVM/doc` fails, build failures https://travis-ci.org/scalacenter/scalafix/jobs/265876123#L698
```scala
[error] /home/travis/build/scalacenter/scalafix/scalafix-core/shared/src/main/scala/scalafix/internal/patch/ImportPatchOps.scala:194: don't know how to check whether scala.meta.tokens.Token is scalafix.util.Newline
[error]               val isNewline = x.is[Newline]
[error]                                   ^
[error] /home/travis/build/scalacenter/scalafix/scalafix-core/shared/src/main/scala/scalafix/internal/rewrite/ExplicitReturnTypes.scala:88: don't know how to check whether scala.meta.tokens.Token is scalafix.util.Whitespace
[error]           !x.is[Token.Equals] && !x.is[Whitespace])
[error]                                       ^
[error] /home/travis/build/scalacenter/scalafix/scalafix-core/shared/src/main/scala/scalafix/util/TokenClasses.scala:11: don't know how to check whether scala.meta.tokens.Token is scalafix.util.Newline
[error]     token.is[Space] || token.is[Tab] || token.is[Newline] || token.is[FF]
[error]                                                 ^
[error] /home/travis/build/scalacenter/scalafix/scalafix-core/shared/src/main/scala/scalafix/util/TokenClasses.scala:19: don't know how to check whether scala.meta.tokens.Token is scalafix.util.Whitespace
[error]     token.is[Whitespace] || token.is[Comment]
[error]             ^
```

The problems seems related to scalamacros/paradise, the following macro annotations in the same projects are not expanded under scaladoc https://github.com/scalacenter/scalafix/blob/016d01cc0286f555bad3ecd898a23ade637786d4/scalafix-core/shared/src/main/scala/scalafix/util/TokenClasses.scala#L7

@xeno-by could analyzer hijacking be conflicting with scalamacros/paradise analyzer hackery under scaladocglobal?

Disabling semanticdb-scalac fixes the problem.

**Comment by olafurpg** [comment]
This is increasingly annoying since it's blocking me from using scalafix for development in both the scalameta and scalafix repos. Any idea what might be causing this @xeno-by ?

**Comment by xeno-by** [comment]
Does the issue only occur when paradise is enabled?

**Comment by olafurpg** [comment]
Yes, scalamacros/paradise annotations are not expanded causing compile errors.

**Comment by xeno-by** [comment]
Scalamacros/paradise doesn't do any analyzer hijacking, at least not on Scala 2.11+. Instead, it installs so-called analyzer and macro plugins: https://github.com/scalamacros/paradise/blob/2.12.3/plugin/src/main/scala/org/scalamacros/paradise/Plugin.scala#L14-L15. 

If I were to guess, I'd say that semanticdb hijacking replaces the analyzer with the paradise plugins installed with the new analyzer that doesn't have these plugins anymore. Why this happens only under scaladoc - that's not immediately obvious.

**Comment by olafurpg** [comment]
I opened https://github.com/scalameta/scalameta/pull/1095 to fix this.
