### ISSUE TITLE
Ability to query names in scope 

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1075]
Currently, it's not possible to query which symbols are in scope at a particular location. This makes it hard to implement several important scalafix rewrites such as ExplicitReturnTypes. Example:

```scala
package test
trait Buz {
  object shapeless {
    class Foo
    val x = new Foo
  }
}
object Box extends Buz {
  implicit val buz = _root_.shapeless.HNil
  // scalafix ExplicitReturnTypes output
  implicit val buz: shapeless.HNil = _root_.shapeless.HNil // Compile error, <<shapeless>> resolves to Buz.shapeless
}
```

Related work: There was made an attempt to fix this in https://github.com/scalacenter/scalafix/pull/42 using the scalafix compiler plugin.

Workaround: fully qualify inserted names with _root_.

**Comment by xeno-by** [comment]
As we discussed with @olafurpg right now, there are two possibilities here: 1) convert the entire universe to semanticdb and then do name resolution from there, 2) store adhoc information about scopes in every semanticdb.

While I personally believe that 1 is within reach, it is research that will take at least weeks to materialize. For now, I think 2 is the most reasonable thing to do, especially given that we can immediately reap non-trivial benefits such as ExplicitReturnTypes that doesn't suck.

**Comment by xeno-by** [comment]
@olafurpg suggested to sidestep this issue altogether by emitting denotations in a correctly shortened form. Our compiler plugin has enough information to pull this off, so let's try this workaround first.

**Comment by olafurpg** [comment]
I am going to reopen this issue since even if we are able to sidestep the problem for ExplicitResultTyeps, there are many other useful scalafix rules that require full scoping information. Example
- expand wildcard imports
- renaming symbols
- creating fresh names for new definitions

**Comment by ShaneDelmore** [comment]
I have also wanted this information many times for debugging, especially implicit resolution.  Seems like a nice add.

**Comment by olafurpg** [comment]
I opened #1148 to address this issue.

**Comment by olafurpg** [comment]
Now that #1148 has been merged it should be possible to build the lexical scope for each position from a semanticdb.

**Comment by olafurpg** [comment]
I have worked on this ticket for the past month in the scalafix repo and made nice progress. We are currently blocked by work on metacp in order to be able to query `members` from a symbol, track https://github.com/scalameta/scalameta/projects/1?card_filter_query=label%3Ametacp for updates on that front.

**Comment by olafurpg** [comment]
Quick update, I have a WIP implementation that is able to run ExplicitResultTypes on akka-actor and slick with short names. There are still quite a few rough edges, but I'm hopeful this ticket will be resolved in the next few weeks 🎉

**Comment by tgodzik** [comment]
This seems to have been implemented using the presentation compiler.

I am taking a look at some of the older issues and closing the ones that have no chance of anyone working on them. If I am wrong we can for sure reopen, but I would focus on bugfixes to the current functionalities.
