### ISSUE TITLE
Better name for "Sugars"

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1077]
Following feedback from a discussion with my colleagues at the Scala Center. The name "sugar" (see http://scalameta.org/tutorial/#Sugars) may be confusing for many since it does not include traditional Scala syntax sugar 

- for comprehensions
- `val Pattern(a, b) = foo`

Instead, scalameta sugars are typically synthetic trees generated during typer

- inferred types via denotations
- implicit args
- implicit conversions
- `.apply`/`.unapply` (arguably sugar, but questionably "syntax sugar" since they require typing information).

I propose we use another name than "sugars" that carries less baggage. Some potential candidates:

-  Invisibles: since they are not visible in the source file
-  Hidden: since they're not strictly invisible, just not present in the source file

Feedback is very welcome, since I'm somewhat blinded by implementation details 

cc/ @ShaneDelmore @DavidDudson @gabro

**Comment by ShaneDelmore** [comment]
@olafurpg All of these usages look inferred to me but I could see how some people would say that implicit is not quite the same as inferred.  I would vote for something that hints that this is added by the compiler, not a part of user code.  How about one of these?

- Inferred
- Generated
- Typer

I would agree that I tend to think of sugars as purely syntactic operations and don’t immediately associate them with type inference or implicit search.

**Comment by xeno-by** [comment]
I like Invisible and Inferred. The latter is a stretch for `.apply/.unapply`, so I'd prefer the former.

**Comment by olafurpg** [comment]
I don't find Inferred a stretch for `.apply`. However, I'd like to keep this section generic enough to accommodate other stuff that's not inferred, for example macro expansions. No thoughts on "Hidden", I personally find it clearer than "Invisible" since they can be "seen". For example, `Input.Invisible` is less intuitive than `Input.Hidden` IMO.

**Comment by xeno-by** [comment]
To me, "hidden" sounds more like something that was in the source code, but then got omitted. In comparison, I understand "invisible" as something that is not in the source code, but can be exposed with special techniques. Looks like this all is very subjective. Wdyt @ShaneDelmore @DavidDudson?

**Comment by gabro** [comment]
I think `Synthetic` would capture the nature of this, but maybe it's too obscure?

**Comment by xeno-by** [comment]
Superseded by #1091.

**Comment by olafurpg** [comment]
FYI @gabro , we ended up going with `Synthetic`. Thanks a lot for suggesting it 😄

**Comment by olafurpg** [comment]
Massive renaming PR in #1094
