### ISSUE TITLE
Add matrix of supported/planned/not-intended features

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1080]
See https://github.com/scalameta/scalameta.github.com/pull/14

It would be nice to include a table in our website with something like

| Dialect | Syntax | Semantic |
| ------- | ------- | --------- |
| 2.10  .sbt files   | Yes | Yes* |
| 2.10    | Yes | Yes* |
| 2.11    | Yes | Yes |
| 2.12    | Yes | Yes |
| 2.12  .sbt files   | No | No |
| Dotty   | Partial | No |

Semantic api

| Feature | |
| -------- |- |
| Symbol at position | Yes |
| Type at definition | Yes |
| Type at term position | No |
| Type members | No |
| Inferred implicit arg | Yes |
| Inferred implicit conversion | Yes |
| Inferred `.apply`/`.unapply` | Yes |

**Comment by xeno-by** [comment]
Fixed in https://github.com/scalameta/tutorial/pull/27.
