### ISSUE TITLE
Fields that are added by annotation macro, cannot survive `publishLocal` if they are called explicitly.

### ISSUE THREAD

**Issue by cuzfrog** [scalameta/scalameta#1090]
that means before/during `publishLocal`,  macro expansion did not complete.

```scala
class add extends scala.annotation.StaticAnnotation {
  inline def apply(defn: Any): Any = meta {
    val q"object $name { ..$stats }" = defn
    q"object $name { def addedMethod():Unit = () }"
  }
}

@add
object A

A.addedMethod() //call explicitly.
```
code above will throw `addedMethod is not a member of A` during `publishLocal`.

A workaround is to create a dummy method that represents the macro-added method before macro expansion:
```scala
trait dummy{
  def addedMethod():Unit = ???
}
@add
object A extends dummy
```

**Comment by xeno-by** [comment]
Resubmitted as https://github.com/scalameta/paradise/issues/222.
