### ISSUE TITLE
Renamings in semanticdb.proto

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1091]
As discussed during the meeting today:
  * `pos` -> `position`
  * `denot` -> `Denotation`
  * `info` -> `signature`
  * `flags` -> We'll keep this one untouched for the time being
  * `Sugar` -> `Synthetic`
  * `sugars` -> `synthetics`
  * `Attribute` -> `File`
  * `is_binder` -> `is_definition`

**Comment by ShaneDelmore** [comment]
Looks like a productive meeting, these are all nice improvements to clarity.

**Comment by olafurpg** [comment]
How about we also rename `Denotation` to `Definition`?

**Comment by olafurpg** [comment]
I took the liberty to rename

- Attributes -> SourceFile (File conflicts with java.io.File, since we advocate `import scala.meta._` I think we should avoid common conflicts).
- Denotation -> Definition. I feel that definition is more approachable and self explanatory.
