### ISSUE TITLE
Configure Travis to publish nightlies

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1093]
We got rid of per-merge prerelease builds because Bintray didn't work well for us, but I still think that prerelease builds are a good idea. @olafurpg says it'll be easy to set up nightlies on Travis. Even though they aren't a full replacement, they are still much better than nothing. In the meanwhile, I'll check whether this is something that we at Twitter can help with.

**Comment by olafurpg** [comment]
I totally agree, just need to make sure we don't publish when no changes have happened in the last 24hrs. Removed the v2.0 milestone since this should not block a release.

**Comment by xeno-by** [comment]
@olafurpg This is already working, right?

**Comment by olafurpg** [comment]
This is already working.
