### ISSUE TITLE
Add Type.Method

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1099]
Currently, it's not possible to parse Denotation.signature into Type.Method. Scalafix currently works around this with string/regex hacks https://github.com/scalacenter/scalafix/blob/94bf7a4c087310091fa555517202f9f67601c9a2/scalafix-core/shared/src/main/scala/scalafix/internal/rewrite/ExplicitReturnTypes.scala#L63 These hacks break the resolved name positions from #1076 

I took a stab at fixing this myself in the parser but I seem to be missing some context according to the comment here https://github.com/scalameta/scalameta/blob/07007609987783724d32219fffcffd3eae25055c/scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L807

**Comment by xeno-by** [comment]
https://github.com/scalameta/scalameta/issues/902 will be necessary to support polymorphic methods.

**Comment by xeno-by** [comment]
Fixed in https://github.com/scalameta/scalameta/pull/1101.
