### ISSUE TITLE
Move scalameta/contrib to a separate repository

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1110]
As discussed during the meeting today, we're now pushing for limiting our issues to directly actionable items only. I've closed dozens of wishful-thinking tickets in the last several weeks, so now we're at an amazing 75 open issues (down from almost two hundred during the good old times).

While reviewing the remaining issues, I noticed that we have 18 contrib issues, many of which haven't been updated for a while and none of which are on our current roadmap.

I wouldn't like to close these issues, because they have serious potential to improve Scalameta without affecting binary compatibility (which will become a big deal for us after 2.0). Instead, I propose we move contrib to a different repository and migrate current contrib issues there. This will let the experiments evolve at their own pace without being limited by the stringent requirements of the main repository.

**Comment by olafurpg** [comment]
Given the increased focus on stability I think it's a good idea to move non-core functionality into a separate repo. It seems to be working well for circe, at least https://github.com/circe

 wdyt @DavidDudson?

**Comment by DavidDudson** [comment]
Sounds good to me
