### ISSUE TITLE
Migrate changelogs to GitHub release notes

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1111]
During today's meeting, @olafurpg suggested to use GitHub release notes instead of our own changelog/ folder with markdown files. The motivation for this change is to avoid non-standard approaches / tools as much as possible. I am convinced and fully support this idea.

**Comment by olafurpg** [comment]
Done. I've moved the changelogs to GitHub releases. v2.0.0 changelog is saved as a draft. I propose we keep the changelog/ directory with markdown files for at least a few more releases to preserve old links.

**Comment by olafurpg** [comment]
I propose we release v2.0.0 since RC3 seems to be working nicely for 5 days now without problems.

**Comment by xeno-by** [comment]
👍
