### ISSUE TITLE
Type.Param with Name.Anonymous is not supported in Dotty

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1119]
```scala
trait F[_]
```

results in
```scala
-- [E039] Syntax Error: foo.scala:1:8 ------------------------------------------
1 |trait F[_]
  |        ^
  |        an identifier expected, but '_' found

Explanation
===========

If you necessarily want to use '_' as identifier, you may put it in backticks.

```

**Comment by xeno-by** [comment]
What about type parameters of type parameters and type members?

**Comment by olafurpg** [comment]
This compiles fine:

```scala
trait a[G[_]] {
  type F[_]
}
```

The way I understand it is that `trait A[_]` in scalac creates a type with name `_`, and wildcards are invalid identifiers in dotty https://github.com/lampepfl/dotty/issues/3104#issuecomment-329142839 (which we should handle in the Dotty dialect too).
