### ISSUE TITLE
semanticdb-scalac silently disables scalamacros/paradise 

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1135]
Minimized repro https://github.com/olafurpg/inThisBuild/commit/56371fac9f2f24316c9002eb9d3a17274c62112f

Execute `sbt a/run`

```scala
[error] [E2] a/src/main/scala/a/A.scala
[error]      not enough arguments for method asJson: (implicit encoder: io.circe.Encoder[a.Bar])io.circe.Json.
[error]      Unspecified value parameter encoder.
[error]      L10:  println(Bar(13, "Qux").asJson)
[error]      L10:                         ^
[error] [E1] a/src/main/scala/a/A.scala
[error]      could not find implicit value for parameter encoder: io.circe.Encoder[a.Bar]
[error]      L10:  println(Bar(13, "Qux").asJson)
[error]      L10:                         ^
[error] a/src/main/scala/a/A.scala: L10 [E1], L10 [E2]
[error] (a/compile:compileIncremental) Compilation failed
```

Commenting out `addCompilerPlugin(semanticdb)` makes the program compile and run.

Originally reported by @ngbinh in https://gitter.im/scalacenter/scalafix?at=59e5e2d9b20c64242911e7d3

**Comment by olafurpg** [comment]
Possibly related https://github.com/scalameta/scalameta/issues/1072

**Comment by ngbinh** [comment]
Wondering if there is a work around for this? It is blocking me from using `scalafix` :(

**Comment by olafurpg** [comment]
There's no workaround for this issue yet @ngbinh :/ I will try to take a look later this week, it is indeed blocking many from using scalafix!

**Comment by olafurpg** [comment]
It seems that it matters in which order the plugins are loaded, if -Xplugin:semanticdb-scalac  comes before -Xplugin:paradise then I'm unable to reproduce the problem. I can only reproduce the problem when -Xplugin:paradise comes before -Xplugin:semanticdb-scalac. A workaround for this problem might be to reorder the `addCompilerPlugin(paradise)` statement so that it is evaluated latest. I have an idea how to fix this problem permanently.

**Comment by ngbinh** [comment]
ok, will try it out

**Comment by olafurpg** [comment]
Let me know if that helps @ngbinh You can validate the order of the plugins with `show compile:scalacOptions`

**Comment by olafurpg** [comment]
I have a pending fix for this problem 🎉

**Comment by ngbinh** [comment]
It would be a bit complicated for me because we add `addCompilerPlugin(paradise)` through an in house sbt plugin (so it's applied to all our projects) and `sbt-scalafix` through `addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.5.3")` so not sure how I can control the order

**Comment by olafurpg** [comment]
Something like this should do the trick
```scala
scalafixEnabled := false // sbt-scalafix does addCompilerPlugin behind the scenes if set to true
 addCompilerPlugin("org.scalameta" % "semanticdb-scalac" % "2.0.1" cross CrossVersion.full)
addCompilerPlugin(paradise)
scalacOptions += "-Yrangepos"
```

**Comment by olafurpg** [comment]
I plan to remove the automatic setup of `addCompilerPlugin` in sbt-scalafix and let users do it in 0.6 onwards https://github.com/scalacenter/scalafix/pull/419

**Comment by ngbinh** [comment]
ok, will try it out

**Comment by olafurpg** [comment]
Pending PR to fix this issue in #1143

**Comment by ngbinh** [comment]
Opps, I am blocked because we already upgraded to scala 2.12.4. Will downgrade and try this out

**Comment by olafurpg** [comment]
I'm working on adding 2.12.4 support, it's not an easy upgrade for us since many things have changed in typer since 2.12.3.

**Comment by olafurpg** [comment]
Pending PR adding 2.12.4 support https://github.com/scalameta/scalameta/pull/1144
