### ISSUE TITLE
Parser fails on valid `package name\n{` definition

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1136]
scalac parses the following input file 
```scala
package a

package object b
{
  object c
}

package d
{
  object e
}

```
while scalameta reports

```
<input>:8: error: { expected but \n found
package d
         ^
```

Changing to `package d {` fixes the error.

**Comment by kpbochenek** [comment]
Fixed with commit(Fix parsing package with leftbrace in newline) https://github.com/scalameta/scalameta/commit/7415a6fb595ac66ccc77e23fa852d950dc09ef40

Just checked that mentioned example parses properly now.
