### ISSUE TITLE
SBT command to configure the build before compiling

### ISSUE THREAD

**Issue by blorente** [scalameta/scalameta#1138]
It would be incredibly useful to have a custom sbt command to configure the project build settings and automatically prepare projects for compilation. Since it involves a relatively small number of steps, a series of commands passed to sbt after loading a project could suffice. Something along the lines of:

`sbt "++ 2.12.3" ; "scalacOptions ++= Seq("-Yrangepos")" ;  "<scalameta command>"`

**Comment by olafurpg** [comment]
Can you try this command?

```scala
// build.sbt
commands += Command.command("semanticdb") { s =>
  val extracted = Project.extract(s)
  import extracted._
  val V: Map[(Int, Int), String] = Map(
    (2 -> 11) -> "2.11.11",
    (2 -> 12) -> "2.12.3"
  )
  val settings: Seq[Setting[_]] = for {
    p <- extracted.structure.allProjectRefs
    version <- scalaVersion.in(p).get(structure.data).toList
    partialVersion <- CrossVersion.partialVersion(version).toList
    fullVersion <- V.get(partialVersion).toList
    setting <- List(
      scalaVersion.in(p) := fullVersion,
      scalacOptions.in(p) += "-Yrangepos",
      libraryDependencies.in(p) += compilerPlugin(
        "org.scalameta" % "semanticdb-scalac" % "2.0.1" cross CrossVersion.full)
    )
  } yield setting
  extracted.append(settings, s)
}
```

`sbt semanticdb compile` should first setup the required settings and then use them for compile regardless of the original build.

**Comment by olafurpg** [comment]
If this works, then you can either put this command in a `semanticdb.sbt` file that you copy into each project or turn it into a global sbt plugin like this

```scala
// ~/.sbt/0.13/plugins/SemanticdbCommandPlugin.scala
import sbt._, Keys._
import sbt.plugins.JvmPlugin

object SemanticdbCommandPlugin extends AutoPlugin {
  override def requires: Plugins = JvmPlugin
  override def trigger: PluginTrigger = allRequirements
  override def globalSettings = List(
    commands += Command.command("semanticdb") { ... }
  )
}

```

**Comment by olafurpg** [comment]
I created an sbt plugin for this so that the `semanticdb` command both installs semanticdb and runs compile in the main/test configuration for all affected projects https://gist.github.com/olafurpg/e581ed507d32a867007246bc9d7b38bd

**Comment by blorente** [comment]
It works in a project that needed manual configuration before, thank you!
