### ISSUE TITLE
semanticdb.HasFlags should not be private

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1139]
It would be nice if `HasFlags` was not private so it can be reused for non-Denotation data structures
https://github.com/scalameta/scalameta/blob/207e64eed3db6e7f5853a536269a48239717da91/langmeta/shared/src/main/scala/org/langmeta/semanticdb/Flags.scala#L33

It should also `extends Any`, so it can be used for zero-cost enrichment methods.

One example use case is to  enrich `schema.Denotation` with these methods, another use-case is to add these methods to a data container around `m.Denotation` that contains other fields like `m.Symbol`.

**Comment by xeno-by** [comment]
@olafurpg Is this still relevant given that we've started sunsetting the high-level API?

**Comment by olafurpg** [comment]
Sure, I've managed to workaround this anyways by putting code in org.langmeta.semanticdb anyways.
