### ISSUE TITLE
Decide what to do with the "high-level" API (Denotation, Symbol, Signature, etc)

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1140]
I'm missing `Signature.productPrefix`

**Comment by olafurpg** [comment]
I gave this a try in #1148 but it was a binary breaking change so this will have to wait until v3

**Comment by xeno-by** [comment]
@olafurpg Is this still relevant given that we've started sunsetting the high-level API?

**Comment by olafurpg** [comment]
`Symbol` and `Signature` are still highly relevant, I don't consider them as part of the high-level API like `Synthetic`, `Denotation` or `ResolvedName`

**Comment by xeno-by** [comment]
What kind of API do you expect from `Symbol` and `Signature`? Are you happy with the way things are implemented right now?

**Comment by olafurpg** [comment]
The current API is nice, I don't see any replacement for symbol or signature appearing in the near future.

**Comment by xeno-by** [comment]
Do you think we should add those apis to semanticdb3 then?

**Comment by olafurpg** [comment]
I `Symbol` and `Signature` should be part of semanticdb3.

**Comment by xeno-by** [comment]
In the brave new world when every symbol has a corresponding symbol information that includes `kind`, `name` and `owner`, do you think that there is still need in `Symbol` and `Signature`.

**Comment by olafurpg** [comment]
Maybe not, but I'll need to see it to believe it.

**Comment by xeno-by** [comment]
Sure. I've added this ticket to our board, so that we don't forget about it.

**Comment by olafurpg** [comment]
Even if SymbolInformation.owner comes in, we do several ad-hoc transformations on symbols in scalafix/metals that I'm not sure how do on strings. Example, go from case class `copy` term parameter to case class field. Maybe the new api will provide better ways to accomplish the same thing, but it will likely take a while until all tools have switched to that so Symbol and Signature will stay with use for quite some time

**Comment by xeno-by** [comment]
Sure, we can keep `Symbol` and `Signature` around for a while. The only question is whether they will become part of the new exciting SemanticDB v3 world, or they will stay in langmeta which is about to be sunset.

Ideally, I'd like to make all string manipulations unnecessary. The use case that you're requesting would be achieved by something like `p.owner.owner.decl(d => d.kind == GETTER && d.name == p.name)`. Let's see how this pans out though - we don't have to make any decisions right now.

**Comment by olafurpg** [comment]
Resolved in #1506, the high-level API is gone and will find a new home in package `scalafix.v0`.
