### ISSUE TITLE
Persist semanticdb flavor

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1151]
Currently, it's possible to build slim/fat semanticdbs. In #1150 and #1148, there will be 4-6 more options (denotations/messages/synthetics/members/...). Clients that read .semanticdb files don't know what settings where used to build the semanticdb. For settings like members, it's critical to be able to tell if `Denotation.members` is truly empty or if the setting was not enabled (protobuf is not able to represent `Option[List[Signature]]`. If we persist this information in `s.Document`, then we could let `scala.meta.Denotation.members` become an `Option[List[Signature]]`

**Comment by olafurpg** [comment]
Related discussion in https://github.com/scalameta/scalameta/pull/1158/files#r150067558, we can include in the Document whether it's "message-only", meaning it has only filename + messages.

**Comment by xeno-by** [comment]
@olafurpg Is this still relevant?

**Comment by olafurpg** [comment]
No longer relevant, tools that would consume this information (like scalafix) should instead extract the scalac options from the build tool. 

If we are to implement this however, I believe a good place to put this information might be semanticidx.
