### ISSUE TITLE
Braces from a quasi-quote are omited in the produced code

### ISSUE THREAD

**Issue by letalvoj** [scalameta/scalameta#1164]
I have encountered the following problem with scala.meta. In [pbmeta](https://github.com/btlines/pbmeta/blob/master/macros/src/main/scala/pbmeta/PBSerializable.scala#L136) a pair of simple brackets specified in a quasi-quote is omited from the produced code.

This line
```scala
p"case tag if (tag >> 3) == $i => $name ::= pbmeta.PBReads[$typeName].read(from)"
```
produces those cases
```scala
case tag if tag >> 3 == 1 => // <---- see the missing brackets
  logTs ::= pbmeta.PBReads[Long].read(from)
case tag if tag >> 3 == 2 =>
  colTs ::= pbmeta.PBReads[Long].read(from)
case tag if tag >> 3 == 3 =>
  sourceAddress ::= pbmeta.PBReads[String].read(from)
case tag if tag >> 3 == 4 =>
  destinationAddress ::= pbmeta.PBReads[String].read(from)
case tag if tag >> 3 == 5 =>
  action ::= pbmeta.PBReads[String].read(from)
```
which is unfortunatelly *mistakingly* labeled as an error by InteliJ ([SCL-12918](https://youtrack.jetbrains.com/issue/SCL-12918)). The code was produced by clicking on the expand icon in InteliJ.

<img width="201" alt="screen shot 2017-11-13 at 16 36 19" src="https://user-images.githubusercontent.com/5262321/32733941-ecc70f5e-c890-11e7-92e4-449ffd8df99b.png">

The sbt settings (in pbmeta) are:
```
  addCompilerPlugin("org.scalameta" % "paradise" % "3.0.0-M8" cross CrossVersion.full),
  scalacOptions += "-Xplugin-require:macroparadise",
  libraryDependencies += "org.scalameta" %% "scalameta" % "1.7.0"
```
and my InteliJ Scala plugin is of version `2017.2.11`.

Is it an expected behaviour? Since the code is equivalent, only the syntax is slightly different it does not sound like a big deal. Yet I would expect meta to preserve as much detail as possible. One never knows what can go wrong.

Thanks

**Comment by olafurpg** [comment]
Thank you for reporting! The braces are not necessary since you get the same AST if you omit them. This behavior is expected. The bug is in the IntelliJ parser.

Quasiquotes don't preserve any trivia, not even comments (see #1137), and I don't see a workaround for this appearing in the near future.

```scala
@ p"case tag if (tag >> 3) == 3 =>"
res12: Case = Case(
  Pat.Var(Term.Name("tag")),
  Some(Term.ApplyInfix(Term.ApplyInfix(Term.Name("tag"), Term.Name(">>"), List(), List(Lit.Int(3))), Term.Name("=="), List(), List(Lit.Int(3)))),
  Term.Block(List())
)

@ p"case tag if tag >> 3 == 3 =>"
res13: Case = Case(
  Pat.Var(Term.Name("tag")),
  Some(Term.ApplyInfix(Term.ApplyInfix(Term.Name("tag"), Term.Name(">>"), List(), List(Lit.Int(3))), Term.Name("=="), List(), List(Lit.Int(3)))),
  Term.Block(List())
)
```

**Comment by olafurpg** [comment]
One possible workaround is to maybe wrap `tag >> 3` inside a block like this `{tag >> 3}`?

**Comment by olafurpg** [comment]
Cool project btw! I always wanted something like that :) We use scalapb and it generates a lot (!) of code.
