### ISSUE TITLE
Add SymbolInformation.documentation

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1166]
It would be useful if denotation contains the docstring of that symbol. This can be used by documentation tools and editors like the language server.

**Comment by ShaneDelmore** [comment]
I don’t know if we need the full docstring but I would love to have the position of the docstring as well as the position of the definition.  This would make it easy to show docstring, definition, as well as making it easy to calculate nesting.

**Comment by xeno-by** [comment]
As discussed today, I think the following would make sense:
  * [ ] Add a string field `SymbolInformation.documentation` to the schema
  * [ ] Improve `semanticdb-scalac` to save docstrings to SemanticDB.
  * [ ] Improve `scalacp` to detect associated `-sources.jar` or even `-scaladoc.jar` jars and automatically figure out docstrings to stuff from classfiles.
  * [ ] Ditto for `javacp`.

Let's start with the first two action items, and if everything goes as we expect, then we'll follow up with separate tickets for `scalacp` and `javacp`.

**Comment by sander** [comment]
@xeno-by @laughedelic Just to be sure: action items 1 & 2 are not yet added to SemanticDB right? Asking since Metals does seem to support docstrings, and from what I understand it is based on SemanticDB.

**Comment by tgodzik** [comment]
It seems storing docs in semanticdb might make the files much bigger than needed. We handled it in Metals by going through the source jars. I think it's the better solution here. If anyone needs this functionality we can reopen.
