### ISSUE TITLE
ArrayIndexOutOfBoundsException when parsing sources from an SBT task

### ISSUE THREAD

**Issue by netvl** [scalameta/scalameta#1175]
I'm using Scalameta to parse sources of all projects of an SBT build as a part of source generation for one of the projects. The code looks basically like this:
```scala
  import scala.meta._

  val scalaSources = (ThisBuild / baseDirectory).value
    .globRecursive(new SimpleFilter(_.endsWith(".scala")))
    .get
  scalaSources.iterator
    .flatMap(_.parse[Source].toOption)
```
and then I extract whatever data I need from the parsed sources.

However, when I run compilation (and thus code generation) several times without restarting SBT, I get exceptions like this:
```
[error] java.lang.ArrayIndexOutOfBoundsException: 2022
[error]         at scala.meta.internal.parsers.ScalametaParser.<init>(ScalametaParser.scala:144)
[error]         at scala.meta.internal.parsers.ScalametaParser$$anon$189.apply(ScalametaParser.scala:3465)
[error]         at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:21)
[error]         at scala.meta.parsers.Api$XtensionParseInputLike.parse(Api.scala:10)
[error]         at $867f5d78038e82f55208$.$anonfun$collectConnectorKeys$3(build.sbt:220)  // my task implementation
```
The index in the exception is different each time, but the errror happens consistently after between one to five invocations of the task which uses Scalameta.

Once I restart SBT, the errors goes away for a while, but then comes back very quickly. This is really annoying, because it breaks the development loop in quite a nasty way.

I'm using Scalameta 2.1.2 and SBT 1.1.0-RC1, although this also happened with older SBT versions.

**Comment by olafurpg** [comment]
Thank you for reporting @netvl ! Can you adding a call to `megaCache.clear()` like here?https://github.com/scalameta/scalafmt/blob/6cddfe9e217de11738c47240911eaf024cecbb0e/scalafmt-sbt/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala#L13 
see https://github.com/scalameta/scalameta/issues/1068 for the gory details

**Comment by netvl** [comment]
Oh, I get it. Indeed, we talked about this cache before on gitter, I should have though about it. Thanks, I'll try it.

**Comment by netvl** [comment]
Anyway, looks like duplicate of [https://github.com/scalameta/scalameta/issues/778]. Strange, I searched the tracker for `ArrayIndexOutOfBoundsException` and didn't find anything.
