### ISSUE TITLE
langmeta tests210 is not 2.10 specific

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1183]
those tests should run on all scala versions. Regressed #1173

**Comment by xeno-by** [comment]
We run them on other Scala versions in the reorganized build, as part of the `tests` project.

**Comment by olafurpg** [comment]
Currently, `publishLocal` fails because tests210 is `scalaVersion := "2.10"` and depends on langmeta_2.12/2.11 The conventional way is to use `crossScalaVersions := List(2.11/2.12/2.10)`. We can move to this setup when langmeta becomes a standalone repo.

**Comment by olafurpg** [comment]
IntelliJ import no longer works because `tests210/update` causes a resolution error
```
[info] Packaging /Users/ollie/dev/scalameta/scalameta/semanticdb-scalac-plugin/target/scala-2.12/semanticdb-scalac_2.12.4-2.1.3-31-75e5df82.jar ...
```
