### ISSUE TITLE
Add post order traversal macro

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalameta#1191]
I trialed handwriting a custom traversal algorithm for scalagen. 

However we need to handle `Term.Block` which means we need to handle all `Terms`.
There's too many cases to handle via pattern matching.

In order to implement full transformations we need to have a post-order transform method in scalameta.

**Comment by DavidDudson** [comment]
Actually, I have not actually looked. But is `transform` post-order already?

**Comment by olafurpg** [comment]
Is this fixed with `leafFirstTranform` in https://github.com/scalameta/scalagen/pull/14/files#diff-430d2cf7cf04c40062d98b67c80416eeR8 ?

**Comment by DavidDudson** [comment]
Yes
