### ISSUE TITLE
Expose InternalInput offset <-> line:column conversions

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1196]
https://github.com/scalameta/scalameta/blob/11a66cb6476d62783bcad27845a2db2a9a5a0128/langmeta/langmeta/shared/src/main/scala/org/langmeta/internal/inputs/InternalInput.scala#L27-L36

These would be helpful in language-server and could help prevent bugs like https://github.com/scalameta/language-server/issues/119

**Comment by xeno-by** [comment]
@olafurpg Is this ticket still relevant now that we switched to line/column in SemanticDB v3?

**Comment by olafurpg** [comment]
This is absolutely still relevant, start/end offsets appear all over the place.

**Comment by xeno-by** [comment]
Superseded by https://github.com/scalameta/scalameta/issues/1588.
