### ISSUE TITLE
`.syntax` does not maintain newlines on statements with a non-apply body

### ISSUE THREAD

**Issue by pjrt** [scalameta/scalameta#1198]
I wrote the following test (in `SyntacticSuite.scala`) to show this:

```scala
  test("newline should be preserved before bodies") {
    val src =
      """
      |object A {
      | def f(a: K) =
      |   a
      |}
      """.stripMargin

    assert(source(src).syntax == src)
  }
```

It fails with:

```
[info] - newline should be preserved before bodies *** FAILED ***
[info]   "[object A { def f(a: K) = a }]" did not equal "[
[info]   object A {
[info]    def f(a: K) =
[info]      a
[info]   }
```

Note that `\n` has been removed.

**Comment by olafurpg** [comment]
What happens if you add a comment in that test? Scalameta .syntax does not preserve any trivia.

**Comment by pjrt** [comment]
Add a comment? Like a scaladoc to the func?

**Comment by pjrt** [comment]
Adding a comment does remove it:
```
[info]   "[object A { def f(a: K) = a }]" did not equal "[
[info]   object A {
[info]    // some-comment
[info]    def f(a: K) =
[info]      a
[info]   }
```

Am I misunderstanding what `.syntax` is?

**Comment by olafurpg** [comment]
A tree parsed from an input will have an `Origin` that contains tokens. `.syntax` checks if those tokens exists, if they do it prints out the exact same string as the input, otherwise it runs TreeSyntax https://github.com/scalameta/scalameta/blob/11a66cb6476d62783bcad27845a2db2a9a5a0128/scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala which is a tree printer that discards any trivia like formatting or comments.


I've made decent progress in https://github.com/olafurpg/scala-syntax to replace TreeSyntax, but there is still some remaining work to preserve comments/trivia.

**Comment by pjrt** [comment]
Not sure I follow (don't know much about Origin or scalameta internals). Are you saying this is working as expected? If so, should I be trying a different method? `toString` did the same.

**Comment by olafurpg** [comment]
Yes it's working as intended and there is no workaround for it at the moment, except maybe run scalafmt on the string input. Note that SynctacticSuite removes the Origin in order to test TreeSyntax, if you `.parse[Source]` it will print the original input verbatim.

**Comment by pjrt** [comment]
Oh, that did work. Now I'm confused though. You said there is no work around but doing `.parse` works.

**Comment by olafurpg** [comment]
I think I misunderstood what you were trying to accomplish. That test suite
is for TreeSyntax which is a pretty printer. With parse then syntax does
nothing except print the string input that was parsed.

**Comment by olafurpg** [comment]
Good to hear `.parse` fixed the problem.

**Comment by pjrt** [comment]
@olafurpg 
Well this is really my issue. I am trying to parse the following in stags:

```
@someAnno
def f =
    2
```

I do the normal `.parse` when getting the AST. I then run a modifier function on it where I remove any annotations that `f` may have. However, after doing that, when I go to run `.syntax` or `.tokens.mkString`, I end up with 

```
def f = 2
```

The `\n` gets removed. The test I made in SyntaticSuite doesn't seem to capture that. Maybe if I modify the tree I can get it to happen again. 

Is there a more appropriate test suite for me to do this on?

**Comment by olafurpg** [comment]
@pjrt as soon as you transform the tree then `.syntax` falls back to TreeSyntax which does not preserve any trivia. Syntax preserving tree transforms is the holy grail of refactoring tools and is still an active research area https://github.com/camfort/reprinter (paper https://www.cs.kent.ac.uk/people/staff/dao7/publ/reprinter2017.pdf) They have this in ReasonML and with refmt and I want scalafmt v2 to also support tree transforms 😄

**Comment by olafurpg** [comment]
> Is there a more appropriate test suite for me to do this on?

The latest progress on syntax preserving tree transforms is in https://github.com/olafurpg/scala-syntax, (in particular `comments` branch) which I hope to turn into scalafmt v2 once it's [more complete.
