### ISSUE TITLE
.transform/.traverse should only trigger partial function once

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1200]
I had to admit it but I was writing a partial function today that did have a side effect and I hit on this
```scala
@ var i = 0
i: Int = 0

@ q"A".transform {
    case q"A" if {
    i += 1
    i < 2
  } => q"b"
  }
scala.MatchError: A (of class scala.meta.Term$Name$TermNameImpl)
  scala.PartialFunction$$anon$1.apply(PartialFunction.scala:254)
  scala.PartialFunction$$anon$1.apply(PartialFunction.scala:252)
```
We should use `.applyOrElse` which is designed exactly for this use-case.

**Comment by DavidDudson** [comment]
I agree that it should not do that. But... side effects in the pattern are just asking for trouble!
