### ISSUE TITLE
Replace/Extract (Term/Type).Name

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalameta#1211]
For prettyprinting purposes, I would like to print out owner tree's in scalagen, tagged with their name, and/or Term.Select clause

```
Defn.Source
  Defn.Package : foo.bar.baz
    Defn.Class : Foo
      Defn.Def : getBar
    Defn.Object : Bar
```

**Comment by olafurpg** [comment]
Contrib has been stable for a while now and is working great. Let's defer feature requests like this ticket until we have someone driving the work.
