### ISSUE TITLE
Prefix is missing for abstract ThisType in denotation.signature

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1215]
The following tests is failing with `Classifier != Foo.this.Classifier`
```scala
  targeted(
    """
      |package ah
      |
      |trait EventBus {
      |  type Classifier
      |}
      |trait Foo { this: EventBus =>
      |  val <<x>>: Classifier
      |}
      |""".stripMargin, { (db, x) =>
      val sig = db.symbols.find(_.symbol == x).get.denotation.signature
      assertNoDiff(sig, "Foo.this.Classifier")
    }
  )
```

This bug is the root cause of existing ExplicitResultTypes bugs in scalafix https://github.com/scalacenter/scalafix/issues/324

**Comment by xeno-by** [comment]
@olafurpg Is this still relevant now that we're moving full steam ahead towards https://github.com/scalameta/scalameta/issues/1221?

**Comment by olafurpg** [comment]
This was already fixed in a PR actually
