### ISSUE TITLE
Improve Type

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1262]
https://github.com/scalameta/scalameta/pull/1259#discussion_r166001942

**Comment by xeno-by** [comment]
I'll be working on this ticket this week. The overhead of dealing with the current implementation of `Type` is becoming unbearable.

**Comment by olafurpg** [comment]
I had thought about this and have some ideas

* all suptypes of `Type` use `.extends`

```
  option (scalapb.message).extends = "scala.meta.semanticdb3.Type"
```


* `Type` is not defined in protobuf, it's hand written in scala and has a custom `TypeMapper` as documented here https://scalapb.github.io/customizations.html where

**Comment by olafurpg** [comment]
I am working on this. It seems that the best option is to extend ScalaPB to generate more idiomatic Scala code for special cases of `oneof` that have the following shape
```proto
message Lit {
  int32 value = 1
}
message Add {
  Expr lhs = 1;
  Expr rhs = 2;
}
message Expr {
  oneof value {
    Lit lit = 1;
    Add add = 2;
  }
}
```

The message `Expr` will be detected as the supertype of a sealed ADT and generate roughly the following code
```scala
case class Lit(value: Int) extends Expr { ... }
case class Add(lhs: Expr, rhs: Expr) extends Expr { ... }
sealed trait Expr {
  def asExprMessage: Expr.Message
}
object Expr {
  case object Empty extends Expr { ... }
  class Message(
      underlying: scalapb.Message[Expr] with scalapb.GeneratedMessage,
      tag: Int
  ) extends scalapb.Message[Expr] with scalapb.GeneratedMessage
}
```

I will open a discussion in ScalaPB to see if this encoding makes sense and could be contributed upstream. It's possible to write custom scalapb code generators, but I prefer to use the standard ScalaPB encoding.

**Comment by olafurpg** [comment]
Proposal to add "sealed oneof" option to ScalaPB https://github.com/scalapb/ScalaPB/issues/455

**Comment by olafurpg** [comment]
Current status: https://github.com/scalameta/scalameta/blob/74e7c070ae90363857b7abe576ed9f6369b2f6de/semanticdb/semanticdb3/src/main/generated/scala/meta/internal/semanticdb3/TypeMessage.scala

with this protobuf encoding for `Type`
```proto
message Type {
 //   reserved 1, 3, 4, 5, 6;
  oneof sealed_value {
    TypeRef typeRef = 2;
    SingletonType singletonType = 16;
    IntersectionType intersectionType = 17;
    UnionType unionType = 18;
    WithType withType = 19;
    StructuralType structuralType = 7;
    AnnotatedType annotatedType = 8;
    ExistentialType existentialType = 9;
    UniversalType universalType = 10;
    ClassInfoType classInfoType = 11;
    MethodType methodType = 12;
    ByNameType byNameType = 13;
    RepeatedType repeatedType = 14;
    TypeType typeType = 15;
  }
}
```
It's actually a compatible change on the protobuf layer.

**Comment by olafurpg** [comment]
ScalaPB PR adding "sealed oneof" https://github.com/scalapb/ScalaPB/pull/458

**Comment by olafurpg** [comment]
Here is an example commit porting metap to the new types https://github.com/scalameta/scalameta/commit/9e35ef48be3ec596243113960d2aff2c316080ff I would like to turn `SingletonType` into a "sealed oneof" as well but that will require more work in the scalapb PR. Any thoughts before I go ahead and port rest of the codebase?

**Comment by xeno-by** [comment]
That's a significant improvement! I am pleasantly surprised that we get to keep Protobuf-level compatibility. A few notes.

1) Let's add `val NoType = Type.Empty` to the package object, so that we don't have to violate our naming convention with `Type.Empty` vs `FooType`.

2) I would like to see the example commit to be extended to get rid of options completely. `Type.Empty` vs `toOption` is like `Type.Empty` vs `FooType` - we should have one way of doing things. Please add overloads for `opt` to take types. `tpe.foreach(fn)` can probably be rewritten into `opt(fn)(tpe)`.

**Comment by olafurpg** [comment]
Great ideas! I've implemented your feedback and the output is indeed nicer
https://github.com/scalameta/scalameta/commit/79b00b05eba5e338a5b4d8603a6cc6273ee2e9de
