### ISSUE TITLE
Let's write documentation!

### ISSUE THREAD

**Issue by MasseGuillaume** [scalameta/scalameta#1265]
There is two kind of documentation: reference manual and api doc (scaladoc).

Here is a non-exhaustive list where we need reference documentation:

* [x] [semanticdb plugin options](https://github.com/scalameta/scalameta/blob/master/semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/ConfigOps.scala)
* [x] semanticdb
* [x] metap
* [x] metac
* [ ] classifiers
* [ ] dialects
* [ ] parsers
* [ ] prettyprinters
* [ ] quasiquotes
* [ ] io
* [ ] inputs
* [ ] tokenizers
* [ ] tokens
* [ ] transversers
* [ ] trees

What puzzled me in the beginning:
* equality for trees
* how to get information out of the semanticdb. (If you don't have the exact position, you don't get the symbol)

For the api doc, I can't find where the unidoc is published.

**Comment by MasseGuillaume** [comment]
Related: https://github.com/scalameta/scalameta/issues/816

**Comment by DavidDudson** [comment]
In what for would you like documentation, just a better version of http://scalameta.org/tutorial/#AWhirlwindTourofScalameta ???

**Comment by MasseGuillaume** [comment]
@DavidDudson indeed, when I wrote this ticket I forgot about that tutorial. It does cover the wtf with equality. I guess a good start would be to make this more discoverable.

There are still missing pieces:

* where is the api doc?
* expand this section: http://scalameta.org/tutorial/#SemanticAPI

**Comment by xeno-by** [comment]
Here are some long overdue process documents:
  * https://github.com/scalameta/scalameta/pull/1268
  * https://github.com/scalameta/scalameta/pull/1269

**Comment by olafurpg** [comment]
Great idea @MasseGuillaume 

I added `metap` and `metac` to the list, they can be used to quickly produce and print semanticdb files from the command line.

**Comment by olafurpg** [comment]
Superseded by #816
