### ISSUE TITLE
Rethink method symbols

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1295]
I've run into a hard blocker implementing metacp with scalap. 

From within scalap, there is no way to compute an erasure of a type, which means that we can't generate specification-compliant method symbols (https://github.com/scalameta/scalameta/blob/master/semanticdb/semanticdb3/semanticdb3.md#symbol).

This is another situation that highlights that current method symbols are problematic. During the SemanticDB v3 design period, we had a discussion about  using a different symbol format, but we didn't have time to follow through. Looks like now we have to do that.

**Comment by olafurpg** [comment]
I am both excited about improving the format and scared of changing it.

Just brainstorming, would it be possible to use the dealiased symbol for all arguments?

```
def foo(a: Int) = a
// foo(scala.Int#)
def foo(a: String) = foo(a.length)
// foo(java.lang.String#)
def foo(a: Either[String, Int]) = foo(a.length)
// foo(scala.util.Either#)
```

I had problems reproducing the symbol method format in mtags for metals because there we only have syntax trees. The information have syntactically from the source is

* position of definition
* parameter names
* syntax for parameter type

With that information we could do a best-effort for compute the actual symbols, it would at least likely be easier than matching erased signature.

**Comment by xeno-by** [comment]
Let's summarize our current experience with using unique identifiers for modeling method symbols (well, not unique unique, but unique-within-universe unique - see [the spec](https://github.com/scalameta/scalameta/blob/master/semanticdb/semanticdb3/semanticdb3.md#symbol) for details):
* Symbol generation in producers
    * Current approach has proven to be really bad in this aspect, since it requires computing erasures, which requires lots of semantic APIs (dealiasing, parents + members - for value classes, maybe more). These semantic APIs are hard to come by, as our experience with mtags and metacp shows.
* Symbol lookup in consumers
    * We don't really provide the API to look up symbols within other symbols, so this is currently a moot point.
* Manually writing down symbols
    * Current approach is really bad at this, too. A human would have to perform type erasure in their head to be able to easily write down a symbol. The state of the art solution is to write example code and see what symbols are generated for it by semanticdb-scalac.
* Eyeballing
    * Current approach produces walls of text, which is pretty bad.
* Incremental compilation
    * Current approach has the benefit of theoretically supporting perfect incremental compilation. If the enclosing file changes, but the method signature stays the same, then we don't need to recompute dependent SemanticDBs that only use the method in question. None of the existing build tools for Scala can leverage this benefit though.

All in all, we can see that current method symbols are all-around terrible, so we really have to come up with something better.

Based on your suggestion to exclusively use syntactic information I propose the following strategy:
* By default, a method symbol is a concatenation of owner symbol, encoded name and parenthesized line number, e.g. `_root_.com.foo.Foo.bar(42).` for a method Foo.bar defined on line 42.
* In the unlikely event when this produces name clashes (multiple methods on the same line), add column number to the mix too, e.g. `_root_.com.foo.Foo.bar(42:3).`
* In the even more unlikely event when this still produces name clashes (existing members that have parentheses in their name), add an integer suffix and increase it until the resulting symbol is unique, e.g. `_root_.com.foo.Foo.bar(42:3+1).`

This also generalizes to metacp, where instead of line number we could use entry index within Scala signatures or entry index within the classfile constant pool.

**Comment by olafurpg** [comment]
> By default, a method symbol is a concatenation of owner symbol, encoded name and parenthesized line number, e.g. _root_.com.foo.Foo.bar(42). for a method Foo.bar defined on line 42.

I'm not convinced this is a good scheme. How hard is it to compute from reference site? I don't think we can count on the source information being available in the classfiles.

This would mean the same method has different syntax when you add a line above in the source file. For example, `Option.get` might be different in scala 2.11 vs 2.12. This is not friendly when manually reading/writing symbols, in scalafix it's quite common to hand-write symbol IDs for migration rules.

What do you think about my proposal in https://github.com/scalameta/scalameta/issues/1295#issuecomment-364645139 ?

> In the unlikely event when this produces name clashes (multiple methods on the same line), add column number to the mix too, e.g. _root_.com.foo.Foo.bar(42:3).

Can't this happen quite frequently for synthesized members from macro annotations?

**Comment by xeno-by** [comment]
Fixed in https://github.com/scalameta/scalameta/pull/1323.
