### ISSUE TITLE
Tighten compatibility guarantees for semanticdb3

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1300]
Because of the fact that ScalaPB generates case classes, `semanticdb3` would violate [our compatibility guarantees](https://github.com/scalameta/scalameta/blob/master/COMPATIBILITY.md) if it was made a public API. Problematic APIs include case class `apply`, `unapply`, `copy` and some other methods.

**Comment by olafurpg** [comment]
Looks like this is outside the scope of Scalameta since the fix involves contributing to ScalaPB.
