### ISSUE TITLE
Add support for denotation by tree

### ISSUE THREAD

**Issue by ShaneDelmore** [scalameta/scalameta#1311]
A common request is to get the denotation of a tree.  As a rough guess this would be the denotation of the last element in the tree unless it is a block, in which case it would be the denotation of the last statement in the block.

**Comment by xeno-by** [comment]
Can you give an example?

**Comment by olafurpg** [comment]
If I understand correctly, this sounds like `Term.tpe` which will require https://github.com/scalameta/scalameta/issues?q=is%3Aissue+is%3Aopen+label%3ASymtab

**Comment by ShaneDelmore** [comment]
@olafurpg What is the current proper usage of index.denotation(tree)?  This came up as the last couple of times I have paired with people working with scalameta and scalafix this is a thing that frequently looks useful based on type signatures, but always results in None.  I might be misunderstanding when I should be looking for denotation vs tpe

**Comment by olafurpg** [comment]
that method is a shorthand for `denotation(symbol(tree))`, it should return results for refs (`a`, `a.b`) etc but more complex expressions it's expected to return none

**Comment by olafurpg** [comment]
Duplicate of #1212. You can query the type of a symbol with the current api but not a term.
