### ISSUE TITLE
Unused Lit.Byte and Lit.Short

### ISSUE THREAD

**Issue by MasseGuillaume** [scalameta/scalameta#1324]
I suppose this is for Typelevel: https://github.com/typelevel/scala/pull/12/files#diff-0023b3bfa053fb16603156b785efa7adR1011

```scala
0z // Lit.Byte
0s // Lit.Short
```

However:

```scala
import scala.meta._ 
import scala.meta.dialects.Typelevel212 
```

```scala
"object A { 0s }".parse[Source]
```

```scala
Error(
  Range(String("object A { 0s }"), 11, 11),
  "Invalid literal number",
  TokenizeException(
    Range(String("object A { 0s }"), 11, 11),
    "Invalid literal number"
  )
)
```

```scala
"object A { 0z }".parse[Source]
```

```scala
Parsed[Source] = Error(
  Range(String("object A { 0z }"), 11, 11),
  "Invalid literal number",
  TokenizeException(
    Range(String("object A { 0z }"), 11, 11),
    "Invalid literal number"
  )
)
```

**Comment by xeno-by** [comment]
This was introduced before Typelevel Scala compiler added support for byte and short literals (https://github.com/typelevel/scala/pull/12). The main reason was consistency with other literals and needing to have data structures that represent publicly visible bits of internal compiler state (e.g. inferred types of final vals).

But yeah, this is inconsistent with the current reality in which TLS supports those literals. We should update the parser to accommodate that functionality.

**Comment by tgodzik** [comment]
Typelevel compiler is no archived: https://github.com/typelevel/scala
