### ISSUE TITLE
Save enclosing packages in metac payloads

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1340]
See https://github.com/scalameta/scalameta/pull/1339 for a metacp implementation of the same thing.

**Comment by xeno-by** [comment]
@olafurpg This one also looks relevant to your upcoming work.

**Comment by olafurpg** [comment]
After https://github.com/scalameta/scalameta/pull/1660 we no longer persist package symbols since their info can be trivially computed from the symbol syntax. We can close this as won't fix.
