### ISSUE TITLE
Can't find scalameta code generation usage/documentation

### ISSUE THREAD

**Issue by caioquirino** [scalameta/scalameta#1346]
Hello people from scalameta, I'm a newcomer using this API, have already used scala.reflect.macros in the past for HBase Repository generation, so I can't find any documentation that can work with the latest version of scalameta.

I have found only this gist for using inline+meta: 
https://medium.com/@Arhelmus/metaprogramming-magic-with-scalameta-67e849ab490e
https://gist.github.com/ArchDev/935533fba2dfa1257dd54921c38e0ed6
So it doesn't work as:

inline def ... <- can't find inline word -> Can it be @inline instead?
Pat.Var.Term <- does not exist anymore

How can I find some documentation regarding the use of inline+meta for code generation?

**Comment by olafurpg** [comment]
Hei @caioquirino ! Can you elaborate what you mean by code generation? Scalameta no longer supports macro annotations nor other forms of compile-time reflection.

**Comment by caioquirino** [comment]
I'm sorry, I haven't noted that scalameta no longer supports compile-time reflection (it's explained explicitly in the project's readme lol)

Instead I will use scala macros with paradise (thinking about treehugger also). Thank you for your time and sorry for the uggly question ;)

**Comment by olafurpg** [comment]
No worries, scala-reflect macro annotations are your best option 👍
