### ISSUE TITLE
Simplify method symbol descriptor disambiguation

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1358]
Currently, conflicting method descriptors are handled this way

```scala
def foo(a: x.A) // foo(A+1)
def foo(a: y.A) // foo(A+2)
```

I propose we simplify it to

```scala
def foo(a: x.A) // foo(A)
def foo(a: y.A) // foo(A+1)
```

The benefit is to make it easier to compute method symbols, a simple loop like this should be enough

```scala

val descriptors = mutable.Map[String, Int]
node.methods.foreach { method =>
  val descriptor = method.descriptor
  val suffix = descriptors.getOrElseUpdate(descriptor, 0)
  descriptors(descriptor) = suffix + 1
...

```

The current scheme is harder to support because the suffix requires knowing all possibly conflicting method symbols beforehand.

**Comment by gabro** [comment]
@xeno-by can this be closed?

**Comment by xeno-by** [comment]
Good catch! I thought that github will take care of that automatically.
