### ISSUE TITLE
Investigate rare scope resolution errors in javacp

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1365]
There are still a handful of type parameters that don't get resolved in javacp. I'm only able to reproduce with spark-sql.

**Comment by xeno-by** [comment]
Is this still relevant?

**Comment by olafurpg** [comment]
Yes, the TODO that needs addressing is here https://github.com/scalameta/scalameta/blob/32de4fa4ee105bb198917c5d82b13cbf6b82384f/semanticdb/metacp/src/main/scala/scala/meta/internal/javacp/Scope.scala#L13-L15

IIRC, I was only able to reproduce it in jars that seem shaded.

**Comment by xeno-by** [comment]
@olafurpg Is this still relevant?

**Comment by olafurpg** [comment]
Let's reopen if this problem surfaces in a real-world example.
