### ISSUE TITLE
Remove support for SymbolInformation.signature/members

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1370]
* [x] Remove from the spec
* [x] Remove from protobuf
* [x] Remove from Denotation
* [x] Remove from semanticdb-scalac
* [x] Remove from tests

These fields are superseded by the new functionality provided in SymbolInformation.tpe and semanticdb.semanticidx. I'm removing them from the specification, but keeping support for them in the protobuf schema and semanticdb-scalac. @olafurpg, please reply here when you're ready to let these fields go.

**Comment by olafurpg** [comment]
Fixed in https://github.com/scalameta/scalameta/pull/1506
