### ISSUE TITLE
Javacp produces incorrect constructor symbols for inner classes

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1372]
```
_root_.com.javacp.ClassSuffix#Inner#<init>(ClassSuffix). => private[javacp] def <init>: (): Unit
  Unit => _root_.scala.Unit#
```

**Comment by olafurpg** [comment]
Can you include the expected output? I think I know what the issue is but it's not obvious from the description.

**Comment by xeno-by** [comment]
The symbol itself (`_root_.com.javacp.ClassSuffix#Inner#<init>(ClassSuffix).`) still includes the synthetic parameter :)

**Comment by olafurpg** [comment]
```diff
- obtained
+ expected

- _root_.com.javacp.ClassSuffix#Inner#<init>(ClassSuffix). => private[javacp] def <init>: (): Unit
+ _root_.com.javacp.ClassSuffix#Inner#<init>(). => private[javacp] def <init>: (): Unit
```

**Comment by olafurpg** [comment]
It appears that metac does not follow the requested behavior either https://github.com/scalameta/scalameta/blob/373fe5b4a75254c75de02ab6a45f55dd99666c90/tests/jvm/src/test/resources/metac-metacp.expect.diff#L63-L65

**Comment by xeno-by** [comment]
Superseded by https://github.com/scalameta/scalameta/issues/1537.
