### ISSUE TITLE
Javacp produces incorrect constructor signatures

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1375]
The spec mandates that constructor signatures are METHOD_TYPE types with the return type equal to the type of the enclosing class. In Javacp, the return type is unit.

**Comment by olafurpg** [comment]
It's now possible to see the full diff between metacp and metac here https://github.com/scalameta/scalameta/blob/373fe5b4a75254c75de02ab6a45f55dd99666c90/tests/jvm/src/test/resources/metac-metacp.expect.diff

**Comment by xeno-by** [comment]
Superseded by https://github.com/scalameta/scalameta/issues/1546.
