### ISSUE TITLE
Symbol format API

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1381]
Some context: https://github.com/scalameta/scalameta/pull/1376#discussion_r171241289.

**Comment by xeno-by** [comment]
Now that we're getting rid of the `_root_.` prefix, structured symbol handling becomes even more important, because it's no longer enough to concatenate owner symbol and descriptor to obtain a child symbol (for a top-level package `p`, owner is `_root_.`, but the symbol is `p.`).

**Comment by xeno-by** [comment]
However, I found that implementing this is harder than I thought. A centerpiece of the symbol structure API is a symbol parser, and it presents unexpected difficulties.

At first, I thought that I'll simply take the existing symbol parser from `langmeta` and move it to `semanticdb3`. However, that parser is tied to `Symbol` and `Signature` data structures, which are, in my opinion, too high-level for `semanticdb3`. 

Making `Symbol` and `Signature` internal and hiding them behind a more low-level API (e.g. `String.owner`, `String.descriptor`, etc) is out of the question, because these data structures are part of the public API of `langmeta`.

Refactoring the parser to introduce abstractions that would handle both high-level and low-level APIs seems a significant overkill. Moreover, it will further convolute the already non-trivial parser logic, which makes me doubt the usefulness of the exercise.

This seemingly leaves no other choice than to copy/paste the parser, which is outright awful given its size and the amount of intricacies involved in the parsing logic. All in all, this needs more thoughts.

**Comment by olafurpg** [comment]
Implementation details aside, how do you envision the long-term semanticdb3 API for symbols? Will it be extension methods on String or some low-level `semanticdb3.Symbol` class?

Just brainstorming. Maybe we can expose a circe-`Json` inspired `semanticdb3.Symbol` API that looks something like

```
sealed abstract class Symbol {
  def syntax: String
  def name: String
  def owner: Symbol
  def isLocal: Boolean
  def isGlobal: Boolean
  def isMethod: Boolean
  // ...
  
  // transformers
  def withMethod(f: MethodSymbol => Symbol): Symbol
  def withGlobal(f: GlobalSymbol => Symbol): Symbol
}

sealed abstract class MethodSymbol { .. } // does not extend symbol
```

Users should never see subtypes of `Symbol`. Source: https://github.com/circe/circe/blob/6f32e3068f31d19efd351e1cb27b47dd6854f5ea/modules/core/shared/src/main/scala/io/circe/Json.scala#L63-L88

I don't have enough experience with circe myself to judge how convenient/useful this API would be. I think it's an interesting approach that keeps the public API fairly closed but still high-level without exposing pattern matching.

**Comment by xeno-by** [comment]
I think I finally know how to do this. Will implement and submit a pull request today.

**Comment by xeno-by** [comment]
Fixed in https://github.com/scalameta/scalameta/pull/1430.
