### ISSUE TITLE
Lit.Double, Lit.Float format is not preserved

### ISSUE THREAD

**Issue by MasseGuillaume** [scalameta/scalameta#1385]
Obtained

```scala
import scala.meta._
"-0D".parse[Term].get.asInstanceOf[Lit.Double].format == "0"
"-0F".parse[Term].get.asInstanceOf[Lit.Float].format == "0"
```

Expected:

```scala
import scala.meta._
"-0D".parse[Term].get.asInstanceOf[Lit.Double].format == "-0"
"-0F".parse[Term].get.asInstanceOf[Lit.Float].format == "-0"
```

Expected Alternatively, preserve the suffix:

```scala
import scala.meta._
"-0D".parse[Term].get.asInstanceOf[Lit.Double].format == "-0D"
"-0F".parse[Term].get.asInstanceOf[Lit.Float].format == "-0F"
```

EDIT: remove Long & Int.

**Comment by olafurpg** [comment]
I agree `.format` should return `"-0"` for Double and Float.

I'm unable to reproduce for Long and Int
```scala
@ "-0L".parse[Term].get.asInstanceOf[Lit.Long].format == "-0L"
cmd8.sc:1: value format is not a member of scala.meta.Lit.Long
val res8 = "-0L".parse[Term].get.asInstanceOf[Lit.Long].format == "-0L"
```

Also, note that
```
@ -0d == 0
res7: Boolean = true
```
so the two are structurally equal.

**Comment by MasseGuillaume** [comment]
should be `.value` editing above.

**Comment by MasseGuillaume** [comment]
-0d == 0 but they do not have the same memory layout.

**Comment by olafurpg** [comment]
I'm not sure how we can preserve -0

```scala
@ Integer.valueOf(-0)
res15: Integer = 0
@ java.lang.Double.valueOf(-0)
res16: java.lang.Double = 0.0
```

Question is whether all literal trees should be written as strings. We opted for only doing this for floats and doubles where the semantics different on different runtimes. However, I'm not convinced it's necessary to do the same for Int and Long. I'd say "working as intended".

**Comment by MasseGuillaume** [comment]
IEEE754 has the notion of -0, we should preserve it.

```
(new java.lang.Float(0.0)).equals(new java.lang.Float(-0.0))
res1: Boolean = false
```

**Comment by MasseGuillaume** [comment]
There is also lot's of numerical properties about signed zeros: https://softwareengineering.stackexchange.com/questions/280648/why-is-negative-zero-important

**Comment by MasseGuillaume** [comment]
@olafurpg you are right. There is no negative zero for Int or Long.

```scala
java.lang.Long.toBinaryString(0) == java.lang.Long.toBinaryString(-0)
java.lang.Integer.toBinaryString(0) == java.lang.Integer.toBinaryString(-0)
```

**Comment by MasseGuillaume** [comment]
It looks this depends on the Token representation:

```scala
scala.meta.tokens._

object Token {
  object Constant {
    class Double(value: scala.BigDecimal) extends Token
  }
}
```

I don't think it's possible to know if we have BigDecimal("-0D") or BigDecimal("0D")

https://stackoverflow.com/questions/49774540/distinguish-zero-and-negative-zero-with-java-math-bigdecimal

**Comment by olafurpg** [comment]
Fair enough, looks like this is not fixable without changing the token representation for `Constant.Double`, which will not happen since that would be a big breaking change
