### ISSUE TITLE
Add more SymbolOccurence roles

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1386]
In addition to `Definition` and `Reference`-, it would be nice to have a some other roles

* `Import`: to exclude imports from "find all references" or `Disable.symbols` in Scalafix.
* `Extends`: to find all implementation of a class or trait
* `Override`: to find all implementations of a def
* (up for debate) `AliasDefinition`: in Scala it's common to `val EitherAlias = scala.util.Either`, it would be possible to register an `AliasDefinition` at the same location where `EitherAlias` is defined. Would make it easier to find all references to `scala.util.Either` via `EitherAlias`.

This opens the question whether roles are mutually exclusive, if we turn it into a bitmap then it's possible for roles to be both `Import` and `Reference`.

**Comment by xeno-by** [comment]
@olafurpg How about we close this ticket? It's been open for three months, and it looks like there hasn't been a compelling enough use case to warrant extensions to Roles.

**Comment by olafurpg** [comment]
I think this is still an important use-case that would benefit both scalafix and metals. I haven't had time to work on and I don't think I will have time to work on this later this year so I'm fine with closing it instead of leaving it here to grow stale
