### ISSUE TITLE
SemanticDB plugin tempers with ammonite's execution logic

### ISSUE THREAD

**Issue by Baccata** [scalameta/scalameta#1389]
I'd like to have a go at leveraging metals to provide LSP to ammonite scripts. I have some idea of how the different pieces could fit together, but the first hurdle is to make SemanticDB work with ammonite. 

After the [following fix](https://github.com/scalameta/scalameta/issues/1387), running ammonite on the following script : 

```
interp.repositories() ++= Seq(coursier.maven.MavenRepository("https://oss.sonatype.org/content/repositories/snapshots"))

@

import $plugin.$ivy.`org.scalameta:semanticdb-scalac_2.12.4:3.4.0-2-021f7f30-SNAPSHOT`

1+1
```

yields the following error : 

```
macro implementation not found: generateRoutes
(the most common reason for that is that you cannot use macro implementations in the same compilation run that defines them)
  def apply() = ammonite.main.Router.generateRoutes[$routesOuter.type]
                                                   ^
Compilation Failed
```

I believe the semanticDB plugin might be tempering with the way ammonite [uses the compiler](https://github.com/lihaoyi/Ammonite/blob/master/amm/interp/src/main/scala/ammonite/interp/Compiler.scala), maybe because of mutations of analysers / reporters on both sides ? 

I understand the very experimental nature of what I'm trying to achieve and don't expect to get a lot of support on this, but if I could get some pointers from you guys to better understand the problem and attempt to provide a fix, it'd already be awesome !

**Comment by olafurpg** [comment]
It would be awesome to support mill in metals! I have tried mill a bit and my first impressions have been so far great I'm excited to try and use it for my next projects.

The semanticdb compiler plugin emits *.semanticdb files in target under META-INF/semanticdb alongside classfiles (in sbt this is typically something like `target/scala-2.12/classes/META-INF/semanticdb`). The Ammonite compiler seems to use virtual directories for emitting compilation artifacts and seems to discard non-classfiles https://github.com/lihaoyi/Ammonite/blob/7b6beba1c1c0ba27de2bcd9f24eeb777cdb77a8c/amm/interp/src/main/scala/ammonite/interp/Compiler.scala#L345 For metals to work with mill we will need to write *.semanticdb files to a non-virtual directory. In mill, I suppose `out/` would be an acceptable place for that. Any idea how we can detect whether the compiler is running under mill?

Another potential problem that we might encounter is that tree positions are wrong when compiling under ammonite. The SemanticDB format for symbol occurrences (see spec https://github.com/scalameta/scalameta/blob/master/semanticdb/semanticdb3/semanticdb3.md#symboloccurrence) is based on positions. I hit on similar problems when trying to get support for *.sbt files with semanticdb, and I believe the best solution here is to fix upstream tools (sbt/ammonite) to make sure trees have correct positions.

**Comment by olafurpg** [comment]
A few undocumented tricks when developing with semanticdb. I have these aliases in my shell

```
# drop in replacement for scalac
alias metac='coursier launch org.scalameta:metac_2.12:3.4.0 -- -classpath $(coursier fetch org.scala-lang:scala-library:2.12.4 -p)'
# utility to pretty-print *.semanticdb files
alias metap="coursier launch org.scalameta:metap_2.12:3.4.0 --"
```

You can use these to produce semanticdb files 
```scala

➜  target git:(master) cat foo.scala
object a extends App {
  println(42)
}
➜  target git:(master) metac foo.scala
➜  target git:(master) metap META-INF/semanticdb/foo.scala.semanticdb
foo.scala
---------

Summary:
Schema => SemanticDB v3
Uri => foo.scala
Text => non-empty
Language => Scala212
Symbols => 1 entries
Occurrences => 4 entries

Symbols:
_empty_.a. => final object a

Occurrences:
[0:7..0:8): a <= _empty_.a.
[0:17..0:20): App => _root_.scala.App#
[0:21..0:21):  => _root_.java.lang.Object#`<init>`().
[1:2..1:9): println => _root_.scala.Predef.println(Any).
```

`metap` is helpful to see if positions are for example correct, `[1:2..1:9]` means "line 1 column 2 until line 1 column 9".

**Comment by Baccata** [comment]
Awesome, thanks for the information, it'll certainly come in handy 

> Another potential problem that we might encounter is that tree positions are wrong when compiling under ammonite. The SemanticDB format for symbol occurrences (see spec https://github.com/scalameta/scalameta/blob/master/semanticdb/semanticdb3/semanticdb3.md#symboloccurrence) is based on positions. I hit on similar problems when trying to get support for *.sbt files with semanticdb, and I believe the best solution here is to fix upstream tools (sbt/ammonite) to make sure trees have correct positions. 

AFAIK ammonite actually does that (I remember seeing a piece of code that does it in the Ammonite codebase). Will do some digging this week.

**Comment by Baccata** [comment]
Some pointers about tuning the compiler in ammonite : 

* [Loading compiler plugins](https://github.com/lihaoyi/Ammonite/blob/master/amm/repl/src/test/scala/ammonite/session/AdvancedTests.scala#L263-L289) 

* Setting compiler flags on the go : http://ammonite.io/#CompilerFlags

**Comment by olafurpg** [comment]
Thanks for the links! I was able to enable the compiler plugin in the ammonite shell using https://github.com/scalameta/scalameta/commit/91b98c839199c94343167466b3b3d66ad9711568 this change gives a decent workflow to edit semanticdb and run the latest changes in an ammonite repl without having to publish all scalameta modules.

How do you enable compiler plugins for build.sc in mill?

**Comment by olafurpg** [comment]
I naively tried to add

```scala
interp.repositories() ++= Seq(coursier.maven.MavenRepository("file:/Users/ollie/.m2/repository"))
import $plugin.$ivy.`org.scalameta:semanticdb-scalac_2.12.4:3.4.0-5-761b647e`
```
to the top of a build.sc but the custom repository doesn't seem to get picked up.

**Comment by Baccata** [comment]
If you mutate the interpreter to dynamically add repositories, you'll have to turn your script into a [multi-staged](http://ammonite.io/#Multi-stageScripts) one using the magic `@` symbol which gets interpreted by ammonite as "start a new compilation stage" 

Sadly there's no syntax to "statically add repositories". Not sure how that could look tbh

**Comment by Baccata** [comment]
> For metals to work with mill we will need to write *.semanticdb files to a non-virtual directory. In mill, I suppose out/ would be an acceptable place for that. Any idea how we can detect whether the compiler is running under mill ?

There are two things to take into consideration : 
* `out` is to mill what `target` is to sbt : that's where the mill tasks outputs their results / cache 
* what's the mill equivalent of `project/target` ? It used to be under /out, but I recently PR'd mill to be able to have global plugins : https://github.com/lihaoyi/mill/pull/163. 

I believe the output of compiling `build.sc` will be under `$HOME/.mill/ammonite`, so the question is : how do I detect when the compiler is run by ammonite ? Not sure it's doable in the current state of things, but if you know some way a compiler instance could be "annotated", I don't think @lihaoyi 
would oppose a PR that would allow to discriminate the ammonite case. 

As for the location where the `.semanticdb` file relative to `.sc` scripts should live, I think it'd be better to solve the problem for ammonite in general (as opposed to the specific case of mill).

**Comment by olafurpg** [comment]
> how do I detect when the compiler is run by ammonite ? 

I dirty solution could be something like 

```scala
val isAmmonite = global.getClass.getName.startsWith("ammonite")
```

> As for the location where the .semanticdb file relative to .sc scripts should live, I think it'd be better to solve the problem for ammonite in general (as opposed to the specific case of mill).

Sure. The semanticdb files can live wherever per se but it would be best to have an easy-to-reproduce way to map from an ammonite script files like `build.sc` to some location where it's corresponding semanticdb/class files live. In semanticdb lingo we need to know the "target root" and "source root"


* target root, the directory that contains the output from the compiler. In sbt this is typically `classDirectory` and is `target/scala-2.12/classes`
* source root, absolute directory used to absolutize relative filenames inside *.semanticdb files. In metals, we use by convention the "workspace directory" (directory containing build.sc) as the source root.

**Comment by Baccata** [comment]
Compelling point. 

> source root, absolute directory used to absolutize relative filenames inside *.semanticdb files. In metals, we use by convention the "workspace directory" (directory containing build.sc) as the source root. 

Interesting ^^. How does semanticdb know about the "source root" ? A quick look at metals' [sbt plugin](https://github.com/scalameta/metals/blob/master/project/MetalsPlugin.scala) makes me think it's not communicated by the build tool.

**Comment by olafurpg** [comment]
The source root is not persisted to disk because it's not portable across machines. Typically, any tool that loads semanticdb files needs to accept the source root somehow. For example, scalafix has a cli flag --sourceroot, that defaults to the current working directory if it's not provided. In metals, we assume it's the current working directory without a way to configure it.

**Comment by Baccata** [comment]
I [see now](https://github.com/scalameta/metals/blob/00483bd2448acb93822aca8683183ab51eb10136/build.sbt#L178) . I suppose defaulting to `pwd / "out"` is the right way to go then, even if the `out` folder is not used by ammonite in general.  

How would you set the `-P:semanticdb:sourceroot` flag programmatically then ? (I'm not too familiar with scalac's internals)

**Comment by olafurpg** [comment]
The sourceroot should match the workspace directory, which defaults to `sys.props("user.dir")`. IIRC, you can set it programmatically given a `Global` with

```scala
global.settings.processArguments("-P:semanticdb:sourceroot" + sourcerootPath :: Nil, true)
```

Target root should probably be `out/somekey`.

**Comment by Baccata** [comment]
> global.settings.processArguments("-P:semanticdb:sourceroot" + sourcerootPath :: Nil, true)

Gotcha. There seem to be a bug in Ammonite. In the REPL, the compiler-settings mutation gets applied on every execution. I'll try and see if I can fix it and potentially add a pluginOption flag that 
semanticdb could inspect and avoid `global.getClass.getName.startsWith("ammonite")  `

> Target root should probably be out/somekey. 

Am i correct to think that [this](https://github.com/scalameta/scalameta/blob/021f7f30a89d2a28a96ea8be5d34a4f7d9baf9e6/semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SemanticdbPipeline.scala#L15) is the piece of code to amend with the following logic ? 

```
if (the compiler runs in ammonite) 
then (targetRoot == "./out/someKey") 
else (perform as usual)  
``` 

or would you envision it otherwise ? 

> Another potential problem that we might encounter is that tree positions are wrong when compiling under ammonite 

Went back digging and found this : https://github.com/lihaoyi/Ammonite/blob/9db2c21bdb41b939b19b44b63b90a480e374970c/amm/interp/src/main/scala/ammonite/interp/AmmonitePlugin.scala#L282 which is the piece of logic I was talking about. Maybe it won't be sufficient, but considering ammonite prints out correct line/column when a script fails to compile, I'm hopeful ^^

**Comment by olafurpg** [comment]
> Am i correct to think that this is the piece of code to amend with the following logic ?

Correct, but I think it might be worth to refactor targetroot into `SemanticdbConfig.targetroot` where all the other configuration options are defined.

https://github.com/scalameta/scalameta/blob/ee0143562e012109ff5ccea70360ce74eadb86a6/semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/ConfigOps.scala#L7

The default value can be the workingDirectory like sourceroot, but then we override it here https://github.com/scalameta/scalameta/blob/ee0143562e012109ff5ccea70360ce74eadb86a6/semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SemanticdbPlugin.scala#L25 where we have access to a `global`

> but considering ammonite prints out correct line/column when a script fails to compile, I'm hopeful ^^

Fingers crossed.

**Comment by Baccata** [comment]
Taking the liberty to close my own ticket. 

Ammonite behaviour is kept unchanged after https://github.com/scalameta/scalameta/pull/1390 
Following PR takes steps towards providing ammonite support : https://github.com/scalameta/scalameta/pull/1401

Some work is to be done on the ammonite side to accommodate the semanticdb plugin, namely setting `-Yrangepos` before the compiler is instantiated, which might require significant effort since ammonite seems to rely on offsets. 

I'll open subsequent tickets for more specific questions. 

Thank you for the help ^^
