### ISSUE TITLE
Reuse Reporter between metac/metacp/metap

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1397]
In #1394 introduces three identical implementation of `Reporter(out: PrintStream, err: PrintStream)`. This is not sustainable, we should have a reusable implementation. Once langmeta compiles to native we should be able to keep the cli utilites there, alongside `Classpath`/`AbsolutePath`/`FileIO`/`Position` and friends.

I wold love to add more advanced utilities to `Reporter` such as `.error/.warning/.info`. I would consider using that from scalafix instead of rolling my own there. 

Another pattern we could abstract over 
```scala
    scala.Console.withOut(reporter.out) {
      scala.Console.withErr(reporter.err) {
        ScalacMain.process(args.toArray)
      }
    }
```

**Comment by ShaneDelmore** [comment]
If reporter is going to be consolidated and re-used it would be nice to come up with a strategy for playing nice with other utilities that also hijack the reporter.  I have seen conflicts with scala-clippy and ammonite already.

**Comment by olafurpg** [comment]
@ShaneDelmore the hijacking conflicts with clippy is a different issue, this Reporter is not used by semanticdb-scalac.

**Comment by ShaneDelmore** [comment]
Thanks for the clarification @olafurpg
