### ISSUE TITLE
Investigate making metacp parallel

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1398]
In 1cd839e462a7cf9ac1414d9dc553d2e220d44e86 we removed `.par` from metacp to prevent a deadlock. We should consider making metacp parallel again because it's processing steps are trivially parallelizable and in my brief experiments processing spark-sql (110mb of jars) metacp was ~2-3x faster with parallel collections on my machine.

**Comment by gabro** [comment]
@xeno-by / @olafurpg was the deadlock reproducible?

I've naively tried to reintroduce the `.par` and I was able to successfully run `testsJVM/testOnly scala.meta.tests.metacp.*`

**Comment by olafurpg** [comment]
No, I wasn't able to reproduce the deadlock :/

 I suspect the usage of `par.map` was the cause. I use `.par.foreach` with `j.u.ConcurrentLinkedQueue.add` in scalafix/scalafmt and have never experienced problems.

**Comment by olafurpg** [comment]
For the record the deadlock happened with `.toParArray` and not `.par`, that might also be the culprit 🤔 

The benefit with `.foreach` is that we can maybe parallelize over the individual .class files in each classpath. Some entries like the JDK are large

**Comment by olafurpg** [comment]
I've used `.par` + `.foreach` in scalafix and scalafmt for over two years and have never received bug reports about deadlocks. If we revert, what will be the condition that we merge another attempt to make metacp parallel?

**Comment by xeno-by** [comment]
> If we revert, what will be the condition that we merge another attempt to make metacp parallel?
I suggest that we don't merge until: 1) we are able to reproduce the deadlock at will, and 2) we understand that our another attempt will fix the reason behind the deadlock.

**Comment by olafurpg** [comment]
Condition 1) is too strict IMO and it's not consistent with the principles we use to merge other functionality. Metacp is on a critical path for applications like scalafix and running it in parallel makes it faster. I think it's fair that we try my `.foreach` suggestion before blindly rejecting further attempts to make it work.

**Comment by xeno-by** [comment]
Since metacp is planned to become a mandatory dependency of Scalafix, which is used for day-to-day work, I think we could approach this more carefully than, say, new APIs in `contrib` or new features in `metap`.

As a compromise, I suggest: 1) merging the foreach approach, 2) hiding it under `-par` flags in both metacp and scalafix,  3) keeping these flags off by default.

**Comment by olafurpg** [comment]
That sounds like a fair compromise 👍 I will work on this tomorrow
