### ISSUE TITLE
Upgrade scalapb dependency

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1403]
It seems scalapb 0.7.0 final is out, we should upgrade asap.

**Comment by xeno-by** [comment]
I suggest that we wait for Scala Native 0.3.7 before doing the upgrade. Otherwise, we'll have to publish ScalaPB 0.7.0 and (all or some) of its dependencies against our custom fork of Scala Native 0.3.6 (this isn't hard, but it'll take 1-2 hours of our life that we won't be getting back).

**Comment by xeno-by** [comment]
Scala Native 0.3.7 has been staged, but it doesn't work with our build yet (see my attempt at https://github.com/xeno-by/scalameta/commit/6d97eccd4dd8112240980b525a3af6ecb75f18ea):

```
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? r
[info] Loading project definition from /Users/eburmako/Projects/scalameta/project/project
[info] Loading project definition from /Users/eburmako/Projects/scalameta/project
/Users/eburmako/Projects/scalameta/build.sbt:101: error: not found: value NativePlatform
lazy val semanticdb3 = crossProject(JSPlatform, JVMPlatform, NativePlatform)
                                                             ^
/Users/eburmako/Projects/scalameta/build.sbt:187: error: not found: value NativePlatform
lazy val metap = crossProject(JSPlatform, JVMPlatform, NativePlatform)
                                                       ^
sbt.compiler.EvalException: Type error in expression
[error] sbt.compiler.EvalException: Type error in expression
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

Can this happen because we're using `org.portable-scala % sbt-crossproject`? I vaguely remember running into the same problem when I forked Scala Native 0.3.6. /cc @densh

**Comment by xeno-by** [comment]
Fixed in https://github.com/scalameta/scalameta/pull/1464.
