### ISSUE TITLE
Decide on constructor names

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1410]
Even though constructors don't have names written in source code, we do give them names inherited from Scalac internals / VM implementation. This affects:
  * Method symbols, e.g. ``_empty_.C#`<init>`(Int).(p1).``
  * Info names, i.e. `SymbolInformation.name`

I suggest we revisit `<init>`, since this name is something that's never mentioned in the SLS and implemented differently in different backends. I like the idea of using an empty string for constructor names.

**Comment by xeno-by** [comment]
Empty string isn't quite satisfying for constructor symbols, since it creates an annoying ambiguity with parameter symbols. 

E.g. for `_empty_.C#(Int).`, you need to scan the symbol right until the ending `.` to disambiguate it with a parameter symbol that would be written as `_empty_.C#(Int)`. Machines can do that, and humans can do that too, but it's annoying.

**Comment by olafurpg** [comment]
I personally like `<init>` since it's people are already familiar with it as a constructor symbol. Empty name is problematic because it means you don't how how to pronounce it or write about it.

**Comment by xeno-by** [comment]
`<init>` is not portable though - if I recall correctly, both Scala.js and Scala Native have different constructor names.

**Comment by ShaneDelmore** [comment]
Why not just use <constructor>?

**Comment by xeno-by** [comment]
In my opinion, `<constructor>` is similar `<init>` - an artificial name for something that doesn't have a name. It also has the disadvantage of being unfamiliar to everyone, whereas `<init>` is familiar to at least some folks.

**Comment by xeno-by** [comment]
Since didn't have any further suggestions, we'll keep `<init>`. It's one of the few bits of compiler internals that unfortunately leak into SemanticDB, but as long as it's specced (which it is), it's not that bad.
