### ISSUE TITLE
Fix all <?> in metac.expect

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1418]
Looking at lowlevel.expect, there seems to be quite many `<?>` types
https://github.com/scalameta/scalameta/blob/75cd40e35e73ef8987843341e44b0e1fafacf672/tests/jvm/src/test/resources/lowlevel.expect#L126

This could indicate either a bug in metac or in metap. We should fix all of  those cases so there are no more `<?>` remaining.

**Comment by xeno-by** [comment]
It turns out that this ticket is superseded by a combination of: https://github.com/scalameta/scalameta/issues/1426, https://github.com/scalameta/scalameta/issues/1504 and https://github.com/scalameta/scalameta/issues/1585.
