### ISSUE TITLE
Decide on `language` for package symbols

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1420]
It's annoying that for javacp, package symbols are `JAVA`, but for scalacp/metac package symbols are `SCALA`.

**Comment by olafurpg** [comment]
In my opinion, package symbols should set the language. Namespaces are neutral, maybe we should have `Language.NONE`

**Comment by xeno-by** [comment]
Unassigning and pushing this ticket down to the priority list of the RC1 roadmap, since it seems to depend on https://github.com/scalameta/scalameta/issues/1647.

**Comment by olafurpg** [comment]
I've updated the spec in #1660 to say package symbols have empty `language` fields.
