### ISSUE TITLE
Emit correct names/symbols for anonymous definitions

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1421]

**Comment by olafurpg** [comment]
According to the spec on "Name is:" https://github.com/scalameta/scalameta/blob/f7b2d17eb03298ee5049fb5b1bd69a059b608065/semanticdb/semanticdb3/semanticdb3.md

> Name is:
> For anonymous parameter, self parameter or type parameter, an underscore (_).

Seems like this would introduce conflicting symbols for sibling parameters. Should we update the spec to reflect that?

**Comment by xeno-by** [comment]
@olafurpg `SymbolInformation.name` doesn't have to be unique across siblings. Only `SymbolInformation.symbol` does.

**Comment by xeno-by** [comment]
Partially fixed, partially superseded by https://github.com/scalameta/scalameta/issues/1582, https://github.com/scalameta/scalameta/issues/1583, https://github.com/scalameta/scalameta/issues/1584.
