### ISSUE TITLE
Add contract for Term.Try

### ISSUE THREAD

**Issue by MasseGuillaume** [scalameta/scalameta#1423]
In scalac, it's possible to create a try without a catch block or a finally block.

```scala
scala> try 1
<console>:12: warning: A try without a catch or finally is equivalent to putting its body in a block; no exceptions are handled.
       try 1
       ^
```

It's also possible to do this in scalameta:

```scala
Term.Try(Lit.Int(1), Nil, None)
```

I think we should prevent this with asserts:

```scala
require(catchp.nonEmpty || finallyp.nonEmpty)
```

**Comment by olafurpg** [comment]
Why should scalameta disallow it if scalac allows it with a warning?

**Comment by MasseGuillaume** [comment]
Do we have a way to emit a warning as well?

**Comment by olafurpg** [comment]
Nope, that would be the responsibility of a tool like scalafix instead of the parser.

However, I've always wanted to add a `Reporter` to the parser that can be used to report multiple errors etc. Related https://github.com/scalameta/scalameta/issues/1170

**Comment by olafurpg** [comment]
Adding a reporter to the Scalameta parser is not on the roadmap. It is the responsibility of another tool like scalafix to report errors on tree nodes like `try foo()` without finally/catch
