### ISSUE TITLE
Location is unused in SemanticDB

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1440]
`Location` is still listed in https://github.com/scalameta/scalameta/blob/97e1e8af7ba75b7508bc47e25c766c5f83c96e1c/semanticdb/semanticdb3/semanticdb3.proto#L39 and documented in https://github.com/scalameta/scalameta/blob/master/semanticdb/semanticdb3/semanticdb3.md#location despite it not being used anywhere.

**Comment by ShaneDelmore** [comment]
Is this the location of the source of the message?

**Comment by olafurpg** [comment]
It used to be `SymbolInformation.location`, the definition location of a symbol. The field was removed since it wasn't implemented yet, but I suspect it will be supported eventually.

**Comment by xeno-by** [comment]
@olafurpg I suggest we don't do anything here. It's not like `Location` is a major maintenance tax.

**Comment by olafurpg** [comment]
Fair enough
