### ISSUE TITLE
Release semanticdb-scalac for 2.12.5

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1445]

**Comment by xeno-by** [comment]
Looks like Scala 2.12.5 is critically broken (https://github.com/scala/scala-dev/issues/480). Let's wait a little bit to see whether it's here to stay or it'll be superseded by Scala 2.12.6 shortly afterwards.

**Comment by fommil** [comment]
I had a look at locally publishing 2.1.8 so I could use it with scalafix but there are compilation errors.

BTW, if in the future you need to make a release for a new version of scala without any source changes, but `sbt-dynver` trips you up on the version label, you can create a file like `hack.sbt` in the base directory containing the version override

```
version in ThisBuild := "2.1.8"
```

**Comment by olafurpg** [comment]
@fommil `sbt -Dscalameta.version=2.1.8` should do the trick to override the dynamic version. We'll likely wait for the macro issues to be resolved before publishing for 2.12.5. Typically, it requires quite a bit of manual work to upgrade semanticdb-scalac because it touches on a large surface of compiler internals (so other tools like scalafix don't have to 😄 )

**Comment by xeno-by** [comment]
2.12.6 is planned to be released in about 2 weeks: https://contributors.scala-lang.org/t/scala-2-12-6-coming-soon/1729. I suggest we don't bother upgrading unless there's a pressing need.
