### ISSUE TITLE
Add metap -scala

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1448]
As suggested by @olafurpg, let's introduce a third prettyprinting mode to metap that prints type signatures in Scala syntax, much like javap and scalap.

**Comment by olafurpg** [comment]
I have unmerged code in Scalafix to turn s.Type into scala.meta.Tree, which we should be able to reuse for this purpose

**Comment by olafurpg** [comment]
This option will require the ability to lookup a `SymbolInformation` for any symbol in the classpath, something like `def info(symbol: String): Option[SymbolInformation]`

**Comment by xeno-by** [comment]
Alright, then it probably shouldnt be on the board just yet, since we've got to implement some other stuff first.

**Comment by xeno-by** [comment]
Superseded by https://github.com/scalameta/scalameta/issues/1644.
