### ISSUE TITLE
scala.meta.Input.File: Too many open files

### ISSUE THREAD

**Issue by MasseGuillaume** [scalameta/scalameta#1462]
To reproduce:

```scala
import scala.meta._
import scala.meta.testkit.{Corpus, CorpusFile}
import java.nio.charset.StandardCharsets

Corpus.files(Corpus.fastparse).map{file =>
  val jFile = file.jFile
  val input = Input.File(jFile, StandardCharsets.UTF_8)
  input.parse[Source].get
}
```

https://github.com/scalameta/scalameta/blob/ed8480bfe65ebbe9263e523486541619d88f0b52/langmeta/langmeta/jvm/src/main/scala/org/langmeta/internal/io/PlatformFileIO.scala#L50-L51

I think we should call `.close()` on the Source.

```scala
val buffer = scala.io.Source.fromFile(path.toFile)(scala.io.Codec(charset))
val text = buffer.mkString
buffer.close()
text
```

**Comment by olafurpg** [comment]
General rule of thumb is "don't use Input.File". But yes we should definitely close the source, probably best to use nio.Files
