### ISSUE TITLE
Simple compiletime lints

### ISSUE THREAD

**Issue by fommil** [scalameta/scalameta#1466]
I have an example of a lint that I want to see with the compile, not after in a separate linting stage: I want to ban the compiler inferring `Nothing`. I can imagine there being more examples.

It might be good if the scalac-semanticdb plugin allowed the user to apply some very simple rules that could abort the compile. I'm really thinking of a minimal variant of the scalafix `Disable` rule that can be applied on semanticdb data directly without requiring the scalameta ast.

Perhaps this is best as a separate compiler plugin, but that seems very adhoc.

**Comment by olafurpg** [comment]
I'm afraid this is outside of the scope of the semanticdb compiler plugin. 

I understand it would be nice to have certain errors on compile. There is a great recent article about this from Google (behind a pay wall I'm afraid) https://m.cacm.acm.org/magazines/2018/4/226371-lessons-from-building-static-analysis-tools-at-google/abstract

 Any reason you don't can't use Wartremover for this purpose?

**Comment by fommil** [comment]
Wartremover does too much, in the context of scalafix existing. A new plugin would be better.

**Comment by olafurpg** [comment]
Lint on compile is very sensitive to effective false positives. Have you considered proposing those warnings to scala / scala?

**Comment by olafurpg** [comment]
I thought Wartremover was configurable and extensible so you could enable the rules you want.

**Comment by fommil** [comment]
wartremover includes far too much at this point, maybe it can get a second wind as a linter for things that aren't suitable for scalafix.
