### ISSUE TITLE
Line numbers and columns are off-by-one

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1487]
Line and column numbers in semanticdb currently start at 0 when they should start at 1. I hit on this problem while upgrading metadoc, and added `+1` when converting semanticdb ranges to monaco ranges.

Fixing the problem is easy and binary compatible, but will require regeneration of all payloads and potentially break code in subtle ways.

**Comment by xeno-by** [comment]
Why should line and column numbers start from 1?

To quote the LSP spec (which our spec is written after in that area): "Position in a text document expressed as zero-based line and zero-based character offset".

**Comment by olafurpg** [comment]
Phew, that sounds good. I have no preference either way, as long as it's justified. Let's keep it unchanged then. Link to the LSP spec for those interested https://microsoft.github.io/language-server-protocol/specification#text-documents

**Comment by fommil** [comment]
it's convention in editors (and in scalac) to count from 1, so I guess everybody is going to have to handle this multiple times.

I'm not surprised that the LSP spec does it the wrong way.

**Comment by ShaneDelmore** [comment]
It’s convention in editors to display starting at 1, but in code I believe it varies.  I was just working with line number and column index in IntelliJ yesterday and it uses 0 based indexing from the api, while 1 based for the display.

**Comment by fommil** [comment]
C, you have much to answer for.
