### ISSUE TITLE
detect toString (and other) calls on primitive values

### ISSUE THREAD

**Issue by fommil** [scalameta/scalameta#1488]
It would be very useful to be able to detect methods on primitives, e.g.

```scala
  implicit val long: UrlEncodedWriter[Long] = { (n: Long) => n.toString }
```

which currently resolves to

```
[36:6..36:14): toString => scala.Any#toString().
```

but I'd like to see

```
[36:6..36:14): toString => scala.Long#toString().
```

or, at least

```
[36:6..36:14): toString => scala.AnyRef#toString().
```

This impacts scalafix `Disable` rules.

**Comment by olafurpg** [comment]
This boils down to getting the type of a term which is tracked in https://github.com/scalameta/scalameta/issues/1212.
