### ISSUE TITLE
Token inference

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#149]
[Tokens](https://github.com/scalameta/scalameta/blob/8b71a66000fcc5e6b8e6213122079fb2e460d0e0/scalameta/src/main/scala/scala/meta/syntactic/Token.scala) are our way of comprehensively capturing syntactic details of Scala source code. Each scala.meta tree has an associated collection of tokens that keep track of everything that comprises its corresponding source code, including whitespace, comments, etc.

Our parser automatically populates tokens for the trees that it emits (that means that trees that come from human-written source code are guaranteed to have tokens), but tokens for synthetic trees (e.g. ones that are created via tree transformations) are currently stubbed: https://github.com/scalameta/scalameta/blob/master/scalameta/src/main/scala/scala/meta/internal/ui/InferTokens.scala.

**Comment by xeno-by** [comment]
Actually we already have a pull request courtesy of @mdemarne that implements this functionality: https://github.com/scalameta/scalameta/pull/141, and we just need to review and merge it.

**Comment by xeno-by** [comment]
Initial support for token inference has landed in https://github.com/scalameta/scalameta/pull/170. https://github.com/scalameta/scalameta/pull/141 is still pending review though.

**Comment by xeno-by** [comment]
I think that we might need to revert #170 because of:
1) Significant performance degradation of prettyprinting: https://github.com/xeno-by/scalahost/commit/8e0d0d2d533de352a6bbf4e2009b485ef581792f
2) Style.Lazy/Style.WithFfi were essential to semantic tests in scalahost: https://github.com/xeno-by/scalahost/commit/7f4a598df5e304badb049e4c978bc015bb9737b9
3) Some uncommon use cases for prettyprinting ended up being printed incorrectly: https://github.com/xeno-by/scalahost/commit/8e0d0d2d533de352a6bbf4e2009b485ef581792f

/cc @mdemarne

**Comment by xeno-by** [comment]
It seems that even after merging #170, layout inference works only in very few places in language's syntax.

**Comment by mdemarne** [comment]
I like the idea of #226, it would make the system simpler. The question now is whenever `inferToken` could use a good mechanism it in order to persist the comment in `/* Comment */ class C` under transformation of the `Defn.Class(...)` itself (or any of its subtrees). By doing so, even changing the class itself would keep the comment.

**Comment by xeno-by** [comment]
I think this issue should be handled by 0.1, because precise prettyprinting is a big part of scala.meta's value proposition.

The current system is quite broken in all but a few hardcoded cases. Two biggest issues that I'm thinking of right now:
  * Necessity to know one's parent to retain leading/trailing trivia. Those tokens aren't associated with a tree, but are only present in the parent's token collection.
  * Possibility for parent's and child's trivia to become unsynchronized. If we take a source with a bunch of declarations and then transform one of them, then we need to analyze source's tokens to cut out the transformed part and replace it with the tokens of the transformed child.

Roslyn proposed the following design: a) trivia is associated with trees that it "belongs to" as described in #226, b) tokens are part of the CST (https://msdn.microsoft.com/dynimg/IC776863.png, see https://msdn.microsoft.com/en-us/magazine/dn904670.aspx for details). This design seems to fix both aforementioned issues, so I believe that we should go for it for 0.1.

**Comment by xeno-by** [comment]
Superseded by #379. Now that `Tree.tokens` don't play a foundational role due to changes in 9688110, the future of format-aware prettyprinting of semi-synthetic trees may very well lie outside the domain of token inference.
