### ISSUE TITLE
Polish the semantic index

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1490]
This is a proposal to change how the index file `META-INF/semanticdb.semanticidx` works

- move to `META-INF/semanticdb/indexes` so that all semanticdb related files are in the same directory
- change `semanticidx3.proto` schema to
```proto
message Indexes {
  repeated Index indexes = 1;
}
message Index {
  // keys are symbols, values are uri to semanticdb files
  repeated map<string, string> toplevels = 1;
}
```
- change contents of `indexes` file to be payloads of `Indexes` to enable merging of indexes via byte concatenation.

**Comment by olafurpg** [comment]
While refactoring the file location, we should also take the opportunity to introduce
```proto
message Indexes {
  repeated Index indexes = 1;
}
```
which will be the binary payloads contained in `semanticdb.semanticidx`. This enables users to safely concatenate such payloads while with tools like sbt-assembly without breaking SemanticDB functionality.

**Comment by xeno-by** [comment]
Another potential change that we discussed is removing `PackageEntry.member`, since they are currently unused by Scalafix.

**Comment by olafurpg** [comment]
Additionally, I propose we change the schema for `Index` to look like this

```proto
message Indexes {
  repeated Index indexes = 1;
}
message Index {
  repeated map<string, ToplevelSymbols> package_members = 1;
}
message ToplevelSymbols {
  repeated ToplevelSymbol symbols = 1;
}
message ToplevelSymbol {
  string symbol = 1;
  string uri = 2; // relative URI to semanticdb file containing full information
}
```

The filename should be `META-INF/semanticdb/indexes`.

**Comment by xeno-by** [comment]
I suggest something simpler that doesn't encode package members who doesn't have a use case at the moment.

```protobuf
message Indexes {
  repeated Index indexes = 1;
}
message Index {
  repeated map<string, ToplevelSymbol> toplevels = 1;
}
message ToplevelSymbol {
  string uri = 1; // relative URI to semanticdb file containing full information
}
```

I'm fine with the proposed filename.

**Comment by olafurpg** [comment]
Sounds good, we can simplify that even further
```proto
message Indexes {
  repeated Index indexes = 1;
}
message Index {
  // keys are symbols, values are uri to semanticdb files
  repeated map<string, string> toplevels = 1;
}
```
