### ISSUE TITLE
scala.Singleton is missing from scala-library-synthetics

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1496]
I can't find reference to `scala.Singleton` in scala-library so I suspect it needs to be synthesized like Any/AnyRef and friends.
https://github.com/scalameta/scalameta/blob/0b41ec6a0cac00eef35fc043a74e6cffda12afdc/semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/Scalalib.scala

**Comment by gabro** [comment]
See also https://github.com/scala/scala/blob/6ff3facb1791f54ad10fbf44059d892e5fd00510/src/reflect/scala/reflect/internal/Definitions.scala#L1328-L1361
