### ISSUE TITLE
Remove LOCAL as a kind

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1503]
Currently, `LOCAL` is a kind. In #1502, the kind for local class/def/val/var are all changed to `LOCAL` because those symbols are not accessible globally. However, making the kind `LOCAL` for those symbols means loosing the ability to distinguish local def/val/object/class. Given that local symbols must start with `local*` there is no need to store in the kind whether a symbol or `LOCAL` or not

**Comment by xeno-by** [comment]
By the way, why do we need `p.LOCAL`? Isn't checking `info.symbol.startsWith("local")` enough?

**Comment by olafurpg** [comment]
Good point @xeno-by I agree, I've updated the title and description to be about removing `k.LOCAL` (without proposing `p.LOCAL`)

**Comment by xeno-by** [comment]
Actually, `k.LOCAL` means something else (the fact that a val, a var or a pattern variable aren't defined as a member - meaning they aren't modelled as `k.FIELD` or `k.METHOD`). All `k.LOCAL` symbols must be `localNNN`, but not vice versa. 

However, the naming aspect of this is clearly confusing. Any suggestions about what could be done here?

**Comment by olafurpg** [comment]
`k.LOCAL` is staying for local variables inside block (whatever gets allocated on the stack).
