### ISSUE TITLE
Use delegating reporter error/warn/info count

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1505]
Following up from discussion in https://github.com/ghik/silencer/issues/7#issuecomment-383330461

It would be smart if our reporter used info/warn/error counts from the delegating reporter. 
Example how this can be done https://github.com/ghik/silencer/blob/099138fff63d3060ddb70be11d65f4cd73e3a6c5/silencer-plugin/src/main/scala/com/github/ghik/silencer/SuppressingReporter.scala#L44-L48
If anyone wants to take a stab at this, a good place to start would be https://github.com/scalameta/scalameta/blob/110147dfa610b7859623ff2aad7f5ee3abbc60b3/semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SemanticdbReporter.scala

**Comment by ghik** [comment]
The workaround mentioned in https://github.com/ghik/silencer/issues/7#issuecomment-383330461 no longer works because reporters changed in Scala 2.13.1 (https://github.com/scala/scala/pull/8338). `SemanticdbReporter` needs to be rewritten for Scala 2.13.1+

**Comment by olafurpg** [comment]
> SemanticdbReporter needs to be rewritten for Scala 2.13.1+

Can you elaborate? Our tests are passing on 2.13.1 with the current implementation but if I understand correctly we need to make some changes to make it play nicely with other plugins that also change the reporter?

**Comment by ghik** [comment]
Yes, the problem only arises in interaction with other compiler plugins like silencer. However, the API used by `SemanticdbReporter` is deprecated in 2.13.1 so it should be ported anyway. The new API eliminates the necessity to manually track error/warn/info count.

**Comment by olafurpg** [comment]
Thanks for the explanation! Makes sense.

**Comment by bmarker** [comment]
I seem to be having a similar problem with Scala 2.12.17. I wonder if the reporter change was ported back to 2.12.17.

The fix checks for 2.13.0. Maybe it needs to check for some 2.12.x patch as well.

**Comment by bmarker** [comment]
Looks to me like the reporter change from 2.13.1 was also merged into 2.12.13.
