### ISSUE TITLE
TODO: Obtain charset from Global.reader.

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1509]
#1506 removed the following TODO 
https://github.com/scalameta/scalameta/blob/110147dfa610b7859623ff2aad7f5ee3abbc60b3/semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/InputOps.scala#L27

I'm not sure what the TODO means, assigning ticket to @xeno-by

**Comment by xeno-by** [comment]
This hasn't been a problem.
