### ISSUE TITLE
release for scala 2.12.6

### ISSUE THREAD

**Issue by fommil** [scalameta/scalameta#1515]
![](https://thecatmademedoit.com/wp-content/uploads/2017/05/c5d5b517c9a526eb953dd4fd121667040b3512959c8de616ec8f2f01190d3540.jpg)

**Comment by olafurpg** [comment]
I am excited myself to upgrade, the new setting to cache compiler plugin classloaders may speed up compilation with semanticdb-scalac up to 15%! I haven't been able to try upgrading until this morning thanks to https://github.com/scalamacros/paradise/issues/116

Upgrading patch versions for SemanticDB requires more work than bumping up a version number in build.sbt due to the fact that semanticdb-scalac instruments several steps in typer to recover lost syntactic structure. I took a quick look at what changed between 2.12.4 and 2.12.6 in scalac `Typers` and the diff is ~300 loc so I will need to through that one by one https://gist.github.com/olafurpg/864d497882689e0b8d0a0d25f4840c08 

I'm at flatMap(Oslo) this week so I'm afraid I won't have time to look into this until next week.

**Comment by fommil** [comment]
Disgraceful, you should give everybody their money back :stuck_out_tongue:

**Comment by olafurpg** [comment]
This is on my queue after https://github.com/scalacenter/scalafix/issues/704

**Comment by ochrons** [comment]
This is also blocking sbt 1.1.5 usage, since it seems to use 2.12.6, which leaks into sbt plugins requiring semanticdb 2.12.6, which is not available.

```
Downloading https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.6/2.1.7/semanticdb-scalac_2.12.6-2.1.7.pom
Downloading https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.6/2.1.7/semanticdb-scalac_2.12.6-2.1.7.pom.sha1
[error] coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]     org.scalameta:semanticdb-scalac_2.12.6:2.1.7:
[error]         not found:
[error]             C:\Users\oc\.ivy2\local\org.scalameta\semanticdb-scalac_2.12.6\2.1.7\ivys\ivy.xml
[error]             https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.6/2.1.7/semanticdb-scalac_2.12.6-2.1.7.pom
[error] (coursierResolutions) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]     org.scalameta:semanticdb-scalac_2.12.6:2.1.7:
[error]         not found:
[error]             C:\Users\oc\.ivy2\local\org.scalameta\semanticdb-scalac_2.12.6\2.1.7\ivys\ivy.xml
[error]             https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.6/2.1.7/semanticdb-scalac_2.12.6-2.1.7.pom
```

**Comment by olafurpg** [comment]
@ochrons how are you using semanticdb-scalac with sbt 1.1.5? semanticdb-scalac is intended to be used only for compiling normal project sources, not sbt builds.

**Comment by olafurpg** [comment]
I apologize the slow reponse, past weeks have been busy with conference. I've been at ScalaDays all this week. I will take a look at this issue next week before continuing https://github.com/scalacenter/scalafix/issues/704

**Comment by ochrons** [comment]
@olafurpg I have no idea where the semanticdb-scalac comes from, but if I change sbt version from 1.1.4 to 1.1.5 I get that error 😅 

The project uses Scala 2.12.4

My sbt plugins are
```scala
addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.0")

addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.2.2")

addSbtPlugin("se.marcuslonnberg" % "sbt-docker" % "1.4.1")

addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.6")

addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.22")

addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.12")

addSbtPlugin("com.vmunier" % "sbt-web-scalajs" % "1.0.6")

addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "1.1.2")

addSbtPlugin("org.irundaia.sbt" % "sbt-sassify" % "1.4.12")

addSbtPlugin("com.typesafe.sbt" % "sbt-digest" % "1.1.3")

addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.2")

addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "1.5.1")

addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.5.10")
```

**Comment by fommil** [comment]
if you're not specifying a default `scalaVersion` I think it falls back to the same version of scala used by sbt. You should be able to fix this with 

```
scalaVersion in ThisBuild = "2.12.4"
```

I bet you forgot the `in ThisBuild` bit. Everybody forgets it.

**Comment by ochrons** [comment]
The `in ThisBuild` seems to have been The Trick, thanks Sam! I recently migrated this project from sbt 0.13 to 1.x...

**Comment by olafurpg** [comment]
Opened #1557 upgrading to 2.12.6 :)

**Comment by olafurpg** [comment]
scalameta/paradise for 2.12.6 is on it's way to Maven Central, please note that scalameta/paradise is no longer under development and will not support 2.13. Please migrate to https://docs.scala-lang.org/overviews/macros/annotations.html those macro annotations are supported natively by the compiler in 2.13 under the scalac option -Ymacro-annotations https://github.com/scala/scala/pull/6606

**Comment by hepin1989** [comment]
```sbt
scalaVersion := "2.12.6"

scalafixSemanticdbVersion := "4.0.0-M1"
```

**Comment by EmergentOrder** [comment]
Could you release this for 2.12.7?
Thanks!

**Comment by olafurpg** [comment]
@EmergentOrder I opened https://github.com/scalameta/scalameta/issues/1781 to track this 😉

**Comment by EmergentOrder** [comment]
@olafurpg Yeah that'd be the right way to do this :stuck_out_tongue: 
oops
