### ISSUE TITLE
Is scalameta as powerful as the old macro system?

### ISSUE THREAD

**Issue by doofin** [scalameta/scalameta#1520]
I saw that in home page it says: 
`Originally, Scalameta was founded to become a better macro system for Scala, but over time we shifted focus to developer tools and spun off the new macro system into a separate project.`

What's the difference between them?

**Comment by olafurpg** [comment]
Scalameta does not support macros. It is recommended to use the macros that are included with the scala compiler and are documented here https://docs.scala-lang.org/overviews/macros/overview.html those macros are used by most major libraries like scalatest/sbt/circe/...

The latest update on future macros is here https://www.scala-lang.org/blog/2018/04/30/in-a-nutshell.html with the roadmap to be released sometime early 2020.
