### ISSUE TITLE
Remove scala.meta.{Symbol,Signature} 

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1525]
Now that SemanticDB symbols are primarily strings, we should no longer expose `scala.meta.{Symbol,Signature}` in the public API.

**Comment by xeno-by** [comment]
@olafurpg Do we want this in 4.0.0?

**Comment by olafurpg** [comment]
I am leaning towards keeping them since there's quite a bit of code that uses symbols and there's no equivalent alternative. Need more time to think about it

**Comment by xeno-by** [comment]
Let's keep it in 4.0.0 for now, and if we decide against this ticket in the end, we'll just remove the milestone assignment.

**Comment by olafurpg** [comment]
I propose to move Symbol and Signature to package `scalafix.v0` like we do with Database and friends in https://github.com/scalacenter/scalafix/pull/737 In `scalafix.v1` a symbol will be a wrapper around a string
