### ISSUE TITLE
semanticdb.semanticidx does not play nicely with incremental compilation

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1528]
Steps to reproduce https://github.com/olafurpg/semanticdb-zinc/commit/60ac13efe7604c2177a3d4fc6523210fa3007615

We need to figure out how to make semantic.semanticidx handle incremental compilation.

**Comment by olafurpg** [comment]
Seems the best testing strategy for bugs like this is to use the sbt scripted framework https://www.scala-sbt.org/1.0/docs/Testing-sbt-plugins.html this enables us to reproduce longs chains of actions and write assertions in plain scala code.

**Comment by olafurpg** [comment]
Another idea is to depend on bloop as a library and write unit tests that write `.bloop/*.json` files with configuration and programmatically trigger `bloop compile <id>`. This would run faster than scripted tests as part of `testsJVM/test`. Maybe it's possible to do the same directly with zinc, but I have no experience with zinc.

**Comment by xeno-by** [comment]
Sure, let's give it a try.
