### ISSUE TITLE
Unapply returns String for Lit.Double and some others

### ISSUE THREAD

**Issue by aishfenton** [scalameta/scalameta#1535]
The unapply of `Lit.Double` returns a string value rather than a double.  

```
val Lit.Double(v) = "2.0".parse[Stat].get
v != 2.0
v == "2.0"
```

This is in contrast to Lit.Byte and Lit.Int that work as expected (i.e. they return a Byte and Int).

**Comment by olafurpg** [comment]
Thanks for reporting! This is working as intended to support multiple platforms (JS/JVM). There's a note in the source code for why doubles are treated this way
https://github.com/scalameta/scalameta/blob/e72245f7a0f1c56f592701b5df112cc24065aa18/scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala#L50-L54

`Lit.Double.value` gives you a parsed `Double` value
