### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#154]
There is already a lot in scala.meta, and there are early adopters (https://github.com/metadoc/metadoc and http://blog.codacy.com/2015/06/04/a-quick-look-at-scalameta/) who are using it to solve practical issues. However, there are no comprehensive guides that describe available functionality and give lightweight examples (the [readme](https://github.com/scalameta/scalameta/blob/master/README.md) in this repo introduces some of the key concepts, but it's by no means exhaustive, and [scalameta/example](https://github.com/scalameta/example) is very much a DYI thing + the build is quite scary).

**Comment by xeno-by** [comment]
As per @Dveim's suggestion, we should document the concept of Quasi types and why their exact runtime type is important.

**Comment by xeno-by** [comment]
https://github.com/scalameta/tutorial is quite basic, but at least it's a start. I'll try to expand it when I get a chance (most likely in winter).

**Comment by xeno-by** [comment]
See #307

**Comment by xeno-by** [comment]
Don't forget to update https://github.com/scalameta/tutorial, which is currently written against quite an old version - 0.0.4.

**Comment by xeno-by** [comment]
We also need to publish scaladocs and make sure we don't expose internal stuff.

**Comment by xeno-by** [comment]
Looking forward to having time to check out @olafurpg's pull request that adds a skeleton of a scalatex documentation page: https://github.com/scalameta/scalameta/pull/387.

**Comment by xeno-by** [comment]
It would be nice to publish scaladocs automatically by the upcoming Drone build (see #400 for details).

**Comment by fommil** [comment]
I don't think you need to publish scaladocs with any more effort than `sbt publish`. That will publish the javadocs (scaladocs) to sonatype and there are now web services that will host those things as browsable web pages. I don't care so much in ENSIME because it has a javadoc/scaladoc file server for all files in the project :grinning:

**Comment by xeno-by** [comment]
@fommil Could you point to some of these services? I found javadoc.io, but it seems unreliable (down for the at the moment) and only working with javadocs.

**Comment by fommil** [comment]
Oh that's the one I meant. Doesn't it also support scaladoc?

Why do you want to publish the javadocs on a web server anyway since all IDEs can use a downloaded jar?

**Comment by olafurpg** [comment]
It should be straightforward to publish the scaladocs for the latest release to the gh-pages branch. If you want to have public links to the scaladocs for each released version it's gets trickier but should still be possible.

**Comment by xeno-by** [comment]
Situation with docs is partially fixed by https://github.com/scalameta/scalameta/pull/417.

Since https://github.com/scalameta/scalameta/pull/410, we have a better-looking website. Now the website, clearly states our mission, provides instructions on getting started, showcases most features with basic REPL examples and explains our roadmap.

I'd love to do more and comprehensively explain the feature set that we have and provide tips & tricks. However, I've got to hand in my thesis in less than three months, so I should really get to writing. 

Verdict: Not closing this issue, but removing the "1.0" milestone tag from it.

**Comment by xeno-by** [comment]
If you'd like to contribute to the documentation, it's actually pretty easy. You just have to modify https://github.com/scalameta/scalameta/blob/master/readme/Readme.scalatex, which is pretty self-explanatory. The best thing about our new infrastructure that it provides a neat facility to automatically execute code in REPL and insert printouts into the generated website.

**Comment by olafurpg** [comment]
The new documentation looks gorgeous. An excellent start 👏

**Comment by xeno-by** [comment]
Here's the @olafurpg's tutorial that has been recently given at ScalaWorld 2016: https://github.com/olafurpg/scala.meta-workshop.
