### ISSUE TITLE
Consider dropping -P:semanticdb:symbols:all

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1576]
In metacp days, `-P:semanticdb:symbols:all` was pretty much required for doing non-trivial Scalafix refactorings. Nowadays, with metacp working pretty well, the need in `symbols:all` is basically gone, but the maintenance burden is non-trivial.

**Comment by olafurpg** [comment]
You mean `-P:semanticdb:symbols:all`? I vote in favor of this while admitting that the setting may still be useful in some niche use-cases. The maintenance burden is real and in projects like metals/scalafix/metadoc I consider it a bug if `-P:semanticdb:symbols:definitions` is not enough

**Comment by xeno-by** [comment]
Yep, `-P:semanticdb:symbols:all`, indeed. Thanks - I've updated the ticket.
