### ISSUE TITLE
More precise prettyprinting layouts

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#164]
After https://github.com/scalameta/scalameta/issues/149 is implemented, we'll have basic support for merging different trees together using a simple 2-space indentation scheme. It would be nice to make it possible for the users to customize this scheme by providing various options for the token inferencer.

**Comment by xeno-by** [comment]
There's a discussion going on about this in a dedicated gitter channel. Please let me know if you're interested in following this topic, and I'll add you to the discussion.

**Comment by RSchulz** [comment]
I have a strong interest in code formatting some experience with generating surface level syntax from  ASTs. Perhaps I could help out. Would you mind adding me to that discussion channel?

**Comment by xeno-by** [comment]
This is a wishful thinking part of another wishful thinking ticket (#149) that ended up not working. Please follow https://github.com/scalameta/scalameta/issues/379 for a discussion about a practical subset of this functionality.
