### ISSUE TITLE
Index generation breaks for Java-only compilation

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1643]
While working on #1641 I observed that incrementally compiling only Java sources in a hybrid Java/Scala module causes semanticdb-scalac to be ignored. Thanks to @Duhemm's observation, if there are no Scala compilation units to compile then Zinc does not invoke the Scala compiler at all: https://github.com/sbt/zinc/blob/58a07868e29232fdfc861258ff1a00b554fb349e/zinc/src/main/scala/sbt/internal/inc/MixedAnalyzingCompiler.scala#L69

This implies hybrid Scala/Java projects are likely to produce incorrect symbol indices during incremental compilation.

We could report an issue to zinc since this behavior is inconsistent with how the `scalac` command-line triggers compiler plugins even when all units are Java

```
$ cat A.java && \
  scalac -Xplugin:$(coursier fetch --intransitive org.scalameta:semanticdb-scalac_2.12.6:4.0.0-M4) -P:semanticdb:profiling:on A.java
public class A {}
Created 1 semanticdb file in /Users/ollie/dev/scalameta/target/META-INF/semanticdb
```

However, I think we enter a rabbit's hole if we continue to use semanticdb-scalac to handle incremental compilation in hybrid Java/Scala projects. I think it's a better solution to require a clean compilation for hybrid projects and invest instead in creating a Java compiler plugin semanticdb-javac to handle Java compilation units.

**Comment by xeno-by** [comment]
@olafurpg Is this still relevant?

**Comment by olafurpg** [comment]
Index generation has been removed from metac so this is no longer relevant.
