### ISSUE TITLE
Provide {Signature/Type}.toScalaString

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1644]
Based on our internal feedback, I think it would be beneficial to have a facility to stringify a signature for prettyprinting purposes. I think that metap is too involved to reuse it, so a simple recursive pattern match should be enough here.

**Comment by olafurpg** [comment]
To make it easier to call metap programmatically for individual symbols I wrote these utilities
```scala
  implicit class XtensionTextDocumentSymtab(doc: s.TextDocument) {
    private def withPrinter(f: DocumentPrinter => Unit): String = {

      val out = new ByteArrayOutputStream()
      val reporter =
        scala.meta.cli.Reporter().withOut(new PrintStream(out)).withErr(new PrintStream(out))
      val settings = scala.meta.metap.Settings().withFormat(Format.Detailed)
      val printer = new DocumentPrinter(settings, reporter, doc)
      f(printer)
      out.toString()
    }
    def info(sym: String): s.SymbolInformation =
      doc.symbols.find(_.symbol == sym).getOrElse(throw new NoSuchElementException(sym))
    def syntax: String = withPrinter(_.print())
    def infoSyntax(sym: String): String = withPrinter(_.pprint(this.info(sym)))
  }
```

I think it would be good to expose something like this from `import scala.meta.internal.semanticdb._`.

**Comment by xeno-by** [comment]
I'm inclined to close this ticket as wontfix, because there doesn't seem to be a one-size-fits-all solution here:
  * In Metap, we'd want one style of prettyprinting (because we're interested in more details and don't mind seeing internals). 
  * In Metals, we'd want another style (because the users of Metals care about eye candy, and we wouldn't want to expose them to internals).
  * Other applications, like Scalafix, may want fully-qualified or partially-qualified prettyprinting to prevent inadvertent name capture.

In the future, I propose that we start with domain-specific prettyprinting and then upstream that logic to Scalameta only if it can be shared between multiple domains.
