### ISSUE TITLE
Use slash / for package symbols

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1647]
Currently, SemanticDB package symbols use `.` like for `scala` in `scala.Predef.String#`. This is problematic since it's not possible to distinguish packages from Scala objects like `Predef`. I propose we change the format to be `scala/Predef.String#` instead. The benefit of this strategy is that we can stop persisting package symbols altogether and we can implement lookup for packages with a stateless method like this

```scala
def info(symbol: String): SymbolInformation =
  if (symbol.endsWith("/")) SymbolInformation(symbol, k.PACKAGE)
  else ???
```

We currently have problems like https://github.com/scalameta/scalameta/issues/1420 where package symbols are attributed different languages in metac/scalacp/javacp.

A downside to this change is that it's less natural to write `scala/collection/immutable/List#` than `scala.collection.immutable.List#` and it's breaking with existing code that hardcodes strings. To smoothen the breaking change, it's possible to support `a.b.c.D#` symbols by automatically converting them to `a/b/c/D#` behind the scenes if you know which which symbols are packages.

**Comment by xeno-by** [comment]
I'm tentatively assigning this ticket to RC1 while we're figuring out whether we want to tackle it at the 11th hour of the release.
