### ISSUE TITLE
Make targetroot configurable in metac

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1671]
Metac should support `-P:semanticdb:targeroot:<path>` to override the default which matches `-d`. There are valid cases where users might not want to persist SemanticDB files alongside classfiles. If the custom targetroot ends with `.jar` then metac should compress the output files into a jar file instead of directory.

**Comment by xeno-by** [comment]
After having implemented this functionality, we'll also need to update the Java compiler plugin to use the same UI.

**Comment by olafurpg** [comment]
> After having implemented this functionality, we'll also need to update the Java compiler plugin to use the same UI.

The Java compiler plugin already requires targetroot to be provided as ```"-Xplugin:semanticdb <target-dir> --sourceroot <source-root>"``` since it doesn't have access to the compiler output directory.

**Comment by xeno-by** [comment]
Fixed in https://github.com/scalameta/scalameta/pull/1743.
