### ISSUE TITLE
Implement metai

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1689]
https://github.com/scalameta/scalameta/pull/1682 removes support for `.semanticidx` to simplify the codebase and streamline SemanticDB generation for the common case. 

However, this is critical for our Symtab in Rsc (https://github.com/scalameta/scalameta/pull/1682#issuecomment-403993748), which is why we decided to keep the semantic index fuctionality, spinning index generation into a standalone tool called `metai`. This way common case would stay simple, and more advanced cases don't regress.

Here is the schema that I propose for `.semanticidx` (Note the `PackageEntry` message - we need this functionality in Rsc):

```protobuf
message Indexes {
  repeated Index indexes = 1;
}
message Index {
  repeated map<string, Entry> entries = 1;
}
message Entry {
  oneof sealed_value {
    PackageEntry packageEntry = 1;
    ToplevelEntry toplevelEntry = 2;
  }
}
message PackageEntry {
}
message ToplevelEntry {
  string uri = 1; // relative URI to semanticdb file containing full information
}
```

**Comment by olafurpg** [comment]
Can you provide example UX for `metai`? For example:

```
$ metai <mclasspath>
```

Writes `META-INF/semanticdb/semanticdb.index` file in-place for every classpath entry.
