### ISSUE TITLE
scala 2.13 support

### ISSUE THREAD

**Issue by pshirshov** [scalameta/scalameta#1693]
Hi,

Yup, I've seen that it's hard and so on. Though 2.13 is our inevitable future. 
So, `scalameta` has to support it or cease it's existence.

Related: #1023

**Comment by olafurpg** [comment]
Superseded by https://github.com/scalameta/scalameta/issues/1695.

>  So, scalameta has to support it or cease it's existence.

Threats like this is not a nice way to start a discussion, I ask you to be more respectful in future communications. Here is a template you can use for reference

> Hi, I am using Scalameta in my project https://github.com/pshirshov/izumi-r2 and I would love to upgrade to 2.13. I saw the plans to support 2.13-M2 in https://github.com/scalameta/scalameta/issues/1023 had been dropped, would it be possible to revisit that decision?
