### ISSUE TITLE
Cross-build for 2.13

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1695]
We currently build for JVM/JS/Native against the latest 2.11 and 2.12 releases. It would be great to support 2.13 once it gets closer to a stable release.

- I suspect most but not all modules will build on 2.13 with minimal changes
- The compiler plugin `semanticdb-scalac` usually needs a decent amount of custom work. Here is for example the PR that upgraded 2.12.4 to 2.12.6 https://github.com/scalameta/scalameta/pull/1557
- Our CI is already quite overloaded with work and a fast CI is critical for having productive pull requests and a good contributor experience.

**Comment by kubum** [comment]
ScalaTest - only `scalatest_2.13.0-M2` is on maven, but no `scalatest_2.13.0-M5` yet
ScalaCheck - has `2.13.0-M5` build
Acyclic - has `2.13.0-M5` build
Scodec - has `2.13.0-M4` build published
FastParse - can't see anything published for 2.13 yet

**Comment by SethTisue** [comment]
Scalameta's dependencies are all green now in the Scala 2.13 community build

ScalaPB 0.9.0-M4 is available for 2.13.0-RC1

**Comment by SethTisue** [comment]
ScalaPB 0.9.0-M4 is available for 2.13.0-RC1

Scalameta's dependencies are all green now in the Scala 2.13 community build

Scalameta is now the top "blocker" in the 2.13 CB (it has the most downstream projects waiting on it)

**Comment by olafurpg** [comment]
@SethTisue thanks for the update. I have opened https://github.com/scalameta/scalameta/issues/1695 building against 2.13.0-RC1. It may take a few attempts to get the CI green, but the JVM and JS tests are passing for me locally. I moved a few non-critical test suites to 2.12 only directories. The upgrade to RC2 should be easy once our library dependencies have updated.

**Comment by SethTisue** [comment]
agree that RC1 is still worth pursuing even though RC2 is out

trying #1870 here: https://github.com/scala/community-builds/pull/910
