### ISSUE TITLE
Fix HKT wildcard parameters

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1701]
Currently, `metacp.undefined` contains an entry `advanced/D#_#`
https://github.com/scalameta/scalameta/blob/master/tests/jvm/src/test/resources/metacp.undefined#L1
that origins from the following definition
https://github.com/scalameta/scalameta/blob/cff7e738052f22727d5286b0e4c8db7f184aa3b5/semanticdb/integration/src/main/scala/example/Advanced.scala#L23

I've seen the same error appear a lot in the real-world when testing scalafix against larger classpaths. We should fix this bug before v4.0

**Comment by xeno-by** [comment]
Looks related to https://github.com/scalameta/scalameta/issues/1586.

**Comment by olafurpg** [comment]
Indeed. Duplicate of https://github.com/scalameta/scalameta/issues/1586
