### ISSUE TITLE
Feature Request: Set operations on Tokens

### ISSUE THREAD

**Issue by MasseGuillaume** [scalameta/scalameta#1717]
for example, the exclusion operator would be useful:

```scala
val ap = q"f(x)"
val x = ap.args.head

ap.tokens -- x.tokens // expected: f()
```

**Comment by olafurpg** [comment]
Reference equality for synthesized tokens on quasiquote trees will not work.

If we have a tree parsed from a string, then it work if you do `ap.tokens.toList.filterNot(token => ap.args.head.tokens.contains(token))` or alternatively `ap.tokens.filter(ap.fun.tokens.contains)`
