### ISSUE TITLE
build fails on Java 9+ (sbt-jdi-tools isn't compatible)

### ISSUE THREAD

**Issue by SethTisue** [scalameta/scalameta#1719]
f9c534f93c630f21cff4dee03cb96e77e01364a8 added `addSbtPlugin("org.scala-debugger" % "sbt-jdi-tools" % "1.0.0")` but this breaks the build (as in, you can't even start sbt) on Java 9 and 10, because of https://github.com/chipsenkbeil/sbt-jdi-tools/issues/5

yes, Scalameta is normally built on Java 8, but we want to build it on Java 9 and 10 as part of the Scala community build. or at least, we want the build definition to be loadable, so we can use the same project list regardless of JDK version

**Comment by SethTisue** [comment]
@xeno-by I've submitted https://github.com/chipsenkbeil/sbt-jdi-tools/pull/6 which should fix sbt-jdi-tools, but that repo isn't set up to cross-publish for sbt 0.x and 1.x, only 1.x.

is there anything blocking you from upgrading this repo to sbt 1.x?

**Comment by SethTisue** [comment]
> is there anything blocking you from upgrading this repo to sbt 1.x?

I submitted https://github.com/scalameta/scalameta/pull/1720 on this, but it will need some additional work before it can be merged.

**Comment by SethTisue** [comment]
if the sbt 1 upgrade stalls out, and/or if my sbt-jdi-tools PR stalls out, another path forward would be to remove the binary dependency on sbt-jdi-tools and instead, copy the plugin's one source file (with my fix) into your `project` directory and call it good

**Comment by chipsenkbeil** [comment]
We can backport your fix, @SethTisue, to the plugin's 1.0 release or update the plugin to cross-compile for 0.13.x and 1.x. I've not done sbt plugin cross-compiling myself, though.

**Comment by SethTisue** [comment]
@chipsenkbeil thanks Chip!!

**Comment by xeno-by** [comment]
Thank you everyone! 🤝

**Comment by chipsenkbeil** [comment]
Just finished signing, publishing, and releasing versions 1.0.1 (for sbt 0.13.x) and 1.1.1 (for sbt 1.x) of the plugin. Once Maven Central gets the resources in order, feel free to give it a try and see if it helps.

**Comment by SethTisue** [comment]
PR: https://github.com/scalameta/scalameta/pull/1732
