### ISSUE TITLE
Consider upgrading to sbt 1.x

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1721]
@SethTisue got the upgrade partially working in https://github.com/scalameta/scalameta/pull/1720. Let's discuss whether/when/how this should be done.

**Comment by olafurpg** [comment]
I think it's good to look into this once Scalameta v4.0 and sbt v1.2 are out. sbt v1.2 adds nice improvements to cross-building which could avoid a lot of boilerplate in build.sbt

**Comment by kpbochenek** [comment]
Using sbt 1.3.8 now - can be closed?

**Comment by olafurpg** [comment]
Yes. This issue is now fixed
