### ISSUE TITLE
Figure out how to populate SymbolTable with all symbols from TextDocument

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1724]
At the moment, there's no easy way to create a SymbolTable that would comprehensively cover s.TextDocument. Just `GlobalSymbolTable` is not enough, because it only looks into `TextDocument.symbols` and doesn't recur into hardlinks.

As a result, SymbolInformationPrinter from Metap, PrettyType from Scalafix and RscCompat from Rsc all hack around this by having a mutable something that tracks hardlinks as they are discovered. This is clearly suboptimal - both UX-wise and duplicate-wise.

**Comment by olafurpg** [comment]
I'm not confident we will find a generic solution here. I think we will need more experimental data to figure out how to best deal with hardlinks. I propose to close this for now unless you have as concrete suggestion.
