### ISSUE TITLE
ClasspathIndex should expose ability to lookup Classdir

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1729]
After #1723 it became impossible to debug `ClasspathIndex.dirs`. The fact it was public before made it possible to track down critical bugs like #1696. I propose to revert the change in #1723 to make the field public again so that it's possible to drill into the `Map` to investigate problems.

Alternatively, we can replace
```scala
def isClassdir(path: String): Boolean
```
with
```scala
def getClassdir(path: String): Option[Classdir]
```
instead.

For stable public APIs I agree that private fields are a good default. However, `ClasspathIndex` is an unstable and internal API so I think it's fine to default to public even if the data structure is mutable.

**Comment by xeno-by** [comment]
I don't mind either way. Will do a PR.

**Comment by olafurpg** [comment]
I prefer to have `val dirs: mutable.Map` in that case so it's possible to `pprint.log(index.dirs)`
