### ISSUE TITLE
Support conversion between SemanticDB Range and scalameta Position

### ISSUE THREAD

**Issue by maxov** [scalameta/scalameta#1744]
SemanticDB Range and scalameta Positions are very similar. Positions contain more information than Ranges, so converting this way is straightforward:

```scala
implicit class PositionOps(pos: Position) {
    def range: s.Range = s.Range(
      startLine = pos.startLine,
      startCharacter = pos.startColumn,
      endLine = pos.endLine,
      endCharacter = pos.endColumn
    )
  }
```

I have had to implement this many times when writing SemanticDB tools, so it deserves inclusion in some library. It would also be useful to convert from Range to Position, which can be done if provided with an input, potentially as follows:

```scala
implicit class PositionOps(range: s.Range) {
    def position(input: Input): Position = Position.Range(
      input, range.startLine, range.startCharacter, range.endLine, range.endCharacter
    )
  }
```

The question is where to include this API, as semanticdb and input have no dependency relation between them, and as far as I know there is no relevant library that depends on both.

**Comment by olafurpg** [comment]
I agree 👍 we have such a method in scalafix that would be nice to have in scalameta instead
