### ISSUE TITLE
Parser fails when inline keyword starts template

### ISSUE THREAD

**Issue by gabro** [scalameta/scalameta#1776]
Copy-pasted from #1038 (since Sam doesn't want to have pending open issues).

The parser fails if a `Template` starts with `inline`, for example:

```scala
object a {
  inline def foo = 2
}
```

It parses fine, however, if `inline` is not at the beginning of the template body

```scala
object a {
  val dummy = 2
  inline def foo = 2
}
```

**Comment by kitbellew** [comment]
@gabro is `inline` a valid scala2 keyword??? if not, could you try this with `dialect = scala3` instead?

**Comment by gabro** [comment]
I had opened this issue only to keep tracking it since the original author closed all his open issues at that time.

That said, AFAIK `inline` was a keyword under the now deprecated "meta paradise" plugin (the experimental feature that would allow defining macros using scalameta).

I think this bug applies to that specific dialect (Paradise212) which I expect is essentially unused now.

With this in mind I think we can close this bug
