### ISSUE TITLE
Incorrect syntax result of Term.Interpolate

### ISSUE THREAD

**Issue by hugo-vrijswijk** [scalameta/scalameta#1792]
Hi, when I have a `Term.Interpolate` that interpolates a variable with characters in the string right after it, Scalameta does not add brackets around the expression, resulting in an incorrect syntax.

Example:

```scala
val s = Term.Interpolate(Term.Name("s"),
                         List(Lit.String(""), Lit.String("bar")),
                         List(Term.Name("foo")))

s.syntax
```

Actual result: `s"$foobar"` (can cause compile error)

Expected result: `s"${foo}bar"`

Having a `Term.Select` or `Term.Apply` as the interpolated variable causes the brackets to appear properly (`s"${foo.baz()}bar"`).

Tried on Scala 2.12.7 with Scalameta versions 3.7.3 and 4.0.0

**Comment by hugo-vrijswijk** [comment]
Hmm, i see. Thanks! Is replacing the printer on the (relative) short-term schedule? Otherwise I could have a look at fixing it in the tree printer.

**Comment by olafurpg** [comment]
A PR fixing the current printer is welcome 😊  There are no short-term plans to replace the printer with scala-syntax.
