### ISSUE TITLE
Upgrade to fastparse 2.0

### ISSUE THREAD

**Issue by jvliwanag** [scalameta/scalameta#1800]
Found this while trying to use scalameta with ammonite-repl 1.3.2 which uses fastparse 2.0 .

**Comment by olafurpg** [comment]
I opened #1801 shading the fastparse dependency, this should unblock incompatibilities used by the scalameta parser but we may still encounter problems when using parsing SemanticDB data structures from strings (esoteric use-case, blocked by https://github.com/scalapb/ScalaPB/issues/510).
