### ISSUE TITLE
Term.ApplyInfix prettyprint removes neccessary brackets

### ISSUE THREAD

**Issue by hugo-vrijswijk** [scalameta/scalameta#1817]
```scala
val add = q"def add(a: Int, b: Int) = a + b"
val list = q"val list = List(1, 2, 3)"
val added = q"list map (add(_, 1))"

added.syntax // list map add(_, 1)
```

The printed result gives a compile error as the brackets around `add(_, 1)` are needed while Scalameta removes them

**Comment by hugo-vrijswijk** [comment]
I assume this is another issue with the tree printer, similar to #1792. I know @legopiraat had a go at fixing the previous issue I posted, but did not get very far due to the complexity of it

**Comment by hugo-vrijswijk** [comment]
I've just run into another case where this goes wrong. When giving a `Seq` to a function that requires `varargs` it's common to add `foo: _*` (a `Term.Repeated`). 

Calling `.syntax` on the following expression `foo op (bar: _*)` returns `foo op bar: _*` which is invalid Scala code.

**Comment by olafurpg** [comment]
good catch @hugo-vrijswijk I added a commit to #1818 fixing the repeated case.

**Comment by hugo-vrijswijk** [comment]
I think we should re-open this issue. I've just found another case that this doesn't fix: `foo map (_.bar)` syntaxes to `foo map _.bar`, which is incorrect. Also see [this issue for Stryker4s](https://github.com/stryker-mutator/stryker4s/issues/148)

**Comment by olafurpg** [comment]
@hugo-vrijswijk please open a separate issue. FWIW, the prettyprinter has a decent number of known issues. If I had a few weeks to work on it I would finish https://github.com/scalacenter/scala-syntax to replace the current printer but I estimate that won't happen in the near future. I will do my best to review fixes to the current printer in the meantime.

**Comment by hugo-vrijswijk** [comment]
Alright, will do. I'll also have a look at a fix 👍
