### ISSUE TITLE
Code completion

### ISSUE THREAD

**Issue by ratoshniuk** [scalameta/scalameta#1831]
Hello everyone! I recently start using vsc with metals and found that it currently does not support code completion and doesn't expand list of properties and methods after putting a dot. What is a current progress of this issue? And maybe there some workarounds for current usage (maybe other plugins)

Thank you!

**Comment by olafurpg** [comment]
Thanks for reporting! This is a duplicate of https://github.com/scalameta/metals-feature-requests/issues/8 There is no workaround for current usage.
