### ISSUE TITLE
Path fails to resolve on Windows

### ISSUE THREAD

**Issue by Arthurm1** [scalameta/scalameta#1835]
Using Metals on VSCode on Windows I get an error trying to resolve the path.

I don't think `java.nio.file.Path.resolve` can't cope with a full URI passed as a String on Windows.

```
failed to generate semanticdb for C:\dev\XXXX\foo.scala:
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///C:/dev/XXXX/foo.scala.semanticdb
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
	at scala.meta.io.AbsolutePath.resolve(AbsolutePath.scala:27)
	at scala.meta.internal.semanticdb.scalac.SemanticdbPaths$.toSemanticdb(SemanticdbPaths.scala:50)
```

**Comment by olafurpg** [comment]
Thank you for reporting! What JVM version are you using? I am seen similar reports but only when compiling via IntelliJ, we were never able to reproduce in sbt.

**Comment by Arthurm1** [comment]
I think this is my error.

I'm using Bloop from Gradle so no SBT.  I had to specify the scala options manually in the json and spelt them wrong - doh.

I can't reproduce and code navigation works now.

Sorry for the noise.

**Comment by 4lex1v** [comment]
I don't know if this would help with reproduction, but getting this issue with plain SBT (don't use Intellij). The error happens when I try to depend on the remote project:

```
val sdpProducer = ProjectRef(uri("ssh://git@private.git.repository.co/sdp/sdp.git#master"), "producer")
val fakeProducer = (project in file("producer")).dependsOn(sdpProducer)
```
Now calling `sbt fakeProducer/compile` gives the error similar to the above one:

```
[error] failed to generate semanticdb for C:\....\string.scala: [error] java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///C:/..../string.scala.semanticdb
[error]         at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
[error]         at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
[error]         at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
```

Hope this would help to reproduce the issue.
