### ISSUE TITLE
Implicit val moved to start of class constructor (Prettyprinting)

### ISSUE THREAD

**Issue by hugo-vrijswijk** [scalameta/scalameta#1837]
```scala
val tree = q"class foo(number1: Int, implicit val number2: Int = 4)"
tree.syntax == "class foo(number1: Int, implicit val number2: Int = 4)" // false
tree.syntax == "class foo(implicit number1: Int, val number2: Int = 4)" // true
```

Also see https://github.com/stryker-mutator/stryker4s/issues/162

**Comment by RCMartins** [comment]
@olafurpg Yes, this only works in the primary constructor and the use case is to make the `y` implicit inside the class so
```scala
class Foo(x: Int, implicit val y: String)
```
could also be written as (It's not completely equivalent but pretty close):
```scala
class Foo(x: Int, val y: String) {
  private implicit val y2 = y
}
```

I also found an interesting edge case related to this.
scalac allows multiple implicit sections when the first keyword is not `implicit`
```scala
@ class Foo(private implicit val a: Int, b: String)(implicit c: Boolean)
defined class Foo

@ implicit val i = 1
i: Int = 1

@ implicit val s = "abc"
s: String = "abc"

@ implicit val bool = false
bool: Boolean = false

@ val foo = new Foo
foo: Foo = ammonite.$sess.cmd0$Foo@3c4bc9fc

@ val foo2 = new Foo()(2, "bar")
foo2: Foo = ammonite.$sess.cmd0$Foo@6c37bd27

@ val foo3 = new Foo()(2, "bar")(true)
foo3: Foo = ammonite.$sess.cmd0$Foo@12968227
```

But if you change the order of the modifiers (implicit with private), the code stops compiling:

```scala
@ class Foo(implicit private val a: Int, b: String)(implicit c: Boolean)
(console):1: an implicit parameter section must be last
class Foo(implicit private val a: Int, b: String)(implicit c: Boolean)
          ^
(console):1: multiple implicit parameter sections are not allowed
class Foo(implicit private val a: Int, b: String)(implicit c: Boolean)
                                                  ^
```

So having implicit has the first keyword in a section has special meaning.

**Comment by olafurpg** [comment]
Makes sense, thanks for the explanation!

> I also found an interesting edge case related to this

Huh, that an interesting find! It seems unintended because Scala does not in general allow multiple implicit parameter lists.
