### ISSUE TITLE
Goto definition doesn't work for classOf

### ISSUE THREAD

**Issue by tgodzik** [scalameta/scalameta#1856]
**Describe the bug**
Go to definition doesn't work when class is in classOf[] 

**To Reproduce**
1. Create any classOf[], for example classOf[Boolean] 
2. Try to goto on Boolean
4. No definition available

**Expected behavior**
Lsp would go to definition of the class inside classOf[]

**Screenshots**
![bug](https://user-images.githubusercontent.com/3807253/56358079-d9210f80-61dd-11e9-9ce1-c7ed000918aa.png)

**Installation:**
- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.5.0

**Search terms**
goto definition classOf

**Comment by olafurpg** [comment]
Thank you for reporting! This is a SemanticDB bug, a test case reproducing the issue is already commited in the repo here
https://github.com/scalameta/scalameta/blob/ff542e7c5b937822c12d0aa1ef7d6ab92b2fc5e1/tests/jvm/src/test/resources/example/Types.scala#L114

**Comment by olafurpg** [comment]
Looks like there's nothing we can do on our side, this needs to be fixed upstream in the compiler. Definition used to work for `classOf` in older versions of SemanticDB when we instrumented the typer but this was removed in https://github.com/scalameta/scalameta/pull/1804 to simplify compiler upgrades and improve interoperability with other compiler plugins.
