### ISSUE TITLE
scalameta-contrib for Scala 2.13

### ISSUE THREAD

**Issue by hmf** [scalameta/scalameta#1876]
I see that the contrib module has been moved to a separate repository and no version exists for Scala 2.13. Am I to assume that this will not be updates in the future. If so maybe references to it should be removed from the documentation. For example in the following guide:

https://scalameta.org/docs/trees/guide.html

TIA

**Comment by olafurpg** [comment]
Thanks for reporting! The contrib module got merged into the main scalameta module in https://github.com/scalameta/scalameta/pull/1863.
