### ISSUE TITLE
Symbols don't seem to have any sort of useful `hashCode`

### ISSUE THREAD

**Issue by blast-hardcheese** [scalameta/scalameta#1877]
Is this on purpose, or would you accept a PR to resolve this?

```
scala> Set(t"Long", t"Long")
res0: scala.collection.immutable.Set[meta.Type.Name] = Set(Long, Long)

scala> res0.contains(t"Long")
res1: Boolean = false

scala> t"Long".hashCode
res2: Int = 167054986

scala> t"Long".hashCode
res3: Int = 448322632

scala> q"Long".hashCode
res4: Int = 1586943225

scala> q"Long".hashCode
res5: Int = 1175465249
```

I'd like to be able to test membership of a set non-structurally. This breaks assumptions about literals being structurally representative in any way, as they can't be meaningfully compared either:
```
scala> q"Long" == q"Long"
res6: Boolean = false
```

I've seen [this comment](https://github.com/blast-hardcheese/scalameta/blob/b72de3644115f13226f8fa00834fea9ebb287f77/scalameta/contrib/shared/src/main/scala/scala/meta/contrib/equality/Structurally.scala#L13) in contrib, but this seems more broadly applicable than just some extension methods.

Was this done on purpose? Are there instances where we absolutely want to prevent comparison to ensure we don't accidentally collapse trees?

**Comment by olafurpg** [comment]
Thanks for reporting! This is working as expected, trees have reference equality. See https://scalameta.org/docs/trees/guide.html#compare-trees-for-equality

It's not clear what other form of equality would be a better default. Even if you have two trees that share the same `q"Long"` structure they might have for example different positions.

**Comment by blast-hardcheese** [comment]
Understood, thanks for clarifying @olafurpg!
