### ISSUE TITLE
scaladocs available by http?

### ISSUE THREAD

**Issue by johnynek** [scalameta/scalameta#1903]
It would be great to see the scaladoc for scalameta linked on the readme. Documentation is nice, but actually seeing the available methods and types is very valuable.

I couldn't find them published anywhere. Maybe I missed them?

**Comment by johnynek** [comment]
https://oss.sonatype.org/service/local/repositories/releases/archive/org/scalameta/scalameta_2.12/4.2.3/scalameta_2.12-4.2.3-javadoc.jar/!/index.html

using sonatype, we can browse into the published jar. This seems to be an easy way to go to just add a link there.

**Comment by johnynek** [comment]
trees is probably the most useful: https://oss.sonatype.org/service/local/repositories/releases/archive/org/scalameta/trees_2.12/4.2.3/trees_2.12-4.2.3-javadoc.jar/!/scala/meta/Source.html

**Comment by olafurpg** [comment]
Thank you for reporting! The Javadocs are available on https://static.javadoc.io/org.scalameta/trees_2.12/4.2.3/scala/meta/index.html. I have added a new "Scaladoc" page to the website linking to static.javadoc.io for the main modules such as `org.scalameta:trees` https://github.com/scalameta/tutorial/commit/c610b8608fdfb0d98852102b7ff9d6b48a92139a. It should go live on the website in the next hour.
