### ISSUE TITLE
Construct/pattern-match operators with different precedence

### ISSUE THREAD

**Issue by Dveim** [scalameta/scalameta#193]
At the moment following fails:

```
scala> val q"$a $b $c $d $e" = q"x + y * z"
scala.MatchError: x + y * z (of class scala.meta.internal.ast.Term$ApplyInfix$Impl)
  ... 43 elided
```

**Comment by xeno-by** [comment]
@olafurpg I don't see how we can reasonably support this. What do you think?

**Comment by olafurpg** [comment]
I'd say this case is better suited with vanilla apply/unapply.

**Comment by xeno-by** [comment]
Allright, I'm closing as wontfix. I don't see a way to support this scenario without significantly complicating the code generated by quasiquotes.
