### ISSUE TITLE
Minus sign in literal based singleton type parameters does not compile

### ISSUE THREAD

**Issue by agilesteel** [scalameta/scalameta#1955]
```scala
val x: Option[-1] = Some(1)
```
produces
```scala
error: ] expected but integer constant found
```
Here is a reproduction in the [AST explorer](https://astexplorer.net/#/gist/a730e401a1821fca6ec4a5c39404df79/855ef81e845a97e1636656d10e89b568040cde3c)

This issue affects everything: bloop/scalafmt/.scala/.worksheet.sc files etc.

**Comment by kitbellew** [comment]
Looks like doubles are similarly not supported: https://github.com/scalameta/scalafmt/issues/2023 @olafurpg @kpbochenek

**Comment by kitbellew** [comment]
@kpbochenek do you believe that the attached issue regarding double literals is related?

**Comment by kpbochenek** [comment]
@kitbellew positive, it is related and with new scalameta it should be solved
