### ISSUE TITLE
Macro annotations

### ISSUE THREAD

**Issue by MasseGuillaume** [scalameta/scalameta#2]
is it possible to expand an annotation macro (see http://docs.scala-lang.org/overviews/macros/annotations.html) currently with scalameta ?

**Comment by xeno-by** [comment]
Might be easier than it looks, because our syntactic APIs are already of really decent quality at the moment.

**Comment by xeno-by** [comment]
There's a prototype implementation published in https://github.com/scalameta/paradise. Let's continue the discussion there.
