### ISSUE TITLE
Unexpected message from the parser in case of parsing errors

### ISSUE THREAD

**Issue by tgodzik** [scalameta/scalameta#2002]
This might be correct, but I wanted to report it just in case. However it looks to me like a regression.

Getting this error:
```
a/src/main/scala/Main.scala:3:1: error: <error> is already defined as object <error>
           |object object B
           |^^^^^^^^^^^^^^^
```
on
```
object object A
object object B
```

It looks like it treats the error `object` identifier as an actual identifier. This came up between `4.3.0` and `4.3.4`
Connected to https://github.com/scalameta/metals/pull/1499

**Comment by olafurpg** [comment]
Thanks for reporting! Are you sure this is a Scalameta regression? Scalameta doesn't report type error diagnostics like this one. The parser only reports syntax errors, type errors come from BSP.

**Comment by tgodzik** [comment]
@olafurpg That could, I'll take a look and see where it's coming from. Though it happened after we upgrade to `4.3.4`, so it can't be a coincidence, can it?

**Comment by olafurpg** [comment]
Have you confirmed where the diagnostic is reported? Is it a syntax error from the parser?

**Comment by tgodzik** [comment]
It looks like this also got fixed by https://github.com/scalameta/scalameta/pull/2004

Confirmed with 4.3.6 here: https://github.com/scalameta/metals/pull/1510
