### ISSUE TITLE
`Try` fails to parse partially parenthesized expression without braces

### ISSUE THREAD

**Issue by kitbellew** [scalameta/scalameta#2031]
The following fails parsing (4.3.7 and 4.3.10):
```
  try (a.b).c
  finally d
```
while these work:
```
  try { (a.b).c }
  finally d
```
and
```
  try (a.b.c)
  finally d
```
@olafurpg i can try to fix it, wanted to include the fix in `scalafmt 2.5.0`, but don't know where to start.

**Comment by olafurpg** [comment]
Thank you for reporting! You might get inspiration from https://github.com/scalameta/scalameta/pull/1980

**Comment by kitbellew** [comment]
@olafurpg there's something interesting going on there. looks like the code assumes that if `try` is followed by `{` or `(`, it's a fully-enclosed expression. probably causes #2009 too.

i can check that the enclosed expression is not followed by `catch` or `finally` but what method should be called to read more (and how to combine it with the enclosed expression read so far)?

in fact, one of the difficulties in `scalafmt` is that `tree.tokens.head` frequently points to the token *after* the brace, which requires extra handling to find the previous token. is it too late to suggest keeping delimiters as part of the expression and not try to "eat" them?
