### ISSUE TITLE
Pretty print of block

### ISSUE THREAD

**Issue by dieu** [scalameta/scalameta#2046]
Hey folks, 

I encounter incorrect behavior of pretty print from scala meta in case of blocks:

```
import scala.meta._

val a = q"val a = 1; a"

val tree = q"val b = 1; $a"

println(tree.syntax)
```

produce: 

```
{
  val b = 1
  {
    val a = 1
    a
  }
}
```
which is incompatible with scala syntax.

https://scastie.scala-lang.org/GaU07vEdSxOMuUArWk8Zyw

**Comment by kpbochenek** [comment]
Yes it is an issue, problem is:
`val b = 1 { ... }` => error `Int(1) does not take parameters`
Compiler treats {} as parameter to 1. Additional newline should solve it.
```
{
  val b = 1

  {
    val a = 1
    a
  }
}
```

Also compiles fine for dotty.

**Comment by dieu** [comment]
>  Additional newline should solve it.
I didn't find a way to force pretty print to print an additional newline. I use `scala.Predef.identity` as a workaround.

**Comment by DmytroMitin** [comment]
I ran into this bug in https://stackoverflow.com/questions/76066871/scalac-2-13-compiling-large-auto-generated-scala-file-method-too-large

**Comment by dieu** [comment]
Thanks @RCMartins and @kitbellew
