### ISSUE TITLE
Publish for Scala.js 1.0.0

### ISSUE THREAD

**Issue by neko-kai** [scalameta/scalameta#2047]
A lot of the ecosystem has migrated to Scala.js 1.0.0, I am currently unable to migrate one of the projects using scalameta to 1.0.0 because scalameta is not published for 1.0.0 right now. Could you please publish when you have the time? Thanks!

**Comment by kpbochenek** [comment]
It should at least wait for https://github.com/scalameta/scalameta/pull/2021 to be merged I think

**Comment by neko-kai** [comment]
Thanks!
