### ISSUE TITLE
Regression in 4.3.16: method called "given" with Scala 2.13.3

### ISSUE THREAD

**Issue by japgolly** [scalameta/scalameta#2083]
I have a method called `given` in my codebase and scalameta is crashing parsing a file that calls the `given` method.

Minimisation:

```scala
object Test {
  def given = 1
  given
}
```

**Comment by tgodzik** [comment]
This mightbe regression grom adding the dotty support. @kpbochenek could you check it out?

**Comment by kpbochenek** [comment]
looking at it :+1:

**Comment by kpbochenek** [comment]
@japgolly thanks for finding it and reporting! It is indeed an issue in leaking dotty keyword syntax into scala2.

Fix is on a way.

Also be aware that `given` will become a keyword in dotty and you will have to change this to something else.

**Comment by japgolly** [comment]
Well done, that was fast!!

Thanks for the suggestion. I just renamed to both workaround this issue and prepare for Dotty :smile:
