### ISSUE TITLE
Parse error for infix operator with a brace-enclosed expression on RHS

### ISSUE THREAD

**Issue by mjadczak** [scalameta/scalameta#2089]
This piece of code fails to parse:
```scala
package test.scalafmt

class Dummy {
  val foo = 1 max { 3 + 2 }
}
```
with the error "} expected but end of file found".
The issue is the `1 max { 3 + 2 }` expression - `1 max { 3 }` and `1.max { 3 + 2 }` parse fine.
I encountered this issue in scalafmt (2.6.1) but I am assuming that this is the correct repo to report a parsing error.
Scalac accepts this code (and fwiw the IDEA parser also does).

**Comment by kpbochenek** [comment]
Thanks for reporting! 

It parses fine with latest scalameta and scala 2.13 / 2.12

https://scastie.scala-lang.org/8a5RWsnQTm2xiwrSD1YhAA

**Comment by kitbellew** [comment]
@mjadczak please submit a report, with your `scalafmt` configuration used, to https://github.com/scalameta/scalafmt/issues/new/choose

might be a bug in a rewrite rule, if you use any of them.
