### ISSUE TITLE
Scala.Names.encode does not handle Scala keywords

### ISSUE THREAD

**Issue by liancheng** [scalameta/scalameta#2096]
While checking whether a name should be quoted, [`Scala.Names.encode`][1] does not check for Scala keywords. For example, a variable named `macro` should be encoded as `` `macro` `` but right now it's not quoted after being encoded. I believe this is the root cause of https://github.com/liancheng/scalafix-organize-imports/issues/101.

The following diff is probably good enough to fix it:

```diff
diff --git a/semanticdb/semanticdb/src/main/scala/scala/meta/internal/semanticdb/Scala.scala b/semanticdb/semanticdb/src/main/scala/scala/meta/internal/semanticdb/Scala.scala
index c38c3f153..64b892fb4 100644
--- a/semanticdb/semanticdb/src/main/scala/scala/meta/internal/semanticdb/Scala.scala
+++ b/semanticdb/semanticdb/src/main/scala/scala/meta/internal/semanticdb/Scala.scala
@@ -175,6 +175,8 @@ object Scala {
     private[meta] def encode(value: String): String = {
       if (value == "") {
         "``"
+      } else if (tokenizers.keywords(value)) {
+        "`" + value + "`"
       } else {
         val (start, parts) = (value.head, value.tail)
         val isStartOk = Character.isJavaIdentifierStart(start)
```

[1]: https://github.com/scalameta/scalameta/blob/aba8169969b6c6ba2e8f541a20cd58d17318e664/semanticdb/semanticdb/src/main/scala/scala/meta/internal/semanticdb/Scala.scala#L175-L185

**Comment by olafurpg** [comment]
Thank you for reporting! I think the current behavior is working as expected according to the SemanticDB spec https://scalameta.org/docs/semanticdb/specification.html#symbol-1

> For other definition, the name of the binding introduced by the definition [70]. If the name is not a Java identifier [22], it is wrapped in backticks.

You can use “scala.meta.Term.Name” as an alternative if you want to generate valid source code that handles things like backticking identifiers.

**Comment by liancheng** [comment]
Thanks for the pointers, @olafurpg! I later realized that I was using `Term.Name` and `TreeSyntax` indrectly instead of the `Scala.Names.encode` method while generating the source code. (I got the wrong impression due to https://github.com/scalacenter/scalafix/issues/1097.)

However, we still had the issue that the name `macro` is not properly quoted. Further investigation showed that it's because `macro` is not listed as a keyword in [`scala.meta.internal.tokenizers.keywords`][1]. On the other hand, a token class named `KwMacro` can be found in [`scala.meta.tokens.Token`][2], which seems to suggest that `macro` is indeed a keyword. And, `macro` is indeed listed as a "reserved word" in the [Scala 2.13 language specification][3]. Is this a bug?

[1]: https://github.com/scalameta/scalameta/blob/aba8169969b6c6ba2e8f541a20cd58d17318e664/scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/package.scala#L8-L62
[2]: https://github.com/scalameta/scalameta/blob/aba8169969b6c6ba2e8f541a20cd58d17318e664/scalameta/tokens/shared/src/main/scala/scala/meta/tokens/Token.scala#L51
[3]: https://www.scala-lang.org/files/archive/spec/2.13/01-lexical-syntax.html

**Comment by liancheng** [comment]
Here is a simple reproduction using Ammonite:

```
@ import $ivy.`org.scalameta::scalameta:4.3.20`, scala.meta._
import $ivy.$                                , scala.meta._

@ val Import(Importer(ref, _) :: Nil) = q"import `macro`.X"
ref: Term.Ref = Term.Name("macro")

@ ref.syntax
res13: String = "macro"
```

**Comment by olafurpg** [comment]
That looks like a bug then. The macro keyword got introduced in 2.10 I think. We should add macro to the keyword list.

**Comment by liancheng** [comment]
Thanks! I'm gonna close this one and create another issue to track the missing `macro` keyword issue.
