### ISSUE TITLE
Scalameta removes Unicode escapes in String literals

### ISSUE THREAD

**Issue by bnavetta** [scalameta/scalameta#2106]
Scalameta escapes backslashes when printing String literals, but this prevents generating Unicode escapes for special characters that Scalameta doesn't already escape, like control characters.

For example, this compiles in a Scala repl: `val str = "xy\u001az"` (`\u001a` is a substitution control character)

However, Scalameta can't generate this. Including the control character with `Lit.String("xy\u001az")` causes it to be printed directly, generating invalid code. Escaping it with `Lit.String("xy\\u001az")` also doesn't work because Scalameta escapes the backslash.

I think the problem is that [`enquote`](https://github.com/scalameta/scalameta/blob/master/scalameta/common/shared/src/main/scala/scala/meta/internal/prettyprinters/Enquote.scala) escapes backslashes but also doesn't escape all characters not allowed in Scala source. I'm not sure if it's better to escape more characters in `enquote` or to allow users to include their own arbitrary Unicode escapes.

Scalameta version: 4.3.20

**Comment by olafurpg** [comment]
Thank you for reporting! This looks like a bug indeed. I opened https://github.com/scalameta/scalameta/pull/2115 that seems to fix this issue without introducing regressions for unicode letter characters like þæö. Could you please take a look?

**Comment by bnavetta** [comment]
That looks great, thank you!
