### ISSUE TITLE
inconsistent construction of Pat.Var.XXX nodes

### ISSUE THREAD

**Issue by Dveim** [scalameta/scalameta#216]
We need easy ways to create `Pat.Var.Term` and `Pat.Var.Type`, and the spec promises it to us in the form of `p"name"` and `pt"name"`. 

However, if we dig deeper, we'll find that even though `p"x"` is a `Pat.Var.Term`, `p"X"` is a `Term.Name` and both `pt"x"` and `pt"X"` are `Type.Name`. This is a direct consequence of how Scala's parser works: `Pat.Var.Term` with capitalized name is only allowed in the lhs of vals and vars, whereas `Pat.Var.Type` is only allowed in type arguments.

**Comment by xeno-by** [comment]
Also need to support `pt"_"` that currently gives an error.
