### ISSUE TITLE
Impossible to use `val importee"$a => $b" = importee"x => _"`

### ISSUE THREAD

**Issue by Dveim** [scalameta/scalameta#219]
So, lhs results in `Import.Selector.Rename(Name.Indeterminate.Quasi(0, (quasiquote$macro$4$hole$0 @ _)), Name.Indeterminate.Quasi(0, (quasiquote$macro$4$hole$1 @ _)))`, and rhs - `Import.Selector.Unimport(Name.Indeterminate("x"))`. `Import.Selector.Unimport` != `Import.Selector.Rename`, therefore pattern-matching fails with  MatchError.

Probably one should merge Unimport into Rename, with `Rename.to` == `_`.

**Comment by xeno-by** [comment]
@olafurpg @ShaneDelmore @DavidDudson What do you think about this one? I feel that we should leave things as is, without overloading the meaning of `Term.Placeholder`.

**Comment by xeno-by** [comment]
Allright. Closing this issue then.
