### ISSUE TITLE
Scala 3: Dollar identifier is incorrectly tokenized as `MacroSplicedIndent`

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#2191]
Steps to reproduce:
```
val dotty = {
  implicit val D = dialects.Dotty
  "map($ => $.a)".tokenize.get.map { t =>
    t.productPrefix -> t.syntax
  }
}

val scala2 = {
  implicit val D = dialects.Scala213
  "map($ => $.a)".tokenize.get.map { t =>
    t.productPrefix -> t.syntax
  }
}

```

In the Dotty example, `$` is tokenized as `MacroSplicedIndent` while it's `Ident` in the Scala 2 example. I expected the tokenizer to emit `Ident` in both examples. cc/ @kpbochenek

**Comment by tgodzik** [comment]
Thanks for finding this! I wonder if we could just check if the next token is `{` or ident, but not sure how to properly do it inside the tokenizer.
