### ISSUE TITLE
traverser doesn't work for @binaryCompat fields

### ISSUE THREAD

**Issue by tgodzik** [scalameta/scalameta#2247]
`@binaryCompatField` were added so that we would be able to add new fields to existing AST nodes in a binary compatible way. This also required quite a bit of work in the ast macros. The only thing that is currently not working is the traverser, which is not used by Metals or scalafmt and should only impact any new Scala 3 code. This is why we left it as is.

The main problem with traverser is that it requires `unapply`, which cannot be binary compatible with the new fields, so a lot of effort might need to be done to work around it. Personally, I would love it if we could just drop the macros as their complexity is huge. Alternatively we could also drop traverser and only allow to explore the tree via the children method.

Related: https://github.com/scalameta/scalameta/issues/2246

We ignored `teskit`'s test `TraverserOrder`, since the results currently are different between traversing via children and traversers.

**Comment by olafurpg** [comment]
> Alternatively we could also drop traverser and only allow to explore the tree via the children method.


Is it possible to implement the traverser API with the children method?

**Comment by olafurpg** [comment]
I recall an experiment that showed that the current traverser API has bad performance, and it’s much faster to go via children. I think the contrib module uses children to implement the “for each” method

**Comment by tgodzik** [comment]
I think the test did actually compare the two approaches, so most likely we should be able to do it.

It's done here: https://github.com/scalameta/scalameta/blob/112fedfacbadf9ab4d30d84edd4181c24b8de23a/scalameta/transversers/shared/src/main/scala/scala/meta/transversers/SimpleTraverser.scala

**Comment by kitbellew** [comment]
is this still a problem, after #2892 and #2889?

**Comment by tgodzik** [comment]
Looks like it works now, thanks! Added https://github.com/scalameta/scalameta/pull/2922
