### ISSUE TITLE
Inconsistent operation with ctor"..."

### ISSUE THREAD

**Issue by Dveim** [scalameta/scalameta#227]
According to specification, `Annotated Reference ctor"$ctorname ..@$annots"` should be represented with `Term.Annotate(expr: Term, annots: Seq[Mod.Annot])`. But `ctorname` have type `Term`, so reverse operation (`val ctor"$ctorname ..@$annots" = ctor"x @q @w"` <=> `ctor"$ctorname ..@$annots"`) fails, because here `ctorname` should have type `Ctor.Call`.

**Comment by xeno-by** [comment]
Fixed in https://github.com/scalameta/scalameta/pull/907.
