### ISSUE TITLE
java.lang.NoSuchMethodError: scala.meta.Dialect.allowSignificantIndentation()Z

### ISSUE THREAD

**Issue by cacilhas** [scalameta/scalameta#2294]
I was trying the [Tree Guide](https://scalameta.org/docs/trees/guide.html), and in the first example I’m “welcomed” by the following message:

```scala
cacilhas-apps@ import scala.meta._
import scala.meta._

cacilhas-apps@ val program = """object Main extends App { print("Hello!") }"""
program: String = "object Main extends App { print(\"Hello!\") }"

cacilhas-apps@ val tree = program.parse[Source].get
java.lang.NoSuchMethodError: scala.meta.Dialect.allowSignificantIndentation()Z
  scala.meta.internal.parsers.ScalametaParser.isColonEol(ScalametaParser.scala:207)
  scala.meta.internal.parsers.ScalametaParser.countIndentInternal$1(ScalametaParser.scala:660)
  scala.meta.internal.parsers.ScalametaParser.scala$meta$internal$parsers$ScalametaParser$$countIndent(ScalametaParser.scala:666)
  scala.meta.internal.parsers.ScalametaParser$LazyTokenIterator.nextToken(ScalametaParser.scala:367)
  scala.meta.internal.parsers.ScalametaParser$LazyTokenIterator.next(ScalametaParser.scala:281)
  scala.meta.internal.parsers.ScalametaParser$LazyTokenIterator.next(ScalametaParser.scala:271)
  scala.meta.internal.parsers.ScalametaParser.next(ScalametaParser.scala:688)
  scala.meta.internal.parsers.ScalametaParser.accept(ScalametaParser.scala:860)
  scala.meta.internal.parsers.ScalametaParser.parseRule(ScalametaParser.scala:51)
  scala.meta.internal.parsers.ScalametaParser.parseSource(ScalametaParser.scala:142)
  scala.meta.parsers.Parse$.$anonfun$parseSource$1(Parse.scala:29)
  scala.meta.internal.parsers.ScalametaParser$$anon$257.apply(ScalametaParser.scala:5067)
  scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:25)
  scala.meta.parsers.Api$XtensionParseInputLike.parse(Api.scala:14)
  ammonite.$sess.cmd3$.<clinit>(cmd3.sc:1)
```

I **strictly** followed the guide.

**Comment by kpbochenek** [comment]
You have declared version of Scalameta but ammonite has it's own version that conflicts with the one you declared.
In version you provided there is `allowSignificantIndentation` method but ammonite enforces one that doesn't have it.
(at least that was a case in the past when that error was raised)

You can see version they are using:
https://github.com/com-lihaoyi/Ammonite/blob/a1dec1cfbd9fdf1b3a873196d0c48043a340970d/build.sc#L55

And yes you are right, we should probably update docs or maybe try to do something with it, because it is not a first time someone has this problem :(

**Comment by olafurpg** [comment]
Thank you for reporting! This used to work in the past but a recent Ammonite release introduced a dependency on an older version of Scalameta, which causes this problem. You can work around this issue for now by using an older version of Scalameta inside the Ammonite repl

```
❯ amm
Loading...
Welcome to the Ammonite Repl 2.3.8-32-64308dc3 (Scala 2.13.4 Java 1.8.0_272)
@ q"a"
res1: Term.Name = Term.Name(value = "a")
```

**Comment by olafurpg** [comment]
We're working on fixing the root cause of this issue in #2299 and https://github.com/com-lihaoyi/Ammonite/issues/1177
