### ISSUE TITLE
optional braces: `for` at template level

### ISSUE THREAD

**Issue by kitbellew** [scalameta/scalameta#2302]
This doesn't work:
```
object Foo:
  for
    a <- a
    a <- a
  do
    a
    a

  for {
    a <- a
    a <- a
  } do {
    a
    a
  }
```
the first `for` is parsed as
```
TYPE: Name$Anonymous$NameAnonymousImpl
SOURCE: for
STRUCTURE: Name("")
TOKENS: for
```
if we switch them around, both are parsed correctly. if we add `val a =` before the first `for`, it also works. same with `for-yield`. `if` and `while` seem to work.

**Comment by kitbellew** [comment]
@tgodzik @dos65 sorry, more stuff.

**Comment by dos65** [comment]
@kitbellew I've tried to reproduce it but I don't see any issues with your snippet.
In this case `self` points at [14..14) that looks correct. In position test case it's rendered as it shouldn't point at `for` token:
```
   """|Template :
       |  ...
       |Self   @@for
       |Term.For for
       |    a <- a
       |    a <- a
       |  do
       |    a
       |    a
       |  ...
       |""".stripMargin
```

**Comment by tgodzik** [comment]
I think that might be the same issue we fixed before. Let me check that locally and then run another release if it's fixed.

**Comment by kitbellew** [comment]
> I think that might be the same issue we fixed before. Let me check that locally and then run another release if it's fixed.

ah, sorry, you are right, since the upgrade to scalameta failed, i was running the older one. apologies if it's related to self fix.
