### ISSUE TITLE
In a template, underscore is part of `self` but not `self.name`

### ISSUE THREAD

**Issue by kitbellew** [scalameta/scalameta#2334]
In the following code:
```
val foo = new Bar { _ =>
  println("a")
}
```
the underscore used to be part of `self.name` but now it's not (only part of `self`).

is that intentional and consistent?

**Comment by kitbellew** [comment]
@tgodzik @dos65 ^^^

**Comment by dos65** [comment]
It was intentional. The idea was to consitently cleanup `Name.Anonymous` positions in #2322.
Do we need to revert it for this case?

**Comment by kitbellew** [comment]
but in that case, that name was completely missing in the code, it was not real. in this case, there's actually a token. unless there's another overriding reason, I'd say name should show tokens belonging to it, and not show tokens not belonging to it.

**Comment by dos65** [comment]
@kitbellew
I agree. Thanks for leaving comments in #2322 .  Some of them weren't thoughtful enough. I will revert a part of these changes

**Comment by kitbellew** [comment]
@dos65 unfortunately, still relevant.

**Comment by dos65** [comment]
@kitbellew Sorry, I forgot about this case. Fixed in #2340
