### ISSUE TITLE
Breaking quasiquote pattern matching behavior change in 4.4.16

### ISSUE THREAD

**Issue by robby-phd** [scalameta/scalameta#2339]
Not sure if the change is intended, but the following snippet works using 4.4.15-, but breaks with a `MatchError` using 4.4.16.

```scala
import scala.meta._

val q"..$_ class $tname[..$tparams] ..$_ (...$paramss) extends $_" = "@foo class Bar[T](val baz: Bazz[T, U]) {}".parse[Stat].get
println(tname)
```

Scastie:
* [Using 4.4.15](https://scastie.scala-lang.org/yMPUcNjMSPa8PEqmoWeF1A) (prints: `Bar`)
* [Using 4.4.16](https://scastie.scala-lang.org/1OAmAtZHSLeFliD9x0n9JQ) (breaks: `scala.MatchError: @foo class Bar[T](val baz: Bazz[T, U]) {} (of class scala.meta.Defn$Class$DefnClassImpl)`)

**Comment by tgodzik** [comment]
Thanks for reporting! Reading this again I think it's due to the change I did recently. Template now includes the `extends` keyword

This seems to work:
```
import scala.meta._

val q"..$_ class $tname[..$tparams] ..$_ (...$paramss) $_" = "@foo class Bar[T](val baz: Bazz[T, U]) {}".parse[Stat].get
println(tname)
```
Just with removed `extends` - sorry I didn't realize this sooner.

**Comment by kitbellew** [comment]
@robby-phd if removing `extends`, as @tgodzik suggested, fixes the problem, the change is as intended.

**Comment by robby-phd** [comment]
Yes, that works: https://scastie.scala-lang.org/rIEv9CISRcOyR0hvQ4AABQ
I'm closing this issue since the change seems to be intended.
