### ISSUE TITLE
Parse underscore type lambdas (And `+_` and `-_` symbols)

### ISSUE THREAD

**Issue by neko-kai** [scalameta/scalameta#2347]
Recently added to Scala 2 in: https://github.com/scala/scala/pull/9605 (Under flag `-Xsource:3` + kind-projector flag `-P:kind-projector:underscore-placeholders` https://github.com/typelevel/kind-projector/pull/186)
And to Scala 3 in: https://github.com/lampepfl/dotty/pull/12378 (Under flag `-Ykind-projector:underscores`)

Note: Scala (with the above flags) now accepts tokens `+`/`-` followed by `_` as a type lambda placeholder. Some examples w/ edge cases below:
- https://github.com/scala/scala/pull/9605/files#diff-9cc41709c754ef3f0d8f37556e954ff08ce6a8531205c710a4fa84eb59db145a
- https://github.com/lampepfl/dotty/pull/12378/files#diff-95ae2d65c0a03a3dee556e5d610eaa65bfb4d614282904302d3baed217ba659c
- https://scalacenter.github.io/scala-3-migration-guide/docs/tutorials/kind-projector.html

**Comment by dos65** [comment]
@neko-kai Will this change be included in 2.12.14  + `-Xsource:3`?

**Comment by neko-kai** [comment]
@dos65 Yes
