### ISSUE TITLE
Some proposals on semanticdb protos and Scala3 semanticdb extractor

### ISSUE THREAD

**Issue by tanishiking** [scalameta/scalameta#2367]
I think it might be better to do some refactoring around semanticdb protos in both scalameta and Scala3 before working on the improvement of Scala3's semanticdb extractor.
What do you think about this? @tgodzik @bishabosha @olafurpg 

## some disclaimers :)
- I'm not sure this is an appropriate place to discuss (because this issue is related to both scalameta and scala3 (and lsif-java and every library that use semanticdb) if there's a better place to talk about it, let me know :).
- I don't mean to blame the decision of copy-and-pasting generated code in Scala3; I believe it was a good decision for Scala3's semanticdb extractor for moving the project forward (actually, there were not so many case classes are needed for extracting semanticdb's symbol occurrences).

## Background
- The data structures for semanticdb in Scala3 are copy-and-pasted (and some edits so Scala3 doesn't need to have unnecessary dependencies to protobuf).
  - https://github.com/scalameta/metals/discussions/2593#discussioncomment-529949
- The semanticdb protobuf schema is not included in semanticdb's jar like [common protos](https://scalapb.github.io/docs/common-protos)
- The semanticdb proto in [lsif-java is copy-and-pasted with some modification](https://github.com/sourcegraph/lsif-java/blob/c620f594ab1cea4199d45e5e7ff90ff03e5406c5/semanticdb-java/src/main/protobuf/semanticdb.proto)

## Current problem with Scala3 and Semanticdb
Since the data structures for semantidbdb in Scala3 (e.g. [TextDocument.scala](https://github.com/lampepfl/dotty/blob/78c9bc58d330cd2945c26d98fb9ddc215fe93a11/compiler/src/dotty/tools/dotc/semanticdb/TextDocument.scala)) are copy-and-pasted, there're some problems:

- If we want to add more semanticdb support to scala3 and need additional data structures (such as `ClassSignature,` `MethodSignature,` `TypeRef,`... everything), **we have to do copy-and-paste and some modifications for all those generated case classes, which is tedious.**
- Scala3 have to manually catch up the original protobuf schema's update (by generating scala code and copy-and-pasting)
- Cannot catch up scalapb's update (if there's an update in generated code).

### publish semanticdb proto
It might be better to publish semanticdb proto file (and generated scala code) as [common-protos](https://scalapb.github.io/docs/common-protos) do, so that `lsif-java` and `Scala3` can consume the semanticdb protos without copy-and-pasting.

### Make Scala3's semanticdb extractor depends on the published semanticdb proto
I think it would be easier to maintain the semanticdb data structures in the Scala3 if it generates the code from semanticdb protos instead of copy-and-pasting generated Scala codes.

The problem with this is, if scala3 relies on semanticdb proto and its generated code, Scala3 will have a dependency on `scalapb`, which is unpreferable (because compilers should have as small dependencies as possible). I guess it is inevitable as long as we develop a semanticdb extractor as part of the Scala3 compiler and use scalapb in it.

It could be better to **separate the semanticdb extraction phase as a compiler plugin** as the semanticdb plugin (for scala2) does; this enables us to detach the dependency to scalapb from scala3.

**Comment by tgodzik** [comment]
> I think it would be easier to maintain the semanticdb data structures in the Scala3 if it generates the code from semanticdb protos instead of copy-and-pasting generated Scala codes.

> The problem with this is, if scala3 relies on semanticdb proto and its generated code, Scala3 will have a dependency on scalapb, which is unpreferable (because compilers should have as small dependencies as possible). I guess it is inevitable as long as we develop a semanticdb extractor as part of the Scala3 compiler and use scalapb in it.

> It could be better to separate the semanticdb extraction phase as a compiler plugin as the semanticdb plugin (for scala2) does; this enables us to detach the dependency to scalapb from scala3.

I would prefer to avoid making it again a compiler plugin, since the issue here is that we would need to publish it for every version of the compiler and those will come out every 4 weeks. Additionally, it's currently super easy to have semanticdb in Metals, just add the additional flag, which makes it possible to release Metals within a day.

The alternative approach would be to have the semanticdb schema in Scala 3 compiler and generate protobuf files from it. We could use the protobuf java library here instead of scalap or maybe using scalap wouldn't be that big of a problem if it's just a compile dependency. We don't need to have it in the runtime (?) but just to generate the sources. @bishabosha what do you think? Any other ideas on how to avoid having to copy paste the code?

**Comment by olafurpg** [comment]
Thank you for starting this discussion! I’m excited that you’re looking into this :)

I think the best solution is to continue to copy paste the relevant parts of the generated code into Dotty. However, SymbolInformation requires significantly more code than SymbolOccurrence so I can understand this is painful. My reasoning for copy pasteing the code is that you want to be able to compile the compiler codebase from source. While it’s tedious to copy paste and adjust the generated code, it’s a one time thing (Maybe it can be automated with Scalafix?). SemanticDB as a format has been pretty stable so you it’s not something that needs to be done often.

**Comment by tanishiking** [comment]
Thank you for the comments @tgodzik @olafurpg 
It's good to know the background of why we embedded SemanticDBExtractor to the compiler instead of separating it as a plugin.

As @olafurpg mentioned, this process is a one-time thing, it would be a decent option to keep copy-paste-and-adjust the generated code at this moment (and automating the process with Scalafix is a good idea!)

Therefore, I'm going to work on a project that generates from `semanticdb.proto` and adjust it for Scala3 codebase (using Scalafix).

**Comment by tanishiking** [comment]
Though it's a bit crappy, I think I could generate and adjust semanticdb data structures for Scala3!
https://github.com/tanishiking/semanticdb-for-scala3/tree/main/output/src/main/scala/generated/dotty/tools/dotc/semanticdb

I'll try to build scala3 with these generated codes

**Comment by tanishiking** [comment]
Since the generated Scala code is merged into Scala3 repository, and it works really well to update the schema, I'm closing this issue.

- https://github.com/lampepfl/dotty/pull/12780
- https://github.com/lampepfl/dotty/pull/13239

If there's more to talk about the semanticdb schema, let's create another issue and discuss there :)

Thank you so much all the comments @olafurpg @tgodzik @bishabosha !
