### ISSUE TITLE
Scala 3 new keywords are not escaped correctly when used in names

### ISSUE THREAD

**Issue by vigoo** [scalameta/scalameta#2372]
Example:

```scala
  import scala.meta.dialects.Scala3

  println(Term.Name("trait").syntax)
  println(Term.Name("enum").syntax)
```

prints

```
`trait`
enum
```

This makes it hard to generate scala 3 compatible source code from arbitrary external sources where these new keywords may appear as names.

**Comment by tgodzik** [comment]
Thanks for finding this! I added the new keywords to the list https://github.com/scalameta/scalameta/pull/2373

**Comment by vigoo** [comment]
Wow that was fast, thank you :)
