### ISSUE TITLE
Scala 3 empty object with `end` token error

### ISSUE THREAD

**Issue by soronpo** [scalameta/scalameta#2387]
In Scala 3 dialect (under Scalafmt) we get parse error when an object has no body, but has end token.
```scala
object Foo:
end Foo
```

**Comment by tgodzik** [comment]
Thanks for reporting! This is caused by no indentation after `:`, I wasn't aware this was actually possible :sweat_smile:

**Comment by kitbellew** [comment]
@tgodzik is this possible:
```
object Foo:
object Bar:
trait Baz:
end Baz
```

**Comment by tgodzik** [comment]
@kitbellew it's not, it looks like it can be indented statement or end.

**Comment by dos65** [comment]
In addition, I raised an issue https://github.com/lampepfl/dotty/issues/12918 to be sure if need to fix a similar thing for `DefDef`.
