### ISSUE TITLE
Omitted `else` in optional-braces is not empty

### ISSUE THREAD

**Issue by kitbellew** [scalameta/scalameta#2397]
in this expression:
```
if cond then
        sb.append(doc.text.substring(offset, end))
        sb.append(doc.text.substring(offset, end))
```
the `else` subtree of `Term.If` is a `Lit.Unit` consisting of a single `Token.LF` (rather than empty, as I would expect).

**Comment by kitbellew** [comment]
@tgodzik @dos65 ^^^

**Comment by dos65** [comment]
@kitbellew empty `else` was always been expressed as `Lit.Unit`. Even without an extra `LF` at the end `else` is `Lit.Unit`

I think it would be better to keep it as is.
There is no `EmptyTree` equivalent in scalameta Tree model and we can't change `If.elsep` from `Term` to `Option[Term]`

**Comment by tgodzik** [comment]
@dos65 did you take a look at making it 0 length though? Maybe the LF should not be included.

**Comment by kitbellew** [comment]
> @dos65 did you take a look at making it 0 length though? Maybe the LF should not be included.

sorry if i was a bit unclear. @tgodzik is correct, tree type stays just needs to be empty. just like those self references a few weeks ago in templates...

**Comment by dos65** [comment]
ooops :smile: 
Will look what happens with positions)
