### ISSUE TITLE
[Scala3] Proposal to add new Scala3 Types: TypeLambda and MatchType

### ISSUE THREAD

**Issue by tanishiking** [scalameta/scalameta#2403]
# Background
- We're currently working on adding Signature information to Semanticdb generated by Scala3 https://github.com/lampepfl/dotty/pull/12885
- We could express most of Scala3 types with the current SemanticDB types, however, it looks like some new Scala3 types: TypeLambda and MatchType cannot be expressed with the current types.
  - https://scalameta.org/docs/semanticdb/specification.html#type

Propse to add `Type` for accomodating new Scala3 Types: [Type Lambdas](http://dotty.epfl.ch/docs/reference/new-types/type-lambdas.html) and [Match Types](http://dotty.epfl.ch/docs/reference/new-types/match-types.html).

```diff
     ByNameType by_name_type = 13;
     UniversalType universal_type = 10;
     ByNameType by_name_type = 13;
     RepeatedType repeated_type = 14;
+    TypeLambda type_lambda = 24;
+    MatchType match_type = 25;
+    CaseType case_type = 26;
   }
 }
message TypeLambda {
  repeated Scope parameters = 1;
  Type return_type = 2;
}

message MatchType {
  Type scrutinee = 1;
  Type bound = 2;
  repeated CaseType cases = 3;
}

message CaseType {
  Scope type_parameter = 1;
  Type key = 2;
  Type body = 3;
}
```

# TypeLambda

```protobuf
message TypeLambda {
  repeated Scope parameters = 1;
  Type return_type = 2;
}
```

### Example:
```scala
type Tuple = [X] =>> [Y] =>> (X, Y)
```

```scala
// Scala3 internal representation
HKTypeLambda(
  List(X),
  List(
    TypeBounds(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Nothing),TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Any))
  ),
  HKTypeLambda(
    List(Y),
    List(
      TypeBounds(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Nothing),TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Any))
    ),
    AppliedType(
      TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Tuple2),
      List(TypeParamRef(X), TypeParamRef(Y))
    )
  )
)
// to
TypeLambda(
  List(
    Scope(
      symlinks = List(
        example/TypeLambda$package.Tuple#[X]
      ),
      hardlinks = List()
    )
    Scope(
      symlinks = List(
        example/TypeLambda$package.Tuple#[Y]
      ),
      hardlinks = List()
    )
  ),
  TypeRef(
    Empty,
    scala/Tuple2#,
    List(
      TypeRef(Empty,example/TypeLambda$package.Tuple#[X],List()),
      TypeRef(Empty,example/TypeLambda$package.Tuple#[Y],List()),
    )
  )
)
```

# MatchType
`MatchType` consists of 2 types, `MatchType` and `CaseType`

```protobuf
message MatchType {
  Type scrutinee = 1;
  Type bound = 2;
  repeated CaseType cases = 3;
}

message CaseType {
  Scope type_parameter = 1;
  Type key = 2;
  Type body = 3;
}
```

With the following example,
- `scrutinee` is `X` (technically, `TypeRef` to `X` declared in `Elem[X]`)
- `bound` is `Any`
- `cases` are each case patterns for the match type.
  - for `case String => Char` which is the simplest pattern,
    - the internal representation of the case will be `MatchCase[String, Char]`
    - and `CaseType` will be `CaseType(type_paramter = Empty, key = String, body = Char)`
  - for `case Array[t] => t`, it is encoded as `[t] =>> MatchCase[Array[t], t]`
    - we can convert it to `CaseType` with `CaseType(type_paramter = Scope(t), key = Array[t], body = t)`

```scala
type Elem[X] <: Any = X match
  case String => Char
  case Array[t] => t
  case Iterable[t] => t
```

### Example

```scala
type Elem[X] <: Any = X match
  case String => Char
  case Array[t] => t
```

```scala
MatchType(
  TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Any),
  TypeParamRef(X),
  List(
    AppliedType( // represents `case String => Char`
      TypeRef(ThisType(TypeRef(NoPrefix,module class runtime)),class MatchCase),
      List(
        TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class scala)),object Predef),type String),
        TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object scala),class Char)
      )
    ),
    HKTypeLambda(
      List(t), // [t] =>> MatchCase[Array[t], t]
      List(TypeBounds(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Nothing),TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Any))),
      AppliedType(
        TypeRef(ThisType(TypeRef(NoPrefix,module class runtime)),class MatchCase),
        List(
          AppliedType(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object scala),class Array),List(TypeParamRef(t))), TypeParamRef(t))
      )
    )
  )
)

// to

MatchType(
  TypeRef(Empty,_empty_/MatchType$package.Elem#[X],List()),
  TypeRef(Empty,scala/Any#,List()),
  List(
    CaseType(
      Some(Scope(List(),List())),
      TypeRef(Empty,scala/Predef.String#,List()),
      TypeRef(Empty,scala/Char#,List())
    ),
    CaseType(
      Some(Scope(List(),List())),
      TypeRef(
        Empty,
        scala/Array#,
        List(TypeRef(Empty,local0,List()))
      ),
      TypeRef(Empty,local0,List())
    )
  )
)
```

I'm wondering how should we model the `MatchType` like this: (which contains unapplication `*:`)

```
type Concat[Xs <: Tuple, +Ys <: Tuple] <: Tuple = Xs match
  case EmptyTuple => Ys
  case x *: xs => x *: Concat[xs, Ys]
```
from http://dotty.epfl.ch/docs/reference/new-types/match-types.html

**Comment by tanishiking** [comment]
Until we fix the design of the types, I'll work on Scala3 compiler by
- Add the proposed types to `scalameta.proto` in https://github.com/tanishiking/semanticdb-for-scala3 and generate Types (and copy them to Scala3 repo)
- Try to extract Scala3 types with the generated SemanticDB types.

I will submit a PR to scalameta/scalameta that add SemanticDB types after the PR to Scala3 compiler has merged.

**Comment by tgodzik** [comment]
Thanks for raising this!

I have some questions:
- for TypeLambdas shouldn't it translate to something like this:
```
  TypeLambda(
    Scope(
      symlinks = List(
        example / TypeLambda$package.Tuple#[X]
      ),
      hardlinks = List()
    ),
    TypeLambda(
      Scope(
        symlinks = List(
          example / TypeLambda$package.Tuple#[Y]
        ),
        hardlinks = List()
      ),
      TypeRef(
        Empty,
        scala / Tuple2,
        List(
          TypeRef(Empty, example / TypeLambda$package.Tuple#[X], List()),
          TypeRef(Empty, example / TypeLambda$package.Tuple#[Y], List())
        )
      )
    )
  )
```
?
- do we need bound and scrutinee for MatchType? Is it not covered in the TypeSignature ?
- for CaseTypes I would drop `type_parameter`, what would it be used for?
- for `x *: xs` it should be representable the same way as any InfixType currently or would it be impossible?

**Comment by tanishiking** [comment]
Last week I and @tgodzik talked about we may use [Maps](https://developers.google.com/protocol-buffers/docs/proto3#maps) for representing case patterns of MatchType, but I realized

> the key_type can be any integral or string type (so, any scalar type except for floating point types and bytes). Note that enum is not a valid key_type. The value_type can be any type except another map.

and if I define 

```protobuf
message MatchType {
  Type scrutinee = 1;
  Type bound = 2;
  map<Type, Type> cases = 3;
}
```

and try to generate scala code, I got `scalameta.proto:157:3: Key in map fields cannot be float/double, bytes or message types.`.

**Comment by olafurpg** [comment]
This is exciting! Minor thoughts:

I like the CaseType encoding over using maps. 

TypeLambda should probably be called LambdaType for consistency with other names that also end with “Type”. 

Do type lambda parameters use hard links? If not, it might be better to use “repeated string” over Scope. Although, I’m not 100% sure, I also like using Scope because the parameters introduce a new scope. No strong opinions here, just thinking out loud. 

Can type lambda parameters be referenced externally? If not, then we might want to use local symbols for them. If we keep the global symbol syntax then that needs to be added to the spec on global symbols.

**Comment by tgodzik** [comment]
> I like the CaseType encoding over using maps.

Sure, it makes sense especially that maps cannot operate on Type as key.

**Comment by tanishiking** [comment]
> for TypeLambdas shouldn't it translate to something like this:

👍 

> do we need bound and scrutinee for MatchType? Is it not covered in the TypeSignature ?

- Yeah, maybe we can omit `bound` from `MatchType` by converting `type Elem[X] <: UpperBound = X match { ... }` by `TypeSignature(..., lo = MatchType(...), hi = UpperBound)`
- I think we can't remove `scrutinee` from `MatchType` because without scrutinee, we can't tell which type (parameter) to pattern match.
  - For example, if we have `type Elem = [X, Y] =>> X match { ... }`, it will be converted like `TypeLambda(Scope(X, Y), MatchType(...))`.
  - If we have `MatchType(scrutinee = X, ...)`, we can find the `MatchType` will pattern match on the type of `X,` but without scrutinee, we can't tell which type X or Y to pattern match.

> for CaseTypes I would drop type_parameter, what would it be used for?

👍 

> for x *: xs it should be representable the same way as any InfixType currently or would it be impossible?

Yeah, we might be able to represent it with infix type; I'll take a look!
https://scalameta.org/docs/semanticdb/specification.html#type-1

---

> TypeLambda should probably be called LambdaType for consistency with other names that also end with “Type”.

That's a good idea!
Also, it might be better to rename it to something like `FunctionType` because I personally feel `LambdaType` seems like too much Scala specific.

> Do type lambda parameters use hard links? If not, it might be better to use “repeated string” over Scope.

No, I'm planning to use symlinks here.
I think `Scope` is appropriate here because `LambdaType` is actually introducing a Scope :)

> Can type lambda parameters be referenced externally? If not, then we might want to use local symbols for them. If we keep the global symbol syntax then that needs to be added to the spec on global symbols.

No, it's not.
I thought global symbols are fine because in Scala2 [we use global symbols for parameters of MethodSignature](https://github.com/scalameta/scalameta/blob/main/tests/jvm/src/test/resources/example/Methods.scala), but indeed local symbols could be better 🤔 
For type parameters of TypeLambda, can't we use `[]` of `TYPE_PARAMETERS` for them?
> For TYPE_PARAMETER, concatenation of a left bracket ([), its symbol name and a right bracket (]).
https://scalameta.org/docs/semanticdb/specification.html#languages like this https://github.com/tanishiking/dotty/pull/1/files#diff-9a7362382fd79aa03fd915925371c4b5034b8b8045db0a2c59051bc3b65aea65R3 ?

**Comment by bishabosha** [comment]
Why would you need `TypeLambda` when there is `UniversalType`?

**Comment by bishabosha** [comment]
Here is the argument against reusing `UniversalType` - a type lambda is from Type to Type, whereas the precedent in the Scala 2 implementation is that `UniversalType` goes from Type to Term, e.g. `Option.empty`

**Comment by smarter** [comment]
Instead of adding every new Scala 3 type (and tree) to the semanticdb spec bit by bit, could semanticdb switch to reusing the type and tree representation from TASTY? This way semanticdb wouldn't have to continously play catch-up with the compiler, we would get a lot less semanticdb-specific code to maintain, we could reuse tooling between .tasty and .semanticdb files and I guess semanticdb generation could be faster too.

**Comment by tgodzik** [comment]
> Instead of adding every new Scala 3 type (and tree) to the semanticdb spec bit by bit, could semanticdb switch to reusing the type and tree representation from TASTY?

Not sure how would that be achieved. Semanticdb also supports Scala 2, Java and most likely Kotlin in the near future, so I don't see how it would be possible to use Tasty trees here.

**Comment by smarter** [comment]
You could reuse the tasty format for trees/types common to all languages, and add extra ones for the stuff specific to other languages. Right now, the Scala 3 compiler contains about 5 KLOC for tasty pickling and unpickling, but it also contains 11 KLOC just for semanticdb pickling and this keeps growing. I'm concerned about performance (apparently right now semanticdb generation takes ~15% of our compilation time), maintainablity (how much stuff do we need to change in the semanticdb support when we add a feature to the language?) and duplication of effort (why work on two different serialized AST formats instead of pooling our resources together on one?)

**Comment by tanishiking** [comment]
Thank you for the comments @smarter! I really understand your concerns, especially about duplication of effort.

I guess your suggestion means replacing SemanticDB with Tasty (or enabling semanticdb to embed tasty somehow?) (sorry if I'm misunderstanding!) and/or enabling scalameta to read tasty format?

Though I understand your concerns, I'm not sure it is plausible to reuse a tasty format because:

- Scalameta and tasty have different design choices
  - One of the motivations of SemanticDB is a lower learning curve: enable tooling engineers to develop devtools without deep knowledge about compiler internals.
    - refer: https://scalameta.org/talks/2018-06-20-HowWeBuiltToolsThatScaleToMillionsOfLoc.pdf
  - Though (I'm not so familiar with the tasty and) it has more information than semanticdb, I guess tasty resembles the compiler internal representations. That contradicts SemanticDB's design.
- As @tgodzik mentioned, semanticdb already supports scala2, java, and kotlin. And there's already a lot of tools based on semanticdb.
  - If we decide to reuse tasty trees/types, all those tools have to fit into tasty instead of semanticdb, which isn't feasible, I think.
  - Also, I'm concerned that is Tasty designed to model other languages other than scala2 and scala3

(FYI, around half of the files in `semanticdb/` are automatically generated protobuf models. the real number is around 6KLOC)

**Comment by smarter** [comment]
> or enabling semanticdb to embed tasty somehow?

Something like that yeah, I don't actually know why exactly semanticdb needs to able to refer to TypeLambda and such, but assuming that it's because it needs to store things which are not already stored/easily accessible in the tasty file itself, then it makes sense to reuse the existing encoding of tasty instead of coming up with a new one.

>  I guess tasty resembles the compiler internal representations. That contradicts SemanticDB's design.

I don't see the contradiction. You can see the tasty format spec in the comment at the top of https://github.com/lampepfl/dotty/blob/master/tasty/src/dotty/tools/tasty/TastyFormat.scala (there's also a video of me trying to explain it with too many diagrams at https://www.youtube.com/watch?v=zQFjC3zLYwo), if you look at TYPELAMBDAtype for example it's not very different from the TypeLambda you're proposing in this issue.

> And there's already a lot of tools based on semanticdb. 

But do these tools directly interact with the semanticdb format or do they use scalameta APIs? If the latter then the exact on-disk format shouldn't matter for them.

> If we decide to reuse tasty trees/types, all those tools have to fit into tasty instead of semanticdb, which isn't feasible, I think.

I don't think it's unfeasible, we can reserve a set of trees/types tags in tasty for external languages and then you can define anything you need, in a way that's similar to what you're proposing here but the other way around.

**Comment by tanishiking** [comment]
> But do these tools directly interact with the semanticdb format, or do they use scalameta APIs? If the latter, then the exact on-disk format shouldn't matter for them.

Ah, right. If we, for example:

- Save `.tasty` file instead of `.semanticdb`
- Support the capabilities of libraries that read semanticdb (e.g., scalameta) to read the `.tasty` file (on-disk) and convert it to `semanticdb` format (on-memory?).
- Tools read semanticdb information through the libraries (actually they do).

Tool author's don't need to care about the disk format :+1:

Anyway, I need to know more about the tasty format, let me sleep on it...

**Comment by smarter** [comment]
> Save only .tasty file instead of .semanticdb

Generating semanticdb directly from the compiler is probably still useful for things which are expensive to recompute from tasty like symbol occurences, I don't know much about the other sections in semanticdb and what they're used for so I can't say more about how it compares to tasty (/cc @bishabosha who probably understands both formats the best and might be able to help :)).
