### ISSUE TITLE
[Scala 3] Parser issues

### ISSUE THREAD

**Issue by tgodzik** [scalameta/scalameta#2405]
I've taken a look at parsing the Dotty pos test cases and I found a bunch of errors:

Issues:

- [x] https://github.com/scalameta/scalameta/pull/2408

```scala 
type Macro[X] = (=> Quotes) ?=> Expr[X]
```

- [x] https://github.com/scalameta/scalameta/pull/2409
```scala
given noCaller: Caller(???) with
   override def computeValue() = ()
```

```scala
given C(1) with {}
``` 

```scala     
given t1[T]: E[T]("low") with {}
```

- [x] https://github.com/scalameta/scalameta/pull/2404
```scala
given [T](using e: Exp[T]): Exp[NCtx => T] with
    import NCtx.*
    def lit(i: Int) = {
      case Pos => e.lit(i)
      case Neg => e.neg(e.lit(i))
    }
    def neg(x: NCtx => T): NCtx => T = {
     case Pos => x(Neg)
     case Neg => x(Pos)
    }
    def add(l: NCtx => T, r: NCtx => T): NCtx => T =
      c => e.add(l(c), r(c))
```
      
- [x] https://github.com/scalameta/scalameta/pull/2422
```scala
println(s"\"Hello\", $person")
```
 
- [x] https://github.com/scalameta/scalameta/pull/2419
```scala
check_success("\"\\u0024\" == \"$\"", s"\u0024", "$")
```

- [x] https://github.com/scalameta/scalameta/pull/2410
```scala
'{ val x: Int = ${ (q2) ?=> a } }
``` 

- [x] https://github.com/scalameta/scalameta/pull/2418
```scala
 def f(x: Int) =
  assert(
    if x > 0 then
      true
    else
      false
  )
  assert(
    if x > 0 then
      true
    else
      false)
  assert(
    if x > 0 then
      true
    else
      false, "fail")
  assert(
    if x > 0 then
      true
    else
      if x < 0 then
        true
      else
        false, "fail")
  (
    if x > 0 then
      println(x)
      x
    else
      s"""foo${
        if x > 0 then
          println(x)
          x
        else
          -x
        }"""
  )
```

- [x] https://github.com/scalameta/scalameta/pull/2417
```scala
  object Test:
  try List(1, 2, 3) match
  case x :: xs => println(x)
  case Nil => println("Nil")
  catch
  case ex: java.io.IOException => println(ex)
  case ex: Throwable => throw ex
  end try
```

- [x] https://github.com/scalameta/scalameta/pull/2413
```scala
val y3 =
    if (1) max 10 gt 0
    then
      expr
```
      
- [x] https://github.com/scalameta/scalameta/pull/2420
```scala
type T1 = (Lambda { type Arg = Int } { type Apply = List[Arg] }) # Apply
```

- [x] https://github.com/scalameta/scalameta/pull/2412
```scala
def b2 = "".foo2(using foo)[Any]
```

- [x] https://github.com/scalameta/scalameta/pull/3034
```scala
class Baz1 @deprecated(implicit c: C)
```

- [x] https://github.com/scalameta/scalameta/pull/2416
```scala
def send() =
  c ! "hello"
    ! "world"
    send_! "!"
```

- [x] https://github.com/scalameta/scalameta/pull/2415
```scala
val x * y = v
```

- [x] https://github.com/scalameta/scalameta/pull/2423
```scala
given Context()
```

**Comment by tgodzik** [comment]
The only remaining one in this task is `class Baz1 @deprecated(implicit c: C)`

**Comment by kitbellew** [comment]
@tgodzik please feel free to close this if it's all done. (also, how do you add a link to the pr next to the checkmark?)

**Comment by tgodzik** [comment]
> @tgodzik please feel free to close this if it's all done. (also, how do you add a link to the pr next to the checkmark?)

I just edit the comment, thanks for taking care of that one!
