### ISSUE TITLE
[Scala 3] Spurious `expected template body` when line begins with comment

### ISSUE THREAD

**Issue by griggt** [scalameta/scalameta#2424]
Using Scala 3 optional braces style, I commented out the `inline` keyword to debug something and got an `expected template body` error (Metals 0.10.5 in VS Code):

```scala
object Foo:
  /*inline*/ def bar: String = ???
```
![expected_template_body](https://user-images.githubusercontent.com/17014833/126047635-df71ee14-c7c8-4281-ae2f-0a59f943a888.png)

**Comment by dos65** [comment]
Thx for reporting! That's a scalameta parser issue.
