### ISSUE TITLE
Formatting fails on top-level opaque type definition for Scala 3.0.2

### ISSUE THREAD

**Issue by danicheg** [scalameta/scalameta#2466]
- **Scala version**: 3.0.2
- **Scalafmt version**: 3.0.2
- **Integration**: sbt
- **Configuration**:
```
version = 3.0.2
maxColumn = 100
continuationIndent.callSite = 2
newlines {
  sometimesBeforeColonInMethodReturnType = false
}
align {
  arrowEnumeratorGenerator = false
  ifWhileOpenParen = false
  openParenCallSite = false
  openParenDefnSite = false
  tokens = ["%", "%%"]
}
docstrings.style = Asterisk
rewrite {
  rules = [SortImports, RedundantBraces]
  redundantBraces.maxLines = 1
}
```

## Steps

Given code like this:
```scala
opaque type Sum[A] = A
```

When I run scalafmt like this:

```bash
scalafmtAll
```

## Problem

Scalafmt fails with
```
error: expected class or object definition identifier
opaque type Sum[A] = A
```

**Comment by dos65** [comment]
I've checked this sample and it's parsed well. The problem is in configuration.

@danicheg For scala3 sources you need to add `runner.dialect = scala3` to your `.scalafmt.conf`. You can find more info about dialects [here](https://scalameta.org/scalafmt/docs/configuration.html#scala-dialects)
