### ISSUE TITLE
Release with support for Scala 2.12.15, please?

### ISSUE THREAD

**Issue by SethTisue** [scalameta/scalameta#2473]

**Comment by SethTisue** [comment]
(if needed? I see that Scalameta isn't published by full version, but I also see e.g. https://github.com/scalameta/scalameta/pull/2371)

**Comment by tgodzik** [comment]
Thanks for reminding! I will work on that today and release a new version of scalameta.

**Comment by tgodzik** [comment]
We need macro-paradise first though, I will have a PR ready as soon as it's published.

**Comment by timo-schmid** [comment]
> We need macro-paradise first though, I will have a PR ready as soon as it's published.

https://github.com/scalamacros/paradise/pull/128

Created!

**Comment by SethTisue** [comment]
https://repo1.maven.org/maven2/org/scalamacros/paradise_2.12.15/2.1.1/
