### ISSUE TITLE
Use sbt-git and versioning with Git instead of snapshots

### ISSUE THREAD

**Issue by hseeberger** [scalameta/scalameta#250]
Snapshot resolution in sbt sucks and stable versions like "0.1.0-<commit-id>" make the user experience smoother.

**Comment by xeno-by** [comment]
I'm about to release 0.0.4 in a few days, and starting from then, I'll never be using snapshots in tutorials.

**Comment by hseeberger** [comment]
Don't worry about the tutorial, it was great!
What I'm suggesting here is to get rid of snapshots at all. If you use sbt-git for versioning, you still can still make daily or more frequently releases without the woes of snapshots.

**Comment by xeno-by** [comment]
Implemented in https://github.com/scalameta/scalameta/pull/590/commits/f4ca319c05c292e2bc7a2de7308c43fed9224eab.
