### ISSUE TITLE
scala3: fails to parse TryWithHandler if catch followed by NL

### ISSUE THREAD

**Issue by kitbellew** [scalameta/scalameta#2513]
The following snippet fails parsing with scala3 dialect:
```
  try
    a
  catch
    bar
  finally
    a
```
according to https://docs.scala-lang.org/scala3/reference/syntax.html#expressions, it looks like `catch` can be followed by any expression (not just `case`) and doesn't prohibit newline.

**Comment by dos65** [comment]
@kitbellew It works only if `bar` is in braces that is in line with compiler implementation

**Comment by kitbellew** [comment]
@dos65 the grammar simply says `Expr | ExprCaseClause`, no? and if `try` allows any expression, with or without a newline, why wouldn't catch allow that?

one can write
```
  val a =
    case ... => ...
  val a =
    foo
```
so why can't `catch` allow both `case` and non-case?

**Comment by tgodzik** [comment]
It doesn't compile without `case` from what I checked, so most likely it's an issue with the grammar or maybe we should report it first in Dotty to see if maybe it's expected to work?

**Comment by kitbellew** [comment]
ok, we can postpone this. i was adding additional logic to the formatter, and that resulted in parsing errors.

**Comment by tgodzik** [comment]
> ok, we can postpone this. i was adding additional logic to the formatter, and that resulted in parsing errors.

Let me know if you want me to raise an issue in https://github.com/lampepfl/dotty

**Comment by kitbellew** [comment]
> > ok, we can postpone this. i was adding additional logic to the formatter, and that resulted in parsing errors.
> 
> Let me know if you want me to raise an issue in https://github.com/lampepfl/dotty

i would definitely appreciate it :)

**Comment by kitbellew** [comment]
thank you, @tgodzik, looks like your submission has been accepted and is being fixed. should we fix it here, too?
