### ISSUE TITLE
Option for sourceroot to be relative to targetroot (or another parameter that is)

### ISSUE THREAD

**Issue by aishfenton** [scalameta/scalameta#2515]
Current the `sourceroot` option is treated as being relative to the cwd, rather than the `targetroot`. Unfortunately this causes issues in Gradle.

Sorry it's a little complicated to explain, but reason is:

* Gradle doesn't use the project root as it's cwd. Instead it has N workers that run under their own directories, but point the `scalac` task to a particular scala file and output location (which is under the project).

* If you set `sourceroot` as a compiler option this breaks caching in Gradle, as any differences in compiler options (between machines) forces Gradle to recompile, rather than to download existing compiled artifacts. In our particular case, this is a signifiant overhead. We rely on Gradle's caching to make compiling our very large (almost mono) repo tractable.   
 
However, having an option (either `sourceroot`, or a new option) that you can set relative to `targetroot` solves this. As the `targetroot` is automatically derived from `scalac`'s output directory, which is already set to the right place.

**Comment by aishfenton** [comment]
Related gradle-scalafix issue. https://github.com/cosmicsilence/gradle-scalafix/issues/58

**Comment by tgodzik** [comment]
Thanks for reporting! I wonder, would it be possible (as a workaround) to set sourceroot to maybe something like `../` based on where the Gradle worker directories are located? Are they deterministic? 

We could add another option for sure, this seems like a valid use case to have the artifacts machine independent. I wonder though if it will be easy to figure out the sourceroot based on targetroot. Wouldn't it be the same case as trying to determine sourceroot from the workers' cwd ?

**Comment by johnynek** [comment]
If you are open to it, I could make a PR that adds `-P:semanticdb:relative_sourceroot` which will create a `source_root` by resolving from the `targetroot`.

Should I prepare that PR?

**Comment by jvican** [comment]
I've dug a bit deeper to see what's going on. I think the following:

> Gradle doesn't use the project root as it's cwd. Instead it has N workers that run under their own directories, but point the scalac task to a particular scala file and output location (which is under the project).

might not be true. The real issue here is that Scalafix (+ semanticdb, most likely) doesn't allow the source root to be relative. Here's the place where the check is made

https://github.com/scalacenter/scalafix/blob/a543de1ee943cc8aacf00cef5cbd7a0370563c03/scalafix-cli/src/main/scala/scalafix/internal/interfaces/ScalafixArgumentsImpl.scala

This is impeding us from using a relative path that can be safely cached by Gradle.

The fix for making the scalafix gradle cache work and cacheable involves making Scalafix accept a relative path and resolve it based on the working directory that was configured for Scalafix via `withWorkingDirectory` or the default one.
This solution feels less hacky than making the sourceroot relative to the targetpath.

I don't think it'll be necessary to make the `sourceroot` option in the SemanticDB. So long as Scalafix is launched in the gradle project or root dir --pretty confident this is the case--, we're good because we can pass the right relative path for it.

**Comment by jvican** [comment]
@aishfenton pointed out that we will need the relative sourceroot option to also work in semanticdb, I missed that scalafix is just locating the previously compiled semanticdb files, so this ticket is still relevant in this repository.

**Comment by aishfenton** [comment]
I also confirmed that the CWD in Gradle's compile tasks isn't the project root, it's `GRADLE_USER_HOME/workers`. And from this issue, seem unlikely that there's an option to change it: https://github.com/gradle/gradle/issues/7323

**Comment by tgodzik** [comment]
> If you set sourceroot as a compiler option this breaks caching in Gradle, as any differences in compiler options (between machines) forces Gradle to recompile, rather than to download existing compiled artifacts. In our particular case, this is a signifiant overhead. We rely on Gradle's caching to make compiling our very large (almost mono) repo tractable.If you set sourceroot as a compiler option this breaks caching in Gradle, as any differences in compiler options (between machines) forces Gradle to recompile, rather than to download existing compiled artifacts. In our particular case, this is a signifiant overhead. We rely on Gradle's caching to make compiling our very large (almost mono) repo tractable.  

Alternatively, could we filter that compiler option to not be taken into account for caching?

If not, it seem that we will need the additional setting `relativeSourceroot`, which would be able to derive the semanitcdb location based on the output directory. If anyone is willing to take a stab at it by all means please do :pray:

**Comment by jvican** [comment]
> Alternatively, could we filter that compiler option to not be taken into account for caching?
  
This is what we're investigating, will keep you posted. If we don't manage to do this, then we'll most likely need to add a setting similar to `relativeSourceRoot`.

**Comment by aishfenton** [comment]
Related (but slightly different issue) https://github.com/scalameta/scalameta/issues/2518
