### ISSUE TITLE
Cannot parse Scala 3 syntax - Object

### ISSUE THREAD

**Issue by alpha-delta0** [scalameta/scalameta#2517]
Hi, I see that progress is being made to support Scala 3 and I'm not exactly sure how much progress has already been made but at the moment I'm not able to parse the following code -

```scala
object Foo:
  def bar(): Unit = println("bar")

@main def main(): Unit =
  Foo.bar()
```

Error -
```
[error] (run-main-0) <input>:3: error: ; expected but : found
[error] object Foo:
[error]           ^
[error] <input>:3: error: ; expected but : found
[error] object Foo:
```

Scalameta version: `4.4.31`.

Am I missing something here? How do I get started with parsing Scala 3 source files? I apologize if this was already reported/is being tracked!

**Comment by tgodzik** [comment]
Thanks for reporting! How are you running the parser currently? You need to set the Scala3 dialect in order to parse the Scala 3 code. Everything should work correctly in that case, the parser is compatible with the compiler as far as we can tell.

**Comment by alpha-delta0** [comment]
I guess I missed the `dialect` thingy. Could you help me out with setting that?

**Comment by PawanKartikS** [comment]
Consider looking into `dialects.Scala3`? Here's something minimal that might help -
```scala
dialects.Scala3(program).parse[Source].get
```

**Comment by alpha-delta0** [comment]
Thank you!!

**Comment by tgodzik** [comment]
Let us know if you need any more help. You can always reach out on discord where we are more responsive.

Closing this for now.
