### ISSUE TITLE
Scalafmt should indent code blocks under the `@example` tag

### ISSUE THREAD

**Issue by Atry** [scalameta/scalameta#2526]
- **Version**: 2.13
- **Integration**: sbt
- **Configuration**:
```
runner.dialect = "scala213"
version = "3.1.2"
maxColumn = 80
```

## Steps

Given code like this:
```scala
    /** description
      * @example
      *   my example:
      *   {{{
      *   foo.bar()
      *   }}}
      */
```

When I run scalafmt like this:

```bash
scalafmt
```

## Problem

Scalafmt formats code like this:
```scala
    /** description
      * @example
      *   my example:
      * {{{
      *   foo.bar()
      * }}}
      */
``````

## Expectation

I would like the formatted output to look like this:
```scala

```scala
    /** description
      * @example
      *   my example:
      *   {{{
      *   foo.bar()
      *   }}}
      */
``````

## Workaround

I've found that by commits created by @scala-steward

https://github.com/ThoughtWorksInc/Binding.scala/commit/e5dd057e05568c4df4febf94e84ac6e21292a303

## Notes

Scalafmt should indent code blocks under the `@example` tag

**Comment by kitbellew** [comment]
https://docs.scala-lang.org/overviews/scaladoc/for-library-authors.html
"Code blocks are contained within `{{{ this }}}` and may be multi-line. Indentation **is relative to the starting `*`** for the comment."

so, other than the position of `{{{` themselves, nothing else can be changed.
