### ISSUE TITLE
Rethink Dialect

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#253]
## Background

In 0.0.4, I'm going to obviate the need to write `import scala.meta.dialects.Scala211` everywhere by introducing an implicit materializer that will expand to the dialect corresponding to the current version of Scala.

I was (and still kinda am) against this, because having default language version preselected doesn't feel like the right thing to do in a platform- and version-independent library.

However, as @densh has rightfully pointed out, this doubles the amount of boilerplate for simple tasks (requiring 2 imports instead of 1 imports for semantic APIs), plus it requires explaining an extra concept to the newcomers.

Thinking about this in more depth, I realized that our behavior wrt dialects is inconsistent with our behavior wrt contexts, because concrete implementations in scalahost are called Mirror, Proxy, Toolbox instead of Mirror211, Proxy211 and Toolbox211.

Since it's all so messed up, I'm going to err on the side of simplicity and lift the requirement to import a dialect explicitly. In the meanwhile, I'll keep this issue open so that we don't forget about it.
## Actionable items
- [ ] Figure out how to / whether to switch context implementations on the fly. 
  - Currently it's flat out impossible, because if we try scalahost211 and scalahost212 as separate library linked together in an umbrella scalahost library, it's not going to work, because mixing scala-compiler for 2.11 and scala-compiler for 2.12 (transitive dependencies of scalahosts) is going to lead to jar hell.
  - Maybe Jigsaw will make things better, but I have no idea. Maybe @darkdimius follows the developments there and could provide some info.
  - At some point we might want to rename `scala.meta.internal.hosts.scalac` into `scala.meta.internal.hosts.scalac211`.
- [ ] Find out a way to ensure that `implicitly[Dialect] == implicit[Context].dialect`.
  - We could have `Context.apply` take an implicit dialect and then make sure that it's equal to the dialect of the context that it's going to create. However, it's only going to work if you write `import some.dialect; { implicit val c = Context(...) }`, but it won't catch discrepancies in `implicit val c = Context(...); { import some.dialect }`.

**Comment by Atry** [comment]
What is Context?

**Comment by Atry** [comment]
Is there a macro to create Dialect according to the current compiler setting?

**Comment by xeno-by** [comment]
This issue is pretty dated. `Context` is something that is called `Mirror` now.

There used to be a macro called `currentDialect`, but now it's just a normal method implemented differently by different platforms that we support:
  * https://github.com/scalameta/scalameta/blob/e92a7b9825d6d94dbb0b16815f40a24d4055c35d/scalameta/dialects/shared/src/main/scala-2.11/scala/meta/internal/dialects/InternalDialect.scala
  * https://github.com/scalameta/scalameta/blob/e92a7b9825d6d94dbb0b16815f40a24d4055c35d/scalameta/dialects/shared/src/main/scala-2.12/scala/meta/internal/dialects/InternalDialect.scala

**Comment by Atry** [comment]
So it never returns `Paradise211` or `Paradise212` if I understand correctly.

**Comment by xeno-by** [comment]
Yes, that's right. I think the only solution in your situation is to `import scala.meta.dialects.Paradise211` explicitly. What do you think?

**Comment by Atry** [comment]
I think a macro is able to detect if there is a macro paradise plugin, like:

``` scala
c.compilerSettings.exists(_.matches("""-Xplugin:.*paradise.*"""))
```

**Comment by xeno-by** [comment]
I guess the question is what kind of default we prefer in that case - still `Scala211` or `Paradise211`. I'd vote for the former personally. Wdyt @olafurpg?

**Comment by DavidDudson** [comment]
I'd still vote for the former. Just because someone is using macros does not mean they want to manipulate macro code. Most of the time, it means they want to manipulate regular Scala code

**Comment by Atry** [comment]
@DavidDudson 
There are two questions:

1. How to make `current` method return current dialect?
2. Should `current` method be the default dialect?

I think you mean the `current` method should not be the default dialect on the second question.

**Comment by olafurpg** [comment]
My experience is that most of the time I want a lenient dialect that accepts as many syntactic features as possible

- inline keyword
- literal types
- trailing commas
- trait parameters
- ...

So far, I haven't hit on a single application where I care about failing fast when I falsely use one of those features on in a host language that does not support that feature. For example, if I use trailing commas in Scala211, then I will eventually get a decent parse error message from scalac anyways.

I'm not advocating to get rid of dialects, I see their importance in a lot of applications. However, in most common cases, the complication from dialects is not worth the safety they provide (esp. scalameta beginners)

**Comment by xeno-by** [comment]
@olafurpg Where would you use dialects then?

**Comment by olafurpg** [comment]
For example, if I we're to write a new Scala compiler on top of Scalameta then I would want to use dialects. Same maybe for tooling on top of sbt, then we might want to guard against unsupported syntactic features during parsing. Being able to validate a tree against a dialect might also be useful in some application, related https://github.com/scalameta/scalameta/issues/599.

In all of the above cases, I want to be explicit about what dialect I'm using. When I'm not explicit about the dialect, I would like it to fallback to the most lenient dialect.

The problem with using a strict dialect as `current` is that it forces you to pass around a Dialect across all methods, and be careful to never use the default `implicit Scala21` when calling methods like `Tree.tokens`. Related https://github.com/scalameta/scalameta/issues/674. When you implicitly rely on a strict `current` Dialect, then you can hit on unexpected errors like this
```scala
@ import dialects.Dotty
import dialects.Dotty
@ t"a & b" // repl calls Tree.toString which uses current (Scala211)
java.lang.UnsupportedOperationException: Scala211 doesn't support and types
 scala.meta.internal.prettyprinters.TreeSyntax$syntaxInstances$2$.$anonfun$syntaxTree$1(TreeSyntax.scala:315)
```

**Comment by olafurpg** [comment]
What is the actionable item here for the v1.9 milestone?

**Comment by olafurpg** [comment]
After some thinking and offline discussions, I think the conclusion is to 

- remove dialects from pretty-printing
- remove dialects from tokens
- keep dialects for parsing
- add `Default` dialect that supports as much as possible without conflict. For example, it can support both trailing commas (2.12 only) and trait parameters (Dotty only).
- add `Scala`/`Dotty`/`Sbt` dialects which alias the latest version of those dialects. For example, it's kind of annoying to have to specify the full version `Sbt0137`  when you really just want to parse .sbt files.

**Comment by xeno-by** [comment]
Also see https://github.com/scalameta/scalameta/issues/674

**Comment by xeno-by** [comment]
Also see https://github.com/scalameta/scalameta/issues/874

**Comment by olafurpg** [comment]
I have been convinced that Dialects are still a necessary evil. For example, see https://github.com/scala-native/scala-native/pull/934/files#diff-8af3e1355c23c331ee2b848e12c5219fR8. Scalafmt allows the inline keyword by default but that means valid scala 2.x code that uses `inline` as an identifier fails to parse. In this case, I think it's OK to allow the "advanced user" (scala-native) override the dialect to Scala211 for their application.

**Comment by xeno-by** [comment]
I have to agree. As much as I came to hate dialects, it does seem that we need them.

**Comment by olafurpg** [comment]
Let's remove this from the v2.0 milestone to unblock a release.

**Comment by xeno-by** [comment]
👍

**Comment by tgodzik** [comment]
It looks like this issue is no longer valid, I will close it, since it seems we have loads of really old issues in scalameta.
