### ISSUE TITLE
Scala 3 dialect rejects legal `for` comprehension

### ISSUE THREAD

**Issue by SethTisue** [scalameta/scalameta#2546]
- **Version**: 3.2.1
- **Configuration**:
```
version = 3.2.1
runner.dialect = scala3
```

## Steps

Given:
```scala
class C:
  def foo =
    (for a <- List(1)
         b <- List(2)
     yield a + b).toSet.size
```

When I run scalafmt like this:

```bash
scalafmt .
```

## Problem

Scalafmt bails with an error:
```
/Users/tisue/tmp/20220105/./87.scala:4: error: [dialect scala3] illegal start of simple expression
         b <- List(2)
           ^
```

## Workaround

inserting a line break after `for` avoids the problem

**Comment by tgodzik** [comment]
This looks a bit weird and I am not sure how to treat it indentation wise. We assumed previously that either for can have `{` or indentation. This is none of that and yet it seems to compile.

I can't find any explanation for this in https://dotty.epfl.ch/docs/reference/other-new-features/indentation.html

Should we report it as a bug?

**Comment by dos65** [comment]
@tgodzik it seems that it's a valid case according to https://dotty.epfl.ch/docs/internals/syntax.html. 
```
ForExpr           ::=  ‘for’ ‘(’ Enumerators0 ‘)’ {nl} [‘do‘ | ‘yield’] Expr     ForYield(enums, expr) / ForDo(enums, expr)
                    |  ‘for’ ‘{’ Enumerators0 ‘}’ {nl} [‘do‘ | ‘yield’] Expr
                    |  ‘for’     Enumerators0          (‘do‘ | ‘yield’) Expr
Enumerators0      ::=  {nl} Enumerators [semi]
```

`Nl` before `Enumerators` is optional

**Comment by tgodzik** [comment]
That looks like it should be on one line though:
```
‘for’     Enumerators0          (‘do‘ | ‘yield’) Expr
```
