### ISSUE TITLE
Scaladoc @link split by scalafmt causes warning

### ISSUE THREAD

**Issue by ekrich** [scalameta/scalameta#2552]
When scalafmt formats scaladoc and splits a `{@link SomeClass}` tag, this results in a scaladoc warning
and the link is not rendered.

I am not really an expert but think that many of the Javadoc syntax can be used in scaladoc. In practical
terms it made it much easier to port a Java library to a Scala library.

Going forward with scaladoc 3, it would be great if these things were supported but I totally would like
things deprecated as needed to whatever the scaladoc 3 state of the art should be along with a good
suggestion on how to change the link.
https://docs.oracle.com/en/java/javase/17/docs/specs/javadoc/doc-comment-spec.html#link

Note: wrapping @code does not cause a warning.
https://docs.oracle.com/en/java/javase/17/docs/specs/javadoc/doc-comment-spec.html#code

Example result of scalafmt wrapping at column 80 and splitting the link.

```scala
/**
   * Creates an instance of a class, initializing its fields from a {@link
   * Config}.
```
Results in the following warning:

```scala
[warn] /Users/eric/workspace/sconfig/sconfig/jvm/src/main/scala/org/ekrich/config/ConfigBeanFactory.scala:13:3: Could not find any member to link for "".
[warn]   /**
[warn]   ^
[warn] 34 warnings found
```

If the whole link block remains on one line then the warning goes away.

Some examples at least in the ekrich/sconfig codebase:
```scala
{@link Config}
{@link Config#hasPathOrNull}
{@link ConfigValue#valueType valueType}
{@link ConfigValueType#NULL NULL}
```

**Comment by kitbellew** [comment]
I'm also not an expert but if you're using javadoc syntax which is not documented anywhere to be supported by scaladoc, you could disable wrapping.

**Comment by kitbellew** [comment]
in scaladoc, `[[ ... ]]` provides the same functionality.

**Comment by ekrich** [comment]
It says that they are supported and given that they are parsed and work if not wrapped I would say that is good enough evidence. https://docs.scala-lang.org/overviews/scaladoc/for-library-authors.html

**Comment by ekrich** [comment]
Also being a Scala Native dude, I would like to see more Java ported to Scala and as such it would be great if the javadoc would just work as a first cut - it is hard enough to make the code work, let alone if the docs don't work. We already had this change this which is similar (a wrap which causes an error) https://github.com/scalameta/scalameta/issues/2398

I had like 100 sites in sconfig to get things working. https://github.com/ekrich/sconfig/commit/ffd581a9d89cb73299473299aedb63e769471ac9

**Comment by ekrich** [comment]
Is it possible to have a scalafix for this? If that could be applied and used then this could be closed.

**Comment by ekrich** [comment]
I used a regex to replace `{@link x}` to `[[x]]` and {@code yyy} to `` ` ``yyy`` ` `` and this not only make the scaladoc more readable but scalafmt does not split these items.
