### ISSUE TITLE
Corruption of SemanticDB files

### ISSUE THREAD

**Issue by wchau** [scalameta/scalameta#2561]
It occurs around 1% of the time against our Scala codebase and is rather flaky. Rerunning it seems to fix it, so it's not 100% reproducible either.

SemanticDB version: 4.4.30
Scala versions: 2.11, 2.12, 2.13

Found while running lsif-semanticdb:

Generating LSIF... [######## ] 89% 39,861 files processedcom.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
processedcom.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).

**Comment by tgodzik** [comment]
Thanks for reporting! Could this be an issue with LSIF for Scala? I have never seen this happen in any of the workspaces I worked with.

Maybe it's an issue when we're trying to read the file before it's finished writing?

@olafurpg any idea what might be going on?

**Comment by olafurpg** [comment]
@wchau thank you for reporting! Can you upload the payload that’s failing to parse? This is the first time somebody reports this issue and SemanticDB sees quite heavy usage.

**Comment by wchau** [comment]
@olafurpg I'll see if I can reproduce it in an OSS environment so that I can share the payload.

**Comment by olafurpg** [comment]
Would you be OK with privately sharing the payload with me? I’m happy to troubleshoot this issue with you in the sourcegraph slack (I can join the channel on Monday). It might be tricky to reproduce in an OSS environment if the issue is rooted in your bespoke setup.

**Comment by tgodzik** [comment]
Is this still an issue?
