### ISSUE TITLE
q"0+ 2" gives scala.meta.internal.ast.MergeException

### ISSUE THREAD

**Issue by ValentinRutz** [scalameta/scalameta#257]
When trying to create the AST for the quasiquote q"0 + 2" for example, the execution results in:

  scala.meta.internal.ast.MergeException: encountered unexpected trees during syntactic + semantic merge:
 * Term.ApplyInfix(Lit.Int(0), Term.Name("+"), Nil, Seq(Lit.Int(2)))
 * Lit.Int(2)
 * <-(Term.ApplyInfix) 0 + 2
 * ->(Lit.Int) 2
 *   at scala.meta.internal.ast.mergeTrees$.fail(MergeTrees.scala:281)
 *   at scala.meta.internal.ast.mergeTrees$.scala$meta$internal$ast$mergeTrees$$failCorrelate(MergeTrees.scala:246)
 *   at scala.meta.internal.ast.mergeTrees$loop$2$.apply(MergeTrees.scala:175)
 *   at scala.meta.internal.ast.mergeTrees$.apply(MergeTrees.scala:220)
 *   at scala.meta.internal.hosts.scalac.contexts.Adapter.loop$1(Adapter.scala:118)
 *   at scala.meta.internal.hosts.scalac.contexts.Adapter.loop$1(Adapter.scala:88)
 *   at scala.meta.internal.hosts.scalac.contexts.Adapter.typecheck(Adapter.scala:121)
 *   at scala.meta.internal.hosts.scalac.contexts.Adapter.defns(Adapter.scala:125)
 *   at scala.meta.semantic.Api$XtensionSemanticRefDefn.defns(Api.scala:137)
 *   at scala.meta.semantic.Api$XtensionSemanticRefDefn.defn(Api.scala:139)

**Comment by xeno-by** [comment]
Fixed in https://github.com/scalameta/scalameta/commit/8c01bdf9183df83e61c9730c08cea3a2ec52fdca, published in 0.1.0-SNAPSHOT.
