### ISSUE TITLE
Use of pattern quasiquote expects the wrong type

### ISSUE THREAD

**Issue by ValentinRutz** [scalameta/scalameta#263]
pattern quasiquote p"$name" expects name to be a scala.meta.Tree and not a scala.meta.Term.Name

**Comment by xeno-by** [comment]
Fixed in https://github.com/scalameta/scalameta/pull/272 via a series of changes to [quasiquotes.md](https://github.com/scalameta/scalameta/blob/master/docs/quasiquotes.md). @ValentinRutz, could you verify that it's now clear?
