### ISSUE TITLE
Use of pattern argument quasiquote returns the wrong type

### ISSUE THREAD

**Issue by ValentinRutz** [scalameta/scalameta#264]
Using the quasiquote parg"$pat" in a pattern matching return pat as a Tree not a Pat

**Comment by xeno-by** [comment]
Fixed in https://github.com/scalameta/scalameta/pull/272 via a series of changes to [quasiquotes.md](https://github.com/scalameta/scalameta/blob/master/docs/quasiquotes.md). @ValentinRutz, could you verify that it's now clear?
