### ISSUE TITLE
support for parsing dotty

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#269]
Shouldn't be very hard given that there are not that many changes from scalac. @darkdimius is there a list of changes somewhere?

**Comment by smarter** [comment]
Here are the ones I can think of:
- union types
- trait parameters: http://docs.scala-lang.org/sips/pending/trait-parameters.html
- repeated by-name parameters: http://docs.scala-lang.org/sips/pending/repeated-byname.html
- literal singleton types: http://docs.scala-lang.org/sips/pending/42.type.html#comment-2211350713

And here's the stuff that is not valid anymore:
- procedure syntax
- view bounds

**Comment by DarkDimius** [comment]
>And here's the stuff that is not valid anymore:

self types on objects.

**Comment by smarter** [comment]
Also, implicit val and def must have an explicit type annotation now.

**Comment by xeno-by** [comment]
This should probably be the moment when we split Type.Compound.

**Comment by xeno-by** [comment]
@odersky suggested that we should take a look at https://github.com/lampepfl/dotty/blob/master/docs/SyntaxSummary.txt.

**Comment by jvican** [comment]
The following features are all available for the hackathon. Just pick one and hack on it!
  
To add:
- [ ] Trait parameters
SIP (for docs): http://docs.scala-lang.org/sips/pending/trait-parameters.html
A good place for start is  https://github.com/scalameta/scalameta/blob/master/scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L3061.
Final result should look like `classDef` here: https://github.com/scalameta/scalameta/blob/master/scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L3074.

- [ ] Repeated by-name parameters
SIP (for docs): http://docs.scala-lang.org/sips/pending/repeated-byname.html
A good place for start is https://github.com/scalameta/scalameta/blob/master/scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L2680.

- [ ] Literal singleton types (aka SIP-23 or 42.type).
Description of what singleton types are: https://github.com/scala/scala/pull/5310
A good way to start is by modifying the expected identifier to accept integers. E.g. `"val a: 42 = 42".parse[Stat].get` fails.
Have a look at the current impl: https://github.com/scalameta/scalameta/blob/master/scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L935
  
To remove:
- [ ] View bounds
```scala
def foo[T <% Whatever](t: T) = ???
```
Current implementation: https://github.com/scalameta/scalameta/blob/master/scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L2782
- [ ] Self types on objects
```scala
object A { self =>
}
```
Current implementation: https://github.com/scalameta/scalameta/blob/ea748842832255851f3dc219617c63aa02525d32/scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L3161. A good way to do this would be to pass in an extra parameter to `constBlock` and fail when a `selfInvocation` is correctly parsed.
  
Test should probably go in the DottySuite: https://github.com/scalameta/scalameta/blob/master/scalameta/scalameta/src/test/scala/scala/meta/tests/parsers/DottySuite.scala

**Comment by xeno-by** [comment]
Closing this in favor of individual issues mentioned above.
