### ISSUE TITLE
Run `save-expect` with Scala 2.13

### ISSUE THREAD

**Issue by tanishiking** [scalameta/scalameta#2737]
Currently, `ExpectSuite` is defined only in 2.12  https://github.com/scalameta/scalameta/blob/1a9ec6f9aa06e20bc786b5c7ef6d7aa500e59eaf/tests/jvm/src/test/scala-2.12/scala/meta/tests/semanticdb/ExpectSuite.scala

**Comment by kitbellew** [comment]
@tgodzik @tanishiking did #2995 fix this issue?

**Comment by tgodzik** [comment]
I think so, let's close it
