### ISSUE TITLE
Newer scalameta-parsers npm artifacts

### ISSUE THREAD

**Issue by bjaglin** [scalameta/scalameta#2743]
https://www.npmjs.com/package/scalameta-parsers (added in https://github.com/scalameta/scalameta/pull/949) is currently stuck at 4.4.17, making https://astexplorer.net/ not as useful as it could be for Scala 3.

Bumping & publishing seems [manual](https://github.com/scalameta/scalameta/blob/main/scalameta/parsers/js/npm/PUBLISH.md). I am not familiar with npm but it looks like publishing could be automated by:
1. running some smoke tests (the example from https://github.com/scalameta/scalameta/blob/main/scalameta/parsers/js/npm/README.md could be a good start I guess).
1. on tagged release, having a script populate the `package.json` and publishing it

**Comment by bjaglin** [comment]
I managed to run AST explorer with scalameta 4.5.5 locally

scalameta
- bumped scalameta version in https://github.com/scalameta/scalameta/blob/main/scalameta/parsers/js/npm/package.json
- `npm publish; npm pack` -> tgz

AST explorer
- followed https://github.com/fkling/astexplorer#build-your-own-version-for-development
- `yarn add <path/to/tgz>`

**Comment by tgodzik** [comment]
@gabro any idea what would be the best workflow here? Did you publish it all manually before?

**Comment by gabro** [comment]
I confirm it's been all a manual process so far, and I agree it can be automated with a GitHub action, if someone has the time and will.

Also, the AST Explorer upgrade process is quite trivial, but the release is usually slow since the main maintainer is busy and the process is manual as well.

I'm happy to provide pointers if needed, but I won't have much time myself to work on this task

**Comment by tgodzik** [comment]
This should be closed by https://github.com/scalameta/scalameta/pull/2966, let's check during the next release.

**Comment by tanishiking** [comment]
The new version of `scalameta-parsers` is uploaded to npm :tada: https://www.npmjs.com/package/scalameta-parsers, thanks to https://github.com/scalameta/scalameta/pull/2966 we'll publish to npm for every scalameta releases.
Also, I submitted a PR to AST-explorer https://github.com/fkling/astexplorer/pull/685

I'm going to close this issue as completed, but feel free to re-open if there's something left :+1:

**Comment by bjaglin** [comment]
Thank you @tanishiking !
