### ISSUE TITLE
No apply in synthetics section for Map.apply

### ISSUE THREAD

**Issue by matthughes** [scalameta/scalameta#2755]
### Describe the bug

```scala
object Test {
  val aMap: Map[String, Int] = Map.empty
  aMap.apply("") // call to Map.apply; peek references would find this

  def update[A](fn: A => A): Unit = {
    ()
  }

  // This also is a call to Map.apply but Peek References doesn't find it
  // desugared: update(a => Map.empty.apply(a))
  update(Map.empty)
}
```

Peek references on `Map.apply` finds the first example, but it doesn't find the call that uses ETA expansion.

### Expected behavior

Peek references should find both calls.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.5

### Extra context or search terms

point-free, eta expansion, function application, peek references

**Comment by tgodzik** [comment]
Actually, this is working correctly! Map.empty is a function, so no actual synthetic apply is added. Also it seems apply will never be synthetically added in that case.

Take a look here: https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/Map.scala#L103

I always forget about it :sweat_smile:
