### ISSUE TITLE
some anonymous function arguments, not wrapped in Term.AnonymousFunction

### ISSUE THREAD

**Issue by zmerr** [scalameta/scalameta#2776]
When we have 

```
def curried(a: Int)(b: Int) = a + b

List(1, 2, 3).map(curried(6) _ )

```

It is expected that `curried(6) _ ` should be wrapped in Term.AnonymousFunction, but it is not.

Also, sometimes a similar thing happens for 
`List(true, false).map(true && !negate(_) && false)`
 when  `def negate(b: Boolean) = !b`

**Comment by kitbellew** [comment]
> When we have
> 
> ```
> def curried(a: Int)(b: Int) = a + b
> 
> List(1, 2, 3).map(curried(6) _ )
> ```
> 
> It is expected that `curried(6) _ ` should be wrapped in Term.AnonymousFunction, but it is not.

where's the anonymous function here?

> 
> Also, sometimes a similar thing happens for `List(true, false).map(true && !negate(_) && false)` when `def negate(b: Boolean) = !b`

what does it mean "sometimes"?

**Comment by zmerr** [comment]
> where's the anonymous function here?

I mean in the AST, the parent to `Term.Eta` should be `Term.AnonymousFunction` but instead it is directly passed as an argument to `Term.Apply`

This is a bug @tgodzik

**Comment by zmerr** [comment]
> what does it mean "sometimes”?

Basically, sometimes when I test it, it is wrapped in `AnonymousFunction`, and sometimes not :|

**Comment by kitbellew** [comment]
> > where's the anonymous function here?
> 
> I mean in the AST, the parent to `Term.Eta` should be `Term.AnonymousFunction` but instead it is directly passed as an argument to `Term.Apply`
> 
> This is a bug @tgodzik

This is not an anonymous function, it's a conversion of a method into a function via eta expansion. An anonymous function requires at least one placeholder (`_`) argument; in this case, `curried(6) _` is an eta expansion while `curried(6)(_)` is an anonymous function.

**Comment by kitbellew** [comment]
@zmerr please reopen if you reproduce additional valid examples.
