### ISSUE TITLE
scala3: incomplete support for `_` in types

### ISSUE THREAD

**Issue by kitbellew** [scalameta/scalameta#2807]
https://dotty.epfl.ch/docs/reference/changed-features/wildcards.html describes this:

- scala 2:
  - type wildcard is `_`
  - type placeholder is unsupported
- scala 3.0:
  - type wildcard is `?` and `_`
  - type placeholder is `*`
- scala 3.1:
  - type wildcard is `?`, `_` is deprecated
  - type placeholder is `*`
- scala 3.2:
  - type wildcard is `?`
  - type placeholder is `_`, `*` is deprecated
- scala 3.3:
  - type wildcard is `?`
  - type placeholder is `_`

In `Dialect`, we have the following today:

- `allowQuestionMarkPlaceholder` (which is misleading since it's a wildcard but not a placeholder)
- `allowPlusMinusUnderscoreAsPlaceholder` (which is a bit misleading since should apply to invariant placeholder types as well, not just covariant/contravariant)
- `allowTypeParamUnderscore` (not sure if this is for a different syntax element and could remain as-is)

I would suggest the following `Dialect` changes (and corresponding parser modifications):

- rename `allowQuestionMarkPlaceholder` to `allowQuestionMarkAsTypeWildcard`
  - keep `withAllowQuestionMarkPlaceholder` method for now but deprecate it (make it redirect to the new `withAllowQuestionMarkAsTypeWildcard`)
- similarly, rename `allowPlusMinusUnderscoreAsPlaceholder` to `allowUnderscoreAsTypePlaceholder` (to distinguish `_` between wildcard in 3.1 and placeholder in 3.2)
- possibly also add `allowStarAsTypePlaceholder`
  - otherwise, allow star if `allowQuestionMarkAsTypeWildcard=true` and `allowUnderscoreAsTypePlaceholder=false`, although this doesn't cover the 3.2 case

**Comment by kitbellew** [comment]
also:
- `Type.Placeholder` is used for wildcard and might need to be split
- `Type.Placeholder` is used instead of a pattern tree (see scalameta/scalafmt#3303)

**Comment by dos65** [comment]
@kitbellew Thanks for collecting the info! Looks reasonable.

**Comment by tgodzik** [comment]
I really hoped we wouldn't need to create a new dialect for each minor version of Scala 3, which will be super difficult for people to handle :/

I wonder if we could just allow each placeholder in every place, from the parser perspective this wouldn't be much of an issue:

type wildcard is ? and _
type placeholder is * and _

Is there any specific issue that it would cause issues with? Probably the rewrite rules? :thinking:

**Comment by tgodzik** [comment]
Also it seems the 3.2 is not bringing about the advertised changes, `_` is still available as type placeholder.

**Comment by kitbellew** [comment]
> I wonder if we could just allow each placeholder in every place, from the parser perspective this wouldn't be much of an issue:
> 
> type wildcard is ? and _ type placeholder is * and _

interesting idea... as it stands currently, our parser can tell that `F[_ :> lo]` is a wildcard with bounds but when it comes to the simple `F[_]`, it can't yet. perhaps we need to provide it a parsing context flag which will allow it to tell the difference. frankly, i don't know when each is applicable (placeholder vs wildcard)...
> 
> Is there any specific issue that it would cause issues with? Probably the rewrite rules? 🤔

**Comment by kitbellew** [comment]
something like that, yes. is there any documentation on lambdas and where there can be used?

**Comment by kitbellew** [comment]
@tgodzik [the wildcards document](https://dotty.epfl.ch/docs/reference/changed-features/wildcards.html) mentions this:

_It also removes the wart that, used as a type parameter, `F[_]` means `F` is a type constructor whereas used as a type, `F[_]` means it is a wildcard (i.e. existential) type. In the future, `F[_]` will mean the same thing, no matter where it is used._

Does that mean that we **shouldn't** use context-aware parsing which might result in a different interpretation?

**Comment by tgodzik** [comment]
Yeah, accepting all possibilities will not be correct :thinking:  We might need to do different dialects then after the change is introduced.

**Comment by kitbellew** [comment]
> Yeah, accepting all possibilities will not be correct 🤔 We might need to do different dialects then after the change is introduced.

@tgodzik , in that case, would it make sense first to introduce the `allow` flags that i have proposed (#2811 and later PRs), and interpret `_` or `*` based on that, and then later possibly introduce additional validation to make sure that take context into account to ensure that the placeholder or wildcard are actually meaningful?

if so, i can modify/relax the dialect definitions (#2809) to reflect that some things have not yet been done as mentioned in the docs.

**Comment by tgodzik** [comment]
> @tgodzik , in that case, would it make sense first to introduce the allow flags that i have proposed (https://github.com/scalameta/scalameta/pull/2811 and later PRs), and interpret _ or * based on that, and then later possibly introduce additional validation to make sure that take context into account to ensure that the placeholder or wildcard are actually meaningful?

Sure, it makes sense to introduce the flags, but do we need the context actually if we get `?` and `_` to each mean one thing only?

**Comment by kitbellew** [comment]
> > @tgodzik , in that case, would it make sense first to introduce the allow flags that i have proposed (#2811 and later PRs), and interpret _ or * based on that, and then later possibly introduce additional validation to make sure that take context into account to ensure that the placeholder or wildcard are actually meaningful?
> 
> Sure, it makes sense to introduce the flags, but do we need the context actually if we get `?` and `_` to each mean one thing only?

depends on how careful we want to be. since they can mean one thing only but not always acceptable, we can either reject them in inappropriate context or assume the compiler would do that...

**Comment by tgodzik** [comment]
I think it's fine to leave it up to the compiler, we don't always reject all the problematic syntax, which is fine, we can be more inclusive.
