### ISSUE TITLE
split Type.Compound into Type.Intersect and Type.Refine

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#281]
I have found no arguments in favor of conflating these two concepts, so I'll split them soon. Credits to @smarter for noticing this!

**Comment by smarter** [comment]
Great! Minor nit: I'd call it `Type.Intersection` or `Type.And` and `A | B` would be either `Type.Union` or `Type.Or`.

**Comment by xeno-by** [comment]
The verb-vs-noun debate is something that we had when starting the project. Verbs have won (though I don't remember why), and that's reflected in a lot of existing names. Therefore I'd like to go for consistency at the moment and defer the matter of naming until a big accumulated refactoring of trees post-0.1.

Speaking of intersection types. It looks like we'll need to have both `Type.With` (asymmetric linearization-based semantics from scalac) and `Type.And` (honest intersection types). At least, @darkdimius told me today that these are two different notions in dotc.
