### ISSUE TITLE
Regression in Scalameta 4.4.16: object definition tree with non-empty template doesn't match quasiquote

### ISSUE THREAD

**Issue by DmytroMitin** [scalameta/scalameta#2841]
In Scalameta 4.4.15
```scala
import scala.meta._

val source: String =
  "object X extends Y { def foo }"
  
source.parse[Stat].get.traverse {
  case tree@q"..$mods object $ename extends $template" => println("object: " + tree)
}
```
prints `object: object X extends Y { def foo }`.
But since 4.4.16 this produces empty output (including current 4.5.13).

For objects with empty template (`object X extends Y {}`, `object X extends Y`) everything is ok.
Also if we match `case tree@Defn.Object(mods, ename, template)` instead of quasiquote everything is ok.

Tested in Scala 2.13.8.

**Comment by kitbellew** [comment]
@DmytroMitin you can do one of these things:

- match the entire template
```
  val q"object $name $template" =
    q"object X extends Y { def foo }"
```
- match parts of the template which are present
```
  val q"object $name extends ..$parents { ..$stats }" =
    q"object X extends Y { def foo }"
```
- match all possible parts of the signature
```
  val q"..$mods object $name extends { ..$early } with ..$parents { $self => ..$stats }" =
    q"object X extends Y { def foo }"
```

this was indeed fixed sometime last year, by including `extends` in the template but not the parts.

**Comment by DmytroMitin** [comment]
@kitbellew Thanks. Good to know. Shouldn't the page https://scalameta.org/docs/trees/quasiquotes.html be updated?

**Comment by kitbellew** [comment]
> @kitbellew Thanks. Good to know. Shouldn't the page https://scalameta.org/docs/trees/quasiquotes.html be updated?

thanks for the suggestion, done.
