### ISSUE TITLE
Publish for Scala 2.12.17, please?

### ISSUE THREAD

**Issue by SethTisue** [scalameta/scalameta#2857]
2.12.17 JARs are on Maven Central, as per https://contributors.scala-lang.org/t/scala-2-12-17-release-planning/5805

**Comment by tgodzik** [comment]
Released for versions 4.5.11-4.5.13 : https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac-core_2.12.17/

Though 4.5.12 is still pending.
