### ISSUE TITLE
Publish for Scala 2.13.9, please?

### ISSUE THREAD

**Issue by SethTisue** [scalameta/scalameta#2873]
2.13.9 JARs are on Maven Central, as per https://contributors.scala-lang.org/t/scala-2-13-9-release-planning/5693/16

**Comment by dos65** [comment]
ScalaJs and ScalaNative was published - I started backpublishing process for 4.5.11, 4.5.12, 4.5.13 versions

**Comment by tgodzik** [comment]
Looks like it's published! :tada:
