### ISSUE TITLE
`q"opaque type Foo <: String = String"` loses the `<: String` ?

### ISSUE THREAD

**Issue by armanbilge** [scalameta/scalameta#2881]
```scala
//> using scala "2.13.9"
//> using lib "org.scalameta::scalameta::4.5.13"

import scala.meta._
import scala.meta.dialects.Scala3

object Bug {

  def main(args: Array[String]): Unit =
    println(q"opaque type Foo <: String = String")

}
```

```
$ scala-cli bug.scala 
opaque type Foo = String
```

**Comment by tgodzik** [comment]
Thanks for reporting! It seems that the `binaryCompat` fields are somehow lost in the macros, but I can't find where exactly :thinking: 

I would suggest not using quasiquotes for Scala 3 unfortunately :/

**Comment by armanbilge** [comment]
> It seems that the `binaryCompat` fields are somehow lost in the macros, but I can't find where exactly 🤔

Ah, so it's not just me 😅 I spent some time trying to find it but I gave up after a while 🙃 

> I would suggest not using quasiquotes for Scala 3 unfortunately :/

Thanks, good to know :(

**Comment by tgodzik** [comment]
There is a bunch of stuff around quasiquotes that have no documentation and I have no idea why they were done. I think it gets lots around reification, but I don't even know exactly what that means :sweat:
