### ISSUE TITLE
no expected change in files with ExplicitResultTypes rule using scalafix-cli

### ISSUE THREAD

**Issue by mackenziestarr** [scalameta/scalameta#2979]
Hello,
I was attempting to try out the `ExplicitResultTypes` rule with scalafix-cli using SemanticDB files obtained via `metac` and couldn't
get scalafix to add type annotations to my test file as expected.

Since I'm new in this space it is very possible that I've misconfigured something but I would really appreciate some validation from
the expert folks here.

### steps to reproduce

1. add example scala file using the code example from [ExplicitResultTypes](https://scalacenter.github.io/scalafix/docs/rules/ExplicitResultTypes.html)

```shell
# write example file to ./Main.scala
$ cat > Main.scala <<EXAMPLE
package com.example
object Main {
  def myComplexMethod = 1.to(10).map(i => i -> i.toString).toMap
}
EXAMPLE
```

```scala
// Main.scala
package com.example
object Main {
  def myComplexMethod = 1.to(10).map(i => i -> i.toString).toMap
}
```

2. use `metac` to generate semanticdb files

```shell
$ metac Main.scala
$ tree .
.
├── Main.scala
└── META-INF
    └── semanticdb
        └── Main.scala.semanticdb

2 directories, 2 files
```

3. run scalafix

```shell
$ scalafix --scala-version 2.13.10 --verbose --rules ExplicitResultTypes --auto-classpath --stdout
info: Processing (0/1) /tmp/scalafix-sandbox/Main.scala
package com.example
object Main {
  def myComplexMethod = 1.to(10).map(i => i -> i.toString).toMap
}
```

expected to see scalafix add a type annotation to `myComplexMethod`

```scala
package com.example
object Main {
  def myComplexMethod: Map[Int, String] = 1.to(10).map(i => i -> i.toString).toMap
}
```

but the contents of the original file were unchanged

### version info

```shell
$ scalafix --version
0.10.4

$ metac --version
Scala compiler version 2.13.10 -- Copyright 2002-2022, LAMP/EPFL and Lightbend, Inc.
```

Thanks for you time,
Mackenzie

**Comment by tgodzik** [comment]
Thanks for the question! We haven't recently done any work on metac, so things might not be working 100%. I would first check what does the generated semanticdb contain and how does it compare to for example one generated by Metals.

**Comment by mackenziestarr** [comment]
hey @tgodzik thanks for the quick response, here is the contents of the semanticdb file i generated with `metac` if that helps

```
$ metap META-INF/semanticdb/Main.scala.semanticdb 
Main.scala
----------

Summary:
Schema => SemanticDB v4
Uri => Main.scala
Text => empty
Language => Scala
Symbols => 3 entries
Occurrences => 12 entries

Symbols:
com/example/Main. => final object Main extends AnyRef { +1 decls }
com/example/Main.myComplexMethod(). => method myComplexMethod: Map[Int, String]
local0 => param i: Int

Occurrences:
[0:8..0:11) => com/
[0:12..0:19) => com/example/
[1:7..1:11) <= com/example/Main.
[2:6..2:21) <= com/example/Main.myComplexMethod().
[2:26..2:28) => scala/runtime/RichInt#to().
[2:33..2:36) => scala/collection/immutable/Range#map().
[2:37..2:38) <= local0
[2:42..2:43) => local0
[2:44..2:46) => scala/Predef.ArrowAssoc#`->`().
[2:47..2:48) => local0
[2:49..2:57) => scala/Any#toString().
[2:59..2:64) => scala/collection/IterableOnceOps#toMap().
```

**Comment by tgodzik** [comment]
That looks correct, maybe scalafix is not reading the classpath correctly? Are you able to add it manually as a parameter?

**Comment by mackenziestarr** [comment]
hey @tgodzik the classpath tip was just what i needed

```shell
$ tree .
.
├── Main.scala
└── META-INF
    └── semanticdb
        └── Main.scala.semanticdb

2 directories, 2 files

$ scalafix --scala-version 2.13.10 --verbose --rules ExplicitResultTypes --classpath=/tmp/scala-library-2.13.10.jar --semanticdb-targetroots . --stdout
info: Processing (0/1) /tmp/scalafix-sandbox/Main.scala
package com.example
object Main {
  def myComplexMethod: Map[Int,String] = 1.to(10).map(i => i -> i.toString).toMap
}
```

seems like we can close this!

It could be nice to include things like scala-library-*.jar on the classpath by default so that small examples with Semantic rules work when people are trying out the tooling for the first time. let me know what you think about that and maybe I can contribute something.

**Comment by bjaglin** [comment]
> It could be nice to include things like scala-library-*.jar on the classpath by default so that small examples with Semantic rules work when people are trying out the tooling for the first time. let me know what you think about that and maybe I can contribute something.

Agreed :+1:  Can you open an issue on https://github.com/scalacenter/scalafix? We can follow up there, but you can start from https://github.com/scalacenter/scalafix/blob/491deb223cd81b3eeb037ab1ba3436ed52286af7/scalafix-cli/src/main/scala/scalafix/internal/v1/Args.scala#L98-L104C5 if you want to work on it.

**Comment by mackenziestarr** [comment]
hey @bjaglin opened the issue linked above, thanks
