### ISSUE TITLE
Metals show error on operators in beginning of the line

### ISSUE THREAD

**Issue by carlosedp** [scalameta/scalameta#3051]
### Describe the bug

Error:

![image](https://user-images.githubusercontent.com/20382/213281075-131f01f5-faa0-46d8-b5f2-0efb8a203e3c.png)

Sample code:

```scala
  // This works:
  val httpRoutes = (MetricsApp() ++ HomeApp() ++ GreetingApp()) @@
    Middleware.cors(corsConfig) @@
    Middleware.metrics(MetricsApp.pathLabelMapper) @@
    Middleware.debug

  // This shows error:
  val httpRoutes2 = (MetricsApp() ++ HomeApp() ++ GreetingApp())
    @@ Middleware.cors(corsConfig)
    @@ Middleware.metrics(MetricsApp.pathLabelMapper)
    @@ Middleware.debug
```

Both cases compile and run fine.

### Expected behavior

No error shown in the second sample.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.10+56-1cbc85ca-SNAPSHOT

**Comment by carlosedp** [comment]
Guys, I'm still seeing this error in VSCode with latest Metals snapshots:


![image](https://user-images.githubusercontent.com/20382/233166157-877d3a8a-dcb4-46f2-a2c7-edf66d6d202f.png)

![image](https://user-images.githubusercontent.com/20382/233167270-11e34f3d-4969-4912-a123-e6a254003192.png)

If I move the operators `@@` / `*>` to the end of the lines, no error is shown.

Versions:

```
Build server currently being used is Bloop v1.5.6. Also happens with mill-bsp v0.10.12.

Scala 3.3.0-RC4

Metals Java: 17.0.6 from GraalVM Community located at /Users/cdepaula/Library/Caches/Coursier/arc/https/github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.1/graalvm-ce-java17-darwin-amd64-22.3.1.tar.gz/graalvm-ce-java17-22.3.1/Contents/Home

Metals Server version: 0.11.12+13-4e0263a8-SNAPSHOT
```

**Comment by tgodzik** [comment]
I think we need to update Metals to the newest version of scalameta, I am running the release now.
