### ISSUE TITLE
reconsider the need for Term.Placeholder

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#306]
```
13:33 ~/Projects/core/sandbox1 (master)$ parse '_ + 2'
// Scala source: /var/folders/n4/39sn1y_d1hn3qjx6h1z3jk8m0000gn/T/tmp7YNZNF
_ + 2
Term.ApplyInfix[0..5](Term.Placeholder[0..1](), Term.Name[2..3]("+"), Nil, List(Lit[4..5](2)))
```

The more I think of it, the more I dislike the idea of having `Term.Placeholder` as a dedicated tree. Problems that it brings:
1) Complicates processing of lambdas, making people handle two different syntaxes.
2) Makes processing lambdas non-trivial, because users would have to remember the rules that govern the desugaring (I always forget them, for instance, so it's indeed non-trivial... or I'm stupid).
3) Makes classification of members and refs a bit weird. A placeholder is both a member and a ref, so should we make it both or keep it as none.

One radical solution would be to get rid of Term.Placeholder completely and keep the distinction between shorthand and full syntaxes in trivia. 

Another approach that I come up with while writing down this issue is to make the full syntax a desugaring of the short syntax. This actually solves problems 1 and 2, and we can bite the bullet, turn on our brain and come up with something for 3 :)

/cc @densh @olafurpg

**Comment by olafurpg** [comment]
So far, I haven't hit on the issues you listed above. However, I was surprised here:

```scala
ollie-scalafmt@ "var x: Int = _".parse[Stat].asInstanceOf[internal.ast.Defn.Var]
res33: internal.ast.Defn.Var = var x: Int = _
ollie-scalafmt@ res33.rhs
res34: Option[internal.ast.Term] = None
```

I expected the rhs to give me `Some(whatever)` instead of `None`.

PS. @densh just explained to me the `_` is not a placeholder in this case, I'll still comment here instead of filing a new issue.

**Comment by densh** [comment]
@olafurpg I think you should file a separate issue for that one.

**Comment by olafurpg** [comment]
Done, see #354

**Comment by xeno-by** [comment]
@olafurpg @DavidDudson @ShaneDelmore What do you think about this one?

**Comment by olafurpg** [comment]
`Term.Placeholder()` has not bugged me once, it's quite intuitive IMO. I propose we keep this unchanged.

**Comment by xeno-by** [comment]
Allright, closing this issue then.
