### ISSUE TITLE
Wrong `pattern must be a value`

### ISSUE THREAD

**Issue by tgodzik** [scalameta/scalameta#3063]
Found an issue when working on https://github.com/scalameta/metals/issues/4896
```
${ success.tree.asExprOf[InterpolationConverterType] }
```

looks like an issue with Scala 3 dialect

**Comment by kitbellew** [comment]
@tgodzik can you repro? I added to `MacroSuite.scala`
```
    runTestAssert[Stat](
      "${ success.tree.asExprOf[InterpolationConverterType] }"
    )(
      ...
    )
```
and it didn't have any parsing problems.

**Comment by Atry** [comment]
I think it's a splice expression at https://github.com/Atry/html.scala/blob/0df608834dcf0dcdcae32d60f23a4c9560ddbf0a/html/src/main/scala/com/yang_bo/html/package.scala#L193

**Comment by tgodzik** [comment]
> @tgodzik can you repro? I added to `MacroSuite.scala`
> 
> ```
>     runTestAssert[Stat](
>       "${ success.tree.asExprOf[InterpolationConverterType] }"
>     )(
>       ...
>     )
> ```
> 
> and it didn't have any parsing problems.

I wanted to take a look, but I didn't have time yet. @Atry is right, it fails there.

**Comment by sirthias** [comment]
I tripped over this same issue in https://github.com/sirthias/borer.
A parser bug is a real pain since it completely kills the build and cannot be fenced off `// format: OFF`.
For now I had to completely exclude the affected files with `project.excludePaths = [ ... ]`.

**Comment by sirthias** [comment]
It's a weird issue, also for me.
It only happened on complete, clean rebuilds, not on subsequent runs.
I'll try once more to isolate it.

**Comment by kitbellew** [comment]
@tgodzik @sirthias @Atry can you provide the link to a failing file _and_ the line number in that file? Whether on clean builds or every time, doesn't matter.

`pattern must be a value` appears in the parser code only once, when parsing an expression like this:
```
foo match
  case bar[baz] => // parser expects parentheses after brackets
```
(or any other pattern expression which looks like `bar[baz]`, such as in `for { pattern <- ... }`). So, need to know not only the exact expression but its full context.
