### ISSUE TITLE
can't parse worksheet

### ISSUE THREAD

**Issue by doofin** [scalameta/scalameta#3064]
When I try to parse worksheet.sc file with `dialects.Sbt1(programStr).parse[Source]`, it doens't work.

**Comment by doofin** [comment]
Here's the code:
```scala
object obj1:
  case class c1[t](t: t) // { def c: t = { t } }
end obj1
```

maybe this syntax isn't supported yet?

**Comment by tgodzik** [comment]
You should use:
`val dialect = Scala3.withAllowToplevelTerms(true)`

**Comment by doofin** [comment]
thanks,it works!
