### ISSUE TITLE
`.syntax` creates invalid Scala code for string literals that contains \"\"\"

### ISSUE THREAD

**Issue by Atry** [scalameta/scalameta#3065]
Scalameta version: 4.7.3

```scala
import scala.meta._
object Main extends App {
  println(Lit.String("\n\"\"\"").syntax)
}
```

Expected output:
```
"\n\"\"\""
```
Actual output:
```
"""
""""""
```

https://scastie.scala-lang.org/0Xe1ehUxRwiI0Ifr4YrAyw

**Comment by tgodzik** [comment]
Thanks for reporting! The problem here seems that we actually lose the information whether `"` was escaped or not and we just do a multiline string as a default. Question is should that be the default? Or should we escape?

**Comment by tgodzik** [comment]
Also, why do you say the output is illegal?

**Comment by Atry** [comment]
Currently multi-line syntax is used when there is a `\n`, even when it could generate code that is not valid Scala doc

**Comment by tgodzik** [comment]
Och, now I see :sweat_smile:  I must have been brain exhausted when I saw your issue last time.
