### ISSUE TITLE
Errors when Steward runs on this repo

### ISSUE THREAD

**Issue by ckipp01** [scalameta/scalameta#3066]
Just a heads up, I see that our Steward has started throwing errors on this repo. It looks like starting on [Jan 23](https://github.com/scalameta/steward/actions/runs/3982311601/jobs/6826667156#step:4:448) it errors with the following:

```
  Warning:  Your app's responsiveness to a new asynchronous event (such as a
  Error: new connection, an upstream response, or a timer) was in excess of 100 milliseconds.
  Error: Your CPU is probably starving. Consider increasing the granularity
  Error: of your delays or adding more cedes. This may also be a sign that you are
  Error: unintentionally running blocking I/O operations (such as File or InetAddress)
  Error: without the blocking combinator.
  Warning:  Your app's responsiveness to a new asynchronous event (such as a
  Error: new connection, an upstream response, or a timer) was in excess of 100 milliseconds.
  Error: Your CPU is probably starving. Consider increasing the granularity
  Error: of your delays or adding more cedes. This may also be a sign that you are
  Error: unintentionally running blocking I/O operations (such as File or InetAddress)
  Error: without the blocking combinator.
```

Just putting this up here to track it since it's causing the Steward runs to be 🔴 .

**Comment by tgodzik** [comment]
Och, what fun. We might need to remove Scala versions more agressively :thinking:

**Comment by armanbilge** [comment]
Linking to:
- https://github.com/scala-steward-org/scala-steward/issues/2790

---

> since it's causing the Steward runs to be 🔴 .

Huh, I am surprised about this. This is only a warning to stderr, it shouldn't cause a non-zero exit code. I'm going to stare at your log.

**Comment by armanbilge** [comment]
The real problem is this:
```
2023-01-23T00:35:49.5221456Z 2023-01-23 00:35:49,519 ERROR Steward scalameta/metals failed
2023-01-23T00:35:49.5222142Z java.io.IOException: Cannot run program "scala-cli" (in directory "/home/runner/scala-steward/workspace/repos/scalameta/metals"): error=2, No such file or directory
```
which is this:
- https://github.com/scala-steward-org/scala-steward/issues/2948

**Comment by tgodzik** [comment]
Och, thanks for sharing! So that seems to be an unrelated issue then, right? I think we can close this one @ckipp01

**Comment by ckipp01** [comment]
O dang, thanks @armanbilge! I totally glossed over that!

I think yea, we can close this for now and just track the issue linked.

**Comment by fthomas** [comment]
Or you could just install Scala CLI where Scala Steward runs so that it has the chance to update Scala CLI source files.

**Comment by ckipp01** [comment]
> Or you could just install Scala CLI where Scala Steward runs so that it has the chance to update Scala CLI source files.

I haven't had time to look at it yet, but I might try to do the same thing we did with Mill and just ensure it's installed by the `scala-steward-action` when using it.
