### ISSUE TITLE
unexpected behaviour of Tree.children

### ISSUE THREAD

**Issue by johannegger** [scalameta/scalameta#308]
calling .children of a tree doesn't always return what I would expect. 

```someTree.parent.map(_.children.contains(someTree))``` is not always true it seems

Here an example: 
https://gist.github.com/johannegger/c0adc6e8a23318e3513f

**Comment by xeno-by** [comment]
Wow, that's indeed unexpected. How did you come across this bug?

**Comment by johannegger** [comment]
i was looking for groups of imports similar to the example in the gist. 
after finding all imports i wanted to know their sibling relations (are they neighbours in their parent's .children Seq ) and boom, the parent had no children.
do you think it's easy to fix?

**Comment by xeno-by** [comment]
Fixed and published in 0.1.0-SNAPSHOT.

**Comment by johannegger** [comment]
that was fast, thank you :+1:
