### ISSUE TITLE
Scalameta parsers more than three `???` in line as ApplyInfix

### ISSUE THREAD

**Issue by tanishiking** [scalameta/scalameta#3094]
Related https://github.com/scalameta/metals/pull/4877

From scalameta 4.7.2, Scala3 dialect parses the following program as

```scala
def foo =
  ???
  ???
  ???
```

```scala
Defn.Def(
  Nil,
  Term.Name("foo"),
  Nil,
  None,
  Term.ApplyInfix(
    Term.Name("???"),
    Term.Name("???"),
    Type.ArgClause(Nil),
    Term.ArgClause(List(Term.Name("???")), None)
  )
)
```

but it should be

```scala
Defn.Def(
  Nil,
  Term.Name("foo"),
  Nil,
  None,
  Term.Block(List(
    Term.Name("???"),
    Term.Name("???"),
    Term.Name("???")
  ))
)
```

```scala
scala> import scala.meta._
import scala.meta._

scala> val program = """
     | def foo =
     |   ???
     |   ???
     |   ???
     | """
val program: String =
"
def foo =
  ???
  ???
  ???
"

scala> dialects.Scala3(program).parse[Source].get.structure
val res9: String = Source(List(Defn.Def(Nil, Term.Name("foo"), Nil, None, Term.ApplyInfix(Term.Name("???"), Term.Name("???"), Type.ArgClause(Nil), Term.ArgClause(List(Term.Name("???")), None)))))
```

---

Interestingly, 

```scala
def foo =
  x
  x
  x
```

will be parsed as 

```scala
Defn.Def(
  Nil,
  Term.Name("foo"),
  Nil,
  None,
  Term.Block(List(
    Term.Name("x"),
    Term.Name("x"),
    Term.Name("x")
  ))
)
```

**Comment by kitbellew** [comment]
@tanishiking here's why: https://docs.scala-lang.org/scala3/reference/changed-features/operators.html#syntax-change

in scalameta, `withAllowInfixOperatorAfterNL` was set to true in scala 3.0; if it should be in some other version (perhaps the not-yet-released 3.3), we should move the flag setting.

cc @tgodzik

**Comment by tanishiking** [comment]
Oh, I didn't know this syntax change in Scala3, thank you for the info.

However, it seems that the Scala3 compiler (3.2.2) parses the following code snippet as three different statements.

```scala
def foo =
  ???
  ???
  ???
```

while the following one is parsed as infix

```scala
def foo =
  ???
  ???
  x
```

I think this is because the third `???` is not recognized as "token that can start an expression" in https://docs.scala-lang.org/scala3/reference/changed-features/operators.html#syntax-change 🤔 (while I'm not sure what the "token that can start an expression" means...)

> is followed by at least one whitespace character and a token that can start an expression.

```scala
scalameta on  main [!?] via ☕ v17.0.6 via 🆂 took 6s
❯ scala-cli repl -S 3.2.2 --dep org.scala-lang::scala3-compiler:3.2.2 --dep org.scala-lang::scala3-library:3.2.2
Welcome to Scala 3.2.2 (17.0.6, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> import dotty.tools.dotc.core.Contexts._

scala> given Context = (new ContextBase).initialCtx
lazy val given_Context: dotty.tools.dotc.core.Contexts.Context

scala> import dotty.tools.dotc.parsing.Parsers

scala> import dotty.tools.dotc.util.SourceFile

scala> val program = """
     | def foo =
     |   ???
     |   ???
     |   ???
     | """
val program: String = "
def foo =
  ???
  ???
  ???
"

scala> val parser = new Parsers.Parser(SourceFile.virtual("<meta>", program))
val parser: dotty.tools.dotc.parsing.Parsers.Parser = dotty.tools.dotc.parsing.Parsers$Parser@70d28000

scala> parser.parse()
val res19: dotty.tools.dotc.ast.untpd.Tree = PackageDef(Ident(<empty>),List(DefDef(foo,List(),TypeTree,Block(List(Ident(???), Ident(???)),Ident(???)))))

scala> val program = """
     | def foo =
     |   ???
     |   ???
     |   x
     | """
val program: String = "
def foo =
  ???
  ???
  x
"

scala> val parser = new Parsers.Parser(SourceFile.virtual("<meta>", program))
val parser: dotty.tools.dotc.parsing.Parsers.Parser = dotty.tools.dotc.parsing.Parsers$Parser@7ac47e87

scala> parser.parse()
val res20: dotty.tools.dotc.ast.untpd.Tree = PackageDef(Ident(<empty>),List(DefDef(foo,List(),TypeTree,InfixOp(Ident(???),Ident(???),Ident(x)))))
```

**Comment by kitbellew** [comment]
> I think this is because the third `???` is not recognized as "token that can start an expression" in https://docs.scala-lang.org/scala3/reference/changed-features/operators.html#syntax-change 🤔 (while I'm not sure what the "token that can start an expression" means...)

Nor I. The first of them does start an expression so how's the third different?

@tgodzik who can help clarify? perhaps even @odersky?

**Comment by tgodzik** [comment]
To cite Martin:
```
Martin Odersky:
It's on line 435ff in Scanners.scala


Martin Odersky:
def assumeStartsExpr(lexeme: TokenData) =
        (canStartExprTokens.contains(lexeme.token) || lexeme.token == COLONeol)
          && (!lexeme.isOperator || nme.raw.isUnary(lexeme.name))


Martin Odersky: The !lexeme.isOperator is the crucial part. So, the second ??? is treated as an infix operator only if the next token can follow an infix operator, which means the next token cannot be an infix operator again.
```

**Comment by kitbellew** [comment]
> To cite Martin:
> 
> ```
> Martin Odersky:
> It's on line 435ff in Scanners.scala
> 
> 
> Martin Odersky:
> def assumeStartsExpr(lexeme: TokenData) =
>         (canStartExprTokens.contains(lexeme.token) || lexeme.token == COLONeol)
>           && (!lexeme.isOperator || nme.raw.isUnary(lexeme.name))
> 
> 
> Martin Odersky: The !lexeme.isOperator is the crucial part. So, the second ??? is treated as an infix operator only if the next token can follow an infix operator, which means the next token cannot be an infix operator again.
> ```

does that mean that anything that looks like an operator (and what does that mean, specifically?) cannot start an expression? does that mean that `??? foo bar` is also impossible (since `???` cannot start an expression)? and can `???` **be** the entire expression (which means it starts _and_ ends it)?

**Comment by odersky** [comment]
These things are simply heuristics that define when an operator on a new line is treated as one. That's as far as it goes.

**Comment by kitbellew** [comment]
> These things are simply heuristics that define when an operator on a new line is treated as one. That's as far as it goes.

@odersky If you could help review [the fix](https://github.com/scalameta/scalameta/pull/3105), to make sure I understood it correctly, would really appreciate it, as we have gone through a few iterations.

**Comment by tanishiking** [comment]
Thank you all for you efforts! :tada:

**Comment by kitbellew** [comment]
> Thank you all for you efforts! 🎉

Dozo :)
