### ISSUE TITLE
Remove dependency to geny < 1.0.0 or shading geny

### ISSUE THREAD

**Issue by tanishiking** [scalameta/scalameta#3106]
Related issues

- https://github.com/scalameta/metals/pull/5082
- https://github.com/scalameta/metals/pull/4770

Current scalameta parser depends on forked version of fastparse, which depends on geny 0.6.5.
Since, geny < 1.0.0, and geny 1.0.0 are binary incompatible, apps that depends on `scalameta` cannot update have `geny >= 1.0.0`.

> > Not sure how much scalameta fork is aprt from the original one, but it would be awesone if wr can go back to li-hayoi fastparse, I'll take a quick look
> We did that to maintain a binary compatibility and avoid dependency issues such as with Geny, so there are three solutions here:
> - shade geny also
> - remove geny from scalameta's fastparse
> - shade it automatically
https://github.com/scalameta/metals/pull/5082#issuecomment-1494265720

So, isn't going back to li-haoyi/fastparse 3.0.1 (that depends on geny 1.0.0) and bump scalameta/scalameta as 5.0.0 (because it's not binary compatible by geny) an option?

**Comment by tgodzik** [comment]
> So, isn't going back to li-haoyi/fastparse 3.0.1 (that depends on geny 1.0.0) and bump scalameta/scalameta as 5.0.0 (because it's not binary compatible by geny) an option?

We actually spend a considerable amount of effort to keep the binary compatibility, so I would say that currently it's not an option.

**Comment by nafg** [comment]
How much effort would it be to shade `geny`, then?

**Comment by tgodzik** [comment]
> How much effort would it be to shade `geny`, then?

Should be doable in a day I think when anyone has the time
