### ISSUE TITLE
issue in Value Parameters quasiquote

### ISSUE THREAD

**Issue by johannegger** [scalameta/scalameta#311]
```"case class Foo(val Bar:String,Baz:Int)".parse[Stat].collect{ case param"..$mods $paramname: $atpeopt = $expropt" => paramname }``` 

produces a list of size 3 - the last element seems to be an empty name

**Comment by xeno-by** [comment]
Yes, that's right. The last element is a self-type which is internally represented as a parameter. I'll think what to do about that.

**Comment by xeno-by** [comment]
I suggest we work around by checking the parameter's parent. If it's a template, then the parameter represents a self annotation.
