### ISSUE TITLE
Inconsistency with Scalac on package private fields of case classes

### ISSUE THREAD

**Issue by jackkoenig** [scalameta/scalameta#3122]
Scala [3.2.2](https://scastie.scala-lang.org/yKRRHRKjStu1EsBnJ0NhKA), [2.13.10](https://scastie.scala-lang.org/KqrtO9P6TcGnZeogV6TmCw), and [2.12.17](https://scastie.scala-lang.org/0g6bJlZ9RfSZvwx9iK4QdQ) at least (and probably every other version support package private fields of case classes without the `val` keyword:

```scala
package example

case class Foo(private[example] field: String)
```

Semantic db prior to 4.7.5 also supported it, but starting in 4.7.5, semanticdb throws exceptions like:
```
[error] failed to generate semanticdb for .../src/main/scala/example/Hello.scala:
[error] .../src/main/scala/example/Hello.scala:4: error: val expected but identifier found
[error]   case class Foo(private[example] field: String)
[error]                                   ^
[error]         at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:16)
[error]         at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:16)
[error]         at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:22)
[error]         at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:17)
[error]         at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:17)
```

I'm guessing this is actually a bug in Scalac, but ideally the behavior of semanticdb would be consistent with that of Scalac.

**Comment by kitbellew** [comment]
> I'm guessing this is actually a bug in Scalac, but ideally the behavior of semanticdb would be consistent with that of Scalac.

I think it is a bug in scala3: https://dotty.epfl.ch/docs/internals/syntax.html#type-and-value-parameters-3
```
ClsParam          ::=  {Annotation}
                       [{Modifier} (‘val’ | ‘var’) | ‘inline’] Param
Param             ::=  id ‘:’ ParamType [‘=’ Expr]
```

However, in scala2 it's different: https://scala-lang.org/files/archive/spec/2.13/13-syntax-summary.html#context-free-syntax
```
ClassParam        ::=  {Annotation} {Modifier} [(‘val’ | ‘var’)] id ‘:’ ParamType [‘=’ Expr]
```
However, I don't think scala2 allows `class A(private b: B)`.

@tgodzik thoughts? Is this a documentation bug or compiler bug?

**Comment by jackkoenig** [comment]
It's not `class A(private b: B)`, it's `case class A(private[package] b: B)`, and both [2.13.10](https://scastie.scala-lang.org/KqrtO9P6TcGnZeogV6TmCw) and [2.12.17](https://scastie.scala-lang.org/0g6bJlZ9RfSZvwx9iK4QdQ) do support it. I agree this is weird because they do NOT support `case class A(private b: B)` so I am inclined to think it's a long-lived compiler bug.

**Comment by tgodzik** [comment]
If the compiler accepts that I think it would be perfectly fine to have scalameta accept that also. We can be more inclusive than the compiler, since the parser is not used anywhere that requires a strict access control.
