### ISSUE TITLE
Confused over inlined dependencies

### ISSUE THREAD

**Issue by hyandell** [scalameta/scalameta#3124]
Hi scalameta folk,

Looking at https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.13.8/4.7.7/ the jar file contains versions of Google's Protobuf, JLine, scalapb, sourcecode, and RelaxNG in the root of the jar.  

Shouldn't this cause a user concern that the jar file is going to cause dependency problems when used?

**Comment by tgodzik** [comment]
Thanks for the question! It's a compiler plugin, so it needs to have everything included in a single jar. You should use https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac-core_2.13.8/4.7.7/ as a dependency
