### ISSUE TITLE
Publish for Scala 2.12.18 and 2.13.11, please?

### ISSUE THREAD

**Issue by SethTisue** [scalameta/scalameta#3152]
2.12.18 JARs are on Maven Central, as per https://contributors.scala-lang.org/t/scala-2-12-18-release-planning/6089/9

2.13.11 JARs are on Maven Central, as per https://contributors.scala-lang.org/t/scala-2-13-11-release-planning/6088/11

**Comment by tgodzik** [comment]
It's published!

**Comment by SethTisue** [comment]
afaik, only Metals is still pending?

**Comment by tgodzik** [comment]
It's out for 0.11.12, not yet for snpashots, but that's not a big deal
