### ISSUE TITLE
Allow removeOptionalBraces for test cases with Scala 3.3.0 Version

### ISSUE THREAD

**Issue by cosmir17** [scalameta/scalameta#3164]
With the new Scala 3.3.0 version, we can now replace
```
test ("………") {
}
```
with
```
test ("……….") :
```
The complier is happy.
However, Scala fmt sbt plugin is not happy with it. Does anyone know how to add the such rule for tests in `.scalafmt.conf` file? It’s not to format the test codes automatically to that style, it’s to allow such change by human.

**Comment by kitbellew** [comment]
@cosmir17 I am not sure this is actually valid documented syntax, possibly a compiler bug :)

https://dotty.epfl.ch/docs/reference/other-new-features/indentation.html#optional-braces-around-template-bodies-1 states: "colon followed by **one** or more indented statements".

Just below it, https://dotty.epfl.ch/docs/reference/other-new-features/indentation.html#optional-braces-for-method-arguments-1 refers to changes in EBNF: `colon [LambdaStart] indent (CaseClauses | Block) outdent`, so it requires an indent.

Finally, https://dotty.epfl.ch/docs/reference/other-new-features/indentation.html#optional-braces-3 states that indent can only be inserted if "2.1.2) the first token on the next line has an indentation width strictly greater than the current indentation width". So it seems that in your case indent can't be inserted.

@tgodzik @odersky wdyt, bug or undocumented feature?

**Comment by kitbellew** [comment]
@cosmir17 https://scastie.scala-lang.org/MtAMbCewQuSCvYyX2jioxw fails with `indented definitions expected, string literal str found`. so it doesn't look like the compiler allows this.

did you perhaps mean something else? was the empty argument an oversight, and you actually meant a non-empty argument?

**Comment by cosmir17** [comment]
Hi @kitbellew ,

Thank you for your input on this issue. It seems there might have been two misunderstandings in my initial report. I would like to clarify that the syntax I was referring to is as follows:
```scala
test ("………") :
  Some valid test code here
```

and not simply:
```scala
test ("………") :
```

In the first syntax, there's additional test code after the colon on a new indented line. Could you please reconsider this in the context of the current issue and the proposed solution in the pull request?

Also, I mistakenly created this issue in the 'scalameta' repository instead of the 'sbt-scalafmt' repository. Would you be happy if I close this issue here and reopen it in the correct repository?

Thank you for your understanding and assistance.

Best,
Sean

**Comment by kitbellew** [comment]
@cosmir17 i moved the issue to scalameta as it was about the parser, with the empty argument.

if it's about the formatter, please go to scalafmt (not sbt-) and provide everything that issue template is requesting. make sure to be as specific as possible.
