### ISSUE TITLE
Bug: `override' modifier not allowed for classes

### ISSUE THREAD

**Issue by MateuszKowalewski** [scalameta/scalameta#3201]
```scala
trait A:
   type E <: Throwable
   
object B extends A:
   override class E(m: String) extends Exception(m)

@main def entryPoint = try
   throw B.E("😱")
   catch
      case e: Exception => println(e.getMessage)

```

The above code compiles and runs fine but it triggers an error in Metals.

(Try switching "worksheet" mode on in [Scastie](https://scastie.scala-lang.org/oUeY5oDHT0yOoehJvniSig).)

Looks like a bug to me as according to the spec "TemplateStat[ements]" may have "Modifier"s including `override`:

https://docs.scala-lang.org/scala3/reference/syntax.html

**Comment by kitbellew** [comment]
@MateuszKowalewski what is the error? is there a stack trace? why do you think scastie uses scalameta for parsing?

**Comment by MateuszKowalewski** [comment]
I've found the bug in the VSCode Metals plugin. (Like written in the first line). Metals marks a valid (compiling!) source file "red" and says on the affected line in a hover popup:
```
override' modifier not allowed for classes scalameta
No quick fixes available
```

The above code is a minified version of the source that triggers the bug.

But the bug is also reproducible on Scastie. Same error message "`override' modifier not allowed for classes". Which could be easy seen by the click of a button when following the provided link!

That makes imho sense as  the "worksheet mode" of Scastie uses Metals under the hood AFAIC, so it uses Scala Meta in the end. In "worksheet mode" you get the same error as in Metals, but regular compile works fine. (Just disable "worksheet" and see for yourself. _Alternatively try locally._ SBT compile will work, but the file is marked "red" in the IDE).

**Comment by MateuszKowalewski** [comment]
Cool, so this is already on its way in https://github.com/scalameta/scalameta/pull/3205 ! :+1: 

Thanks a lot for the super quick response!
