### ISSUE TITLE
Quasiquote template stats

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#329]
How I would write without quasiquotes

```scala
case t: internal.ast.Template if t.stats.isDefined =>
  ???
```

How the [docs](https://github.com/scalameta/scalameta/blob/master/docs/quasiquotes.md) say I can write with quasiquote:
```scala
case template"{ ..$stats } with ..$ctorcalls { $param => ..$stats }" =>
  ???
```

Why are there two stats, which one should I use?

**Comment by xeno-by** [comment]
The first one is early initializers. The second one is regular statements in the body of the template. You should use both.
