### ISSUE TITLE
Include generated source in source jars

### ISSUE THREAD

**Issue by Arthurm1** [scalameta/scalameta#3314]
In `common_2.13-4.8.3.jar` there are `platform`, `semanticdb` and `semanticidx` packages under the `scala/meta/internal`

These don't exist in the `common_2.13-4.8.3-sources.jar`

I assume this is because they are generated sources by protobuf?

Can they be included in the sources jar or do they get generated directly to `.class` files?

**Comment by tgodzik** [comment]
Ok, I think I managed to release them in https://github.com/scalameta/scalameta/pull/3315 but it's in a protobuf dir (which shouldn't be an issue for metals since we index the actual package anyway)
