### ISSUE TITLE
scala 3 "foreach: x =>" code not accepted

### ISSUE THREAD

**Issue by fgoret** [scalameta/scalameta#3319]
## Configuration ##
Here's my `.scalafmt.conf`:
```
version = "3.7.12"
runner.dialect = scala3
```

## Command-line parameters ##
scalafmt FmtTrouble.scala

## Steps

Given code like this (in ```FmtTrouble.scala```) :
```scala
@main def bug(): Unit =
  List(1,2,3) foreach: elem =>
    println(elem)

```

## Problem

Scalafmt outputs the following error:
```
$ scalafmt FmtTrouble.scala
FmtTrouble.scala:2: error: [dialect scala3] ; expected but => found
  List(1,2,3) foreach: elem =>
                            ^
```

## Expectation
As this code compile, would expect salafmt accept it :)
```
scala-cli FmtTrouble.scala
1
2
3
```
## Program versions
```
$ scala-cli --version
Scala CLI version: 1.0.4
Scala version (default): 3.3.0
$ scalafmt --version
scalafmt 3.7.12
```

**Comment by SethTisue** [comment]
Note that the workaround is to replace `List(1,2,3) foreach` with `List(1,2,3).foreach`. The former style is discouraged anyway. (though if the compiler accepts it, Scalameta should too as well, of course.)

**Comment by kitbellew** [comment]
@tgodzik @SethTisue the way it's specified, what is it:
- `Term.Apply(Term.Select(..., foreach), ...)`, or
- `Term.ApplyInfix(..., foreach, ...)`?

For reference, just above https://docs.scala-lang.org/sips/fewer-braces.html#compatibility, it mentions `InfixExpr`.
