### ISSUE TITLE
scala.meta.tokenizers.TokenizeException

### ISSUE THREAD

**Issue by Quafadas** [scalameta/scalameta#3328]
```2023.09.06 09:41:44 ERROR issues while parsing: C:\Users\partens\AppData\Local\Coursier\cache\v1\https\packages.schroders.com\artifactory\maven\ai\dragonfly\slash_3\0.1\slash_3-0.1-sources.jar
scala.meta.tokenizers.TokenizeException: jar:file:///C:/Users/partens/AppData/Local/Coursier/cache/v1/https/packages.corp.com/artifactory/maven/ai/dragonfly/slash_3/0.1/slash_3-0.1-sources.jar!/ai/dragonfly/math/Constant.scala:25: error: illegal character '\ud835'
  val 𝜑: Double = 1.46557123187676802665 // Golden
```
I think there is enough in that snippet (import the artefact into scala-cli) to reproduce this. I can provide more info if requred.

**Comment by Quafadas** [comment]
I think then that this is close-expected-behaviour? Thanks for looking... I've sent a PR to simplify that char out the library.

**Comment by SethTisue** [comment]
Scalameta _ought_ to support surrogate unicode characters, since the compiler does, so I would think the ticket should remain open.
