### ISSUE TITLE
unclosed character literal '\u005B'

### ISSUE THREAD

**Issue by audacioustux** [scalameta/scalameta#3370]
![image](https://github.com/scalameta/scalameta/assets/7238675/5ff855c6-2564-429f-a9b8-cf4ea6e281a9)

**Comment by kitbellew** [comment]
thank you for your detailed submission which contains everything needed to reproduce the problem in the current version of scalameta, as well as unequivocal evidence that the problem is indeed in 4.8.11 or later.

p.s. since i can't copy-and-paste it, i can't test it either.

**Comment by audacioustux** [comment]
you could just type out that unicode literal though... there's nothing much to copy-paste here. and the error is from a vscode extension. you could maybe ask for the version, and i would give some extra effort to find out the version.. anyway, thanks 👍

**Comment by tgodzik** [comment]
Looks like it's working for me in the latest Metals. Could you double check @audacioustux ? If not please copy and paste the snippet, it's reach much easier than having a screenshot. Thanks!

**Comment by audacioustux** [comment]
@tgodzik The unicode literal was given in the issue title. and yes, the problem was in metals v1.0.1, and fixed in 1.1.0

**Comment by tgodzik** [comment]
> The unicode literal was given in the issue title

Sometimes it might be an issue caused by a specific combination of syntax, but I guess this wasn't the case here.

Cool to hear it works. Thanks @kitbellew for fixing this!
