### ISSUE TITLE
transform-like combinator that supports deletion

### ISSUE THREAD

**Issue by jrudolph** [scalameta/scalameta#340]
I played around a bit with scalameta and found it cumbersome to delete some things from inside a tree.

E.g. removing an `Import.Selector` can require to delete the `Import.Clause` which can require to delete the `Import` statement itself which again requires to manipulate the containing statement container to remove an element from the statement list which may finally may open up the optimization of replacing a block by its result expression. Using, `transform` it seems I need to implement this all by myself (and duplicate it for all statement containers types).

Is a combinator like this already available?

**Comment by xeno-by** [comment]
We've phased out TQL for the time being (https://gitter.im/scalameta/scalameta?at=5717c64898c544f1396cf7e7) in favor of more traditional `Traverser`/`Transformer` approach with several user-friendly shortcuts. I guess this moves this issue further into the backlog.

**Comment by xeno-by** [comment]
The need for this functionality has never widely materialized. I'll be closing this ticket to focus the core team on more popular issues.
