### ISSUE TITLE
Scala211 doesn't support inline modifiers when printing tree with `inline` modifier

### ISSUE THREAD

**Issue by majk-p** [scalameta/scalameta#3409]
**Issue type:** Bug/Inconsistency
**Scala version:** 2.13.12
**Scala meta version:** 4.8.14 (latest)
**Reproduction snippets:** 
- Straightforward: https://gist.github.com/majk-p/f64713be5e910475e2e8c3ea03ee3e77
- In weaver use case: https://gist.github.com/majk-p/cbceb0125b2083e3a10dac6abcfdfb23

**Workaround exists:** true

## Context
I'm using Scala Meta to generate Scala 3 source code and test the code with [weaver](https://github.com/disneystreaming/weaver-test). Here's a simplified version of a test, where `object Codegen` is something that would be defined by my library.

## Problem

```scala
import scala.meta._
import scala.meta.contrib._
import scala.meta.dialects.Scala3
import weaver._

object Codegen {
  def codeWithInline =
    source"""
    object Generated { 
      inline def dummy = scala.compiletime.error("this method shuold not be invoked")
    }
    """

}

object SampleSpec extends FunSuite {

  val result = Codegen.codeWithInline

  test("Should generate code with inline") {
    val expectation = source"""
    object Generated { 
      inline def dummy = scala.compiletime.error("DIFFERENT MESSAGE TO FAIL TEST")
    }
    """
    assert(result.isEqual(expectation))
  }
}
```
**Expected behavior:** Test fails with an error saying that the values are not equal, printing out both sources and highlighting the difference.

**Actual behavior:** Test fails with runtime error: `UnsupportedOperationException: Scala211 doesn't support inline modifiers`. For full stacktrace run `scala-cli test https://gist.github.com/majk-p/cbceb0125b2083e3a10dac6abcfdfb23`.

## Root cause

In the example above weaver finds out that the assertion is failed and tries to print out the code. Unfortunately it attempts to do it using `toString` (rather than using `syntax`) which is defined as `override def toString = internal.prettyprinters.TreeToString(this)`. `TreeToString` then does [select the dialect](https://github.com/scalameta/scalameta/blob/main/scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeToString.scala#L13), builds `TreeSyntax` and calls it. 

```scala
object TreeToString {
  def apply(tree: Tree) = {
    val dialect = tree.origin match {
      case x: Origin.Parsed => x.dialect
      case Origin.None if tree.isInstanceOf[Quasi] => QuasiquoteTerm(Scala211, multiline = true)
      case Origin.None => Scala211 // this dialect is as good as any as a default
    }
    val prettyprinter = TreeSyntax[Tree](dialect)
    val code = prettyprinter(tree).toString
    tree match {
      case _: Quasi => code
      case Ctor.Primary(_, name, _) => s"def this$code"
      case _ => code
    }
  }
}
```
(please note that `tree.origin` is private, not controlled by end user)

The `TreeSyntax` then inspects the code within the context of the dialect and in case the default dialect is used it [throws an error](https://github.com/scalameta/scalameta/blob/main/scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala#L989) in case `inline` is used:

```scala
      case _: Mod.Inline =>
        if (!dialect.allowInlineMods)
          throw new UnsupportedOperationException(s"$dialect doesn't support inline modifiers")
        kw("inline")
```

At this point I doubt that the comment `Origin.None => Scala211 // this dialect is as good as any as a default` is still true :wink: 

I'm not sure what's the proper solution at this point, there are definitely a few, including:
- Changing the default dialect to `Scala3`
- Defining an optional `dialect` on the tree root
- Allowing the end user to modify the `tree.origin`

## Workarounds

To make the test work without a runtime error, one can extract the expectation outside the test body like this:

```scala
object SampleSpec extends FunSuite {

  val result = Codegen.codeWithInline
  val expectation = source"""
    object Generated { 
      inline def dummy = scala.compiletime.error("DIFFERENT MESSAGE TO FAIL TEST")
    }
    """

  test("Should generate code with inline") {
    assert(result.isEqual(expectation))
  }
}
```

The test works again, though the resulting error is not very informative.

```scala
- Should generate code with inline 51ms
  assertion failed (../../../../Code/personal/scalameta-inline-codegen/weaver.test.scala:31)

  assert(result.isEqual(expectation))
                |      |
                false  scala.meta.contrib.equality.Structurally$$anon$1@7c3023ea
```

A better solution might be invoking `expect.eql` directly and providing your own `Show` and `Eq` instances like this:
```scala
object SampleSpec extends FunSuite {

  val result = Codegen.codeWithInline

  test("Should generate code with inline") {

    val expectation = source"""
    object Generated { 
      inline def dummy = scala.compiletime.error("DIFFERENT MESSAGE TO FAIL TEST")
    }
    """
    implicit def catsKernelEqScalaMetaTree[T <: Tree]: Eq[T] =
      (a: T, b: T) => a.isEqual(b)
    implicit val showTree: Show[Source] = _.syntax
    expect.eql(result, expectation)
  }
}
```
This fixes the error output:
```scala
SampleSpec
- Should generate code with inline 350ms
  Values not equal: (../../../../../../tmp/1197344035151293164/.scala-build/1197344035151293164_130f04a371_df73862be1-d8851bd2fa/src_generated/test/weaver.test.scala:38)

  object Generated { inline def dummy = scala.compiletime.error("[this] [method] [shuold] [not] [be][ ][invoked]") }  |  object Generated { inline def dummy = scala.compiletime.error("[DIFFERENT] [MESSAGE] [TO] [FAIL] [TEST]") }
```

Full example in a gist: https://gist.github.com/majk-p/2ce290d9dfd0dc9f56960bddbde4c41e

**Comment by tgodzik** [comment]
Thanks for reporting! Changing the default from 2.11 is probably a good idea, but I guess there is not perfect dialect that will work in all the cases.

To fix it permanently in Scalameta I think we would need to add a public `withDialect` method that would set a special `Origin.Generated` which would only contain the dialect. So when you create a tree you would be able to set which dialect this tree needs. Maybe we could just add it to the InternalTree or have it as public extension method if mima is not too happy.

As a workaround you could use TreeSyntax directly on the tree:
```
val expected = ...
val prettyprinter = TreeSyntax[Tree](Scala3)
val code = prettyprinter(tree).toString
assertNoDiff(code, expected)
```
or something along these lines

**Comment by kitbellew** [comment]
agreed with @tgodzik. `TreeToString` should perhaps be deprecated as it guesses the dialect of trees without origin, and cannot do it anymore.

unfortunately, quasiquote-generated code [loses origin](https://github.com/scalameta/scalameta/issues/1596#issuecomment-1086713206), so I don't know if we can fix it in scalameta. i am not even sure how the rest of the tree is actually preserved post-compilation :)

another idea is to use this, instead of quasiquotes:
```
val input = scala.meta.inputs.Input.String("...")
val tree = scala.meta.parsers.Parse.parseSource(input, dialect).get
```
