### ISSUE TITLE
Trivial non-matching transformation changes formatting

### ISSUE THREAD

**Issue by jrudolph** [scalameta/scalameta#341]
Starting from a simple source that looks like this,

```scala
class Test(
  a: Boolean,
  b: Int
)
```

a simple transformation like this (that shouldn't even touch the tree)

```scala
tree.transform {
    case q"1" => q"2"
}
```

will reformat the code when pretty printing into this:

```scala
class Test(a: Boolean, b: Int)
```

Is this expected or can it be prevented?

**Comment by xeno-by** [comment]
This is a bug. How urgent is this for you?

**Comment by jrudolph** [comment]
It isn't urgent.

Are trivia preserving transformations/refactoring a realistic short-term goal with scalameta? I tried removing import statements but this usually wreaked havoc with unrelated scaladoc and other comments and formatting.

**Comment by xeno-by** [comment]
Superseded by #379. @jrudolph, I'd be interested in hearing your opinion on the matter.
