### ISSUE TITLE
better error messages for parse errors

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#351]
@olafurpg proposes to also include parts of original source code with a caret pointing to offending fragments in tokenization and parsing errors. This may also be able to indirectly fix https://github.com/scalameta/scalameta/issues/334.

**Comment by olafurpg** [comment]
Yes please! Here is the my own implementation: https://github.com/olafurpg/scalafmt/blob/ae64dcbafb867e45c92db99cba6eb8c34d357815/core/src/test/scala/org/scalafmt/util/FormatAssertions.scala#L70

**Comment by xeno-by** [comment]
Fixed via https://github.com/scalameta/scalameta/pull/366. Take a look at the description of the pull request for examples of how error messages are now formatted.
