### ISSUE TITLE
Merge internal.ast and public API

### ISSUE THREAD

**Issue by densh** [scalameta/scalameta#353]
The idea of splitting this up has been unfortunate overgeneralisation. We never had time to implement more than one ast backend for quasiquotes and it seems that it will stay this way for foreseeable future.

**Comment by xeno-by** [comment]
This wasn't just an overgeneralisation. The idea of not needing case classes in the public API was one of the core initial hypotheses of the project. I agree though that this idea needs work, and for 0.1 we just need to release whatever works.
