### ISSUE TITLE
expected but , found

### ISSUE THREAD

**Issue by timothyklim** [scalameta/scalameta#3531]
## Configuration (required) ##

```
version = 3.7.17
runner.dialect = scala3
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `scalafmt -c .scalafmt.conf Request.scala`

## Steps

Given code like this:
```scala
final case class Request(value: Option[Int], b: String)

Request(
  value = true match
    case true => Some(1)
    case _ => None,
  b = "xxx"
)
```

## Problem

Scalafmt formats code like this:
```scala
Request.scala:6: error: [dialect scala3] ; expected but , found
    case _ => None,
```

## Expectation

I would like the formatted output to look like this:
```scala
final case class Request(value: Option[Int], b: String)

Request(
  value = true match
    case true => Some(1)
    case _ => None,
  b = "xxx"
)
```

## Workaround

Exclude files like this.

**Comment by kitbellew** [comment]
could you please point to section in https://dotty.epfl.ch/docs/internals/syntax.html which allows swapping comma and outdent tokens?

**Comment by timothyklim** [comment]
> could you please point to section in https://dotty.epfl.ch/docs/internals/syntax.html which allows swapping comma and outdent tokens?

Hi!
I cannot but scalac works without problem with it...

**Comment by kitbellew** [comment]
> > could you please point to section in https://dotty.epfl.ch/docs/internals/syntax.html which allows swapping comma and outdent tokens?
> 
> Hi! I cannot but scalac works without problem with it...

that's not reason enough 😁

**Comment by timothyklim** [comment]
Thank you
