### ISSUE TITLE
rhs of var with default value should be Some(x)

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#354]
``` scala
ollie-scalafmt@ "var x: Int = _".parse[Stat].asInstanceOf[internal.ast.Defn.Var]
res33: internal.ast.Defn.Var = var x: Int = _
ollie-scalafmt@ res33.rhs
res34: Option[internal.ast.Term] = None
```

I expected the rhs to give me `Some(whatever)` instead of `None`.

**Comment by densh** [comment]
This is a tough one. It does look syntactically as a val definition with placeholder on the right, but it has completely different meaning from a placeholder as means to express function literals.

**Comment by xeno-by** [comment]
@olafurpg Is this a blocker or an optional improvement? We have a whole bunch of AST improvement ideas, but I've been saving them for 0.2 and beyond.

**Comment by olafurpg** [comment]
Consider it an optional improvement.

**Comment by xeno-by** [comment]
@olafurpg What do you think about this issue these days?

**Comment by xeno-by** [comment]
We're on the verge of releasing 2.0, and afterwards we plan to start being really conservative about breaking changes. The matter discussed in the ticket can probably be improved, but there's not enough interest to justify potential breakages.
