### ISSUE TITLE
Scalameta inserting parenthesis 

### ISSUE THREAD

**Issue by q-danpryer** [scalameta/scalameta#3544]
I'm using scalameta to generate a function and I notice its inserting some redundant parentheses. Note that this isn't a breaking issue, its just about aesthetics.

The quasiquote is something like this:

```
q"def someFunction(args1: Option[Int]) = args1.map{ case args1 => args1.map(_.toString) }"
```

and the generated Scala looks like this:

```
def someFunction(args1: Option[Int]) = args1.map({
    case args1 =>    
        args1.map(_.toString)    
})
```

whereas I'd want it to not have that extra set of parentheses as they are redundant, to keep things cleaner and more closely matching the original quasiquote:

```
def someFunction(args1: Option[Int]) = args1.map{
    case args1 =>    
        args1.map(_.toString)    
}
```

Wasn't sure if this was a scalameta thing or an interaction with scalafmt or if there is any way round this? I tried playing around with the RedundantParenthesis config option in scalafmt but it didn't seem to have an effect. Am quite new to scalameta so sorry if it's something obvious. I notice when I remove the case statement from the map, it just gives me:

```
def someFunction(args1: Option[Int]) = args1.map{ }
```

so no extra parentheses, wasn't sure if these are being caused by the case statement or the line breaks?

**Comment by kitbellew** [comment]
@q-danpryer i made the change but please keep in mind that syntax printing in scalameta is not designed nor intended to be  beautiful, aesthetic or even human-readable. usually people don't read generated code.

as to scalafmt, it should remove them if you configure correctly, but how (and why) do you run scalafmt on generated code?

**Comment by q-danpryer** [comment]
Hey @kitbellew , thanks for the very speedy turnaround/fix on that one! Appreciate that its just generated code that people don't usually look at, it was more of a nice to have.
I didn't think scalafmt was necessarily involved, I was just scratching my head a bit as to why this was happening or what could be the cause.
