### ISSUE TITLE
New warning under `-Wunused:locals` on main for quasiquotes expanded code

### ISSUE THREAD

**Issue by bjaglin** [scalameta/scalameta#3546]
https://github.com/scalameta/scalameta/pull/3480 introduces a warning

```
//> using scala 2.13.12
//> using option -Wunused:locals

//> using repository sonatype:snapshots
//> using dep org.scalameta::scalameta:4.8.15+150-a7c0baa0-SNAPSHOT

import scala.meta._

object Quasiquotes {
  importee"importee"
}
```

```scala
$ scala-cli compile quasiquotes.scala 
Compiling project (Scala 2.13.12, JVM (17))
[warn] ./quasiquotes.scala:10:3
[warn] local val dialectOnly$macro$4 in value <local Quasiquotes> is never used
[warn]   importee"importee"
[warn]   ^
Compiled project (Scala 2.13.12, JVM (17))
```

**Comment by kitbellew** [comment]
@bjaglin would annotating with `@unused` help?

**Comment by bjaglin** [comment]
@kitbellew it looks like `@nowarn` works also on 2.12 (with `-Ywarn-unused`), white `@unused` does not have any effect. I didn't get the chance to look at generated code, but I am surprised that we don't get warnings for other existing fields used for reification. Maybe there is some tweak to follow?

**Comment by kitbellew** [comment]
this field is used only if the tree doesn't contain another origin, hence it could be unused. let's add nowarn, then.

**Comment by kitbellew** [comment]
@bjaglin you mentioned on discord that new versions of scala will be released soon. do you know when?

meanwhile, would you mind trying the most recent snapshot build to see whether it solves the warning problem?

**Comment by bjaglin** [comment]
> do you know when?

supposedly this week
- https://contributors.scala-lang.org/t/scala-2-12-19-release-planning/6216
- https://contributors.scala-lang.org/t/scala-2-13-13-release-planning/6315
- https://contributors.scala-lang.org/t/3-4-0-release-thread/6445/

**Comment by kitbellew** [comment]
> > do you know when?
> 
> supposedly this week
> 
> * https://contributors.scala-lang.org/t/scala-2-12-19-release-planning/6216
> * https://contributors.scala-lang.org/t/scala-2-13-13-release-planning/6315
> * https://contributors.scala-lang.org/t/3-4-0-release-thread/6445/

@tgodzik should we wait a week until 2.12 and 2.13 are released, and then add new patch (and remove oldest patch as well), before issuing a 4.9.0?

**Comment by tgodzik** [comment]
> @tgodzik should we wait a week until 2.12 and 2.13 are released, and then add new patch (and remove oldest patch as well), before issuing a 4.9.0?

I think it would be better to release 4.9.0 to have support for binary literals ready. I can release semanticdb for older versions without an issue.

**Comment by kitbellew** [comment]
> > @tgodzik should we wait a week until 2.12 and 2.13 are released, and then add new patch (and remove oldest patch as well), before issuing a 4.9.0?
> 
> I think it would be better to release 4.9.0 to have support for binary literals ready. I can release semanticdb for older versions without an issue.

@tgodzik sorry if i am a little slow today :) are you saying release now, don't wait until scala patch release?

**Comment by tgodzik** [comment]
Yes, exactly.
