### ISSUE TITLE
Single element Term.Block parsing simplification (change between 4.8.15 and 4.9.0)

### ISSUE THREAD

**Issue by robby-phd** [scalameta/scalameta#3570]
It seems that a Term.Block containing single element is simplified to the element when parsing in 4.9.0 while the block is preserved in 4.8.15. I think it would be best if simplification is not done during parsing to preserve term syntax/structure consistency.

Here's an example that illustrates the behavior change (the assertion fails using [4.8.15](https://scastie.scala-lang.org/Y73ljyKWTTyUuqRH6P1UJQ) but passes using [4.9.0](https://scastie.scala-lang.org/ePSFLs86QL22gwkiIgA5hA)):

```scala
import scala.meta._

val term = Term.Apply(Term.Name("Foo"), Term.ArgClause(List(Term.Apply(Term.Name("bar"), Term.ArgClause(Nil, None))), None))
val parsedTerm = "Foo{bar()}".parse[Term].get
println(term)       // Foo(bar())
println(parsedTerm) // Foo{bar()}
assert(term.structure == parsedTerm.structure)
```

**Comment by bjaglin** [comment]
I also hit this behavior change when [assessing the impact of scalameta 4.9.0 on the largest repo of scalafix community rules](https://github.com/bjaglin/scalafix-rules/pull/1).

Might be related to https://github.com/scalameta/scalameta/pull/3517.

I don't have a strong opinion on whether it's a good or bad change, but I am eager to hear whether that behavior is here to stay or not, to decide if I should hold a Scalafix release.

**Comment by bjaglin** [comment]
Thanks @kitbellew! I assume you'll be tagging a 4.9.1 shortly to address all the early scalafmt 3.8.0 bug reports?

**Comment by kitbellew** [comment]
> Thanks @kitbellew! I assume you'll be tagging a 4.9.1 shortly to address all the early scalafmt 3.8.0 bug reports?

soon. there's still one bug, filed under sbt-scalafmt.
