### ISSUE TITLE
support SIP 53 in parser

### ISSUE THREAD

**Issue by bishabosha** [scalameta/scalameta#3610]
https://docs.scala-lang.org/sips/quote-pattern-type-variable-syntax.html

i.e. some code like this
```scala
import scala.quoted.*

def toTuple(list: List[Type[?]])(using Quotes): Type[?] = list match
  case '[t] :: ts => toTuple(ts) match
    case '[type ts <: Tuple; ts] => Type.of[t *: ts]
  case _ => Type.of[EmptyTuple]
```

im trying this out in 3.4.0 which compiles, but metals complains with `identifier expected but type found (scalameta)`

**Comment by tgodzik** [comment]
Thanks for reporting! We didn't notice that change :thinking:  I will try to take a look on the weekend if no one manages to look until then.
