### ISSUE TITLE
OutOfMemoryError since 4.9.0

### ISSUE THREAD

**Issue by xuwei-k** [scalameta/scalameta#3650]
https://github.com/xuwei-k/scalameta-memory-issue-3650/commit/765dccba2154d1bf90d9c8281ec3e2b7aaa5fa04

reproduce code

```scala
package example

import scala.meta._
import scala.meta.inputs.Input
import scala.meta.parsers.Parse
import scala.meta.prettyprinters._
import scala.meta.transversers._
import scala.jdk.StreamConverters._
import java.io.File

object Main {
  def main(args: Array[String]): Unit = {
    // parse many scala code
    // e.g. https://github.com/scala/scala 2.13.x branch
    java.nio.file.Files.find(
      new File("scala", "src").toPath,
      100,
      (p, _) => p.toFile.getName.endsWith(".scala") && (p.toFile.getName != "Singleton.scala")
    ).toScala(List).map { f =>
      val tree = implicitly[Parse[Source]].apply(Input.File(f), scala.meta.dialects.Scala213Source3).get
      tree.traverse { a => () }
      tree
    }
  }
}
```

VisualVM results in my local Mac

- https://visualvm.github.io/

### 4.8.15

<img width="1142" alt="meta-4-8-img-1" src="https://github.com/scalameta/scalameta/assets/389787/434bc1e8-06a4-4837-8380-e114cbd18603">

<img width="1145" alt="meta-4-8-img-2" src="https://github.com/scalameta/scalameta/assets/389787/356faea2-4a37-4e2e-96cc-136a19ce9001">

### 4.9.0

<img width="1141" alt="meta-4-9-img-1" src="https://github.com/scalameta/scalameta/assets/389787/6c5498e7-c151-4f54-8bab-c0266705a17c">

<img width="1146" alt="meta-4-9-img-2" src="https://github.com/scalameta/scalameta/assets/389787/7a6a1530-d0ec-4526-b6a9-25e379f4c5f7">

## GitHub Actions result

- https://github.com/xuwei-k/scalameta-memory-issue-3650/actions/runs/8305399108

### 4.8.15

```
[info] running (fork) example.Main 
[success] Total time: 18 s, completed Mar 16, 2024, 4:43:48 AM
```

### 4.9.0

```
[info] running (fork) example.Main 
[error] Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
```

## note

generated too many `TrieMap`. maybe https://github.com/scalameta/scalameta/commit/f840d2ec9046d92a88c15714f8ed31b8c44775e2 🤔

**Comment by xuwei-k** [comment]
## scalafmt gc log

### scalafmt 3.8.0( scalameta 4.9.0)

<img width="1593" alt="scalameta-4-9-img-1" src="https://github.com/scalameta/scalameta/assets/389787/97fc42e8-5ae8-4cac-8178-6c6a72059ec9">
<img width="799" alt="scalameta-4-9-img-2" src="https://github.com/scalameta/scalameta/assets/389787/f15a51dd-47a8-46b0-9518-aaa233053939">

### scalafmt 3.7.17( scalameta 4.8.14)

<img width="1599" alt="scalameta-4-8-img-1" src="https://github.com/scalameta/scalameta/assets/389787/351deb93-fc33-403b-a999-f68077fc93ef">
<img width="798" alt="scalameta-4-8-img-2" src="https://github.com/scalameta/scalameta/assets/389787/0bfdf999-5b5f-41b2-99cd-3f6f7a0c9640">

**Comment by kitbellew** [comment]
this seems like a strange oversight to me: https://github.com/scalameta/scalameta/commit/f840d2ec9046d92a88c15714f8ed31b8c44775e2#diff-328bbe30c12809ccabef99878be748a69632e114e66ba67003f7be8d3b77d1e1R64

not sure if lazy vals can contribute.

**Comment by kitbellew** [comment]
@xuwei-k is it possible to verify whether this problem is present in 4.9.3, please?

**Comment by xuwei-k** [comment]
I have confirmed not present in 4.9.3. Thanks! 👍
