### ISSUE TITLE
Parsing fails in presence of significant space pattern match as a non-last parameter

### ISSUE THREAD

**Issue by rpiaggio** [scalameta/scalameta#3664]
scalameta 4.8.7 can't parse the following valid Scala code:

```scala
val component =
  List(1,2,3)
    .map: (props) =>
      TableOptions(
        getRowId = (row, _, _) =>
          row.value match
            case Left(HeaderRow(rowId, _)) => rowId
            case Right(stepRow)            => stepRow.step.rowId,
        onColumnSizingChange = dynTable.onColumnSizingChangeHandler
      )
```

It fails on line 3 with `; expected but => found`.

However, it works fine if the last parameter (`onColumnSizingChange`) is moved above `getRowId`, or if braces are added to the pattern match.

In other words, both of these work:
```scala
val component =
  List(1,2,3)
    .map: (props) =>
      TableOptions(
        onColumnSizingChange = dynTable.onColumnSizingChangeHandler,        
        getRowId = (row, _, _) =>
          row.value match
            case Left(HeaderRow(rowId, _)) => rowId
            case Right(stepRow)            => stepRow.step.rowId
      )
```

```scala
val component =
  List(1,2,3)
    .map: (props) =>
      TableOptions(
        getRowId = (row, _, _) =>
          row.value match {
            case Left(HeaderRow(rowId, _)) => rowId
            case Right(stepRow)            => stepRow.step.rowId
          },
        onColumnSizingChange = dynTable.onColumnSizingChangeHandler
      )
```

(Thanks @keynmol for helping isolate the issue).

**Comment by kitbellew** [comment]
@rpiaggio the current version is 4.9.2: https://github.com/scalameta/scalameta/releases

could you please verify to make sure this problem hasn't still been fixed?

**Comment by rpiaggio** [comment]
Hi @kitbellew !

I tried it on https://astexplorer.net/, which has 4.8.7.

It's still happening with scalafix 0.12.0, so it's still happens with scalameta 4.9.1. How can I test with 4.9.2?

**Comment by keynmol** [comment]
Confirmed on 4.9.2: https://scastie.scala-lang.org/ffq28TY2TMqJEaZTERJTVA

**Comment by rpiaggio** [comment]
Thank you!
