### ISSUE TITLE
better website

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#367]
scalameta.org is very minimalistic - both design-wise and information-wise. We need it to be more impressive.

**Comment by olafurpg** [comment]
I've had a really great experience using [Scalatex](http://www.lihaoyi.com/Scalatex/) in https://olafurpg.github.io/scalafmt/. The source for the page is [here](https://github.com/olafurpg/scalafmt/blob/master/readme/Readme.scalatex).

My favorite parts:

* the site is an sbt project. For example, you can depend on your library from the site project.
* `.scalatex` files are just Scala code. You can use your API inside the docs and you can abstract over the structure of your docs.
* Examples are always up to date, when you change your api your docs don't compile
* live preview site while writing docs using `~readme/run` + https://www.browsersync.io/

My not so favorite parts:
* HTML links/lists are boilerplatey compared to markdown
* error messages are sometimes cryptic
* no IDE support when writing `.scalatex` files

**Comment by olafurpg** [comment]
Btw, I implemented something similar to [tut](https://github.com/tpolecat/tut) but for scalatex. See [implemenatation](https://github.com/olafurpg/scalafmt/blob/02b21136817ba335d0b33d188d926b8eba9aaf0f/readme/Readme.scala#L25). This means you can write code in your docs [like here](https://github.com/olafurpg/scalafmt/blob/02b21136817ba335d0b33d188d926b8eba9aaf0f/readme/Readme.scalatex#L155) and it compiles with scalac and produces output [like here](https://olafurpg.github.io/scalafmt/#Standalonelibrary)
