### ISSUE TITLE
faithfully reimplement Sbt parsing logic

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#368]
`0.1.0-RC2` is going to parse `.sbt` files under `Sbt0136` and `Sbt0137` dialects. However, it'll be much more permissive than what's implemented in SBT. It would be useful to reproduce that logic in our parser, if only to have a spec for `.sbt` files. 

See https://github.com/sbt/sbt/blob/6b6fd305ff7aab36ce2daad918c534ff9bdaf737/main/src/main/scala/sbt/EvaluateConfigurations.scala#L226 for the implementation that currently serves as a spec.

**Comment by xeno-by** [comment]
Evidently, this functionality isn't popular with our users. I'm closing this for now, but can consider reopening this issue if the demand becomes non-zero.

**Comment by dwijnand** [comment]
I would expect more demand when executing scalameta (or scalameta-depending code) doesn't require performing backflips in zero gravity (i.e class-loading from Scala 2.10). I for one want to ship features in sbt plugins using scalameta.

**Comment by xeno-by** [comment]
Allright. Let's keep an eye on this in the future!
