### ISSUE TITLE
ScalametaParser: pos for trailing comments on multi-line expression inconsistent from one dialect to another

### ISSUE THREAD

**Issue by bjaglin** [scalameta/scalameta#3689]
```scala
import scala.meta._

val program =
"""
object Main extends App {
  val a = 1 // comment attached to Defn.Val on all dialects
  val b =
    1 // comment attached to Defn.Val on Scala 3 dialect only
}
"""

{
  println("Scala213")
  implicit val scala213: Dialect = dialects.Scala213
  println(program.parse[Stat].get.collect { case v: Defn.Val => v }.map(_.pos))
  println()
}

{
  println("Scala3")
  implicit val scala3: Dialect = dialects.Scala3
  println(program.parse[Stat].get.collect { case v: Defn.Val => v }.map(_.pos))
  println()
}
```

```diff
---Scala213
+++Scala3
 List([29..38) in Input.String("
 object Main extends App {
   val a = 1 // comment attached to Defn.Val on all dialects
   val b =
     1 // comment attached to Defn.Val on Scala 3 dialect only
 }
-"), [89..102) in Input.String("
+"), [89..158) in Input.String("
 object Main extends App {
   val a = 1 // comment attached to Defn.Val on all dialects
   val b =
     1 // comment attached to Defn.Val on Scala 3 dialect only
 }
 "))
```

This makes cross-dialect usage of `AssociatedComments` hard.

I don't have any opinion on what is the right behavior. FWIW,
- the behavior for the Scala213 dialect hasn't changed since at least 4.2.0
- the behavior for the Scala3 dialect hasn't changed since [4.4.33](https://github.com/scalameta/scalameta/releases/tag/v4.4.33) (before that, Scala3 had the same behavior as Scala213)

I found this inconsistency while trying to port a Scala2 Scalafix test to Scala3. I am not aware of any reported problem in production, so "won't fix" is definitely a reasonable outcome for this issue.

**Comment by kitbellew** [comment]
@bjaglin I added a test and see that `val a` does NOT have an attached comment for either of two dialects.

However, `val b` does have an attached comment in scala3 (although it's because its value tree `Lit.Int(1)` has it attached).

Here are my thoughts on `val b`, or its value specifically:
- in scala2, that value is parsed as `Lit.Int(1)`
- in scala3, that value is parsed as `Term.Block(List(Lit.Int(1))` because it's an outdented block with significant indentation, although we are dropping the block as superfluous -- and copying the block's positions to the underlying single expression (as usual)

I can modify parsing behaviour NOT to drop the block in this type of case, which would also detach the comment from `Lit.Int(1)`. would that work?

**Comment by bjaglin** [comment]
Thanks for having a look at that!

> @bjaglin I added a test and see that val a does NOT have an attached comment for either of two dialects.

Right, sorry for the mix-up!

> I can modify parsing behaviour NOT to drop the block in this type of case, which would also detach the comment from Lit.Int(1). would that work?

Injecting (or rather keeping, from an implementation perspective) a `Term.Block` would effectively be a breaking change from a Scalafix perspective (similar to https://github.com/scalameta/scalameta/issues/3594), which is acceptable if signaled properly. But if I understand well, the presence of that `Term.Block` would be dialect-dependent, right? If that's the case, I am concerned that this proposal would bring more pain than benefits. 

Btw, I just realized you did [tag me on that topic](https://github.com/scalameta/scalameta/pull/2550#issuecomment-1015574411), but I think I didn't invest time on the question after seeing in the comments that scalafix tests had been successfully run...

**Comment by kitbellew** [comment]
yes, the presence of significant indentation is indeed specific to scala3.

would you like to go in the opposite direction and attach comments to single expressions in scala2?

**Comment by bjaglin** [comment]
> would you like to go in the opposite direction and attach comments to single expressions in scala2?

I don't have a strong opinion. From a compatibility perspective, I would naively assume that the scala2 behavior has been around for so long that it's better to stick to it and rather change the scala3 one for outdented blocks? But I am not aware aware of the cost/complexity that this would require (if we don't want the `Term.Block`, which would trade a difference between scala2 and scala3 for another).

**Comment by bjaglin** [comment]
That sounds good :+1:

**Comment by bjaglin** [comment]
I am afraid I misunderstood your proposal, as I can now see from your test cases in https://github.com/scalameta/scalameta/pull/3695 that this only changes behavior for the case "if the last line of the block contains only comments" (keeping the block, and thus including the comment in the position), which was not my original issue.

I thought the proposal was to never attach comments in Scala3, except in the case of comment-only last lines (in which case we would introduce a new block, which didn't matter since it was a Scala3-only feature and shouldn't come as a surprise for users targeting both dialects.

Specifically, if I reformulate the original issue at the light of your test case, I was looking at unifying this dialect-specific behavior:
```diff
---scala2
+++scala3
   // #3689 2
   checkPositions[Term](
    """|{
        |  val b =
        |    1 // comment
        |}
        |""".stripMargin,
     """|Defn.Val val b =
-       |    1
+       |    1 // comment
        |""".stripMargin
   )

**Comment by kitbellew** [comment]
hmm... let me think.

**Comment by kitbellew** [comment]
@bjaglin could you please check the linked pr?

**Comment by bjaglin** [comment]
Perfect, thanks!
