### ISSUE TITLE
can't fmt scal with `\ud801`,which actually is  `?`

### ISSUE THREAD

**Issue by laglangyue** [scalameta/scalameta#3690]
##  Description
orginal code in pekko-grpc
org.apache.pekko.grpc.scaladsl.headers.HeadersSpec

```scala
  "Status-Message.value()" should {
    "use percent-encoding" in {
      // test cases taken from https://github.com/grpc/grpc-java/blob/79e75bace40cea7e4be72e7dcd1f41c3ad6ee857/api/src/test/java/io/grpc/StatusTest.java#L65
      val inAndExpectedOut = Table(
        ("raw input", "expected encoded value"),
        ("my favorite character is i", "my favorite character is i"),
        ("my favorite character is \n", "my favorite character is %0A"),
        ("my favorite character is \u0000", "my favorite character is %00"),
        ("my favorite character is %", "my favorite character is %25"),
        ("my favorite character is 𐀁", "my favorite character is %F0%90%80%81"),
        // \ud801 is a high surrogate, a lone surrogate character is getting decoded as ? with UTF-8
        ("my favorite character is \ud801", "my favorite character is ?"),
        // \udc37 is a low surrogate, a lone surrogate character is getting decoded as ? with UTF-8
        ("my favorite character is \udc37", "my favorite character is ?"),
        // a pair of surrogate characters is fine
        ("my favorite character is " + 0xDBFF.toChar + 0xDFFF.toChar, "my favorite character is %F4%8F%BF%BF"))

      forAll(inAndExpectedOut) { (in, expected) =>
        new `Status-Message`(in).value() should equal(expected)
      }
    }
  }
```

when scalafmtAll

```shell

[error] org.scalafmt.sbt.ScalafmtSbtReporter$ScalafmtSbtError: scalafmt: /home/laglang/coding/pekko-grpc/runtime/src/test/scala/org/apache/pekko/grpc/scaladsl/headers/HeadersSpec.scala:39: error: invalid unicode surrogate pair
[error]         ("my favorite character is \ud801", "my favorite character is ?"),
[error]                                    ^ [/home/laglang/coding/pekko-grpc/runtime/src/test/scala/org/apache/pekko/grpc/scaladsl/headers/HeadersSpec.scala]
[error] (runtime / Test / scalafmt) org.scalafmt.sbt.ScalafmtSbtReporter$ScalafmtSbtError: scalafmt: /home/laglang/coding/pekko-grpc/runtime/src/test/scala/org/apache/pekko/grpc/scaladsl/headers/HeadersSpec.scala:39: error: invalid unicode surrogate pair
[error]         ("my favorite character is \ud801", "my favorite character is ?"),
[error]                                    ^ [/home/laglang/coding/pekko-grpc/runtime/src/test/scala/org/apache/pekko/grpc/scaladsl/headers/HeadersSpec.scala]
[error] Total time: 3 s, completed 2024年4月14日 下午2:38:01

```

## Question
pekko-grpc can fix it by use `${0xD801.toChar}`, I'm not sure if this is a bug in scalafmt, report it.

 `\ud801` actually is  `?`

**Comment by kitbellew** [comment]
@laglangyue now that it's linked to scalameta, can you explain why your code uses high-surrogate and low-surrogate _parts_ of a unicode character **separately**?

currently, the parser follows the unicode standard and parses all unicode characters completely; if it encounters an 32-bit integers which falls into unicode high-surrogate range, it will then read the next 32-bit integer (which must come from the low-surrogate range) and combine the two together. these two parts cannot be separate.

**Comment by laglangyue** [comment]
This is the test code of pekko-grpc, where headerSpec tests for special characters.
Users may fill in such characters, so we need to test them in Spec，grpc-java also do the test.
Now we have changed it to ${0xD801. toChar},
So pekko-grpc has solved this problem. 
If it is confirmed that there will be not support, I think we can close the issue，because there are alternative solutions in the source code

**Comment by kitbellew** [comment]
what exactly can we support here? it's invalid Unicode. does the scala compiler support it?

**Comment by laglangyue** [comment]
when a string has `\ud801`, sbt scalafmtAll will cause exception, but `sbt clean compile` can execute successfully.
BTW I copy it to google search, it will be '?'.
so In my opinion, scalafmtAll can ignore it but not throw exception.
I don't understand how scalafmt works, I close the issue.

**Comment by kitbellew** [comment]
@laglangyue `\ud801` is not a valid character, it cannot be stored in a `char`. there are plenty of discussions online about this.

and the `?` that you see is not the value of that character but a message from the system telling you it doesn't know what that character is.
