### ISSUE TITLE
RC2: alternative for good old parse[Stat]?

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#371]
I would like to use the same parser for:

* Statement ending with semicolon
```scala
""" new Foo();
                """.parse[Stat]
res6: Parsed[Stat] = <content>:1: error: end of file expected but ; found
new Foo();
          ^
```

* Term.Block / sequence of statements (up for debate, but has been useful for me) 
```scala
""" val x = 1
    val y = 2
                """.parse[Stat]
res7: Parsed[Stat] = <content>:1: error: end of file expected but \n found
val x = 1
          ^
```

**Comment by xeno-by** [comment]
I've fixed the first part of the issue yesterday in `0.1.0-SNAPSHOT`. 

I'd say we don't fix the second part and replace it with a `parse[Stats]` helper in your code. `parse[T]` doesn't require `T` to be `<: Tree`, so you could create a helper wrapper and an implicit instance of `Parse[Stats]` that reproduces the old logic of `parse[Stat]` and then wraps the result. Wdyt?

**Comment by olafurpg** [comment]
>  you could create a helper wrapper and an implicit instance of Parse[Stats] that reproduces the old logic of parse[Stat] and then wraps the result.

I hadn't thought about that, pretty neat. Still, I may decide to just wrap those stats in a `{}` block.
