### ISSUE TITLE
better usability for tokens

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#372]
I think it'd be useful to have something more concise than `token match { case _: Foo => ... }` and `token.isInstanceOf[Foo]`. Maybe something like `token match { case Foo() => ... }` and `token.is[Foo]`?

**Comment by xeno-by** [comment]
Also, I'm sure @olafurpg has more ideas about improving quality of life for Token users. Olaf, could you elaborate please?

**Comment by olafurpg** [comment]
I agree that the syntax to match on token types gets tiring to write. Still, I like it because I get exhaustibility checks from scalac during pattern matching and it's plain vanilla scala.

For token APIs in other languages I've seen 100s of methods on the token class like `token.is{Comma,OpenParen,Underscore}`. I think I prefer scala.meta's approach.

I don't think `token match { case Foo() => ... }` would help. However, I do think that having `token.is[T]` would be a nice improvement over `token.isInstanceOf[T]`. My reasoning being that the use of `isInstanceOf` is typically discouraged in Scala but it is in my opinion definitely idiomatic when working with scala.meta tokens.

**Comment by xeno-by** [comment]
Summing up the discussion of #350. 

@olafurpg says that backticks were very readable in his experience with scalafmt. He also notes that he doesn't mind giving tokens regular names, because of scariness for newcomers and other small issues with Scala not quite accommodating backquoted names.

@densh says that backticks don't need renaming, because they are crucial for readability.

**Comment by xeno-by** [comment]
Changes to the token API introduced in the fix:
  * Renamed most tokens: `` `keyword` `` => `Keyword`, spelt out symbolic names, `Literal` => `Constant`. See https://github.com/scalameta/scalameta/blob/v0.1.0-RC3/scalameta/tokens/src/main/scala/scala/meta/tokens/Token.scala for details.
  * Removed auxiliary traits: `Static`, `Dynamic`, `Literal`, `Keyword`, `Modifier`, `Delim`, `Trivia`, `Whitespace`. These were internal implementation details mistakelny exposed in the public API.
  * Removed `Token.name`. This was an internal method mistakenly exposed in the public API.
  * Removed `Token.code`. This was a duplicate of `Token.show[Syntax]`.
  * Removed `Token.adjust`. This was an internal method mistakenly exposed in the public API.
  * Introduced `Token.is[T]/isNot[T]`, where T can be any token type.
  * Unapply methods on token companions have been changed to only carry payload, e.g. `case Ident(value) => ` or `case LeftBrace() =>`.

Migration notes:
  * You can use https://github.com/xeno-by/dotx/blob/master/migrate on your .scala files and directories to apply renamings automatically.
  * If you've been using internal functionality exposed in the public API by mistake, you'll have to rewrite your code. The functionality seems to be quite limited, so I don't expect much (if any) effort required here. If the effort is significant, let me know, and we'll figure something out.

Quality of life improvements:
  * Can now refactor `token.isInstanceOf[T]` to `token.is[T]`.
  * Can now refactor `case _: T =>` to `case T() =>`.
  * Can now refactor `case token: T =>` to `case token @ T() =>`.

**Comment by xeno-by** [comment]
It turns out that `Token.code` was much popular than I thought. In order to avoid requiring the unwieldy `Token.show[Syntax]`, in `0.1.0-SNAPSHOT` I've introduced the `.syntax` (and `.structure`) extension method for all types that allow `.show[Syntax]`.

**Comment by olafurpg** [comment]
Thank you! 🙏 I use `.code` and `.show[Structure]` all the time, `.syntax` and `.structure` will be nice to have.
