### ISSUE TITLE
Init Seq vs List ambiguous overload

### ISSUE THREAD

**Issue by sjbiaga** [scalameta/scalameta#3725]
Whereas pattern matching `scala.meta.Init` works with last parameter `argss` as `Nil` - i.e., a `List[List[Term]]` -, when creating `Init`, there is the primary constructor that uses `argClauses` which is a `Seq[Term.ArgClause]`, and a secondary constructor, so gives this error:

    Ambiguous overload. The overloaded alternatives of method apply in object Init with types
     (tpe: scala.meta.Type, name: scala.meta.Name, argss: List[List[scala.meta.Term]]): scala.meta.Init
     (tpe: scala.meta.Type, name: scala.meta.Name, argClauses: Seq[scala.meta.Term.ArgClause]): scala.meta.Init
    both match arguments (scala.meta.Type.Select, scala.meta.Name.Anonymous, (Nil scala.collection.immutable.Nil.type))

Working textually at the metaprogramming level, I have to use `sed` to replace `Nil` with `Seq()` before pasting the constructor, e.g., `Init(Type.Name(...), Name.Anonymous(), Seq())`. But trying to find the occurrence of `Nil` is a no go.

It is the only exception of this case afik. (EDIT: `Ctor.Primary(Nil, Name.Anonymous(), Nil)` is also the case)

Pointing only at `scala.meta.Trees.scala#1084`, a quick fix is to add a ("another"?) _secondary_ constructor:

    def this(tpe: Type, name: Name, _nil: Nil.type) = this(tpe, name, Seq())

but isn't it cumbersome?! ;)

**Comment by tgodzik** [comment]
Thanks for reporting. This is a problem that was caused by making sure we maintain binary compatibility. Once we release a new 5.0.0 version (which is becoming more and more tempting), the additional methods should disappear.

For now you can either type it fully via `List.empty[ArgClause]` or use named arguments.

**Comment by sjbiaga** [comment]
Two more peculiarities pop up:

    "var c = 'a'".parse[Stat].get.structure
    "var c = 'a".parse[Stat].get.structure

give `Lit.Char(a)` and _not_ `Lit.Char('a')`, respectively, `Lit.Symbol(Symbol(a))` and _not_ `Lit.Symbol(Symbol("a"))`.

I don't know if the problem you refer to is the same as this issue  - which poses in fact a question a lot more simpler.

The documentation mentions:

    This document lists examples of how Scala source code maps to Scalameta tree nodes.

It does not specify whether _pasting_ unmodified the string yielded by the parser in, say, the evaluation line of `REPL`, gives back the AST, _not_ programmatically  "type"d by the user - because I don't want to "type" it.

With me - besides the `REPL` example, there is also the case of pipelines which use the parser output without modifications redirected to a `.scala` file, and then process the entire `Source(...)` AST "as if" "type"d - but it's pasted, not typed.

Will the output of the parser be directly usable as an AST in next versions?

**Comment by tgodzik** [comment]
> Will the output of the parser be straightly usable as an AST in next versions?

This could be fixed before, looks like a bug.
