### ISSUE TITLE
Term.Anonymous multiple inheritance

### ISSUE THREAD

**Issue by sjbiaga** [scalameta/scalameta#3726]
The parameter `within: Ref` to `Mod.Private` or `Mod.Protected`, when it is `Term.Anonymous()`, is not clear whether a `scala.meta.Name` is intended or a `scala.meta.Term.Ref`?

Translating a `parse`d string in a strongly-typed context (for "within"), it is not clear whether I should issue a `Term.Ref` type or a `scala.meta.Name` type: I cannot do both for `scala.meta.Ref` because `"Term.Anonymous"` is actually a key in a (`Perl`) hash.

**Comment by kitbellew** [comment]
can you please include the code of what you're attempting to do, with types? i don't think i understand what you're describing.

**Comment by sjbiaga** [comment]
Yes, I realized that myself after grasping it that I didn't specify what I had in mind. Here is the link:

https://github.com/sjbiaga/hascalam/blob/1426b499cc7bdc4daa220f5b65fd2141646babe5/bin/Scalameta2Haskell.pl#L140

Basically there are two `Haskell` data constructor(s):
- `Term.Anonymous` mapped to `RName(NAnonymous(...`
- `Term.Anonymous` mapped to `R_TRef(RTAnonymous(...`

Maybe if I rephrased the question. I see that `Term.Anonymous` inherits `scala.meta.Name` only to have an empty `value = ""`.
It matches `case _: Name => true` in `checkFields(within.isWithin)`.

That's fine by me if I further knew - to be blunt - how/when/for which case... does the parser issue a `Term.Anonymous`?

**Comment by kitbellew** [comment]
i still don't understand the question. could you please share some scala code which fails to compile, or whatever else is happening with it? and if it's not failing, then what are you asking, then?

i am neither familiar with Haskell nor see the relevance.

**Comment by sjbiaga** [comment]
Which are all occurrences of `Term.Anonymous` in the 
`scalameta/scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala` (or just "in the parser")? Does it occur where a `scala.meta.Name` is expected or where a `scala.meta.Term.Ref` is expected, or both? Because used `IDE` is not loading the project properly.

**Comment by kitbellew** [comment]
feel free to use a grep. or intellij. that's what i do when i need to do this.
