### ISSUE TITLE
formatting-aware code transformations

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#379]
Current metaprogramming frameworks for Scala don't support formatting-aware code transformations. Here's the summary of the state of the art (do let me know if I've forgotten something):
- scala.reflect doesn't even support parsing without destroying formatting. It: a) throws away comments and whitespace, b) desugars some trees during parsing - which irreversibly loses information about original code.
- Scala Refactoring is based on scala.reflect, so it features a very elaborate framework that tries to undo the damage that scala.reflect does. The end result has a number of known issues discussed at length at ScalaSphere this year (https://www.youtube.com/watch?v=Josjt_awx08).
- Scalariform features a comprehensive CST, but unfortunately doesn't have an API to transform those trees - it only can prettyprint them.

This is the situation that we want to remedy with scala.meta. We can already parse code and prettyprint parsed trees without losing formatting, and now we want to provide facilities to perform code transformations with full control over formatting.
## Problem statement

We would like to come up with such an API and the accompanying internal infrastructure that will:
1. Allow users to ignore the matters of formatting when they don't care. For example, macro writers are unlikely to be interested in how macro expansions look like, so they shouldn't pay any complexity tax.
2. Enable users to do everything theoretically possible when they do care. If an author of a macro annotation wants to attach a documentation comment to synthetic members, they should be able to do so. If an author of a code formatter wants to apply a certain indentation/spacing style consistently to the entire codebase, then should be able to.
## Goal 1: Never lose formatting upon unrelated changes

```
scala> "{ /* hello */ def world = 42; def foo(bar: Int) = ??? }".parse[Term].get
res0: scala.meta.Term = { /* hello */ def world = 42; def foo(bar: Int) = ??? }

scala> res0.transform { case q"bar" => q"baz" }
res1: scala.meta.Tree =
{
  def world = 42
  def foo(baz: Int) = ???
}
```

The example above highlights undesired behavior. Even though we've transformed a parameter of an unrelated method, that destroyed formatting of other trees - swallowing the comment belonging to a different method and reformatting/reindenting the entire block.
## Goal 2: Expose facilities to perform manual formatting

```
scala> "foo // bar".parse[Term].get
res0: scala.meta.Term = foo // bar

scala> q"foo // bar"
res1: meta.Term.Name = foo

scala> Term.Name("foo") // how do I even attach comments here?
res2: scala.meta.Term.Name = foo
```

In the example above, res0 results from parsing a formatted input. scala.meta remembers all details of formatting for such trees, as can be seen from the printout. res1 is created by a quasiquote that, as currently implemented, only remembers semantically significant syntactic details (see #159). res2 is created manually, and manual AST creation doesn't even have the option to specify formatting details.
## Related work: Clang

The Clang platform is a popular front-end for C/C++ with more than a decade-long history. It also exposes public metaprogramming APIs, providing a widely-used foundation for code analyses and refactorings. Here's a more or less recent blog post that provides an example of using Clang to automatically rewrite code: http://eli.thegreenplace.net/2014/07/29/ast-matchers-and-clang-refactoring-tools/.

``` c
int main(int argc, const char **argv) {
  CommonOptionsParser op(argc, argv, ToolingSampleCategory);
  RefactoringTool Tool(op.getCompilations(), op.getSourcePathList());

  // Set up AST matcher callbacks.
  IfStmtHandler HandlerForIf(&Tool.getReplacements());

  MatchFinder Finder;
  Finder.addMatcher(ifStmt().bind("ifStmt"), &HandlerForIf);

  // Run the tool and collect a list of replacements. We could call
  // runAndSave, which would destructively overwrite the files with
  // their new contents. However, for demonstration purposes it's
  // interesting to show the replacements.
  if (int Result = Tool.run(newFrontendActionFactory(&Finder).get())) {
    return Result;
  }

  llvm::outs() << "Replacements collected by the tool:\n";
  for (auto &r : Tool.getReplacements()) {
    llvm::outs() << r.toString() << "\n";
  }

  return 0;
}

class IfStmtHandler : public MatchFinder::MatchCallback {
public:
  IfStmtHandler(Replacements *Replace) : Replace(Replace) {}

  virtual void run(const MatchFinder::MatchResult &Result) {
    // The matched 'if' statement was bound to 'ifStmt'.
    if (const IfStmt *IfS =
          Result.Nodes.getNodeAs<clang::IfStmt>("ifStmt")) {
      const Stmt *Then = IfS->getThen();
      Replacement Rep(*(Result.SourceManager), Then->getLocStart(), 0,
                      "// the 'if' part\n");
      Replace->insert(Rep);

      if (const Stmt *Else = IfS->getElse()) {
        Replacement Rep(*(Result.SourceManager), Else->getLocStart(), 0,
                        "// the 'else' part\n");
        Replace->insert(Rep);
      }
    }
  }

private:
  Replacements *Replace;
};
```

In this example, we can see an analogue of our Traverser, which looks for if statements and then adds comments to their structural parts. Goal 1 is achieved by, I believe, the framework being able to keep track of diffs instead of prettyprinting the entire modified source. Goal 2 is achieved by providing a low-level string-based API that doesn't involve any ASTs.
## Related work: Roslyn

Roslyn is a new compiler for C# and Visual Basic .NET developed specifically with the goal of having a publicly usable and useful metaprogramming API. As far as I understand, an entire ecosystem of Visual Studio-based code analyses/quickfixes is based on Roslyn. The example below originates from https://msdn.microsoft.com/en-us/magazine/dn904670.aspx.

``` csharp
[ExportCodeFixProvider(LanguageNames.CSharp, Name = nameof(RegexAnalyzerCodeFixProvider)), Shared]
public class RegexAnalyzerCodeFixProvider : CodeFixProvider
{
  ...

  public sealed override async Task RegisterCodeFixesAsync(CodeFixContext context)
  {
    var root = 
      await context.Document.GetSyntaxRootAsync(context.CancellationToken)
      .ConfigureAwait(false);

    var diagnostic = context.Diagnostics.First();
    var diagnosticSpan = diagnostic.Location.SourceSpan;

    // Find the invocation expression identified by the diagnostic.
    var invocationExpr =    
      root.FindToken(diagnosticSpan.Start).Parent.AncestorsAndSelf()
      .OfType<InvocationExpressionSyntax>().First();

    // Register a code action that will invoke the fix.
    context.RegisterCodeFix(
      CodeAction.Create(title, c => 
      FixRegexAsync(context.Document, invocationExpr, c), equivalenceKey: title), diagnostic);
  }

  private async Task<Document> FixRegexAsync(Document document, 
    InvocationExpressionSyntax invocationExpr, 
    CancellationToken cancellationToken)
  {
    var semanticModel = 
      await document.GetSemanticModelAsync(cancellationToken);

    var memberAccessExpr = 
      invocationExpr.Expression as MemberAccessExpressionSyntax;
    var memberSymbol = 
      semanticModel.GetSymbolInfo(memberAccessExpr).Symbol as IMethodSymbol;
    var argumentList = invocationExpr.ArgumentList as ArgumentListSyntax;
    var regexLiteral = 
      argumentList.Arguments[1].Expression as LiteralExpressionSyntax;
    var regexOpt = semanticModel.GetConstantValue(regexLiteral);
    var regex = regexOpt.Value as string;

    var newLiteral = SyntaxFactory.ParseExpression("\"valid regex\"")
      .WithLeadingTrivia(regexLiteral.GetLeadingTrivia())
      .WithTrailingTrivia(regexLiteral.GetTrailingTrivia())
      .WithAdditionalAnnotations(Formatter.Annotation);
    var root = await document.GetSyntaxRootAsync();
    var newRoot = root.ReplaceNode(regexLiteral, newLiteral);

    var newDocument = document.WithSyntaxRoot(newRoot);

    return newDocument;
  }
}
```

Unlike Clang, Roslyn is able to express formatting-aware code rewritings using their tree-based APIs. Goal 1 is achieved by Roslyn trees actually being CSTs, capturing and preserving every little token in their trees (read more in the blog post linked above or in #226). 

![Roslyn CST](https://i-msdn.sec.s-msft.com/dynimg/IC776862.png)

Goal 2 is achieved by providing an API to go ahead and extract/specify every little token from/in existing/new syntax trees.
## State of the art (scala.meta 0.1.0-RC5)

Scala.meta 0.1 gets rid of all the cruft accumulated over the years and keeps features that our users found essential. Therefore, its functionality is both similar and different to what's there in 0.0.x. Here's a quick overview.

Our trees express all semantically important syntactic information, i.e. we have dedicated trees for e.g. for loops, but not for comments. Additionally, all trivia, i.e. semantically insignificant information, is captured in tokens, and that makes our data structures comprehensive. This was the case for 0.0.x and is still the case for 0.1.0-RCx.

```
scala> "foo // bar".parse[Term].get
res0: scala.meta.Term = foo // bar

scala> res0.structure
res1: String = Term.Name("foo")

scala> res0.tokens
res2: scala.meta.tokens.Tokens = Tokens(foo,  , // bar)
```

In comparison with Roslyn, scala.meta tokens aren't part of syntax trees - they are standalone data structures that get associated with syntax trees during parsing. Scala.meta is designed like that to simplify AST manipulations for cases when tokens don't matter, e.g. for writing macros. This makes scala.meta trees ASTs, not CSTs like in Roslyn.

Unlike 0.0.x, scala.meta 0.1.0-RC5 can achieve neither goal 1, nor goal 2, and this issue is about teaching it do so. Below you can find an overview of what's been done before, as well as some of my thoughts on the matter.
## Previous attempts

A) In 2014, @densh and I were thinking about ways to improve scala.reflect's idioms of linking trees to original sources. In scala.reflect, the only way of doing that is through setPos, which in the presence of desugarings and trivia-ignoring parsing is very limited. We were considering not only the obvious renouncement of desugarings, but also creating something called Tree.origin, which would capture not just the full extent of a parsed tree, but also the original tree for a transformed tree. Then we'd be able to use the position of the original tree for error reporting, formatting, etc. This didn't work well, though, because the framework can't know whether a transformed tree is supposed to inherit original trivia or not. So we need manual control.

B) In 0.0.x, it was possible to not only read tokens via the public API, but to also write them via Tree.withTokens. This effectively allowed users to specify arbitrary formatting for ASTs. Unfortunately, this API was very low-level and easy to misuse (one had to manually ensure that new Tree.tokens is coherent with tokens of all child ASTs), so I removed this functionality in 0.1.0-RCx.

C) In his semester project (https://infoscience.epfl.ch/record/218350), @mdemarne explored using the now defunct Tree.withTokens API to make tree transformations formatting-aware. See chapter 4 of the linked technical report for more information. @mdemarne implemented his technique in #141, moving the state of the art ahead, achieving goal 1 for some use cases (see #149 for details). However, now that Tree.withTokens is gone, we can't directly use Mathieu's results.
## Current thoughts

In Clang, the state of the art seems to be limited to [the IndentNewLines parameter](http://clang.llvm.org/doxygen/classclang_1_1Rewriter.html#a5fd6f665d719a8f2dbd6a6e6b5e1436b), if I understand everything correctly. In Roslyn, everything seems to have to be done manually with a little help from [elastic trivia](https://social.msdn.microsoft.com/Forums/vstudio/en-US/22937f3d-0945-436e-b516-635022acbba5/what-is-elastic-trivia?forum=roslyn). Unfortunately, I don't have either Clang or Roslyn set up at the moment, so I may be overlooking something, but I'm fairly confident that this accurately captures the big picture.

I think that in the light of related work, we shouldn't push for a magic solution that somehow detects formatting of either the tree we're inserting something into or the tree that we're inserting, and then makes things look nice automatically.

Instead, I propose we achieve goals 1 & 2 in a simplest possible way, remaining as dumb as possible, and then only afterwards think of some magic:
1. Change `Transformer` and the `Tree.transform` method currently based on Transformer to keep track of trees that aren't explicitly rewritten by the user, i.e. those that fall into `super.transform(tree)` in a custom Transformer or those that aren't present in the pattern match in `tree.transform { case ... }`. If a child (or a parent) of such a tree is modified, then it'll be transitively copied by the framework. We want the resulting copy to retain as much of the original formatting as possible.
   
   In order to do that, one can add `@adt.leaf class Origin.Transformed(tree: Tree) extends Origin` to [Origin.scala](https://github.com/scalameta/scalameta/blob/b738e38a40f2ac57bfe89a8fb3c5f1a802c1b332/scalameta/trees/src/main/scala/scala/meta/internal/ast/Origin.scala) and then change the [@transformer codegen macro](https://github.com/scalameta/scalameta/blob/05c0a9cc047723e3bf9381bce8c1fa38349754d2/scalameta/common/src/main/scala/scala/meta/internal/transversers/transformer.scala#L21) to make use of it.
2. Change `TreeSyntax`, the current AST prettyprinter, to take tracked originals into account. Such trees should be prettyprinted differently, retaining all original formatting except for modified parts. What exactly this means should be figured out experimentally.
   
   A starting point for this can be the following addition to the current prettyprinting algorithm in scala.meta (of course, this sketch will most likely need to be refined):
   - If a tree is marked as `Origin.Transformed`, then obtain its `original` by recursively going through origin.tree in Origin.Transformed until we reach Origin.Parsed. If we haven't reached Origin.Parsed (which means that the tree is synthetic), then bail and proceed with prettyprinting as usual.
   - Figure out tree's children that have been modified (by comparing `tree.field` with `original.field` for all fields - just comparing Tree.children is not enough, because we might've added new children). 
   - For all the modified children, figure out the affected range positions. Roslyn's heuristic or a variation thereof (described in #226) may work. Cut out those positions from `original.syntax`.
   - Prettyprint modified children and insert the results into the cut holes.
3. Introduce an API to manually format a tree. This should be considered carefully, because the obvious Tree.withTokens not only didn't work well, but also confused us for quite a while. Some possibilities that come to mind:
   - Specifying prefixes/suffixes in Roslyn's style of `WithLeadingTrivia/WithTrailingTrivia`. This covers indentation and most comments. Also should be very easy to integrate into `TreeSyntax`.
   - Overriding the entire prettyprint with a template of some kind. We may want to use quasiquotes for this purpose, but for that I'll have to fix #159 first. Token quasiquotes may also be useful, but before using them for this (or any) purpose we need to consider issues described in #355. The template should take possible parenthesization issues into account (check out calls to `m(...)` in TreeSyntax to see what I mean).

**Comment by olafurpg** [comment]
I think it's worth to mention Google's approach in their paper [Large-scale automated refactoring using ClangMR](http://research.google.com/pubs/pub41342.html). Key quote:

> . A final pass with ClangFormat, a Clang-based formatting tool [10], ensures the
resulting code meets formatting and style guide recommendations.

My interpretation is that they don't try to preserve the original formatting.

**Comment by xeno-by** [comment]
Unfortunately, we didn't have much progress implementing the proposed scheme. Realistically speaking, we don't know how to proceed here in order to obtain good results in a reasonable timeframe. Since this functionality is not on our roadmap, I'll be closing this issue.
