### ISSUE TITLE
better API for the Tokens collection

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#385]
0.1.0-RC6 removes our overly complicated attempts at having methods on Tokens, such as filter, slice, some maps, flatMaps, etc return Tokens. At the moment, Tokens simply subclasses Seq[Token] and that's it - very simple to understand and maintain.

However, this simplification makes the life of Tokens users a bit more complicated. In order to slice tokens, one now has to do `Tokens(tokens.slice(...): _*)` instead of just `tokens.slice(...)`. In order to filter tokens, you need to do the same. And so on.

We should assess how big of a deal this is (the assessment may change depending on what API to specify custom formatting we choose in #379), and then improve the API if necessary.

Here's the source code for the reference: https://github.com/scalameta/scalameta/blob/master/scalameta/tokens/src/main/scala/scala/meta/tokens/Tokens.scala.

**Comment by xeno-by** [comment]
In https://github.com/xeno-by/scalameta/commit/f065e3e4fc7287078ffc52c9b977940ce6607bc2, I tried to replace `class Tokens` with `type Tokens = Seq[Token]`. There were some problems with implicits, because type aliases can't have companions, but I could overcome them. What was a real showstopper, though, is the impossibility to define custom toString. It was a fun exercise though.

**Comment by ShaneDelmore** [comment]
I have addressed a few of these in https://github.com/scalameta/scalameta/pull/532.

I would be happy to add more of them.  Is there a desired list anywhere?

**Comment by olafurpg** [comment]
I've got a ton of ideas that I summarised in #537, I'd be interested to hear what you think about that @ShaneDelmore. I am not aware of other missing enrichment operators on Tokens, #532 made a big improvement on that side. I think we are safe to close this issue.
