### ISSUE TITLE
reconsider the split into multiple projects

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#388]
Splitting scala.meta into multiple projects was very useful to clearly realize what depends on what and to prevent conflation of concerns in the future. However, some modules are really arbitrary (see common) or really small (see dialects and inputs) and people are consistently scared by https://github.com/scalameta/scalameta/blob/4d997ac2b969e74d8746a2387b76ad49fe8b1fd1/docs/modules.svg, so there are shortcomings as well.

One approach to getting the best of both worlds would be merging everything back into a single project (except for macro implementations needed to compile scala.meta) and then using @lihaoyi's acyclic to ensure lack of cyclic dependencies where they are undesired. Another approach would be to use sbt-assembly to generate and publish a single artifact to avoid scaring people away.

**Comment by lihaoyi** [comment]
seems like an easier solution would be to have a scalameta-all artifact people can depend on without thinking. Then they get something working out of the box and can tweak dependencies later if they wish.

It would be like 1 line of sbt config to implement too :p

**Comment by Atry** [comment]
IMHO, It's OK to separate to small libraries. For example, I split Binding.scala into [five libraries](https://static.javadoc.io/com.thoughtworks.binding/unidoc_2.11/10.0.1/index.html#com.thoughtworks.binding.package), one file per library.

The real problem is the lack of [unidoc].

**Comment by xeno-by** [comment]
I think that by now the split between projects has proven to be a good idea. It establishes conceptual boundaries and avoid the problem of everything depending on everything. While it would be interesting to theorize about better ways of writing software, we have stuff to ship and world to take over. I'm closing this one.
