### ISSUE TITLE
Code expressions in Scaladoc parsing

### ISSUE THREAD

**Issue by charpov** [scalameta/scalameta#3908]
The Scaladoc parser expects code expressions to be formatted as `{{{x + y}}}`. There are two problems with that:

- The current Scaladoc generates a _code block_ from it, even when `{{{` is not followed by a newline.
- The Scaladoc documentation suggests _not_ to use wikidoc in new projects but to switch to markdown instead.

So, `{{{x + y}}}` should really be `` `x + y` `` in new code, but this is _not_ parsed as a `CodeExpr` token by Scalameta. This causes problems in tools that rely on Scalameta, such as Scalafmt (see <https://github.com/scalameta/scalafmt/issues/4147>).

I think `` `x + y` `` should be parsed as a new `MdCodeExpr` that extends `TextPart` like `CodeExpr` (there is already `MdCodeBlock` as an alternate to `CodeBlock`).

**Comment by kitbellew** [comment]
> * The current Scaladoc generates a _code block_ from it, even when `{{{` is not followed by a newline.

can you please provide an example of this behaviour? we have a test that seems to confirm this part should work:
https://github.com/scalameta/scalameta/blob/0281ed2790f9260c59b2accc65d45c4204b200f0/tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala#L208

**Comment by charpov** [comment]
Here is my test case.

`build.sbt`:

```scala
ThisBuild / scalaVersion := "3.5.0"
ThisBuild / crossPaths   := false
```

`TestDoc.scala`:

```scala
/** Inline code is like this: {{{x + y}}} and not like this: `x + y`. */
class TestDoc
```

Opening `target/api/index.html` with Safari after running `sbt doc` produces something like:

<img width="398" alt="Screenshot 2024-08-25 at 7 21 57 PM" src="https://github.com/user-attachments/assets/34c6e66f-1530-4ae1-ab42-6f9d69a26802">

**Comment by kitbellew** [comment]
hmm :) what does `sbt doc` have to do with this?

does scalafmt format
```
/** Inline code is like this: {{{x + y}}} and not like this: `x + y`. */
class TestDoc
```
as
```
/** Inline code is like this:
  * {{{
  *     x + y
  * }}}
  * and not like this: `x + y`. */
class TestDoc
```
or does scalameta produce a `CodeBlock` instead of `CodeExpr`?

if not, this bug should be moved to wherever `sbt doc` is maintained.

**Comment by charpov** [comment]
I didn't say that _Scalafmt_ produces a code block but that _Scaladoc_ does (and I use `sbt` to run Scaladoc). I could raise the issue with Scaladoc, but since their documentation says _not_ to use the `{{{code}}}` syntax anymore, they may not be eager to fix it. Furthermore, I don't really care if they do because I already use `` `code` `` as they suggest.

My problem is that Scalafmt may insert a newline inside `` `x + y` `` because Scalameta parses it as separate tokens. Once <https://github.com/scalameta/scalameta/pull/3930> is merged, `` `x + y` `` will be its own token, and it should be easy to fix Scalafmt.

**Comment by kitbellew** [comment]
> I didn't say that _Scalafmt_ produces a code block but that _Scaladoc_ does (and I use `sbt` to run Scaladoc). I could raise the issue with Scaladoc, but since their documentation says _not_ to use the `{{{code}}}` syntax anymore, they may not be eager to fix it. Furthermore, I don't really care if they do because I already use `` `code` `` as they suggest.
> 
> My problem is that Scalafmt may insert a newline inside `` `x + y` `` because Scalameta parses it as separate tokens. Once #3930 is merged, `` `x + y` `` will be its own token, and it should be easy to fix Scalafmt.

Where exactly does scaladoc say not to use `{{{`? the only resource i am aware of is: https://docs.scala-lang.org/overviews/scaladoc/for-library-authors.html

**Comment by charpov** [comment]
The quote I use in <https://github.com/scalameta/scalafmt/issues/4147> comes from <https://docs.scala-lang.org/scala3/guides/scaladoc/docstrings.html>. (Scaladoc documentation is a mess, which is somewhat ironic.)
