### ISSUE TITLE
semanticdb-scalac plugin causes scalac to ignore -Wconf options

### ISSUE THREAD

**Issue by robby-phd** [scalameta/scalameta#3967]
As the title suggests, `-Wconf` is not honored when using the semanticdb-scalac plugin.

Here is one example to produce such behavior:

```sh
git clone https://github.com/sireum/kekinian
cd kekinian
git checkout 4a9617a
bin/init.sh
cd ..
git clone --depth=1 https://github.com/sireum/runtime
cd runtime
../kekinian/bin/sireum proyek compile --meta --slice library-shared .
#cat out/runtime/modules/library-shared/scalac-args-main                    # displays all scalac options/arguments
```

As can be observed in the `scalac-args-main` file, scalac is provided with `-Wconf:cat=scala3-migration&msg=legacy-binding^msg=symbol^msg=outer:s`, but warnings that should have been filtered were displayed.

If the semanticdb-scalac plugin is removed from `scalac-args-main`, then running the following in `runtime`:

```sh
../kekinian/bin/scala/bin/scalac @out/runtime/modules/library-shared/scalac-args-main
```

there is no warning generated from scalac.

This behavior disallows the use of `-Xfatal-warnings` in such cases like the above.

**Comment by tgodzik** [comment]
Thanks for reporting! Was this connected to the other issue you reported (first in Metals)? I haven't seen this problem and we do use that setting in metals https://github.com/scalameta/metals/blob/main/build.sbt#L152

**Comment by robby-phd** [comment]
Sorry, it's a -Wconf misconfiguration, and my scalac-plugin filtered those, but didn't work when the semanticdb plugin was added. Closing this as it's user error.
