### ISSUE TITLE
Support capture checking related syntax

### ISSUE THREAD

**Issue by KacperFKorban** [scalameta/scalameta#3996]
Scalameta should support syntax related to capture checking.
These changes include:
- syntax for indicating captures `tpe^` and `tpe^{...}`
- syntax for capturing functions `tpe ->^{...} tpe`

Links:
- implementation PR: https://github.com/scala/scala3/pull/15877/files#diff-7b0af84ac42fe737a4f3700b2ce9838c02f7bc1f7d4d266f44b07c6b33199abb

**Comment by kitbellew** [comment]
@KacperFKorban this is a complex feature and requires explicit documentation, including changes to EBNF.

so far, the only document I have found is this: https://www.scala-lang.org/api/3.3.3/docs/docs/reference/experimental/cc.html

this document makes no mention of EBNF changes -- and does not show in its examples your `^{....}`. so, at this point its under-documented to be implemented, at least not without deprecations or binary-breaking changes soon after.

**Comment by kitbellew** [comment]
@KacperFKorban @tgodzik are pure functions possible without capture checking? does it make sense to add separate `Dialect` flags, one for pure functions and another for capture checking?

one scenario that i thought was described somewhere was that perhaps `->` will be supported in scala2 but captures will be done via an annotation...

**Comment by KacperFKorban** [comment]
@kitbellew Yes, pure functions are possible without capture checking. They are enabled by a separate language feature/import. https://github.com/scala/scala3/blob/d78516aa97b986024681cb59ebf7817c205742bb/library/src/scala/runtime/stdLibPatches/language.scala#L78
