### ISSUE TITLE
Support named type arguments syntax

### ISSUE THREAD

**Issue by KacperFKorban** [scalameta/scalameta#3998]
Scalameta should support named type arguments syntax.
This syntax allows for specifying type arguments by name in a type parameter clause.

Example:
```scala
def construct[Elem, Coll[_]](xs: Elem*): Coll[Elem] = ???

val xs1 = construct[Coll = List, Elem = Int](1, 2, 3)
val xs2 = construct[Coll = List](1, 2, 3)
```

Syntax changes:
```
SimpleExpr1       ::=  ...
                    |  SimpleExpr (TypeArgs | NamedTypeArgs)
NamedTypeArgs     ::=  ‘[’ NamedTypeArg {‘,’ NamedTypeArg} ‘]’
NamedTypeArg      ::=  id ‘=’ Type
```

Links:
- docs: https://dotty.epfl.ch/docs/reference/experimental/named-typeargs.html#
- more docs: https://dotty.epfl.ch/docs/reference/experimental/named-typeargs-spec.html

**Comment by soronpo** [comment]
Another example:
```scala
val y = summon[Tuple2[Int, String] <:< (x: Int, y: String)]
```
Currently gives ``` `)` expected but `:` found ``` error

**Comment by soronpo** [comment]
It should be mentioned here that Named Tuples are officially part of Scala as of version 3.6.x

**Comment by soronpo** [comment]
Oops, sorry I thought this was about named tuples. Should read carefully at 3AM.

**Comment by KacperFKorban** [comment]
@soronpo There was a PR regarding named tuples recently. You can check the tests to see if anything is missing. https://github.com/scalameta/scalameta/pull/4001
