### ISSUE TITLE
support Mac OS and Windows in our CI

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#400]
During the big code/infrastructure cleanup in April, I removed integration with Travis due to it being very unreliable in the past. Since then, we had several really nasty breakages that could've been caught by a CI service. It is of huge importance to reintroduce Travis support again.

**Comment by fommil** [comment]
You're welcome to use the ensime drone infrastructure. Our machines are more powerful.

**Comment by xeno-by** [comment]
@fommil How does this work? Where can I learn more?

**Comment by fommil** [comment]
github.com/drone/drone also just look at any .drone.yml file we have. I'll need to enable the project.

**Comment by xeno-by** [comment]
Thanks for your offer! Would you advise any comparison between drone and travis? Stuff that I just googled looks outdated. What was your personal experience with drone vs travis?

**Comment by fommil** [comment]
not sure, the biggest advantages of drone are: a) use your own hardware (better RAM and CPU) b) use docker to define the build environment.

**Comment by fommil** [comment]
you're an admin on fommil.com, go to http://fommil.com/scalameta/scalameta to enable and then create a .drone.yml (use an ensime one as a template).

**Comment by xeno-by** [comment]
I have a pull request that enables pull request and push validation via @fommil's Drone instance (https://github.com/scalameta/scalameta/pull/402). Github is currently screwed up - new commits don't show up, triggers are not running - so I'll merge it later when everything is back to normal.

**Comment by xeno-by** [comment]
An important point brought up by @fommil in a private discussion is to also enable Travis for OS X and Appveyor for Windows to make sure that we support all flavors of line endings. This is not that urgent as having some CI set up, so I'm pushing this part of the issue back for later.

**Comment by xeno-by** [comment]
We already have Linux builds running in Travis and Windows builds in Appveyor. It could theoretically be useful to also have OSX, but all core developers are working on OSX, so I'm not sure what exactly it will buy us in the practical sense.
