### ISSUE TITLE
implement CLA validation in our CI build

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#403]
At the moment, we have a standalone Heroku job that for every pull request checks whether the submitter has signed the Scala CLA. It was a pain to set up and is a pain to maintain. 

Instead, at some point I'd like to make CLA validation part of our Drone build. First, this avoids having multiple codebases devoted to PR validation. Second, it solves the problem of dealing with GitHub authentication that's necessary to post "please sign the CLA" comments. In the new model, we just fail the build with the same message without needing to ever post these spammy comments.

**Comment by fommil** [comment]
https://cla-assistant.io/

**Comment by xeno-by** [comment]
@adriaanm Would it be possible to integrate Lightbend's CLA checking app (http://www.lightbend.com/contribute/cla/scala/check/xeno-by) with CLA Assistant? If yes, I'd be very much in favor of using it in scala.meta.

**Comment by fommil** [comment]
hmm, please don't use Lightbend's unfair CLA though. It enforces the contributor to sign under an unpalatable legal jurisdiction and is the reason why I do not contribute to Lightbend projects. Thankfully, the Scala CLA is different and is really Apache 2.0 in disguise, although it is unfair that scala is then licensed back to the public under a simplified BSD style license.

**Comment by xeno-by** [comment]
Our CLA is Scala CLA. However, as far as I understand, the standard way to sign the Scala CLA is via Lightbend's website: https://www.lightbend.com/contribute/cla/scala, so we need to be compatible with that.

**Comment by xeno-by** [comment]
Integrated CLA checking into our drone build: https://github.com/scalameta/scalameta/pull/408. This fixes the immediate need that we have for 1.0. Still hoping for @adriaanm's answer to replace my ad-hoc solution with the CLA Assistant service.

**Comment by adriaanm** [comment]
I'll try to help out once M5 is out.

**Comment by xeno-by** [comment]
@adriaanm Ping

**Comment by xeno-by** [comment]
The adhoc CLA validator has been working well enough, so I'm gonna close this issue.
