### ISSUE TITLE
infix with `Unit` literal

### ISSUE THREAD

**Issue by xuwei-k** [scalameta/scalameta#4034]
### reproduce steps

`build.sbt`

```scala
libraryDependencies += "org.scalameta" %% "scalameta" % "4.11.0"

scalaVersion := "2.13.15"
```

`Main.scala`

```scala
import scala.meta._

object Main {
  def main(args: Array[String]): Unit = {
    val src = Input.String("""a b ()""")
    val p = implicitly[parsers.Parse[Term]]
    println(p.apply(src, dialects.Scala3).get.structure)
  }
}
```

#### actual:

```scala
Term.ApplyInfix(
  Term.Name("a"),
  Term.Name("b"),
  Type.ArgClause(Nil),
  Term.ArgClause(Nil)
)
```

#### expect if dialects is **2.13 or higher**:

```scala
Term.ApplyInfix(
  Term.Name("a"),
  Term.Name("b"),
  Type.ArgClause(Nil),
  Term.ArgClause(List(Lit.Unit()), None)
)
```

#### Scala 2.13.x or 3.x

```
Welcome to Scala 2.13.15 (OpenJDK 64-Bit Server VM, Java 21.0.5).
Type in expressions for evaluation. Or try :help.

scala> object a { def b(x: Any): Unit = () }
object a

scala> a b ()

scala> object a { def b(): Unit = () }
object a

scala> a b ()
         ^
       error: can't supply unit value with infix notation because nullary method b: (): Unit takes no arguments; use dotted invocation instead: a.b()
```

#### Scala 2.12

```
Welcome to Scala 2.12.20 (OpenJDK 64-Bit Server VM, Java 21.0.5).
Type in expressions for evaluation. Or try :help.

scala> object a { def b(x: Any): Unit = () }
defined object a

scala> a b ()
<console>:13: warning: Adaptation of argument list by inserting () is deprecated: leaky (Object-receiving) target makes this especially dangerous.
        signature: a.b(x: Any): Unit
  given arguments: <none>
 after adaptation: a.b((): Unit)
       a b ()
         ^

scala> object a { def b(): Unit = () }
defined object a

scala> a b ()
```

**Comment by kitbellew** [comment]
> #### Scala 2.13.x or 3.x
> ```
> Welcome to Scala 2.13.15 (OpenJDK 64-Bit Server VM, Java 21.0.5).
> Type in expressions for evaluation. Or try :help.
> 
> scala> object a { def b(x: Any): Unit = () }
> object a
> 
> scala> a b ()
> ```

So `a b ()` is interpreted as `a.b(())`?

> ```
> scala> object a { def b(): Unit = () }
> object a
> 
> scala> a b ()
>          ^
>        error: can't supply unit value with infix notation because nullary method b: (): Unit takes no arguments; use dotted invocation instead: a.b()
> ```

Does that mean that in this last case the user should have specified `a b` instead? I thought in recent versions of scala there's a distinction between `def b = ...` and `def b() = ...`, and parens are mandatory if used in definition.

> #### Scala 2.12
> ```
> Welcome to Scala 2.12.20 (OpenJDK 64-Bit Server VM, Java 21.0.5).
> Type in expressions for evaluation. Or try :help.
> 
> scala> object a { def b(x: Any): Unit = () }
> defined object a
> 
> scala> a b ()
> <console>:13: warning: Adaptation of argument list by inserting () is deprecated: leaky (Object-receiving) target makes this especially dangerous.
>         signature: a.b(x: Any): Unit
>   given arguments: <none>
>  after adaptation: a.b((): Unit)
>        a b ()
>          ^
> 
> scala> object a { def b(): Unit = () }
> defined object a
> 
> scala> a b ()
> ```

And for 2.12, there's no way to tell if `()` is the parameter value or the empty parameter clause? i wonder how this affects semanticdb...

**Comment by kitbellew** [comment]
@xuwei-k is the same applicable to patterns? as in,
```
foo match
  case a :: () =>
```
