### ISSUE TITLE
consider changing Term.Apply to take Seq[Seq[Term.Arg]]

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#405]
Otherwise, we're going to need unsatisfying workarounds like `SyntacticXXX` in scala.reflect. E.g. see #277. I find this prospect suboptimal.

This is probably not 1.0 material, because the fallout may be too strong at the moment.

**Comment by xeno-by** [comment]
@olafurpg @johannegger Could you comment on this please?

**Comment by olafurpg** [comment]
My preference would be to have Term.Apply take a Seq[ArgList] and an ArgList would have a Seq[Term.Arg].

Why? In scalafmt I often have an opening `(` owned by a Term.Apply. The problem is that it gets quite tricky to find out which argument lists "owns" that `(`. If there was something like an ArgList tree node then I could trivially find the owner of `(` and query stuff like how many arguments are in that list.

**Comment by jvican** [comment]
I agree with @olafurpg, his proposal is neat. But introducing the proposed change breaks consistency of Meta tree nodes. The convention of using `Seq[Seq[Term.Arg]]` for representing parameter lists is very present in the Meta trees, as well as Scalac and Dotty. Doing so could lead to confusion, so there's probably a tradeoff here.

**Comment by olafurpg** [comment]
Example problem I've struggled with: given a `Defn.Def`, find the closing parenthesis (if one exists) of the last param list.

If we attach a tree node to each param lists, this would be trivial but currently I to do all sorts of collections gymnastics to cover a bunch of corner cases. However, I agree with @jvican that changing the tree structure may not be the best choice here. A `contrib` module with utilities to do stuff like the problem above might be enough to satisfy me.

**Comment by xeno-by** [comment]
We're on the verge of releasing 2.0, and afterwards we plan to start being really conservative about breaking changes. The matter discussed in the ticket can probably be improved, but there's not enough interest to justify potential breakages.

**Comment by kitbellew** [comment]
@olafurpg @xeno-by wanted to revisit this decision, especially given #2820.

**Comment by olafurpg** [comment]
@kitbellew I'm not active with Scalameta these days, but I recommend avoiding all breaking changes. Breaking changes have a huge hidden cost and in the case of the Scalameta AST, it's often possible to avoid breaking changes by introducing new toplevel AST type. For example, there could be a `Defn.ClauseDef` that encodes the new syntax idiomatically. If you really want to parse all defs as clause defs, then you could add an option on the dialect to emit `ClauseDef` for regular/old-style `def`, allowing downstream users to gracefully upgrade to the new syntax when they're ready to do so.

Breaking changes are particularly frustrating when downstream users have to make changes in their code to support the old syntax. It's fine to require downstream users to make changes to handle new syntax.

**Comment by tgodzik** [comment]
> but I recommend avoiding breaking changes at any cost. 

That has been my feeling as well, we had some initial implementation added for clause interleaving, but the idea was that we would either create a 5.x release or rather introduce AST alongside it(I am thinking more of doing that). The syntax is not yet changed, so this is still not needed.
