### ISSUE TITLE
dotty -> scala.meta tree converter

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#434]
This is the sister issue of #148. Read up on the discussion there to understand the background better.

Much like in #148, the plan for this one is to create a desugaring-oblivious tree-to-tree converter without trying to be overly smart. Here's the initial effort on this attempted by @smarter: https://github.com/smarter/scalameta/tree/dotty-dialect.

**Comment by smarter** [comment]
Actually, the initial converter is at https://github.com/smarter/dotty/commits/add/meta-trees, and not the branch you linked.

**Comment by xeno-by** [comment]
Implemented in https://github.com/liufengyun/eden.
