### ISSUE TITLE
Case classes looses the "case" mod

### ISSUE THREAD

**Issue by tabdulradi** [scalameta/scalameta#440]
I noticed case classes are interpreted by Scala meta as normal classes.

Here is my example:
```
@test object Model {
  case class Person(id: String, name: String)
}
```
Where `test` is a simple identity meta function.
```
object test {
  inline def apply()(defn: Any) = meta {
    defn
  }
}
```

While testing this
```
object Test extends App {
  import Model._
  println(new Person("123", "Test").productPrefix)
}
```
I got 
> value productPrefix is not a member of Model.Person

Which means the `case` mod is gone.

**Comment by xeno-by** [comment]
This a problem in how the current prototype of inline annotations is implemented. Please take a look at  https://github.com/scalameta/paradise/issues/8.
