### ISSUE TITLE
show[Structure] should lowercase Literal.{Float,Double,Long}

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#459]
``` scala
@ """ foo(1l, 1L, 1f, 1F, 1d, 1D)""".parse[Stat].get.structure
//obtained
res9: String = """
Term.Apply(Term.Name("foo"), Seq(Lit(1l), Lit(1L), Lit(1f), Lit(1F), Lit(1d), Lit(1D)))
"""
// expected
res9: String = """
Term.Apply(Term.Name("foo"), Seq(Lit(1L), Lit(1L), Lit(1f), Lit(1f), Lit(1d), Lit(1d)))
"""
```

`show[Structure]` can be used to test AST equality, which is really handy. For example:

``` scala
q"val x = 1f".structure == q"val x = 1F".structure
```

`1f` and `1F` represent the same literal so I think they should have the same structure representation.

This would enable me to more confidently support https://github.com/olafurpg/scalafmt/issues/293

A good place to start seems to be here: https://github.com/scalameta/scalameta/blob/ea748842832255851f3dc219617c63aa02525d32/scalameta/trees/src/main/scala/scala/meta/internal/prettyprinters/TreeStructure.scala#L59

SyntacticTrees seems to be the place to add tests for `show[Structure]`: https://github.com/scalameta/scalameta/blob/ea748842832255851f3dc219617c63aa02525d32/scalameta/scalameta/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

**Comment by xavier-fernandez** [comment]
I started working on this issue, should have it fixed/tested by tomorrow :)

**Comment by xavier-fernandez** [comment]
The commit was merged, so this ticket can be closed :)

**Comment by olafurpg** [comment]
Awesome! Really happy to see the pretty-printer get some love :)

**Comment by xavier-fernandez** [comment]
@olafurpg more to come :)

**Comment by olafurpg** [comment]
You might be interested in https://github.com/scalameta/scalameta/issues/567#issue-195539795 ;)

Those bugs were found with this code here https://github.com/scalameta/scalameta/blob/910cfa67470c5464662db92641f22c1e56d11085/scalameta/testkit/src/test/scala/scala/meta/testkit/ScalametaParserProperties.scala#L26-L35

**Comment by xavier-fernandez** [comment]
@olafurpg Thank you, will take a look for sure :)

**Comment by olafurpg** [comment]
We run those tests on every pr and assert the errors don't increase. You
can see in the ci console output if the number goes down with a fix. You
can also run those tests locally of course.

**Comment by xavier-fernandez** [comment]
Thank you @olafurpg :)
