### ISSUE TITLE
Support Inline as a modifier

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalameta#466]
For scalameta paradise, the ability to generate ```inline def apply(defn: Defn) = meta {}``` blocks is ideal, or even just to use inline by itself. Is it possible to have a trait the adds this modifier to a dialect.

I presume the inline modifier would need to be part of scalameta and exposed as a dialect.

My gut feeling is that I want to write ```@leaf implicit object DottyParadise extends Dotty with Paradise```

This would syntax would be beneficial for future support of other compiler plugins too, such as KindProjector etc.

I'm unsure whether the actual definition of the trait would come from the scalameta/scalameta or scalameta/paradise, but support for extensions to dialects would need to come from scalameta

**Comment by xeno-by** [comment]
That's a good idea. 

We'll probably have to have a separate branch for `inline`-enabled scala.meta, so that this functionality doesn't confuse those who are using meta on older versions of the language. Or maybe we just forgo this ceremony in favor of staying easier to maintain. Needs more thinking.

How urgent would a fix for this be for you?

**Comment by DavidDudson** [comment]
Not urgent at all. If it's blocking me in the future I'll bring it up. For now I'm sure I can live without it. Hopefully the quasiquote trick you mentioned will work (I will have time to look at it tomorrow NZT). Which will make this semi-redundant (although it would still be nice from a static analysis point of view to know whether a method has the inline modifier with ease) I'd say as long as it's ready before scalameta-2.0.0 and around the release of scalameta/paradise 3.0.0 it should be okay. I'm sure people will want to do things like this with a stable release. It would need some decent thought though. I'd rather the problem be documented at least for now.

The important part is that it enables Macro composition. 

For example.... (Rough pseudocode example)

```
@AnnotationComposition
class Case extends StaticAnnotation with ToString with HashCode with Equals with ...
```

Would generate an apply method like...

```
inline def apply(defn: Defn) {
  val a = super[ToString].apply(defn)
  return super[HashCode].apply(a) 
}
```

Although id probably end up using Cats to make macro annotations a semigroup...
needs more thought.
