### ISSUE TITLE
Equality semantics of modifiers are confusing

### ISSUE THREAD

**Issue by cb372** [scalameta/scalameta#467]
For the definition

``` scala
override def toString = "foo"
```

The following case

``` scala
case q"..$mods def $name[..$tparams](...$paramss): $tpe = $expr" if mods.contains(mod"override") => // does not match
```

does not match. If I work around it by pattern matching on the modifier then it does match:

``` scala
def isOverride(mod: Mod) = mod match {
  case mod"override" => true
  case _ => false
}

foo match {
  case q"..$mods def $name[..$tparams](...$paramss): $tpe = $expr" if mods.exists(isOverride) => // matches
}
```

Is this expected behaviour?

I'm using 1.1.0-SNAPSHOT (Wed Aug 17 09:25 UTC).

**Comment by xeno-by** [comment]
Yes, this is expected.

There are multiple ways to define equality on ASTs (structural, structural + trivia, semantic and others), and there's only one opportunity to implement it (equals/hashCode). Therefore, we decided that tree equality should do the dumbest thing ever, i.e. check for reference equality, and expose other kinds of equality in dedicated APIs (pattern matching, prettyprinting, `=:=`, etc).

This reduces the potential for confusion, but it creates problems for functionality that relies on equals/hashCode (e.g. contains and hashmaps). The write-up at https://gist.github.com/xeno-by/9741ce7532cb30368b3753521bbfce4e provides another example of this.

**Comment by cb372** [comment]
I see. So just to confirm, my workaround using pattern matching is actually the recommended way to write this code? Or is there a nice `=:=` like operator that I can use?

**Comment by xeno-by** [comment]
Yes, this is currently the only recommended way. Let's keep the issue open though - later we may want to add a dedicated operator for this.

**Comment by DavidDudson** [comment]
@xeno-by @olafurpg Do we have any thoughts on this yet? Whether a dedicated operator would be useful? It could go into contrib for a start possibly?

**Comment by xeno-by** [comment]
Superseded by https://github.com/scalameta/scalameta/issues/872.
