### ISSUE TITLE
Reject parsing of parameterless classes and case classes

### ISSUE THREAD

**Issue by jvican** [scalameta/scalameta#487]
Scalac:

``` scala
scala> case class A
<console>:1: error: case classes without a parameter list are not allowed;
use either case objects or case classes with an explicit `()' as a parameter list.
case class A
```

Currently, scala meta parses it correctly. I'm not sure if it's convenient to follow 2.11's scalac parser here. IIRC, older scala version parsed parameterless case classes correctly and only emitted warnings. Haven't checked, though.

BTW, the same happens for `implicit class A`, although we probably want to follow scalac's semantics here (currently, scalameta also parses it correctly).

``` scala
scala> implicit class A
<console>:13: error: implicit classes must accept exactly one primary constructor parameter
       implicit class A
```

**Comment by jvican** [comment]
If these are eventually identified as misbehaviours of our parser, I would be happy to fix them.

**Comment by xeno-by** [comment]
This is definitely a bug in our parser. It would be great if you could contribute a fix!

**Comment by jonas** [comment]
DIBS! Will look into a fix for this.

**Comment by jonas** [comment]
This should probably be added to the 1.9.0 milestone.

**Comment by olafurpg** [comment]
Good cathch @jonas
