### ISSUE TITLE
Why isn't Seq[Term.Param.Name] <:Seq[Term.Name]?

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#488]
I'm getting this compiler error
```
[error]  found   : scala.collection.immutable.Seq[scala.meta.Term.Param.Name]
[error]  required: scala.collection.immutable.Seq[scala.meta.Term.Name]
```

Casting Term.Param.Name to Term.Name seems to work. I'm wondering, why is the cast necessary?

**Comment by xeno-by** [comment]
That's because parameters can have anonymous names, and they aren't term names.

**Comment by olafurpg** [comment]
That makes sense. Thanks for the explanation.
