### ISSUE TITLE
Transversers lose precise types

### ISSUE THREAD

**Issue by Dveim** [scalameta/scalameta#490]
Currently all methods in `transversers.Api` return `Tree` as result type:

```
val q"..$mods object $name extends $template" = defn
val newTemplate: Template = template.transform { // found   : scala.meta.Tree
                                                 // required: scala.meta.Template
  case q"..$mods def $name[..$tparams](...$paramss): $tpeopt = $expr" =>
    q"???"

q"..$mods object $name extends $newTemplate // requires Template"
}
```

Possible workaround is to use `asInstanceOf`.

**Comment by xeno-by** [comment]
Improving on the signature of `Tree.transform` would be nice, but noone had an idea how to do that in almost a year. Since this functionality is not on our roadmap, I'll be closing this issue.
