### ISSUE TITLE
Parse literal singleton types in Dotty dialect

### ISSUE THREAD

**Issue by jvican** [scalameta/scalameta#495]
Literal singleton types (aka SIP-23 or 42.type), e.g.

``` scala
val a: SingletonType = SingletonType
```

Description of what singleton types are: https://github.com/scala/scala/pull/5310
Scala meta has the concept of dialect for different Scala syntax (think sbt, scala or dotty). However, support for singleton types is missing.

A good way to start is by modifying the expected identifier to accept integers, as the previous shown example works. However, types starting by number literals like`"val a: 42 = 42".parse[Stat].get` fail.

Have a look at the current impl: https://github.com/scalameta/scalameta/blob/master/scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L935

**Comment by jvican** [comment]
A good place to put the tests is in the DottySuite: https://github.com/scalameta/scalameta/blob/master/scalameta/scalameta/src/test/scala/scala/meta/tests/parsers/DottySuite.scala

**Comment by xavier-fernandez** [comment]
I just started working on this issue.

**Comment by xavier-fernandez** [comment]
Just started to work on this issue :)

**Comment by xavier-fernandez** [comment]
https://github.com/scalameta/scalameta/pull/640

**Comment by xavier-fernandez** [comment]
This ticket can be closed?, the PR #640 was merged :)

**Comment by olafurpg** [comment]
You are right @xavier-fernandez, we can close this issue.
