### ISSUE TITLE
Remove self types for objects in Dotty dialect

### ISSUE THREAD

**Issue by jvican** [scalameta/scalameta#497]
Self types on objects look like:

``` scala
object A { self: A =>
}
```

They are removed in Dotty, although the Dotty dialect still parses it successfully. This syntax should not be supported anymore.

Current implementation: https://github.com/scalameta/scalameta/blob/ea748842832255851f3dc219617c63aa02525d32/scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L3161. A good way to do this would be to pass in an extra boolean parameter to `constBlock` and fail when a `selfInvocation` is correctly parsed.

**Comment by jvican** [comment]
A good place to put the tests is in the DottySuite: https://github.com/scalameta/scalameta/blob/master/scalameta/scalameta/src/test/scala/scala/meta/tests/parsers/DottySuite.scala

**Comment by gosubpl** [comment]
I have started working on this. Will ask for assistance at tomorrow's Spree meetup in Copenhagen.

**Comment by tgodzik** [comment]
Scala 3 is almost released and we have a working dialect.
