### ISSUE TITLE
quasiquote specific to making Stats

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalameta#499]
This is a simple request.

Using paradise, I find the need add `Stat`'s to classes/def's etc. a lot. 

There is currently no way to generate stats via quasi quotes.

The closest we get is meta.Tree. which then requires a cast.

Using parse rather then con

### Current behaviour

```scala
q"import scala.meta._".asInstanceOf[Stat]
"import scala.meta._".parse[Stat].get
```

### Wanted behaviour

```scala
stat"import scala.meta._"
```

I suggest the same behaviour for `Term` too.

### Context
https://github.com/DavidDudson/Elysium/blob/master/test/src/main/scala/nz/daved/elysium/test/MacroStateStore.scala

### Current spec
https://github.com/scalameta/scalameta/blob/master/notes/quasiquotes.md#statements-metastat

**Comment by xeno-by** [comment]
Isn't `Import` already a `Stat`?

```
scala> q"import scala.meta._"
res0: scala.meta.Import = import scala.meta._

scala> res0: Stat
res1: scala.meta.Stat = import scala.meta._
```

**Comment by DavidDudson** [comment]
Interestingly enough. Its an intellij bug
<img width="462" alt="screen shot 2016-10-03 at 8 00 41 am" src="https://cloud.githubusercontent.com/assets/2680733/19022962/ac36e63a-893f-11e6-8249-07fe61c55bc5.png">
<img width="363" alt="screen shot 2016-10-03 at 8 00 30 am" src="https://cloud.githubusercontent.com/assets/2680733/19022964/ad9f1d80-893f-11e6-81bb-40fd7e3f6ad4.png">

**Comment by DavidDudson** [comment]
Looks like theres no scala.meta issue on you track. Made one

https://youtrack.jetbrains.com/issue/SCL-10833

**Comment by olafurpg** [comment]
@DavidDudson I can highly recommend the IntelliJ 2016.3 EAP https://confluence.jetbrains.com/display/IDEADEV/IDEA+2016.3+EAP

It fixes a ton of false positives errors in code that uses scala.meta.

**Comment by DavidDudson** [comment]
@olafurpg I'm using the EAP. But I think the scala EAP is further ahead then the meta EAP at the moment. When I get home from work I'll list my scala plugin version. Although I'm not 100% certain that my scala plugin is using the meta nightly or the scala nightly. I'll double check when I get home.

**Comment by DavidDudson** [comment]
@olafurpg My intellij was using the scala nightly not the meta nightly. Wrong repository selected. whoops.
