### ISSUE TITLE
Runtime modifier validation is missing

### ISSUE THREAD

**Issue by jvican** [scalameta/scalameta#518]
As tracked in https://github.com/scalameta/scalameta/pull/485.

Right now, modifier validation is only performed at compile-time, however we should also check that created trees hold these invariants at runtime. For instance, this example: https://github.com/scalameta/scalameta/blob/master/scalameta/trees/src/main/scala/scala/meta/Trees.scala#L448.

If someone wants to take a stab, a good starting place is https://github.com/jvican/scalameta/blob/3ff1539836049ebfe8a0bb8771b4c14254c87ebd/scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L441.

Assuming that we want to come up with a DRY solution, the representation of modifier validators needs to change -- types won't be known at runtime. Off the top of my head, a generic dictionary mapping tokens/tree nodes to invalid modifiers could work. The idea would be to check that these invalid modifiers are not present, both for compile-time and runtime.

Another solution may be to duplicate some of the logic and specialize it for the runtime checks. I would only go this way if the DRY solution is not eventually feasible, as the other solution is cleaner.

**Comment by xeno-by** [comment]
We're on the verge of releasing 2.0, and afterwards we plan to start being really conservative about breaking changes. The matter discussed in the ticket can probably be improved, but there's not enough interest to justify potential breakages.
