### ISSUE TITLE
Update contributing docs

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#520]
Things to cover
- master vs 2x
- snapshots are published to bintray
- ~/.bintray/.credentials to ignore warning
- probably more...

**Comment by ShaneDelmore** [comment]
Is there a styleguide?  Should we add a .scalafmt.conf file to the project and do a reformat to reduce future formatting changes?

**Comment by olafurpg** [comment]
Styleguide is definitely missing. scalameta/paradise enforces scalafmt in CI and it has worked great for me so far (but I'm obviously biased :)). We'd have to take a look at the diffs for this repo and see, the scalameta codebase uses a ton of quasiquotes and patterns (waaay more than is usual in scala projects) which might not look so great with scalafmt. 

I know @jvican has expressed interest in reformatting the repo with scalafmt.

**Comment by olafurpg** [comment]
We just merged https://github.com/scalameta/scalameta/pull/709, which is a good start for this issue. I think we are safe to close this issue, missing info from CONTRIBUTING.md can be added via PRs.
