### ISSUE TITLE
Support syntactic/semantic macros at all locations

### ISSUE THREAD

**Issue by liufengyun** [scalameta/scalameta#536]
Tonight I conducted a conversation with @olafurpg , we agreed that **syntactic def macros** can also be very useful in practice. At the same time, programmers may want to use semantic APIs for annotation macros.

To support the scenarios above, we can follow the capability metaphor of scala.meta:

``` Scala
inline def macros1(defn: Any): Any = meta { mirror =>       // able to use semantic APIs
    // macros definition
}

inline def macros2(defn: Any): Any = meta {                  // unable to use semantic APIs
    // macros definition
}
```

The syntactic APIs are imported by default via `import scala.meta._`, while semantic APIs can only be accessed via `meta { mirror => }`. This way, we can control whether a macros definition is semantic or syntactic, and expand them accordingly. In Dotty, this syntactical difference also tells macros authors whether the trees are desugared or not.

Usage of semantic APIs for annotation macros can be both useful and tricky, programmers use it at their own risk.

**Comment by olafurpg** [comment]
Some examples of useful def macros that can be done syntactically

- scalatest `assert(a > b)` to produce clean error message "a=10 was not greater than b=20"
- sourcecode `Source[T]`: https://github.com/lihaoyi/sourcecode#overview

**Comment by xeno-by** [comment]
I'd strongly advise against supporting semantic APIs for macro annotations. https://github.com/scalamacros/paradise/issues/75 shows that it's too much trouble for too little gain.

**Comment by xeno-by** [comment]
I also have a comment about the proposed notation to distinguish syntactic and semantic meta blocks.

Strictly speaking, syntactic meta blocks should also take a capability, namely a dialect. This is currently not reflected in the prototype implementation, but it should work like that for completeness.

**Comment by liufengyun** [comment]
After implementing syntactic def macros in Eden, now I don't think syntatic def macros should have a different syntax from semantic ones. Close this for now.
