### ISSUE TITLE
fatal error initializing quasiquote macro

### ISSUE THREAD

**Issue by liufengyun** [scalameta/scalameta#548]
When I try to bridge quasiquote like follows:

```Scala
import scala.{meta => m}

  implicit class StringInterpolators(val sc: StringContext) {

    object q {
      def apply(args: Any*): m.Tree =
        (new m.XtensionQuasiquoteTerm(sc)).q(args)

      def unapply(scrutinee: Any): scala.Any =
        (new m.XtensionQuasiquoteTerm(sc)).q.unapply(scrutinee)
    }
}
```

I get a compilation error:

```
error: fatal error initializing quasiquote macro: Apply(Apply(TypeApply(Select(Select(Apply(Select(New(Select(Select(Select(Ident(scala), [scala.meta aka TermName("m")]), scala.meta.package), TypeName("XtensionQuasiquoteTerm"))), termNames.CONSTRUCTOR), List(Select(This(TypeName("StringInterpolators")), TermName("sc")))), TermName("q")), TermName("apply")), List(TypeTree())), List(Ident(TermName("args")))), List(Select(Select(Select(Select(Ident(scala), scala.meta), scala.meta.dialects), scala.meta.dialects.package), scala.meta.dialects.Scala211)))
               (new m.XtensionQuasiquoteTerm(sc)).q(args)
                                                   ^
```

I'm not sure if I'm doing it the correct way. Any feedback appreciated. Thanks.

**Comment by xeno-by** [comment]
`XtensionQuasiquoteXXX` objects are helpers that are intended to be used with scala.reflect macros. I don't think they will be helpful in your case.

Instead, I suggest that you hardcode scala.meta string interpolators in the compiler and then use the Quasiquote family of dialects to parse their contents and generate code appropriately. If you'd like, I can elaborate during a call. Please drop me an email, and we'll agree on a timeslot.

**Comment by liufengyun** [comment]
Thanks @xeno-by . Just had a talk with @densh during the coffee break, I realised I hit a bootstrap problem with quasiquotes. I'll hard-code the transformation in Dotty as you suggested.

**Comment by xeno-by** [comment]
Allright. Please let me know if you encounter any problems or would like to have a call.
