### ISSUE TITLE
value class parameter must be a val and not be private[this]

### ISSUE THREAD

**Issue by Keshi** [scalameta/scalameta#555]
```
class Identity extends scala.annotation.StaticAnnotation {
  inline def apply(defn: Any): Any = meta {  defn }
}

@Identity
class Test(val value:Int) extends AnyVal

```
// Error: value class parameter must be a val and not be private[this]

Shouldn't this compile?  The macro shouldn't be doing anything, right?

**Comment by xeno-by** [comment]
That's a bug. Resubmitted as https://github.com/scalameta/paradise/issues/136.
