### ISSUE TITLE
Macro loses value declarations in Defn.Class constructor 

### ISSUE THREAD

**Issue by cornerman** [scalameta/scalameta#560]
I have the following macro defined:
```
class test extends scala.annotation.StaticAnnotation {
  inline def apply(defn: Any): Any = meta {
    defn
  }
}
```

Then I use the annotation on a class with two values:
```
  @test
  class TestClars(val x: Int, val y: Int)
  val t = new TestClars(1,2)
  println(t.x)
```

I would have expected TestClars to have values `x` and `y`, like it is defined. So, the `@test` annotation should just be a noop. But I get a compile error: `value x is not a member of examples.MyApp.TestClars`. It works when I remove the `@test` annotation.

So, actually the generated code for TestClars is missing the `val` definitions on the constructor arguments. It looks like this: `class TestClars(x: Int, y: Int)`

Using scala-meta version 1.4.0 and paradise version 3.0.0.132.

**Comment by olafurpg** [comment]
Are you using the latest version of paradise? I think this was fixed around
a week ago.

**Comment by cornerman** [comment]
Thank you, just tested with paradise version "3.0.0-beta4" and it works!
