### ISSUE TITLE
Auto lift for Term.Name -> Pat.Var.Term ?

### ISSUE THREAD

**Issue by liufengyun** [scalameta/scalameta#576]
I'm not sure if it's worth it, but it's a little annoying to have to duplicate myself in the following example:

```Scala
class cache extends StaticAnnotation {
  inline def apply(defn: Any): Any = meta {
    defn match {
      case q"..$mods def $name[..$tparams](...$params): $tpe = $body" =>
        if (tpe.isEmpty)
          abort("@cache can only annotate method with explicit return type")

        val termName = Term.Name("_" + name.toString)
        val patName = Pat.Var.Term(termName)

        val varDef = q"var $patName: $tpe = null"
        val defDef =
          q"""..$mods def $name[..$tparams](...$params): $tpe = {
             if ($termName != null) $termName else { $termName = $body; $termName }
          }"""

        q"{ $varDef ; $defDef }"
      case _ =>
        abort("@cache can only annotate method definitions")
    }
  }
}
```

Notice `termName` and `patName`, and how annoying it is.

From user experience perspective, a name is a name, seems it's possible to do better here.

**Comment by olafurpg** [comment]
I agree, this is confusing for beginners and annoying once you understand it. I bump into this on almost every macro I write. I am not so familiar with the quasiquote implementation, but I think it's definitely worth investigating a solution for this problem.

**Comment by DavidDudson** [comment]
I also found this annoying,

However I thought the real pain point is consistency
```scala
class foo // name = Type.Name
object foo // name = Term.Name
trait foo // name = Type.Name
def foo // name = Term.Name
val foo // NO NAME, could be another pat 
var foo // NO NAME, could be another pat
val q"class $foo with $bar" // No name, makes perfect sense

```
I personally would prefer it if `Defn.Var` and `Defn.Val` were subclasses into the pat and non-pat versions, even if it's just for convenience.

So that the basic Defn.Var/Val has a name field

Because as soon as any macro author hits Vals/Vars they hit the more advanced concept of Pat.

Although plausible this could be added to quasi's aswell

**Comment by xeno-by** [comment]
I agree, the user experience is clearly suboptimal here. I like the idea to split `Defn.Val/Var` into pat and non-pat versions.

@liufengyun @olafurpg @ShaneDelmore @DavidDudson I've created a dedicated issue to collect feedback on pain points in the current AST design: https://github.com/scalameta/scalameta/issues/616. Please let me know what you think.

**Comment by xeno-by** [comment]
Closing in favor of https://github.com/scalameta/scalameta/issues/616.
