### ISSUE TITLE
Add extra abort overload to inline.Api

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalameta#586]
This is simply for improving error messages during abort's. Mostly because of macro expansions.

### Problem:

1. There is no way to nicely print out the syntax and structure during abort.
2. It's impossible to pimp inline.Api and add an extra method.

### Solution:

Add a method to inline.Api

```
  def abort(t: Tree, msg: String): Nothing = {
    val newMsg =
      s"""
       |[Message]
       |===========================================
       |$msg
       |
       |[Syntax]
       |===========================================
       |${t.syntax}
       |
       |[Structure]
       |===========================================
       |${t.structure}
     """.stripMargin
    throw new AbortException(newMsg)
  }
```

I'm raising this issue before a PR for suggested improvements etc.

### Example error output

```
abort(Type.Name("Tree"), "Expected a Type.Select")

[error] scala.meta.internal.inline.AbortException: 
[error] [Message]
[error] ===========================================
[error] Expected a Type.Select
[error] 
[error] [Syntax]
[error] ===========================================
[error] Tree
[error] 
[error] [Structure]
[error] ===========================================
[error] Type.Name("Tree")
[error]      

```

**Comment by DavidDudson** [comment]
Interesting enough due to package constraints this is not currently possible. 
Perhaps we could at least make a non package private object to allow pimps of this.

I'm unsure on how @xeno-by plans to approach errors/warnings and possible pretty printed errors as above. Perhaps this specific idea could co in scalameta/contrib

**Comment by olafurpg** [comment]
I think it would be very useful to have a utility in contrib to pretty-print unexpected trees for debug purposes. I would definitely use it. cc #537

**Comment by xeno-by** [comment]
@DavidDudson I didn't really think that someone would want to pimp `Api` traits, but it does make sense. Could you submit a PR that makes those traits public?

**Comment by xeno-by** [comment]
Speaking of this particular idea, I'd prefer it to be part of contrib. I'd like to keep the API surface in the base library as small as possible.
