### ISSUE TITLE
Add a dialect-aware `validate` method to Tree

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#599]
In https://github.com/scalameta/scalameta/pull/542, @cb372 says:
===========

Following on from the discussion on #498 about how to validate trees for a given dialect, I propose adding a `validate` method to `Tree`. This would replace all the `require` statements, so we no longer throw exceptions, and it also allows validation to take account of the dialect, which is currently not possible.

The downside is that it becomes possible to build invalid trees. The user becomes responsible for calling `validate` on any trees they build.

Things to discuss:

* What should the return type of `validate` be? For now I just made it a `Seq` of error messages, with an empty list representing validity.
* Where should `validate` be called? I guess the pretty-printers will want to validate trees before printing them, but I don't have any experience with that area of the codebase.

If this looks reasonable, I can rewrite all the other `require`s similarly.

**Comment by xeno-by** [comment]
Please follow https://github.com/scalameta/scalameta/pull/542 for an extensive discussion on this matter.

**Comment by olafurpg** [comment]
Related discussion in #253

**Comment by xeno-by** [comment]
Closed in favor of https://github.com/scalameta/scalameta/issues/253.
