### ISSUE TITLE
Illegal start of statement

### ISSUE THREAD

**Issue by 4lex1v** [scalameta/scalameta#603]
I'm trying to expand a function declaration into a private class and it's factory function:

```scala 
object test {
  @constr def Print(s: String): Call[Unit] 
}
```
where `@constr` should expand into a `private class` with a `def`, so the annotation result value looks this: `q"$genClass; $getFunc"`. It fails to compile:

```
[error] <macro>:2: illegal start of statement (no modifiers allowed here)
[error]   private final class $constr$PrintLine(val value: String) extends SystemCall[Unit] {}
[error]   ^
```

So it looks something like this after expansion:

```scala
object test {
  {
    private class generatedClass
    def generatedFunc
  }
}
```

maybe i'm simply missing some restriction

**Comment by xeno-by** [comment]
Could you provide a reproduction and resubmit to https://github.com/scalameta/paradise/issues?
