### ISSUE TITLE
Functionality to work with symbols

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#609]
Prerequisites:
  - [x] Online mirror with support for Ref.symbol (#606)

We start implementing the semantic API with a very simple `Ref.symbol` functionality (#606, #607, #608). While this API suffers from the same issues that `Tree.symbol` has in scala.reflect (dedicated API required to inspect signatures, forgetfulness with respect to prefixes, etc), it's easy to implement and can provide immediate wins, powering important use cases.

Another easy win is porting some of the scala.reflect `Symbol` APIs, providing scala.meta users with basic means to perform many semantic operations. Some inspiration for potential APIs can be drawn from [a previous prototype of semantic APIs](https://github.com/scalameta/scalameta/blob/7d6f917de39f8bfdbeb1f87d145f9797803d9ebb/scalameta/semantic/src/main/scala/scala/meta/semantic/Api.scala#L179-L308).

Usage example:
```scala
implicit val m = Mirror(...)
val sym = ... // scala.meta.semantic.Symbol
println(sym.name) // Int
println(sym.fullName) // scala.Int
println(sym.members) // List(getClass, ##, asInstanceOf, ...)
...
```

Implementation plan:
  - [ ] Figure out the list of APIs that we'd like to support. So far, I've got requests for:
    * `Symbol.toString` (we probably don't want to reveal internal ids in a public API)
    * `Symbol.syntax/structure` (these APIs are too commonly used to be missing)
    * `Symbol.name: Ref` (unwraps the symbol id to reveal a name, probably wrapped in an appropriate `XXX.Name` tree)
    * `Symbol.fullName: Ref` (a fully-qualified path for global symbols, the same as `name` for local symbols)
    * `Symbol.members: Seq[Symbol]` (I'd also add some helpers that filter this list by name and/or kind)
    * Other operations, as requested, given compelling use cases
  - [ ] As far as I can see, the implementation of symbol APIs will be different depending on whether the symbols are local or global:
    * Global symbols should be present in the underlying `Global` (in case of #606) or in a dynamically created `Global` (in case of #607). It should be easy to go from a UID to a corresponding `g.Symbol` and then perform a semantic operation on that symbol.
    * Local symbols that aren't present in `g`'s symbol table (because they were compiled separately and then loaded from a semantic database by #607) may pose a problem, but for them we can create a separate ticket (also see #612 for a related situation).
  - [ ] We can take the methods added to `Symbol` and pimp them on `Ref` and `Member`, because both are convertible to `Symbol` via `Ref.symbol`.

**Comment by xeno-by** [comment]
@olafurpg @DavidDudson @ShaneDelmore Please share your wishlist of semantic APIs that you'd like to see supported for symbols.

**Comment by DavidDudson** [comment]
@xeno-by I haven't actually thought of what would be possible with the Semantic api so I wont be much help in this regard. All I want is 2 things. 

- Fully qualified names
- Inferred types
- In a function be able to somehow find the exit points (This might not actual need the semantic api??)

I'm sure that list will grow once I play with the Api a bit, but for now that's it.

**Comment by xeno-by** [comment]
Fqns are already on the wishlist after a discussion with @olafurpg. Please check the original description of the issue to see whether they work as you'd like.

As for inferred types, could you give some examples of how you would like to use this API? I have a few ideas, but I'd like to hear you first.

Finally, I think that exit point detection can be done on syntactic level.

**Comment by DavidDudson** [comment]
Personally I think from a high level. any tree that has an optional type of some kind should have the type accessible, whether inferred or literal.

eg. for the basic example

```scala
q"def foo = 2".tpe // Int 
```

I think in practice the information would be available at the Term.Select/Term.Name level

```scala
def foo = 2

Term.Name("foo").tpe // Int
```

And for selects

```scala
object Foo {
  def bar = "Hello, world!"
  def baz: Int = 2"
}

Term.Name("Foo").tpe // Foo
Term.Select(Term.Name("Foo"), Term.Name("foo")).tpe // String
Term.Select(Term.Name("Foo"), Term.Name("baz")).tpe // Int
```

Although I'm unsure how to handle the case of subtyping, where the definition is a supertype of the actual type:

```scala
def foo: Seq[String] = List("1", "2")
def bar: AnyVal = 2

Term.Name("foo").tpe // Seq[String]
Term.Name("foo").inferred // List[String]

Term.Name("bar").tpe // AnyVal
Term.Name("bar").inferred // Int
```

Perhaps as suggested above:

tpe prefers the actual over inferred, but uses the inferred where the actual type is missing.

The above is useful to have from a tooling perspective, as the tool can suggest the user changes the type.

**Comment by xeno-by** [comment]
@liufengyun Could you provide some thoughts on the semantic APIs that you'd like to see here?

**Comment by ShaneDelmore** [comment]
@xeno-by This handles most of my current needs.  One idea would be to either encode personally I would prefer path to fullName, but that would be pretty easy to add on if others don't share my feelings.

Instead of 
- ```_root_.scala.Int#```
I prefer
- ```/scala/Int```
as it is frequently useful to do path like operations on types, is this type in package x, what would the path be if moved it to package y, are these two types both in the same package, etc.

**Comment by liufengyun** [comment]
For macros, if possible, I'd like to delay introducing the concept `symbol` to meta-programmers. Meta-programming is hard, tricky, my mindset is that it's good to restrict power of meta-programming to avoid intricate meta-programs.

However, I also see scala.meta could be used for source code analysis and transform. For that purpose, more features can be very helpful. There is some design tension here, IMHO.

**Comment by xeno-by** [comment]
@liufengyun Thank you again for the push for minimalism! I definitely acknowledge the problem of feature creep in metaprogramming APIs and appreciate your relentless resistance to it.

Do you envision a different approach to semantic APIs that doesn't involve symbols? Or do you suggest that we don't support functionality like `Ref.symbol` or `Symbol.members` at all? Also, do you think that a tree-based approach to the functionality mentioned here (#610) would work better that symbols?

**Comment by liufengyun** [comment]
@xeno-by I'm not against providing `symbol` and related API for people using `scala.meta` as a tool for program analysis and transform in order to get the referent of a name, which is generally unavailable in types (caveat: singleton types). Whether to expose `symbol` as a new concept depends on usage. But without it being an explicit concept, users will be unable to check equality of symbols -- e.g., whether two names have the same referent or a name refers to a particular symbol.

I'm only concerned about whether macro writers need or should be given such kind of power. Perhaps I was wrong, people may do need such kind of power to write some very important macros.

**Comment by xeno-by** [comment]
@liufengyun Even if symbols aren't part of the public API, they can still be there under the covers, powering semantic comparison between trees. By exposing an operator like `Tree.===` that makes use of underlying symbols, we can pull off things like `tree === t"Int"`.

**Comment by xeno-by** [comment]
As described in #808, we're giving up on the unicorn semantic API, proclaiming `scala.meta.semantic.v1` as the one and only semantic API. As a result, I'm promoting this issue from "Rudimentary functionality to ..." to just "Functionality to...".

**Comment by xeno-by** [comment]
Also see #863

**Comment by xeno-by** [comment]
Recently, we decided to limit the surface of our work to actionable items only - either bugs in existing code or feature requests that are warranted by the roadmap. 

While semantic API is definitely on our roadmap, we're going to figure out desired APIs from use cases, not from reflecting on scala.reflect and pondering what functionality from there we should add to Scalameta. That's why I'll be closing this issue and letting feature requests be submitted naturally by our users.
