### ISSUE TITLE
Functionality to work with types

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#612]
Prerequisites:
  - [x] Online mirror with support for Ref.symbol (#606)
  - [ ] Term.tpe (#611)

Following #611, we'd like to implement support for the following operations on types, inspired by our experience with scala.reflect:
  - [ ] `Type.=:=`
  - [ ] `Type.<:<`
  - [ ] Other operations, as requested, given compelling use cases

Much like in the case of #609, we may need to create a separate ticket to handle types that refer to separately compiled local symbols.

**Comment by xeno-by** [comment]
@olafurpg @DavidDudson @ShaneDelmore Please share your wishlist of semantic APIs that you'd like to see supported for types.

**Comment by xeno-by** [comment]
@liufengyun Could you provide some thoughts on the semantic APIs that you'd like to see here?

**Comment by ShaneDelmore** [comment]
@xeno-by I believe =:= and <:< cover all of my needs as long as they work properly with type aliases.

**Comment by liufengyun** [comment]
I think (1)`<:<`, (2)`=:=`, (3) create types from string or quasiquote (4) convert type to string or tree  would suffice in the beginning.

For writing macros, I'm unaware of scenarios where people need `Type.members`.  `Type.widen/dealias` are too much knowledge to the programmer, and we can wait for use cases of them to emerge. I think it's good to be conservative and restrictive about features.

**Comment by xeno-by** [comment]
@ShaneDelmore @liufengyun I've updated the implementation plan according to your feedback. Thank you for the push for minimalism!

**Comment by xeno-by** [comment]
Recently, we decided to limit the surface of our work to actionable items only - either bugs in existing code or feature requests that are warranted by the roadmap. 

While semantic API is definitely on our roadmap, we're going to figure out desired APIs from use cases, not from reflecting on scala.reflect and pondering what functionality from there we should add to Scalameta. That's why I'll be closing this issue and letting feature requests be submitted naturally by our users.
