### ISSUE TITLE
Term.desugaring

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#613]
Prerequisites:
  - [x] Online mirror with support for Ref.symbol (#606)

Some code analysis tools (e.g. https://github.com/scalacenter/scalafix) may want to inspect full internal representation of code after typechecking, and we may need to provide an API for that.

However, I'd like to avoid exposing a generic `Term.desugaring` API as much as possible, because desugarings may and will be terribly implementation-specific. Instead, I think it may be enough to introduce APIs like:
  * `Apply.inferredTargs`
  * `Apply.inferredArgs`
  * Same for `Pat.Extract`
  * ...

We'll need practical experience to proceed with this ticket. @olafurpg, @DavidDudson, @ShaneDelmore, @mutcianm please let me know what you think.

**Comment by xeno-by** [comment]
@olafurpg What do you think about this one after working on https://github.com/scalameta/scalameta/pull/1000?

**Comment by olafurpg** [comment]
How is this different from sugars?

**Comment by xeno-by** [comment]
It's not. Let's close this one and then evolve the functionality that you implemented in #1000 according to the arising use cases.
