### ISSUE TITLE
Tree.lexicalScope

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#614]
Prerequisites:
  - [x] Online mirror with support for Ref.symbol (#606)
  - [ ] Rudimentary functionality to work with symbols (#609)

A fairly frequent feature request from scala.reflect users and now from scala.meta users (via our Gitter channel and via scalafix) is the functionality to enumerate definitions visible from a given location in the program. Here's one important practical motivation for introducing this functionality: https://github.com/scalacenter/scalafix/pull/42.

**Comment by ShaneDelmore** [comment]
This functionality would also be useful to view implicits in scope.

**Comment by xeno-by** [comment]
Recently, we decided to limit the surface of our work to actionable items only - either bugs in existing code or feature requests that are warranted by the roadmap. 

While semantic API is definitely on our roadmap, we're going to figure out desired APIs from use cases, not from reflecting on scala.reflect and pondering what functionality from there we should add to Scalameta. That's why I'll be closing this issue and letting feature requests be submitted naturally by our users.
