### ISSUE TITLE
Conversions between tree variations

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalameta#617]
I suggest we have 2 separate conversion implementations following the same conversion pattern as JavaConverters.

### meta.conversions
implicitly will convert between various tree's whose only difference is semantics

eg. any subtype of `Name` can implicitly converted to any other subtype of `Name` without user input.

I believe this has the same semantics as the old macro Api (correct me if I'm wrong) however this should not be the default.

### meta.converters

add methods to trees that can be converted.

eg `Name.asTerm`

The current idea is that all conversion must be possible both ways. 
And tests must show that roundtripping is possible without losing information.

In cases where the conversion loses information and cannot be round tripped I suggest having another set of methods such as `tryAsTerm` which return `Option`

Checklist to add conversions

- [x] All subtypes of `Name`
- [ ] `Term.Select` and `Type.Select`

**Comment by DavidDudson** [comment]
Initial converters and conversions for Names.

https://github.com/DavidDudson/scalameta/commit/0f6a5f8481c20d9c55931a0bccf1505605423a0d

I'll make a PR once the contrib subproject PR has been merged.

It has brought up an interesting issue:

Even with automatic conversions, it is not possible to use arbitrary names inside quasiquotes.

`q"class $termName"` will not work
`q"class ${termName: TypeName}"` will work with conversions
`q"class ${termName.asType}"` will work with converters

Although when building trees normally it all works fine.

**Comment by olafurpg** [comment]
I think there's a general aversion to conversions nowadays. To my best knowledge, the best practice is to prefer explicit converters.

I think this is a perfect candidate for contrib. Big 👍 from me

**Comment by DavidDudson** [comment]
`Term.Select` and `Type.Select` may need to return option `asTerm: Option[Term.Select]`

I think we need to bail if the path is not convertable

**Comment by olafurpg** [comment]
Contrib has been stable for a while now and is working great. Let's defer feature requests like this ticket until we have someone driving the work.
