### ISSUE TITLE
Syntactic Converter outstanding issues

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalameta#619]
This is simply an issue moving the syntactic converter tasks to meta from paradise. See the issue here: https://github.com/scalameta/paradise/issues/84.

This may be slightly out of date.

- [ ] Ctor.Ref.Function
- [ ] Ctor.Ref.Name
- [ ] Ctor.Ref.Project
- [ ] Ctor.Ref.Select
- [x] Defn.Macro (#119)
- [ ] Enumerator.Generator
- [ ] Enumerator.Guard
- [ ] Enumerator.Val
- [x] Mod.Inline
- [ ] Pat.ExtractInfix
- [x] Pat.Type.And (inapplicable for Scala 2.x)
- [ ] Pat.Type.ApplyInfix
- [ ] Pat.Type.Existential
- [ ] Pat.Type.Function
- [x] Pat.Type.Or (inapplicable for Scala 2.x)
- [ ] Pat.Type.Placeholder
- [ ] Pat.Type.Project
- [ ] Pat.Type.Refine
- [ ] Pat.Type.Tuple
- [ ] Pat.Xml
- [ ] Term.ApplyUnary
- [x] Term.For
- [x] Term.ForYield
- [x] Term.TryWithTerm
- [ ] Term.Update
- [ ] Term.Xml
- [x] Type.And (inapplicable for Scala 2.x)
- [ ] Type.Arg.Repeated
- [x] Type.Or (inapplicable for Scala 2.x)
- [ ] Type.Placeholder

**Comment by xeno-by** [comment]
Superseded by https://github.com/scalamacros/scalamacros.
