### ISSUE TITLE
SIP-23 literal types syntax support

### ISSUE THREAD

**Issue by soronpo** [scalameta/scalameta#620]
I'm using typelevel scala for literal types.
SIP-23 is due to be merged for 2.12.2

Simple example: `val one : 1 = 1`

Note:
There is also an open issue of IntelliJ support for SIP-23 syntax [here](https://youtrack.jetbrains.com/issue/SCL-11193)

**Comment by xavier-fernandez** [comment]
Will work on this during this weekend :)

**Comment by xavier-fernandez** [comment]
WIP Branch: https://github.com/xavier-fernandez/scalameta/commit/b736008e387089bcc8f506da126c35ef0f24dfa1

I will continue working this afternoon :)

**Comment by soronpo** [comment]
If you like more test case ideas, you can checkout the files changed to add SIP-23 to scalac:
https://github.com/scala/scala/pull/5310/files

**Comment by xavier-fernandez** [comment]
Thank you @soronpo, will check for sure :)

**Comment by soronpo** [comment]
BTW, my intended use case for meta with literal types is to convert the `singleton-ops` library to the new meta, and simultaneously support Dotty, LBS and TLS. Currently we're dependent on the old macro systems. I think the new meta will provide us with much more interesting capabilities.
https://github.com/fthomas/singleton-ops

**Comment by xavier-fernandez** [comment]
Current WIP implementation: https://github.com/xavier-fernandez/scalameta/commit/d5286497174ab2d3f1f4ef822aada8d18888349f

I am advancing a lot in the process to support literal types on Scalameta, but get blocked when parsing `42.type` directly, getting the following error:

```
[info] - literal types are allowed *** FAILED ***
[info]   scala.meta.parsers.ParseException: <input>:1: error: end of file expected but . found
[info] val a: 42.type = 42
[info]          ^
[info]   at scala.meta.internal.parsers.Reporter$class.syntaxError(Reporter.scala:17)
[info]   at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:23)
[info]   at scala.meta.internal.parsers.Reporter$class.syntaxError(Reporter.scala:18)
[info]   at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:23)
[info]   at scala.meta.internal.parsers.ScalametaParser.syntaxErrorExpected(ScalametaParser.scala:419)
[info]   at scala.meta.internal.parsers.ScalametaParser.accept(ScalametaParser.scala:425)
[info]   at scala.meta.internal.parsers.ScalametaParser$$anonfun$parseStat$1.skipStatementSeparators$1(ScalametaParser.scala:71)
[info]   at scala.meta.internal.parsers.ScalametaParser$$anonfun$parseStat$1.apply(ScalametaParser.scala:77)
[info]   at scala.meta.internal.parsers.ScalametaParser$$anonfun$parseStat$1.apply(ScalametaParser.scala:68)
[info]   at scala.meta.internal.parsers.ScalametaParser.parseRule(ScalametaParser.scala:46)
[info]   ...
```

I am pretty sure the solution has something to do with the `TypeIntro` classifier, but I can't work on this issue until tomorrow.

**Comment by soronpo** [comment]
But 42.type is not available, AFAIK. 
You can do `val a : 42 = 42` and `val b = a.type = 42`, but `val a : 42.type = 42` gives `Error:(136, 13) ';' expected but '.' found.
  val a : 42.type = 42`

**Comment by soronpo** [comment]
I suggest you also try: 
```
val tree1 = "Tuple[1,2]".parse[Type]`
val tree2 = "val tpl : Tuple[1,2] = (1,2)".parse[Term]
val tree3 = "val tpl : (1,2) = (1,2)".parse[Term]
```

**Comment by xavier-fernandez** [comment]
Dotty has the same behaviour?

If not we should split both capabilities in two, one for TLS and the other one for Dotty...

**Comment by soronpo** [comment]
Checked it now. Dotty is the same as TLS in this.
```
Starting dotty interpreter...
Welcome to Scala.next (pre-alpha)  (OpenJDK 64-Bit Server VM, Java 1.8.0_111).
Type in expressions to have them evaluated.
Type :help for more information.
scala> val a : 42 = 42 
a: Int(42) = 42
scala> val a : 42.type = 42 
<console>:1: error: ';' expected but '.' found
val a : 42.type = 42
```

**Comment by xavier-fernandez** [comment]
Cool, I will finish the PR this night then :)

**Comment by xavier-fernandez** [comment]
The PR #640 was merged, this ticket can be closed, or something else needs to be done?

**Comment by xeno-by** [comment]
Yep, let's close it. Thank you!

**Comment by soronpo** [comment]
Wow! Nice. How do I get to use? When will the next release be available? I have big plans for this 😄

**Comment by xeno-by** [comment]
@soronpo Check out `1.6.0-640`.
