### ISSUE TITLE
FormattedStructure

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalameta#630]
This is up for discussion before I throw it out there...

I would like a `Show` variant that formats output.
This is because with any non-trivial tree it is nearly impossible to decipher nesting levels particularly

Basically, all this requires is formatting the structure with scalafmt.

example uses:

`q"foo".formattedStructure`
`q"foo.show[FormattedStructure]"`

Note: We could possibly just add a tree pimp only, and drop the need for a Show instance

Perhaps we could have a formatted syntax variant too.

This would require a scalafmt dependency. Hence why I am creating this ticket.

**Comment by DavidDudson** [comment]
@olafurpg @ShaneDelmore what are your thoughts?

**Comment by ShaneDelmore** [comment]
@DavidDudson Do you mean something similar to this?https://gist.github.com/cb372/262a9e935dba5de740a8e26909237419

**Comment by DavidDudson** [comment]
@ShaneDelmore yes, but my thoughts behind scalafmt were that its shouldnt have any drawbacks with weird structures

**Comment by DavidDudson** [comment]
Id also say that things like.

```
 TermName(
              "a"
            )
```

Should actually be 

```
Term.Name("a")
```

**Comment by olafurpg** [comment]
Scalafmt by defaulttt does not handle pathologically nested code. I might be able to add some options to make the search space not explode. Clang-format does a much better job by default https://gist.github.com/cb372/262a9e935dba5de740a8e26909237419#gistcomment-1892504

However, I think it should be fairly easy to reuse most of TreeStructure but somehow intelligently break large argument lists into multiple lines.

**Comment by DavidDudson** [comment]
Yeah I agree with trying to reuse TreeStructure first, then if that fails move onto something else

**Comment by ShaneDelmore** [comment]
I would definitely use this.

**Comment by xavier-fernandez** [comment]
I would also use it :)

**Comment by olafurpg** [comment]
Contrib has been stable for a while now and is working great. Let's defer feature requests like this ticket until we have someone driving the work.

**Comment by MasseGuillaume** [comment]
@DavidDudson take a look at: https://gist.github.com/MasseGuillaume/f9c1b37d75b443711d92929fa2b34928
