### ISSUE TITLE
Library dependant contrib

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalameta#631]
I'm leaving this ticket here for discussions on how to tackle things that should be a part of contrib, and maintained by the scalameta team, but also depend on other projects.

The 2 main reasons for this are.

- cats
- scalaz

I personally would love typeclasses instances for meta. But I would still like that project to be under the meta banner.

**Comment by DavidDudson** [comment]
@xeno-by @ShaneDelmore @olafurpg do you guys have any suggestions here?

**Comment by olafurpg** [comment]
I experimented with creating typeclass instances for cats yesterday, see https://github.com/scalameta/scalameta/commit/fe38d85529733913d0f6e1b083be6ab9cd77393e. The only ones I could come up with were Eq and Show. I don't have much experience with either scalaz or cats, however.

**Comment by DavidDudson** [comment]
Perhaps for now we could leave them in a separate branch. 

At the level of `Tree`, not soo much can be done. as `Tree` is not a container of anything. You cannot have a `Tree[A]` and then extract an `A` out of it.

Possibly you could define `Traversable` for it (Not sure what else).

However the subtypes of trees can have instances.

Eg. you can combine `Term.Block`
`Lit` is just a container (Although giving it a type param would make it nicer)

**Comment by olafurpg** [comment]
Contrib has been stable for a while now and is working great. Let's defer feature requests like this ticket until we have someone driving the work.
