### ISSUE TITLE
Confusing that mirror.database is required even if database is unused

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#647]

**Comment by xeno-by** [comment]
Do you encounter this problem when trying to do `Ref.symbol`?

**Comment by olafurpg** [comment]
Yes, it seems I need to call database at least once before symbol.

**Comment by olafurpg** [comment]
This is not urgent. I bumped into this when setting up my own test fixture with scalahost+scalafix. I opened the issue just to document the confusion I experienced

**Comment by xeno-by** [comment]
As far as I can see, `Ref.symbol` automatically calls into `database` anyway: https://github.com/scalameta/scalameta/blob/5b1fce6280115ff38c3e0a58a608079dfb955eba/scalahost/src/main/scala/scala/meta/internal/scalahost/v1/Mirror.scala#L56. Could you tell a bit more about how to encountered this problem?

**Comment by olafurpg** [comment]
I am unable to reproduce the problem now. Closing
