### ISSUE TITLE
semanticdb is dumped at the directory where sbt is run

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#650]
It looks like scalac instantiated by sbt has an incorrect path in `global.settings.d.value`, and that confuses scalahost (https://github.com/scalameta/scalameta/blob/f26801820116511945d867d83f2a3f3312d8bf44/scalahost/src/main/scala/scala/meta/internal/scalahost/ScalahostPipeline.scala#L29).

@dwijnand I'd appreciate your advice.

**Comment by dwijnand** [comment]
I don't know global.settings.d.value, but I can spend some time looking into it. I dont know scalahost, so could you tell me what the steps are to reproduce the error? sbt run at the root of the repo?

**Comment by xeno-by** [comment]
Thanks for your help!

The reproduction may be a little tricky, so I'd just like to ask for your knowledge in this area. How does sbt communicate the target directory to the hosted scalac instance?

**Comment by dwijnand** [comment]
It's defined in term of the project's `compile:classDirectory`, which by default is defined as:

```scala
classDirectory := crossTarget.value / (prefix(configuration.value.name) + "classes")
```

So typically `target/scala-2.12/classes`.

On the other end of the spectrum global.settings.d is set (via settings.outputDirs) like so: https://github.com/sbt/sbt/blob/v0.13.13/compile/interface/src/main/scala/xsbt/CompilerInterface.scala#L74

Ping if you need any more, happy to help.
