### ISSUE TITLE
Trailing commas in 2.12.2

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalameta#657]
PR was just merged https://github.com/scala/scala/pull/5245.

We need to allow trailing commas in 2.12.2 but not previous version. much like literal type syntax

**Comment by dwijnand** [comment]
AFAIK @xeno-by said scalameta already did support this.

**Comment by DavidDudson** [comment]
Ah okay, maybe its a recent addition. I may have missed it. My bots only running 1.4 still

**Comment by xeno-by** [comment]
```
scala> """
     | List(1,
     | 2,
     | 3,
     | )
     | """.parse[Term]
res1: scala.meta.parsers.Parsed[scala.meta.Term] =
<input>:5: error: illegal start of simple expression
)
^
```

Trailing commas don't seem to work in scala.meta.

**Comment by DavidDudson** [comment]
I presume we will have to change quasiquotes too?

**Comment by xeno-by** [comment]
@DavidDudson Yes, but it'll happen automatically once we modify the parser.

**Comment by olafurpg** [comment]
See #660 for a PR adding support for trailing commas.
