### ISSUE TITLE
Consider adding tutorials to scala-exercises

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalameta#658]
I think meta would make a great addition to https://www.scala-exercises.org/

To add a project:
https://github.com/scala-exercises/scala-exercises/blob/master/DEV_GUIDE.md

I'm quite happy to assist with this, following the scalameta/tutorial guide.

I'm unsure how stable meta is to be used in this environment. Perhaps we should wait for meta 2.0

**Comment by DavidDudson** [comment]
We may want to also wait for https://github.com/scalameta/scalameta/issues/616

**Comment by xeno-by** [comment]
Thank you for the great idea! Let's wait for a couple monthly releases to make sure that the semantic API stabilizes. Wdyt @olafurpg?

**Comment by olafurpg** [comment]
Sounds good. I think the semantic api will stabilize soon, but I propose we push this issue back one milestone.

**Comment by xeno-by** [comment]
@DavidDudson @olafurpg Do you think it's still worth it to pursue this?
