### ISSUE TITLE
Reorganize dialects

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#661]
I propose to change `Dialect` from an `@root` ADT into a case class (or `@data`). Benefits

- Possible to create custom dialect with `.copy`, eliminates the need for https://github.com/scalameta/scalameta/pull/653
- Less boilerplate in adding new dialects, preventing copy-pasta errors https://github.com/scalameta/scalameta/pull/660/commits/cf8618b30cb9a26f69eb53547b82bd8d66957cd9
- More readable code, for example, `val Scala212 = Scala211.copy(allowTrailingComma = true, allowLiteralTypes = true)`

I suspect dialects will only continue to become more complicated with Typelevel/Lightbend scala + sbt + paradise + "next big thing"

**Comment by xavier-fernandez** [comment]
👍

**Comment by dwijnand** [comment]
I started a patch for this. Happy to take this task unless it's urgent on for anyone.

**Comment by xavier-fernandez** [comment]
I am with this, its on top of this PR: https://github.com/scalameta/scalameta/pull/659

**Comment by olafurpg** [comment]
See https://github.com/scalameta/scalameta/pull/662#issuecomment-278653974 for a draft implementation.

**Comment by olafurpg** [comment]
The problem with case classes is that new fields break binary compatibility 😭
