### ISSUE TITLE
Function0 regression

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalameta#667]
https://github.com/scalameta/paradise/issues/151

Regression:
`syntactic("() => 1")`

**Comment by DavidDudson** [comment]
@xeno-by can we get a scalahost label? It looks like I cant add labels, only use them.

**Comment by olafurpg** [comment]
Good idea, I created a scalahost label

**Comment by DavidDudson** [comment]
@olafurpg can you please make it uppercase like the others? `Scalahost` instead of `scalahost` my OCD is killing me :frowning:

**Comment by olafurpg** [comment]
Haha, I didn't notice the pattern. Done!

**Comment by DavidDudson** [comment]
:+1:

**Comment by xeno-by** [comment]
Superseded by https://github.com/scalamacros/scalamacros.
