### ISSUE TITLE
simplify supporting macros in scala.meta

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#672]
### Macros used in the public API of scala.meta

Essential:
  * Quasiquotes (string interpolators, auxiliary `Lift`/`Unlift` macros)

### Macros used when compiling scala.meta

Essential:
  * `@root`, `@branch`, `@leaf` and supporting infrastructure for ADTs, ASTs and tokens
  * `@transformer` and `@traverser`

Convenience:
  * `unreachable`
  * `require`
  * `@quasiquote`
  * `@classifier`
  * Some implementation details of `Show`
  * Materializers of `Liftable` for core data structures
  * Materializers of `AstInfo` and `TokenInfo`

### Macros used when testing scala.meta

  * `wildcardImportStatics`
  * `allStatics`
  * `allSurface`
  * `typecheckError`

**Comment by xeno-by** [comment]
@olafurpg Do you have other suggestions on what would be better to replace with non-macro equivalents without a significant loss of conciseness?

**Comment by olafurpg** [comment]
What benefits does the `@data` macro have over case classes? I don't mind it so much really, but intellij disagrees.

**Comment by DavidDudson** [comment]
I wonder how much better things would get if we ported the macros to meta macros where possible. As meta macro support far surpasses the old. However intellij still doesn't add new Ref's to its index IIRC

**Comment by xeno-by** [comment]
@olafurpg https://github.com/xeno-by/scalameta/blob/master/scalameta/common/src/main/scala/org/scalameta/data/data.scala#L9

**Comment by olafurpg** [comment]
I'm totally fine with @data in trees. I've seen @data used for example with
exceptions where it seems a case class would work the same.

**Comment by xeno-by** [comment]
Wow, look what I found: https://github.com/scalameta/scalameta/blob/master/notes/macros.md.

**Comment by xeno-by** [comment]
I've inlined the aforementioned markdown file into the issue description.

**Comment by xeno-by** [comment]
We're on the verge of releasing 2.0, and afterwards we plan to start being really conservative about breaking changes. The matter discussed in the ticket can probably be improved, but there's not enough interest to justify potential breakages.
