### ISSUE TITLE
Create scalahost-sbt plugin

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#673]
Prototype here: https://gist.github.com/olafurpg/9c7cf9ddfb299d5e44d511cf99772d66

Features:
- setup the compiler plugin with correct scalacOption for >2.10 projects
- make it possible to pass in path to local jar via system properties for quick testing.

**Comment by xeno-by** [comment]
This looks useful, because the correct setup is nontrivial. Not only users need to specify `addCompilerPlugin(...)`, but also they need to not forget about `-Yrangepos`.

One request would be to annotate the sbt plugin with the same version as the version of the associated scalahost.

**Comment by olafurpg** [comment]
> One request would be to annotate the sbt plugin with the same version as the version of the associated scalahost.

This is easily solvable with sbt-buildinfo.
