### ISSUE TITLE
Explicit method to extract parsed Tokens (no automatic synthesis!)

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#674]
I have been bitten several times by the fact that `.tokens` takes an implicit dialect and synthesizes new tokens if there is no origin OR if the origin had different dialect. Example where this synthesis is a problem

1. parse code with custom dialect in scope
2. pass tree to method with no custom dialect in scope (defaults to Scala211)
3. `.tokens`, passing in default dialect
4. tokens are automatically synthesized and equality/hashCode no longer works with tokens in originally parsed code

I would like to have a method `.parsedTokens: Option[Tokens]` (or similar) and that fails if the tree has no origin.

**Comment by xeno-by** [comment]
Also see https://github.com/scalameta/scalameta/issues/253.

**Comment by olafurpg** [comment]
For context, here is the .tokens method that I have problems with: https://github.com/scalameta/scalameta/blob/5f277eda9c2ec2d812c637a776085637e579cf6e/scalameta/trees/src/main/scala/scala/meta/Trees.scala#L19
