### ISSUE TITLE
org.scalameta/inline 1.5.0 doesn't seem to be available for scala 2.11

### ISSUE THREAD

**Issue by gabro** [scalameta/scalameta#676]
I'm trying to install scalameta 1.5.0 on a scala 2.11 project.

After adding the Sonatype release resolver (1.5.0 doesn't seem to be on maven central) I "almost" got there, but the `"org.scalameta" %% "inline" % "1.5.0"` dependency doesn't seem to be available for scala 2.11 (while it is for scala 2.12).

See here: https://mvnrepository.com/artifact/org.scalameta/inline_2.11

I'm I doing something wrong?

**Comment by DavidDudson** [comment]
The sonatype servers failed to sync properly. @olafurpg has an issue on sonatype somewhere. For now you can use anything from. 

I'm on my phone but the resolver is Resolver.bintrayIvy("scalameta", "maven")

http://dl.bintray.com/scalameta/maven/org.scalameta/ 

You might want to try scalameta-588 at least until 1.6 is released. I'm not sure if that was the exact PR that is tagged 1.5 but it should be close

**Comment by xavier-fernandez** [comment]
```scala
addSbtPlugin("me.lessis" % "bintray-sbt" % "0.3.0")
```
```scala
resolvers += Resolver.bintrayIvyRepo("scalameta", "maven")
libraryDependencies += "org.scalameta" %% "scalameta" % "1.5.0-588"
```

**Comment by gabro** [comment]
Thanks for the responses. Does the bintray repo include snapshots as well? I'd like to try out 1.6, but I can't find it published anywhere.

**Comment by gabro** [comment]
Answering myself, yes it does! https://bintray.com/scalameta/maven/scalameta

Thanks :)
