### ISSUE TITLE
automatic release on tag

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#677]
@olafurpg says that this is already a thing in drone: `event: when: [tag]`, and with our recent build refactoring we're almost there infrastructurally. Looks legit.

**Comment by olafurpg** [comment]
This may give hints how to publish to sonatype from travis

- https://github.com/lucidsoftware/neo-sbt-scalafmt/blob/7321eeddbf52f2a9e3ffa44e061eebeb3d1febb4/build.sbt#L18
- https://github.com/lucidsoftware/neo-sbt-scalafmt/blob/7321eeddbf52f2a9e3ffa44e061eebeb3d1febb4/.travis.yml#L22-L29

**Comment by olafurpg** [comment]
Removing this from milestone, we can release stable releases manually for now.

**Comment by olafurpg** [comment]
Fixed in #1029, 2.0.0-M1 was released with tag push 👏
