### ISSUE TITLE
Set scalaVersion to latest in scalahost-sbt

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#681]
Currently, only 2.11.8 and 2.12.1 are published. This means that projects building against for example 2.12.0 get the error

```
org.scalameta#scalahost_2.12.0;1.6.0-680: not found
```

**Comment by xeno-by** [comment]
Tbh I'd like to limit ourselves to just the latest minor versions of 2.11/2.12. As paradise shows, supporting everything gets old very quickly. Wdyt?

**Comment by olafurpg** [comment]
I agree, would be nice if scalahost-sbt could automatically set the scala version to latest then. I currently get resolve errors running on community build.
