### ISSUE TITLE
Scala meta can't match valid scala code under -Yinfer-argument-types

### ISSUE THREAD

**Issue by rcano** [scalameta/scalameta#691]
Tokenizing works, but parse[Source] doesn't, I also don't see a way to configure this in order to enable it.

**Comment by olafurpg** [comment]
Can you please include a minimal example to reproduce?

**Comment by rcano** [comment]
```bash
 echo 'object A {trait TestMe { def testMe(i: Int) }; object impl extends TestMe { def testMe(i) = ??? }}' > A.scala
scalac -Yinfer-argument-types A.scala
```
Compiles fine, now:
```scala
scala> val code = """object A {trait TestMe { def testMe(i: Int) }; object impl extends TestMe { def testMe(i) = ??? }}""".tokenize
code: scala.meta.tokenizers.Tokenized = object A {trait TestMe { def testMe(i: Int) }; object impl extends TestMe { def testMe(i) = ??? }}

scala> val code = """object A {trait TestMe { def testMe(i: Int) }; object impl extends TestMe { def testMe(i) = ??? }}""".parse[Source]
code: scala.meta.parsers.Parsed[scala.meta.Source] =
<input>:1: error: : expected but ) found
object A {trait TestMe { def testMe(i: Int) }; object impl extends TestMe { def testMe(i) = ??? }}

```

**Comment by xeno-by** [comment]
Looks like we need to add a new field to `Dialect`: https://github.com/scalameta/scalameta/blob/a9f6f83ecd706c0d1309f4f315a4d3d56df7f44e/scalameta/dialects/src/main/scala/scala/meta/dialects/package.scala#L16.

After we have this new field, it would be possible to do something like `Scala211.copy(allowTypelessParams = true).apply(<snippet of code>).parse[...]`.

**Comment by xeno-by** [comment]
@rcano Would you be interested in contributing this new feature? It looks like parser changes are going to be just a couple lines of code around https://github.com/scalameta/scalameta/blob/2289145b9a7927082c5a498e6ae0f677d97bb08f/scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L2590.

**Comment by rcano** [comment]
I'm not familiar at all with scalameta's codebase and that file you linked scared me good 😓

**Comment by olafurpg** [comment]
That file can indeed appear a bit scary at first sight 😅 What's happening there is that we are parsing the type of the parameter, the fix is probably a matter of changing the condition inside the `if` to return None instead of report syntax error when the token is not a colon and `dialect.allowTypelessParams`
