### ISSUE TITLE
Use thrift or protobuf for semanticdb persistence

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#695]
/cc @olafurpg

**Comment by xavier-fernandez** [comment]
I can work with this ticket as soon as I finish working with: https://github.com/scalameta/scalameta/pull/692

**Comment by xeno-by** [comment]
Thank you! Though please ping us on gitter first. We're in the middle of discussing a refactoring to the semantic database data structures.

**Comment by xavier-fernandez** [comment]
@xeno-by Ok, no problem :)

**Comment by olafurpg** [comment]
Done, https://github.com/scalameta/scalameta/pull/748 migrated the persistence format to protobuf.
