### ISSUE TITLE
Referential equality test failure in corpus

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalameta#703]
Change the random number to 650.

Notice that 2 files fail. Both are fully commented out.

Due to transform taking a PartialFunction.

If the input ast does not contain a single Type.Name or Term.Name. The tree will never be transformed. And referential equality will hold.

The below is an example...

```scala
/* Comment */
```

**Comment by olafurpg** [comment]
Good catch! I suspected something like this might happen with the randomized tests, hence I printed out the seed to reproduce.

**Comment by olafurpg** [comment]
Fixed in #704
