### ISSUE TITLE
Simpler `Equal` api

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#708]
Following discussions on gitter here: https://gitter.im/scalameta/scalameta?at=58b4d2391465c46a56c297a8 and here https://gitter.im/scalameta/scalameta?at=58b534eade5049082225abe3

The `Equal` typeclass in contrib is a good start but could improve with

- more discoverability for beginners, for example with `equalStructurally` method. Question, should this method be included in the same `contrib._` import as `equal[T]` 
- more simplicity, e.g., replace `Structurally` with already existing `Structure`

**Comment by DavidDudson** [comment]
@xeno-by @ShaneDelmore opinions wanted.

**Comment by olafurpg** [comment]
After some thinking, I believe it would be best if we can find a way to make `equal` default to structural equality, avoiding a `equalStructurally` method.

**Comment by ShaneDelmore** [comment]
I like the default to structural equality, it seems to be desired most often. As for the two methods, I fear a beginner API as most examples are not written by beginners. If you start working with equalStructurally, then see others using equal[Structure] that might be more confusing than just starting with equal[Structur]

**Comment by olafurpg** [comment]
That is a great point @ShaneDelmore. I managed to hack it so that the type-checker to default to structural equality. I also renamed `equal` to `isEqual` since I've written `equals` by mistake a few times, which always typechecks but causes problem at runtime. Feedback is welcome on #711
