### ISSUE TITLE
Show[Desugared]

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalameta#714]
I really want to implement this at some point. For educational purposes.

For example.

```q"def[A : Show]()".desugared```

There are 2 approaches to this:

1. Make the Scalac => Meta Converters in Scalahost 2 way.
2. Run the compiler to the point after desugaring happens.

To me 2. Seems like the easiest and most reasonable. But I believe 1. is a long term goal.

IIRC desugaring happens at multiple stages in the compiler so perhaps there needs to be `.desugared[Stage]`

I don't know what the best way to do this would be, so I am open for ideas

**Comment by DavidDudson** [comment]
Notes:

I originally having the use as something like `q"Foo".phase[Typer].show[Syntax]`.

We could also compare structural equality this way too. thus optimizing comparisons beetween to bits of code.

Tree's generated by `-Xprint:$phase` are not reparsable into meta tree's (Due to `<>` not being valid pretty much everywhere).

We can either:

A. scrap structural equality, and just have `q"Foo".show[Phase[Typer]]` or similar. And then do string comparisons.
B. Add a `Scalac` dialect, that supports scalac specific compiler internals.

Given  that ScalaJS support was just added, and ScalaNative support will be added in the near future I would also like to support their compiler phases.

We may also want to support Dotty Seperately (Althugh I've never looked at Dotty's compiler phases)

**Comment by olafurpg** [comment]
Contrib has been stable for a while now and is working great. Let's defer feature requests like this ticket until we have someone driving the work.
