### ISSUE TITLE
Implement Equal[A] for all instances of Show

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalameta#716]
Show tends to be similar to a specific "view" of the language. Comparing these is natural.

It would be as simple as `a.show[X].isEqual(b.show[X])` but could be optimised on an individual basis.

**Comment by DavidDudson** [comment]
Related to #717

**Comment by olafurpg** [comment]
Contrib has been stable for a while now and is working great. Let's defer feature requests like this ticket until we have someone driving the work.
