### ISSUE TITLE
Add the ability to diff two trees

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalameta#718]
`q"class Foo".diff(q"class Foo { def bar = Baz }") === "{ def bar = Baz}" : Nil`

For more complex diffs, a more thought out approach would be needed.
This would be useful for debugging large trees that are "almost" what you expect them to be.

- We could possibly look at how git diffs strings and replicate that behavior
- We could possibly create a `Diff` typeclass so that other forms of show can be compared `.diff[Structure]`

**Comment by ShaneDelmore** [comment]
https://github.com/xdotai/diff Might be a good start for a structured diff if we added an ordered diff option. I believe it currently defaults to ignoring order when digging structures containing lists.

**Comment by DavidDudson** [comment]
Looks interesting.

The purpose behind this and the various show tickets. is that some stage I want to analyse various codebase changes overtime, detecting functional changes from non-functional changes so you can throw away import reorders and whitespace changes when reviewing, or automate splitting them into a separate commit.

**Comment by ShaneDelmore** [comment]
That would be amazing.

**Comment by olafurpg** [comment]
If we want to go fancy
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.182.1395&rep=rep1&type=pdf

**Comment by olafurpg** [comment]
Contrib has been stable for a while now and is working great. Let's defer feature requests like this ticket until we have someone driving the work.
