### ISSUE TITLE
ScaladocParser should return a @root/@leaf based documentation tree

### ISSUE THREAD

**Issue by xavier-fernandez** [scalameta/scalameta#721]
The `ScaladocParser` merged into master https://github.com/scalameta/scalameta/pull/692 output class `DocToken` is inconsistent with scala.meta.Tree. Ideally, it should be a full recursive DocTree AST.

This improvovement should be made before 1.7, in order to avoid binary incompatibility on future Scalameta stable releases.

**Comment by olafurpg** [comment]
Contrib has been stable for a while now and is working great. Let's defer feature requests like this ticket until we have someone driving the work.
