### ISSUE TITLE
Make trees serializable

### ISSUE THREAD

**Issue by MasseGuillaume** [scalameta/scalameta#73]
FYI
https://github.com/scala/pickling/issues/264

I wanted to pickle scalameta trees to work with them in scalakata. There is a stackoverflow in the typechecker.

**Comment by xeno-by** [comment]
This should become possible after we fix https://github.com/scalameta/scalameta/issues/144.

**Comment by xeno-by** [comment]
@MasseGuillaume I didn't have time to play with serialization libraries, but I've at least tested our scratchpad-less trees with Java serialization, and it seems to work. I'll be testing in scalahost shortly as well. It'd be great if you could take a look at applying more advanced libraries here.

**Comment by MasseGuillaume** [comment]
@xeno-by wow you are the best! I will try to test this ASAP. Ping me again if I forget.

**Comment by xeno-by** [comment]
@MasseGuillaume Ping.

**Comment by MasseGuillaume** [comment]
@xeno-by pong added to my cal. Trying it out tonight.

**Comment by MasseGuillaume** [comment]
@xeno-by see https://github.com/MasseGuillaume/cats/commit/b5d25c3cd99b05b59df3ea0477d800319051285d
