### ISSUE TITLE
Provide full error list when parse fails instead of single position of first error

### ISSUE THREAD

**Issue by nairbv** [scalameta/scalameta#730]
Maybe I'm missing something, but from Tokenized.Error(position,message,details), and the tutorial (""" val str = "closed literal" """.tokenize match {.... case Error(...)=>???}), it looks like there can only be one error position/message returned if the given code doesn't parse.

In compiling actual Scala code with scalac, there are of course often multiple errors displayed in the output of the command.  Hypothetically someone could use scalameta in an IDE for finding and highlighting positions of all syntax errors in a piece of code.  If there is a way to get multiple error details from incorrect code, it could be better documented.  If that doesn't exist, it seems to me like it should.

**Comment by olafurpg** [comment]
The parser can only provide one error, this is true also for the compiler

```scala
$ cat target/foo.scala                                                                                1   jmh-benchmarks
object Foo // { error 1
  def main(args: Array[String]) {

 //  } error 2
}
$ scalac target/foo.scala                                                                                  jmh-benchmarks
target/foo.scala:2: error: expected class or object definition
  def main(args: Array[String]) {
  ^
one error found
```
The typer phase can report multiple errors.

I think IntelliJ uses advanced parsing tricks to find multiple error points in unparseable code. The same is possible with scala.meta today, but the logic needs to be implemented in the application side. I'm not 100% sure, but I think the trick is to start re-parsing statements at some offset after the first parse error position.

**Comment by olafurpg** [comment]
BTW. I think it would be great to have utilities in `contrib` to implement this logic that recovers from untokenizable/unparseable code and reports as many helpful errors as possible. If someone is interested in taking a swing at this, I'd be happy to help out with review/feedback on design.

**Comment by nairbv** [comment]
Can you explain the comment "The parser can only provide one error, this is true also for the compiler." ?

scalac certainly can return multiple error messages:

```
brian@desktop ~ $ cat Test2.scala 
}
"
brian@desktop ~ $ scalac Test2.scala
Test2.scala:1: error: Unmatched closing brace '}' ignored here
}
^
Test2.scala:2: error: unclosed string literal
"
^
two errors found
```

**Comment by nairbv** [comment]
I see the scala compiler "ignores" the first unmatched closing brace "ignored here," but couldn't scala.meta do the same and return as many errors as the compiler would have?

With type information scalac also reports multiple errors, e.g.

```
object Test{
  foo;
  bar;
}
brian@desktop ~ $ scalac Test.scala
Test.scala:2: error: not found: value foo
  foo;
  ^
Test.scala:3: error: not found: value bar
  bar;
  ^
two errors found

```

Even if it doesn't right now, it seems like understanding types is a goal of scala.meta, so it seems like it would be helpful for the API to support returning all the information it will eventually have?

**Comment by olafurpg** [comment]
I wasn't aware that scalac could report multiple errors from the parser. Thanks for pointing that out.

I guess @xeno-by may be more qualified to answer how difficult it would be support the same in the meta parser.

**Comment by xeno-by** [comment]
`syntaxError` in the scalac parser usually accumulates errors instead of bailing on the first one via exceptions. 

As a result, non-trivial logic is required to restore from some errors, e.g. to move forward on missing braces etc. When porting the scalac parser to scala.meta trees, we removed that logic and never got to reviving it.

It seems that the revival is theoretically possible. However, it may take non-trivial amounts of time.

**Comment by nairbv** [comment]
Even if it's going to be a while and not be part of an immediate release, If it's definitely going to be part of the roadmap then I think it would be nice if there's an API designed in such a way that multiple errors can be returned in the future.  That way code can use the API now without worrying about breaking backwards compatibility later when multiple errors are available.

**Comment by olafurpg** [comment]
Superseded by https://github.com/scalameta/scalameta/issues/1170 which is a related ticket of using the scalameta parser in an interactive setting where buffers are expected to have parse errors.
