### ISSUE TITLE
Access to default parameters of macro annotations

### ISSUE THREAD

**Issue by tkroman** [scalameta/scalameta#734]
There is no way to access a default argument from inside the macro annotation: we operate either on a `new MyMacro(arg1, ..., argN)` in case argument(s) are supplied or on a `new MyMacro()` otherwise. As far as I understand, we can't inspect annotation definitions themselves, so there should be some 'external' mechanism to do it (?).

**Comment by DavidDudson** [comment]
Moved to the correct issue tracker

**Comment by DavidDudson** [comment]
@tkroman See https://github.com/scalameta/paradise/blob/master/tests/meta/src/test/scala/compile/Expansion.scala#L198

and 

https://github.com/scalameta/paradise/blob/master/tests/meta/src/main/scala/namedParam.scala

This is already implemented, and was never an issue
