### ISSUE TITLE
Port ADT macros to scalameta/paradise

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalameta#735]
AFAIK the ADT macros do not depend on any compiler internals.

The Mirror use is also minor, there no def macros.

This seems like the prime candidate for really testing out the new scalameta macro annotations.

Theres 2 reasons:

- Intellij support when maintaining meta is shocking, due to the use of the old macros.
  - It's basically just a memory hogging text editor.
- If all macros can be ported to meta, meta support for 2.10 and SJS/SN should be easier.

Would require:

- scalameta/common dependency on scalameta
- scalameta/common dependency on paradise 3.0
- *possible* dependency on scalameta/contrib

We may want to wait for a more stable semantic api and/or def macros. But I think incrementally moving to meta macros is better then doing it all at once

**Comment by DavidDudson** [comment]
Some examples... Basically all of this prevents any symbol lookup, or refactoring helpers from working. 

![example3](https://cloud.githubusercontent.com/assets/2680733/23687745/f6d1b9a4-0414-11e7-8edf-db18d61083b1.png)
![examplea](https://cloud.githubusercontent.com/assets/2680733/23687746/f6d3e83c-0414-11e7-947e-d193662fb87d.png)
![exampleb](https://cloud.githubusercontent.com/assets/2680733/23687747/f6d52a30-0414-11e7-80d9-471051468ed4.png)

**Comment by cb372** [comment]
I had a quick go at this but I don't see an easy way to solve the cyclic dependency between `common` and `scalameta`.

`scalameta` depends on `common`, so of course we can't add a `dependsOn(scalameta)` to the `common` project.

I wondered if we could naively add a dependency on `"org.scalameta" %% "scalameta" % "1.6.0"` and everything would just work. But unsurprisingly that was also a non-starter. It means we have old and new versions of duplicate scala.meta classes on the classpath, so we get compile errors like this:

```
[error] /Users/chris/code/scalameta/scalameta/common/src/main/scala/scala/meta/internal/ast/Liftables.scala:37: value q is not a member of StringContext
[error]       q"""
[error]       ^
[error] /Users/chris/code/scalameta/scalameta/common/src/main/scala/scala/meta/internal/ast/Liftables.scala:56: type mismatch;
[error]  found   : StringContext
[error]  required: ?{def q: ?}
[error] Note that implicit conversions are not applicable because they are ambiguous:
[error]  both method XtensionQuasiquoteTerm in trait Api of type (ctx: StringContext)Api.this.XtensionQuasiquoteTerm
[error]  and method Quasiquote in trait Quasiquotes of type (ctx: StringContext)LiftableMacros.this.c.universe.Quasiquote
[error]  are possible conversion functions from StringContext to ?{def q: ?}
[error]         val init = q"""c.universe.Ident(c.universe.TermName("_root_"))""": Tree
```

Any ideas on how to work around this bootstrapping problem? If we can solve this, it looks like rewriting the macros should be reasonably simple. As far as I could see they are entirely syntactic.

**Comment by DavidDudson** [comment]
What happens if you make the meta dependency compile time only? Does that actually work?

**Comment by cb372** [comment]
No, I tried making it provided scope but it didn't help

**Comment by DavidDudson** [comment]
Do you have a branch at all? I would like to experiment.

**Comment by cb372** [comment]
There's not much to it, but here it is https://github.com/cb372/scalameta/tree/port-adt-macro-annotations

**Comment by DavidDudson** [comment]
@cb372 I believe the problem is the `provided` exports the dependency as a runtime dependency. What we really want is a compile time only dependency, which SBT does not support out of the box (As it mimics maven).

Also, `scalameta/paradise` can expand old macros aswell as new ones, so instead of the `enable macros` configuration we will need to have a custom one. We will not be able to have `scalamacros/paradise` and `scalameta/paradise` as plugins at the same time.

See this SO post: http://stackoverflow.com/questions/21515325/add-a-compile-time-only-dependency-in-sbt

Are you still willing to approach this?

**Comment by olafurpg** [comment]
Just a thought, maybe we could use the coursier shading plugin to bootstrap https://github.com/coursier/coursier/releases/tag/v1.0.0-RC1

**Comment by xeno-by** [comment]
We're on the verge of releasing 2.0, and afterwards we plan to start being really conservative about breaking changes. The matter discussed in the ticket can probably be improved, but there's not enough interest to justify potential breakages.
