### ISSUE TITLE
Handle conversion from and to sets

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalameta#745]
It is rather annoying convert an existing `Set[Tree]` into a `Set[Structurally[Tree]]`

We could:

Add a pimp for `Set[Tree]`.

I'm unsure of names at this point...

But we need to have something like

`set.usingEquality[Structurally]`

or perhaps if we ignore the typeclass approach

`set.structurally and set.syntactically` which might be easier on most users

**Comment by olafurpg** [comment]
Contrib has been stable for a while now and is working great. Let's defer feature requests like this ticket until we have someone driving the work.
