### ISSUE TITLE
Avoid runtime type checks in TreeSyntax.Lit

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#762]
Scala.js does not support runtime type checks on a few primitives: https://www.scala-js.org/doc/semantics.html#runtime-type-tests-are-based-on-values

TreeSyntax uses this feature to pretty-print ` Lit` tree nodes: https://github.com/scalameta/scalameta/blob/25640d3fe827e2e8c9d5fef31d297d81eac3da4d/scalameta/trees/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala#L403-L412

My attempts to fix this issue so far are

1. add a `@ast class Lit[T:LiteralFormatter(value: T)` type class constraint, but that failed because the `@ast` macro doesn't support type parameters
2. make `Lit` a `@branch trait Lit` and add `LitInt`/`LitDouble`/... subclasses. See WIP commit https://github.com/scalameta/scalameta/commit/4380fdcb159477e891309526a7f9b8542976ff44 This failed with a cryptic compiler error from some macro annotation expansion  in `transformer.scala`

**Comment by xeno-by** [comment]
See https://github.com/scalameta/scalameta/pull/763

**Comment by olafurpg** [comment]
This got fixed in #761
