### ISSUE TITLE
Expose simple method to get Input.File from Tree

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#765]
Following gitter discussions: https://gitter.im/scala/tooling-contrib?at=58d93b384cb8d09173307df1

**Comment by CremboC** [comment]
Is there any particular reason why not just expose
```scala
def input: Input = tokens.head.input
```
under `scala/meta/internal/ast/InternalTrees.scala` as you suggested in the gitter conversation?

Obviously since the input can be many places, it cannot (and shouldn't) return only an `Input.File`.

**Comment by DavidDudson** [comment]
What if there's no tokens?  Does parsing an empty file explode on the head call?

**Comment by CremboC** [comment]
```scala
  it should "explode" in {
    val s      = getClass.getClassLoader.getResource("Empty.scala").toURI
    val parsed = new File(s).parse[Source].get

    assertThrows[Exception] {
      parsed.tokens.head.input
    }
  }
```
resulted in
```
Expected exception java.lang.Exception to be thrown, but no exception was thrown
```

`Empty.scala` is 0 bytes (completely empty)

**Comment by olafurpg** [comment]
There is an Input.None, and trees like `Term.Name("a")` have `VirtualInput`.

This issue is in particular about exposing a simple utility for getting an `Option[Input.File]`, we could add it in contrib.

**Comment by DavidDudson** [comment]
Perhaps we could add both input and inputFile methods

**Comment by olafurpg** [comment]
Contrib has been stable for a while now and is working great. Let's defer feature requests like this ticket until we have someone driving the work.
