### ISSUE TITLE
Contrib tests are not run

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalameta#771]
I believe this affects any module with tests, that has not been ported to a crossbuilt project.

sbt expects tests to be in src/test, but now they are in shared/src/test.

This means "contrib/test" will run 0 tests.
I presume this means CI is not currently running the contrib tests.

**Comment by DavidDudson** [comment]
@olafurpg Side note. I'm ready to re-push the extract stuff. I just want to make sure the CI is building correctly first. I've been super busy writing a presentation among other things. I should have some time for meta in the coming days.

**Comment by olafurpg** [comment]
Good catch! I will fix this asap by porting contrib to Scala.js.

I left contrib out because it depends on testkit which requires file IO to download zips and read files. I plan to move all tests to a `tests` projects.
