### ISSUE TITLE
position

### ISSUE THREAD

**Issue by MasseGuillaume** [scalameta/scalameta#78]
Trees don't have position.

possible hack
https://github.com/aghosn/Obey/blob/master/model/src/main/scala/scala/obey/model/utils.scala#L28

**Comment by xeno-by** [comment]
https://github.com/aghosn/Obey/blob/30a76f4505c869780f6532970bf4f2a111b67c24/model/src/main/scala/scala/obey/model/model.scala#L28

**Comment by xeno-by** [comment]
Positions are on my todo list, right after the semantic API.

**Comment by xeno-by** [comment]
API for positions was introduced a few weeks ago. In the near future I'm going to document it, along with the bunch of other functionality that scala.meta provides, and for now please take a look at http://blog.codacy.com/2015/06/04/a-quick-look-at-scalameta/ which uses positions.
