### ISSUE TITLE
Auto-publish tutorial on merge to master

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#787]
The tutorial (https://github.com/scalameta/tutorial) currently uses an old scala.meta version. It's also annoying to update the tutorial because of version sync problems, see https://github.com/scalameta/tutorial/pull/9

I suggest we move the tutorial contents and host them on `scalameta.org`. I'm personally a big fan of having a single fat webpage with all docs (search with Cmd+F), currently it's difficult for users to find all the content.

**Comment by DavidDudson** [comment]
I would welcome this change!

**Comment by olafurpg** [comment]
@xeno-by any objections to put the tutorial on the scalameta.org page? We could also put it under scalameta.org/tutorial.html, that might scale better if we want to add more pages later.

**Comment by olafurpg** [comment]
I took a quick stab at this and hit on a few bumpers:

1. we can't demo macros with the build version of scala.meta because macros depend on paradise which depends on a released scala.meta version.
2. all the example code (rewrites/macros) has red squiggly marks in IJ, which is a bad experience for users who clone the repo to try them out

I suggest instead that we keep the docs in the tutorial repo and clean it up. The tutorial repo is originally in fact a fork of scalafix, so the build is unnecessarily complex and contains a lot of unrelated code. I think we could have only tutorial related projects

- library (just plain code examples and tests)
- devtools (build some cli interface)
- macro annotations


I can setup CI for the tutorial repo and auto-publish the docs on merge into master. WDYT?

**Comment by xeno-by** [comment]
Sounds awesome! Sorry for the late response.

Do you still want to have the tutorial on the main page?

**Comment by olafurpg** [comment]
I believe the tutorial/docs need to be in a separate repo, because of the reasons I mentioned above. I've updated the title to be about auto-publishing the tutorial on merge to master.

**Comment by olafurpg** [comment]
I cleaned up the tutorial repo considerably in https://github.com/scalameta/tutorial/pull/13 and I've setup auto-publish docs on merge into master.
