### ISSUE TITLE
Support showing decompiled Java code

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalameta#791]
Relating to #714 and #715  It makes sense to include decompiled sources.

For example, it would be really handy for the talk I am writing currently, to show how implicit resolution works, and how encapsulation works under the hood. 

When giving demo's etc. showing java source is a 3 step process involving the file system. It would be nice to do everything in memory and just write

`q"case class Person(name: String, age: Int)".show[Java]` or similar.

**Comment by olafurpg** [comment]
Contrib has been stable for a while now and is working great. Let's defer feature requests like this ticket until we have someone driving the work.
