### ISSUE TITLE
Reemitted Defn.Val's in traits discard backquotes in identifiers

### ISSUE THREAD

**Issue by DylanLukes** [scalameta/scalameta#798]
## Summary

Literal identifiers degrade to unquoted identifiers when reemitted by `StaticAnnotation#apply`.  

This causes unexpected syntax errors when using fields with literal identifiers.

@olafurpg suggested the issue may be related to this line: https://github.com/scalameta/scalameta/blob/b269cd87de10be0b54056609b4777f79e77165e7/scalahost/core/src/main/scala/scala/meta/internal/scalahost/converters/ToMtree.scala#L260

**Note: This probably does not just apply to traits, but at the least to classes and objects as well.**

## Minimal Reproduction:

```scala
class ShowMeASyntaxError extends scala.annotation.StaticAnnotation {
  inline def apply(defn: Any): Any = meta {
    defn match {
      case dt @ Defn.Trait(_, _, _, _, _) => dt
      case _ => abort("@BrokenIdentity must annotate a trait.")
    }
  }
}
```

```scala
@ShowMeASyntaxError
trait ThisIsBroken {
  val `type`: String = "jurisprudence fetishist gets off on technicality"
}
```

## Output (Failing): 

```
[error] <macro>:1: illegal start of simple pattern
[error] trait ThisIsBroken { val type: String = "jurisprudence fetishist gets off on technicality" }
[error]                          ^
[error] <macro>:1: '=' expected but '}' found.
[error] trait ThisIsBroken { val type: String = "jurisprudence fetishist gets off on technicality" }
[error]
```

## Output (Expected):

_None._

**Comment by DylanLukes** [comment]
Confirmed this also occurs for other statements.

```scala
class ShowMeASyntaxError2 extends scala.annotation.StaticAnnotation {
  inline def apply(defn: Any): Any = meta { defn }
}
```

This will break any class, object, trait, etc it is applied to with backquoted vals.

**Comment by xeno-by** [comment]
Hi @DylanLukes! Thanks for reporting the issue. It looks like it is specific to the macro system implemented in scalameta/paradise, and it doesn't affect Scalameta in general.

After discussing the future of Scala macros, we have decided to retire scalameta/paradise in favor of a new implementation that will be living at https://github.com/scalamacros/scalamacros.

This means that in the future we won't be doing bugfixes for scalameta/paradise, focusing on the new implementation of Scala macros instead. We will, however, dedicate effort to providing a migration path from scalameta/paradise to scalamacros/scalamacros. Please follow scalamacros/scalamacros#4 to stay tuned for updates.
