### ISSUE TITLE
Provide umbrella "syntactic" module

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#799]
Currently, the main scalameta module transitively depends on scalapb and protobufs because the semantic module uses protobufs for persistence of the semantic DB. For applications like scalafmt that don't use the semantic module, it's a bit annoying to either

1. pull in such large dependency or
2. pick custom modules like parsers/quasiquotes and miss the `import scala.meta._` import

It would be nice if there was a `syntactic` umbrella module which doesn't bring in the semantic APIs and could be a drop-in replacement for the current `scalameta` module without the semantic baggage.

**Comment by olafurpg** [comment]
The protobuf dependency has become even more tightly coupled after #828. I'm not sure if it's worth the refactoring to pull out protobuf into a separate repo. A workaround is to exclude the semantic dependency with exclusion rules http://www.scala-sbt.org/0.13/docs/Library-Management.html#Exclude+Transitive+Dependencies

**Comment by xeno-by** [comment]
@olafurpg Do we still need this ticket given the recent reorganizations in 2.0?

**Comment by olafurpg** [comment]
We need to solve Input.Denotation. A syntactic module would be nice, so let's keep it open.

**Comment by olafurpg** [comment]
Scalafmt is still on 1.7, so I need to upgrade first.

**Comment by xeno-by** [comment]
@olafurpg Is this ticket still relevant?

**Comment by olafurpg** [comment]
I currently use an exclusion rule for scalapb in scalafmt. Although I still think it would be nice to publish scalameta without scalapb, it's not important enough for me that this ticket has been untouched in over a year. We can reopen if the need becomes more urgent.
