### ISSUE TITLE
Helper method: `Type.Arg.toType`

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#801]
See http://stackoverflow.com/questions/42301941/scala-meta-type-mismatch-when-unquoting-found-optionscala-meta-type-arg-req

I've been bitten on this myself, it could be implemented this way

```scala
implicit class XtensionClassTypeArg(arg: Type.Arg) {
  def toType: Type = arg match {
    case Type.Arg.Repeated(tpe) => tpe
    case Type.Arg.ByName(tpe) => tpe
    case tpe: Type => tpe
  }
}
```

EDIT. removed `case impossible` line

**Comment by CremboC** [comment]
Any particular reason to use `case impossible => ???` instead of `case _ => ???`? Would avoid pointlessly allocating a variable.

P.S.
Sorry if this is not contributing much to the question here..

**Comment by olafurpg** [comment]
@CremboC Just to highlight that this case should never happen, I should probably just remove it. I don't think it allocates, it becomes something like `val impossible = arg`

**Comment by ShaneDelmore** [comment]
If we hit a case that should be impossible I will be most concerned with eliminating confusion, allocating a variable before I crash is not really what I am worried about. I vote to keep it or something else that conveys more meaning than _ like thisLineShouldNeverBeReached.

**Comment by xeno-by** [comment]
In some parts of scala.meta, we use `org.scalameta.unreachable`, possibly in conjunction with `org.scalameta.debug` to indicate just that, e.g. https://github.com/scalameta/scalameta/blob/v1.7.0/scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L148.
