### ISSUE TITLE
Defn.hasMod(mod): Boolean

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#804]
Currently, the most concise way to test if a defn has a modifier is

```scala
q"lazy val x = 2".mods.exists(_.isEqual(mod"lazy"))
```

it would be nice if it was possible to write that as 

```scala
q"lazy val x = 2".hasMod(mod"lazy")
```
instead.

**Comment by xavier-fernandez** [comment]
Will take a look to this during this week :)

**Comment by DavidDudson** [comment]
it should just be an implicit on https://github.com/scalameta/scalameta/blob/master/scalameta/contrib/shared/src/main/scala/scala/meta/contrib/implicits/ExtractExtensions.scala

This is also an item on https://github.com/scalameta/scalameta/issues/741

```scala
 def hasMod(mod: Mod)(implicit ev: Extract[A, Mod]): Boolean = ev.extract(a).exists(_.isEqual(mod))
```

Should be all that's needed i believe

**Comment by olafurpg** [comment]
@DavidDudson Good catch! I didn't notice the `.has` helper, I like that syntax. Closing as dupe of #741

**Comment by DavidDudson** [comment]
@olafurpg I like the name hasMod though, for clarity

**Comment by olafurpg** [comment]
which do you prefer between `hasMod[Mod.Inline]` and `has[Mod.Inline]`? The duplicate `Mod` strikes out IMO.

**Comment by DavidDudson** [comment]
@olafurpg how about.... `has[Mod.Inline]` and `hasAnnot("Foo")`

I think we may be able to make `has` even more generic (But I am not sold on the idea just yet)....

`has[Defn.Def]` vs `extract[Defn.Def].nonEmpty` might make sense too.

**Comment by olafurpg** [comment]
I'm not sure about `hasAnnot(String)`, since annotations can also have type + term arguments.

> I think we may be able to make has even more generic (But I am not sold on the idea just yet)....

We are hitting on grey territory with `extract.exists`, IMO. I would like to limit vocabulary as possible. My motivation for `hasMod` was to expose a parallel to scalac's internal `.hasFlag`, which is often handy.

I'm leaning again towards this signature,

```scala
 def hasMod(mod: Mod)(implicit ev: Extract[A, Mod]): Boolean = ev.extract(a).exists(_.isEqual(mod))
```
it handles annotations (even with arguments) as well as constant modifiers like Mod.Inline. It's also not any more verbose or less typesafe than the parameter kind `hasMod(Mod.Inline())/hasMod(mod"inline")` vs. `hasMod[Mod.Inline]`

**Comment by ShaneDelmore** [comment]
How many options are there?  Has[Mod....] makes me wonder what other types I can stick in there, where is the list to enumerate. Once I find the possible answers it reads cleanly. HasMod makes me think if I want to know what types I can look for I should enter .has then wait for auto-complete to show all of the the things I can check for. No opinion on the matter, just sharing how I might look at the API upon first use.

**Comment by olafurpg** [comment]
It's possible to autocomplete on the available values with `Mod.<autocomplete>`, see https://github.com/scalameta/scalameta/blob/dbb30b57adf148f91bddf1370a531673fb39fc72/scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala#L489-L510

**Comment by xavier-fernandez** [comment]
Cool, will implement this today.

I was thinking in an approach similar to:

```scala
 def hasMod(mod: Mod)(implicit ev: Extract[A, Mod]): Boolean = ev.extract(a).exists(_.isEqual(mod))
```

I should proceed?

**Comment by olafurpg** [comment]
LGTM 👍 I'll re-open this issue then

**Comment by ShaneDelmore** [comment]
@olafurpg To clarify, my question would not be what types of Mod can I look for, it would be what types of things besides Mod I can look for. Has[Param]? Has[DeclTpe]? For example.

**Comment by DavidDudson** [comment]
@ShaneDelmore There is no typeclass for `Has`.

We could make one if there was enough want, the only reason I can forsee it being useful is efficiency

`q"class Foo()".extract[Defn.Def].nonEmpty`

would be equivalent to 

`q"class Foo()".has[Defn.Def]`

**Comment by ShaneDelmore** [comment]
So the only thing that can go inside the brackets in has[...] is Mod.someMod?  I feel like I am missing something. I will go back and read the code. I think I lost the thread over the course of this conversation.

**Comment by ShaneDelmore** [comment]
I was thinking of has[Defn.Def] and if there were many other things that could be placed there. If it's really only Mod then I would lean very strongly towards hasMod. I think anytime you accept a type parameter it hints strongly to the caller of the API that this is generic and that there are many things has can check for the presence of.

**Comment by DavidDudson** [comment]
@ShaneDelmore The final implementation (That was merged) does not use a type parameter.

`q"case class Foo".hasMod(mod"case")` in the intended use (or `q"case class Foo".hasMod(Mod.Case)`)

Implementing it this way allowed for annotation support.

`q"@Bar class Foo".hasMod(mod"@Bar")`

The only reason this exists is to have similar behaviour to `hasFlag` in scalac. It also is quite nice because it defaults to structural equality. Most people do not understand why `Mod.Inline` etc are classes rather then objects, so this also hides that fact for the common use case.

`q"class Foo { def bar = 2 }".extract[Defn.Def].anyMatch(_ isEqual q"def bar = 2")`

Would be the expected way to check for existence of a specific def.

We could possibly implement something kind of like contains (except a non-tree variant) for this.

`q"class Foo { def bar = 2 }".contains(q"def bar = 2")`

Although I'm getting more and more worried about confusion between "Tree" methods, such as transform/collect etc. and methods that traverse the stats canonical container "Class/Defn/Pkg" etc.
It does seem that we actually want the same features for both. I quite often see in gitter developers new to meta writing a collect call without knowing that it will actually traverse all subtrees.

**Comment by olafurpg** [comment]
> Although I'm getting more and more worried about confusion between "Tree" methods, such as transform/collect etc. and methods that traverse the stats canonical container "Class/Defn/Pkg" etc.

I agree. I don't have a concrete solution in mind, but I think we should try to make a clear separation between recursive tree traversals and iterations on sequences.

**Comment by DavidDudson** [comment]
@olafurpg My only thought is having a "view" of some kind for iterations on sequences. Because then at least we can use the same method names if we want. But I don't have a good idea of this
