### ISSUE TITLE
Post ScalaDays Chicago 2017 talk highlights at scalameta.org

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#809]
In order to do that, I need to figure out where I'm storing the slides. scalamacros.org doesn't cut it, and our scalameta.org infrastructure doesn't yet support static files.

**Comment by olafurpg** [comment]
Put the pdf under readme/resources, that should be enough to host static
files on scalameta.org

**Comment by xeno-by** [comment]
https://github.com/scalameta/scalameta/pull/810
