### ISSUE TITLE
Parentheses on constructor annotation

### ISSUE THREAD

**Issue by iTakeshi** [scalameta/scalameta#811]
Question: Why the scalameta parser ignores parentheses appended to constructor annotations?

Use case: In a playframework-2.6 application, I'd like to expand some controllers which use dependency injection, i.e.
```scala
@someMacro class FooController @Inject() (cc: ControllerContexts) extends AbstractController(cc) { ??? }
                                   // ^ those parentheses are indispensable
```
However, it will be expanded into:
```scala
class FooController @Inject (cc: ControllerContexts) extends AbstractController(cc) { ??? }
                        // ^ parentheses are GONE
```
and this results in a compilation error.

Cause: In https://github.com/scalameta/scalameta/blob/master/scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L3367-L3370 , parentheses are removed if `allowArgss` is `false`, and it is actually `false` when parsing constructor annotations: https://github.com/scalameta/scalameta/blob/master/scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L2714

Can I remove those lines? If not, I wonder why.

Thanks

**Comment by olafurpg** [comment]
Are you using inline/meta macro annotations? If so, the problem is probably in LogicalTrees https://github.com/scalameta/scalameta/blob/master/scalahost/core/src/main/scala/scala/meta/internal/scalahost/converters/LogicalTrees.scala

LogicalTrees may be going away soon soon (see  https://github.com/scalameta/paradise/issues/194 and #808) in favor of a more robust approach that makes it easier to preserve all details in the original source

**Comment by iTakeshi** [comment]
Indeed I use inline/meta macro, but the cause is really in LogicalTrees? I just read the source now, but got no idea about where the parentheses is removed.

**Comment by olafurpg** [comment]
Inline/meta macro annotations don't use the scala.meta parser, they use LogicalTrees to convert between scala-reflect trees and scala.meta trees. The motivation behind https://github.com/scalameta/paradise/issues/194 to get rid of the inherent complexity of LogicalTrees. I spent a significant amount of time making sure the converter preserves all syntactic details in the original source and we have a large test suite to check this. However, despite our efforts, the converter is still incomplete.

Is this a blocker? You can try to add a test case [here](https://github.com/scalameta/scalameta/blob/master/scalahost/nsc/src/test/scala/scala/meta/tests/scalahost/converters/Syntactic.scala) and see if you can track down the cause. However, note that LogicalTrees may be going away in the next few weeks in favor of using the scala.meta parser directly.

**Comment by iTakeshi** [comment]
Thanks for comprehensive explanation. I've try that test (`syntactic("class Foo @Inject() (cc: ControllerContexts) extends AbstractController(cc)")`). It passes when `allowArgss == false` (as in this repository), and actually, it fails when `allowArgss == true`. My suggestion was completely wrong, sorry about that.

I decided to use some work-around implementations and wait for you to move to scalameta's parser from LogicalTrees.
Thanks again.
