### ISSUE TITLE
Tests for standalone reading/writing semantic dbs under JVM/JS

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#827]
Creating a note for myself in order not to forget to do this.

**Comment by olafurpg** [comment]
We have such tests now in https://github.com/scalameta/scalameta/blob/f7463f78227e092b5dab0a05667733b0a2b23952/scalameta/tests/shared/src/test/scala/scala/meta/tests/CrossPlatformSemanticSuite.scala writing + reading in JVM and reading only in JS
