### ISSUE TITLE
Having to use the copy method is restrictive

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/scalameta#831]
For example, if you want to do something like map over all `Members` and prefix their name with `m_` it is actually really hard.

There's 2 levels to this problem.

1. We have no idea what subtype of `Name` the `name` field references.
2. We have no idea what subtype of `Member` the actual member is.

This means we cannot create new versions of these tree's.

Solutions:

I believe the only solution is via contrib.  
Something like `Replace[Member, Name]`

Although that's not possible because `Replace` requires a `Seq`

**Comment by olafurpg** [comment]
Contrib has been stable for a while now and is working great. Let's defer feature requests like this ticket until we have someone driving the work.
