### ISSUE TITLE
Loss of lambda parameter type

### ISSUE THREAD

**Issue by vpavkin** [scalameta/scalameta#834]
I have some code of this structure:
`(_: T) => something`

Here I help the compiler to infer the parameter type.

For some reason, scala-meta emits this code without the type helper:
`_ => something`

**Comment by vpavkin** [comment]
@olafurpg cool, thanks for quick response! 
Sorry for reporting a duplicate :) Feel free to close it now or when fix is officially released

**Comment by olafurpg** [comment]
No worries :) this just got fixed only last Monday and the bug was never reported directly, only discovered when fuzzing the pretty-printer in https://github.com/scalameta/scalameta/issues/567

**Comment by olafurpg** [comment]
scalameta v1.8.0 and paradise 3.0.0-M9 just got released with this fix! Please give it a try

**Comment by vpavkin** [comment]
Confirmed, works fine now! Thanks! 👍
