### ISSUE TITLE
Lack of support for pre-1.8 JDK

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#838]
This was reported by @Duhemm in https://gitter.im/scalameta/scalameta?at=590f7891631b8e4e61b0c8a3:

>Hey, I was wondering if it was known and expected that java 8 is required to use scalameta since 1.7.0? I was using 1.6.0 on java 7 with Scala 2.11.8, and started having issues when I switched to 1.7.0. I get a NoSuchMethodException in PlatformTokenizerCache.scala, because of java.util.Map.putIfAbsent which was introduced in Java 8. Everything works great with Java 8.

**Comment by DavidDudson** [comment]
Can we also get a CI build for this to prevent future regressions?

**Comment by olafurpg** [comment]
We stopped testing jdk <=7 after supporting 2.12, we could test 2.11 on jdk 7 using a different docker image here https://github.com/scalameta/scalameta/blob/2128ff7b233aafb797c8c1b9bc747a67e10efab4/.drone.yml#L15 

cc/ @jvican what do you think about adding a scalaplatform/scala_jdk7 (or similar name) docker image? I'm happy to build it and publish myself

**Comment by jvican** [comment]
Sounds good @olafurpg! This is the repository I used to cut the current docker images: https://github.com/scalacenter/drone-docker-sbt.

**Comment by xeno-by** [comment]
I think that requiring JDK 1.8 is fine, so we'll be closing the issue.

**Comment by jvican** [comment]
Good call. The new version of the incremental compiler is also requiring JDK8, so I think this is totally reasonable.
