### ISSUE TITLE
Imprecise warning messages for unused members of selective imports

### ISSUE THREAD

**Issue by gabro** [scalameta/scalameta#839]
With reference to https://github.com/scalacenter/scalafix/pull/152#issuecomment-299727017

Given this code:

```scala
object imp {
  import scala.collection.mutable.{ Map, Set, ListBuffer }

  val l = ListBuffer.empty[Int]
}
```

scalameta produces the following semantic db:

```
Names:
[7..10): imp => _empty_.imp.
[22..27): scala => _root_.scala.
[28..38): collection => _root_.scala.collection.
[39..46): mutable => _root_.scala.collection.mutable.
[49..52): Map => _root_.scala.collection.mutable.Map.;_root_.scala.collection.mutable.Map#
[54..57): Set => _root_.scala.collection.mutable.Set.;_root_.scala.collection.mutable.Set#
[59..69): ListBuffer => _root_.scala.collection.mutable.ListBuffer.;_root_.scala.collection.mutable.ListBuffer#
[79..80): l => _empty_.imp.l.
[83..93): ListBuffer => _root_.scala.collection.mutable.ListBuffer.
[94..99): empty => _root_.scala.collection.generic.GenericCompanion#empty()Lscala/collection/GenTraversable;.
[100..103): Int => _root_.scala.Int#

Messages:
[15..71): [warning] Unused import

Denotations:
_empty_.imp. => final object imp
_empty_.imp.l. => val l: scala.collection.mutable.ListBuffer[Int]
```

Notice the single warning message referring to the whole import statement. The expected result would instead be multiple error messages referring to the separate members that are unused.

**Comment by olafurpg** [comment]
Thank you for reporting! I tracked the error down to this line https://github.com/scalameta/scalameta/blob/d085c4c22282a809c7e2ea91669a2838592016b6/scalahost/nsc/src/main/scala/scala/meta/internal/databases/AnchorOps.scala#L26 it should be `pos.point` instead of `pos.start`. `Anchor` is going away in https://github.com/scalameta/scalameta/pull/828 but the fix for this bug will still be the same. I will open a PR to fix this as soon as #828 is merged

**Comment by gabro** [comment]
Thanks for the fix! I've left a comment on the commit, take a look when you have a minute :)

**Comment by olafurpg** [comment]
The commit that closed this issue got reverted because the change affected positions of sugars. I am investigating what we can do to support both sugars and compiler messages.

**Comment by olafurpg** [comment]
Reading up on [Positions in scala/scala](https://github.com/scala/scala/blob/5a5ed5826f297bca6291cd1b1effd3f7231215f9/src/reflect/scala/reflect/api/Position.scala#L80-L91).

Fun fact 1: Position.start/end are only used for RangePositions.
Fun fact 2: `Position.point` is where the caret `^` should appear
Fun fact 3: for [unused import warnings](https://github.com/scala/scala/blob/5a5ed5826f297bca6291cd1b1effd3f7231215f9/src/compiler/scala/tools/nsc/typechecker/Contexts.scala#L68), start != point != end 👏 

It seems we need a new position type that has a start, end and point field

**Comment by gabro** [comment]
It makes sense. They represent three different things in the compiler, and I don't see why not exposing it to scalameta users.

**Comment by olafurpg** [comment]
Interestingly, Position.point was removed in https://github.com/olafurpg/scalameta/commit/918e2ecab7a0dd95c6ff769f4fd76fb2e5d097f4

**Comment by olafurpg** [comment]
And apparently I co-authored the commit! My memory is failing me 🤔

**Comment by gabro** [comment]
The commit message here is interesting: https://github.com/scalameta/scalameta/commit/7a193ed47638f6a6b3216814866ae95cc7b57344

**Comment by gabro** [comment]
I don't know whether the motivation still apply, but it seems the compatibility with scalac's behavior is there now, isn't it?

**Comment by olafurpg** [comment]
Interesting comment indeed. I still agree with the decision to remove point from Position.Range, I remember being confused when I started hacking on scalafmt. 

I just opened #849  that should fix this issue.
