### ISSUE TITLE
Add configuration support for macros

### ISSUE THREAD

**Issue by dispalt** [scalameta/scalameta#840]
Would it be possible to get some sort of support for `-Xmacro-settings:foo=bar` for annotations?  My use case is I have an `sbt` plugin and I need to get some settings information from that plugin (aka sbt settings) to the macro annotation.  I'd prefer not to have to do some hackery with `sys.props` to get it to work.

Also if it would work where I could do `scalacOptions += "-Dfoo=bar"`, than that would be acceptable too.  I've discussed with @olafurpg and that doesn't seem to work, and he's updated http://stackoverflow.com/questions/42969692/compile-time-parameter-for-macro-expansion

Let me know your thoughts on this.

**Comment by xeno-by** [comment]
See my comment on Olaf's stackoverflow answer.

**Comment by dispalt** [comment]
I don't have enough stackfu to respond, but I've tried this:

```
    javaOptions += "-Dfoo.hello=bar",
    javacOptions += "-Dfoo.hello=bar",
    scalacOptions += "-Dfoo.hello=bar",
```

to no avail.

My current workaround which I think will get messed up for multiple projects is this monstrosity:

```
    initialize := {
      val () = sys.props("foo.hello") =
        (taskFoo in Compile).value.getAbsolutePath
      initialize.value
    }
```

**Comment by olafurpg** [comment]
Thanks for sharing your workaround @dispalt I added a comment on SO linking to your comment in case someone's in the same situation. 

I agree that it would be nice to have some official way to configure macros with compiler options. This is a regularly requested feature. I'm open for the idea if we can find a good api for it. scalameta-based macros are currently undergoing some changes to accommodate https://twitter.com/xeno_by/status/860378404444487680 and https://github.com/scalameta/paradise/issues/194 I will try to think about how we can mix in configuration

**Comment by xeno-by** [comment]
Superseded by https://github.com/scalamacros/scalamacros/issues/7.
