### ISSUE TITLE
Consider removing slim semantic databases

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#865]
Since 1.8.0, our semantic databases come in two variations - fat (including the original code) and slim (not including the source code). Both approaches have their pros and cons, so I hoped to provide both variations simultaneously - with a particular implementation strategy hidden behind a common API. 

It turns out, however, that it's not that simple. For example, slim databases need a sourcepath for deserialization (they don't include source code per se - just relative paths of source files), which fat databases don't. This means that there's no one-size-fits-all API - it's either too much information for fat dbs or too little information for slim dbs.

I suggest that we take an especially good look at user feedback in this area, and then try to pick just one standard and roll with it. At the moment, I'm biased towards fat dbs. In the meanwhile, let's support both with fat dbs are default.

**Comment by xeno-by** [comment]
@olafurpg Would you like to do the honors and change the default to `fat`?

**Comment by olafurpg** [comment]
The default is not `fat`. I'm not yet convinced it's a good idea to remove `slim`. I have a feeling that once we start embedding semanticdb files into sources jars then it will be wasteful to embed the file contents in the semanticdb files.

**Comment by ShaneDelmore** [comment]
This is nearly a special case of fatDb though isn’t it?  I mean in the case of embedding into a jar with sources it seems easy to find the sources, we still don’t need to ask the users anything.  Maybe if slim goes away we end up with fat and virtualFat which looks like a fatDb in every way except it is loaded from a jar and the sources are beside the db instead of inside of it.  A slight tweak to the packaging process could have the sources stripped out on insertion into the jar.

**Comment by olafurpg** [comment]
That is a good observation @ShaneDelmore I agree, .semanticdb files inside -sources.jar may as well considered fat since there's no need for custom `--sourcepath` from the user.

**Comment by xeno-by** [comment]
We're one step away from releasing Scalameta 2.0, and after 2.0 compatibility will become a huge deal. As a result, I'll be closing tickets that would be nice to have, but don't warrant potential associated breakages. This ticket is one of them.
