### ISSUE TITLE
More convenience for tree manipulation

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#872]
I have to admit that our tree manipulation functionality is pretty barebone. That was done intentionally in order to simplify `Trees.scala` as much as possible (it's still very complicated anyway).

With the big reorganization planned for 2.x, I suggest that we take time to discuss what tree helpers we would like to see in the default distribution.

Here are some suggestions off the top of my head (please write yours in comments, and I'll update the list):
  * `Member.mods`
  * `Member`/`Mods`.`isXXX` (`isPrivate`, `isFinal`, etc)
  * `Member`/`Mods`.`setXXX`/`resetXXX`
  * `<ast class>.withXXX` for every `<ast class>.copy(XXX = ...)`
  * `<branch>.withXXX`, too

**Comment by xeno-by** [comment]
@DavidDudson @olafurpg Which parts of `contrib` would you recommend for graduation?

**Comment by DavidDudson** [comment]
I think it's also important to have abstract methods on branch traits such as `Member` and `Name` for `withXXX`

This allows you to still modify the underlying object without caring what it is.

**Comment by xeno-by** [comment]
Superseded by https://github.com/scalameta/scalameta/issues/1112.
