### ISSUE TITLE
Xml literals are desugared before macro expansion

### ISSUE THREAD

**Issue by exlevan** [scalameta/scalameta#877]
See https://github.com/exlevan/scalameta-xml for code example. I expect the code to compile and print `<HelloWorld/>` on run. Instead, it fails to compile with the following message:
```
[error] /home/exlevan/projects/scalameta-xml/xml/src/main/scala/scalameta_xml/Main.scala:5: exception during macro expansion: 
[error] java.lang.RuntimeException: val xml = {
[error]   {
[error]     new _root_.scala.xml.Elem(null, "HelloWorld", _root_.scala.xml.Null, $scope, true)
[error]   }
[error] }
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at scalameta_xml.XmlToString$inline$.apply(XmlToString.scala:14)
[error]   @XmlToString
[error]    ^
[error] one error found
[error] (xml/compile:compileIncremental) Compilation failed
```

**Comment by olafurpg** [comment]
Thank you for reporting! Xml literals are desugared by the scalac parser, which means current scalameta macro annotations can't preserve them. With https://github.com/scalameta/paradise/issues/194 it will be possible to transform parsed xml tree nodes inside scalameta macro annotations.

**Comment by xeno-by** [comment]
Hi @exlevan! After discussing the future of Scala macros, we have decided to retire scalameta/paradise in favor of a new implementation that will be living at https://github.com/scalamacros/scalamacros.

This means that in the future we won't be doing bugfixes for scalameta/paradise, focusing on the new implementation of Scala macros instead. We will, however, dedicate effort to providing a migration path from scalameta/paradise to scalamacros/scalamacros. Please follow https://github.com/scalamacros/scalamacros/issues/4 to stay tuned for updates.
