### ISSUE TITLE
rename Input.LabeledString to Input.VirtualFile

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#881]
How about we tighten the type signature of `Input.LabeledString` to `(AbsolutePath, String)` as opposed to `(String, String)`? Anyway, we aren't using the flexibility provided by the fact that the first field is now typed as `String`.

**Comment by olafurpg** [comment]
Why absolutepath? Would it make more sense to have `Input.VirtualFile(RelativePath, String)`?

The lhs value of labeled string is currently not a path because I wanted to accommodate weird labels like "<macro>", but I personally would be fine to tighten it to RelativePath.

**Comment by xeno-by** [comment]
I agree this should be a relative path.

**Comment by olafurpg** [comment]
RelativePath fails to construct when the path is absolute. Quasiquotes currently use LabeledString to to report helpful messages. I added a hack in https://github.com/olafurpg/scalameta/commit/cc4a1277cf17d4f1abeac2fa621ac5bcd56cb942 to relatevize the path if it's absolute. This ruins the nice absolute filepaths in the reported quasiquote messages. I propose that we use `VirtualFile(nio.Path, String)`. wdyt?

**Comment by xeno-by** [comment]
Oh well, this is sad, but I can't see how anything can be done about this. I agree that `Path` is an improvement over `String`.

**Comment by olafurpg** [comment]
I'm not sure if this refactoring is worth it, so I'm gonna assign this issue to you. I personally like the current flexibility of labeled string. We use inputs to uniquely identify positions which are the cornerstone of the semantic api. Being able to add any arbitrary label is quite handy in my opinion. Restricting the label to `nio.Path` doesn't buy us much IMO. I'm happy to reconsider, we had issues with labeled string not enforcing os-agnostic file paths in .semanticdb files so there is room for improvement.

**Comment by xeno-by** [comment]
I agree that new experiments provide clear evidence that we shouldn't change the type label to any kind of `Path`.
