### ISSUE TITLE
Rethink Ref

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#883]
When extracting the meta API for 2.x, I found our that ApplyUnary is a Ref. This came as a surprise, almost as if Apply or Interpolate were refs too. I think we should undo this inheritance relationship.

**Comment by xeno-by** [comment]
After thinking more about this, I realized that we don't have a clear story about what refs are and what are good for.

Here are the reasons why we added `Ref` in the early days of Scalameta:
  * Scala.reflect had `RefTree` and that trait has proven to be useful in the compiler.
  * We wanted an analogue of `Type.typeSymbol`, and that can be somewhat emulated by matching a type against `${ref: Ref}[...$targs]` and then doing `ref.symbol`.
  * We wanted our ASTs to be safer, so we restricted some AST fields to refs to make sure that it's statically impossible to construct syntactically invalid trees.

Here is the reality of `Ref` today:
  * All Ref-typed fields in Trees.scala (`Type.Select.qual`, `Type.Singleton.ref`, `Pkg.ref`, `Mod.Private.within`, `Mod.Protected.within`, `Importer.ref`) are subject to further `checkFields` validations. 
  * We only have one API that uses refs - `Ref.symbol` - and that one isn't particularly groundbreaking, since Scalafix (the only big client) is using `Database.names` instead.

As a result, I'm starting to think that `Ref` is another instance of early-days wishful thinking that needs to be killed. Concretely, I propose that:
  1) We remove `Ref`, `Term.Ref` and `Type.Ref`.
  2) We approximate Ref-typed fields with their upper bounds and update already existing validations in relevant trees.
  3) We rethink the semantic API that we have right now.

Since this is a big change, and we should release 2.0 pretty soon, I'm deferring this issue to 3.0. Please let me know what you think.

**Comment by DavidDudson** [comment]
I've never really seen a useful case for ref. Sounds good to me.

**Comment by xeno-by** [comment]
We're on the verge of releasing 2.0, and afterwards we plan to start being really conservative about breaking changes. The matter discussed in the ticket can probably be improved, but there's not enough interest to justify potential breakages.
