### ISSUE TITLE
Feature request: s.Attributes.sha/hash

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#886]
It would be nice if there was a shasum or hash field in s.Attributes. This would be useful to validate that the contents of a file match the compilation unit that created the .semanticdb file. This is more relevant for slim dbs than fat dbs.

**Comment by olafurpg** [comment]
I took a stab at this in https://github.com/olafurpg/scalameta/commit/106808a4abd6500fad44e55dba7da62ab321ac40 but realized that our testing story for slim databases is still not good enough. I propose to postpone this for later milestone.

**Comment by xeno-by** [comment]
As per @olafurpg, this is no longer necessary.
