### ISSUE TITLE
allSurface

### ISSUE THREAD

**Issue by paulp** [scalameta/scalameta#890]
I knew class "" would be a problem.
```
scala> org.scalameta.explore.allSurface("com.cra.figaro") foreach println
error: Could not write class  because it exceeds JVM code size limits. Method <init>'s code too large!

```

**Comment by xeno-by** [comment]
`allSurface` and other members of `org.scalameta.explore` are parts of the internal API  that will be hidden in an upcoming refactoring. Please see https://github.com/scalameta/scalameta/issues/889 for more information.
