### ISSUE TITLE
Line wrapping for Syntax and Structure

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#892]
It would be nice to provide a linewrapping pretty-printer for both Structure and Syntax. I experimented with paiges https://github.com/typelevel/paiges and got promising results in only a few minutes https://gist.github.com/olafurpg/44ee2d0a8c5b8330702cf00d23d0978a To begin with, this could be a separate `paiges` module that implements `.show[PrettySyntax]` and `.show[PrettyStructure]`.

**Comment by DavidDudson** [comment]
I would use this all the time :+1: perhaps a prettysyntax method too

**Comment by olafurpg** [comment]
Agreed, `.prettysyntax` would  be handy. PrettyStructure is very easy to implement, the printer for that gist was implemented in one pattern match with 5-6 cases.

**Comment by olafurpg** [comment]
If someone wants to take a swing at this, here is a commit that sets up a new project with tests and a basic PrettyStructure implementation https://github.com/scalameta/scalameta/compare/master...olafurpg:paiges?expand=1#diff-294a43b421efb81603e0a1b510374b40R22

**Comment by DavidDudson** [comment]
Could we have the possibility of naming args for clarity.

Although the below is fairly trivial, in more advanced examples this would help me 

Eg.

```
Term.Select(
  qual = Term.Select(
                 qual = Term.Name("Foo"),
                 name = Term.Name("Bar")
  name = Term.Name("Baz"))
```

**Comment by olafurpg** [comment]
Sure thing! Good idea.

**Comment by olafurpg** [comment]
btw, in the ammonite-repl and with pprint it's possible to get line wrapping for free

```
import $ivy.`org.scalameta::scalameta:1.8.0`, scala.meta._
@ browse(dialects.Sbt0137(new java.io.File("build.sbt")).parse[Source].get) 
res9: Source = Source(
  List(
    Import(List(Importer(Term.Select(Term.Name("java"), Term.Name("io")), List(_)))),
    Import(List(Importer(Term.Select(Term.Name("scala"), Term.Name("util")), List(Importee.Name(Name.Indeterminate("Try")))))),
    Import(
      List(
        Importer(
          Term.Select(Term.Name("scala"), Term.Name("xml")),
          List(
            Importee.Rename(Name.Indeterminate("Node"), Name.Indeterminate("XmlNode")),
            Importee.Rename(Name.Indeterminate("NodeSeq"), Name.Indeterminate("XmlNodeSeq")),
            _
          )
        )
      )
    ),
    Import(
      List(
        Importer(
          Term.Select(Term.Select(Term.Name("scala"), Term.Name("xml")), Term.Name("transform")),
          List(Importee.Name(Name.Indeterminate("RewriteRule")), Importee.Name(Name.Indeterminate("RuleTransformer")))
        )
      )
    ),
    Import(
      List(
        Importer(
          Term.Select(Term.Select(Term.Name("org"), Term.Name("scalajs")), Term.Name("sbtplugin")),
          List(Importee.Name(Name.Indeterminate("ScalaJSCrossVersion")))
        )
      )
    ),
    Import(List(Importer(Term.Select(Term.Name("org"), Term.Name("scalameta")), List(Importee.Name(Name.Indeterminate("os")))))),
    Import(List(Importer(Term.Name("UnidocKeys"), List(_)))),
...
```

The output is also nicely syntax highlighted

![screen shot 2017-07-05 at 18 38 26](https://user-images.githubusercontent.com/1408093/27874843-4c0a11d8-61b1-11e7-818b-c49cb01b0b69.png)

**Comment by ShaneDelmore** [comment]
Great tip, thanks for sharing 👍

**Comment by olafurpg** [comment]
I've found pprint/ammonite to be sufficiently good for my debugging needs. I think we can close this ticket.
