### ISSUE TITLE
Expose scalametaSettings/scalametaScalacOptions with sbt-scalahost

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#894]
EDITED.

See comment below

**Comment by xeno-by** [comment]
So that would look something like the snippet below, right?

```
lazy val foo = crossProject
  .in(file("foo"))
  .enablePlugins(ScalametaPlugin)
```

**Comment by olafurpg** [comment]
Correct. Alternatively, I could make the ScalahostPlugin do nothing by default and let users enable it like this

```scala
lazy val foo = crossProject.settings(
  /// ...,
  scalametaSettings
)
```
That has the benefit that users can more easily enable the plugin in mass, for example by putting scalametaSettings in their `allSettings`.

**Comment by olafurpg** [comment]
I am leaning towards the second option now, this is the same approach as sbt-catalyst takes https://github.com/typelevel/sbt-catalysts  My experience is that many builds set `scalacOptions := ` somewhere which overrides the `projectSettings` defined by sbt-sclahost. Instead of relying on plugin loading order, we should provide a `scalametaSettings: Seq[Def.Setting[_]]` which gives power to the user to enable scalahost in a way that makes sense for that build. Additionally, this makes it easy for users to configure more advanced use-cases like "if scalahost is enabled, disable fatal warnings and enable -Ywarn-unused-import" (which makes sense for example in scalafix)

**Comment by xeno-by** [comment]
Looks much more robust than the current approach. How would a typical build configuration look like in this style?

**Comment by olafurpg** [comment]
Users would be responsible for adding `scalametaScalacOptions` (name up for debate) to their `scalacOptions`

```scala
scalacOptions ++= scalametaScalacOptions.value
```

The nice thing about this approach is that it makes it more transparent what's needed to enable scalahost. It's really just a few scalacOptions.

**Comment by xeno-by** [comment]
@dwijnand How would you advise to proceed here?

**Comment by dwijnand** [comment]
The downside is if you ever need to do more than add to scalacOptions (e.g define globalSettings, configurations, synthetic projects, whatnot) you have to re-educate the user. So principle of least power/YAGNI vs potential migration cost.. It's a gut call, there's no black-and-white advise here. 🙂

> My experience is that many builds set scalacOptions := somewhere

Ouch.. 😢

**Comment by olafurpg** [comment]
I think we will mainly provide a `scalametaSettings: Seq[Def.Setting[_]]` which appends scalametaScalacOptions to scalacOptions and adds to other settings like libraryDependencies. Then docs would recommend something like

```scala
lazy val myProject.settings(
  scalametaSettings,
  // blah
)
```
Power users (think sbt-scalafix) will still be able to use scalametaScalacOptions if they so prefer.

**Comment by xeno-by** [comment]
sbt-scalahost has been killed and so should this ticket.
