### ISSUE TITLE
Add Dotty implicit function to the parser

### ISSUE THREAD

**Issue by MasseGuillaume** [scalameta/scalameta#895]
https://scastie.scala-lang.org/XxaGpCRKRJqOpz2SZo0R5Q

work without instrumentation:

```scala
object B {
	trait A
	type X = implicit A => Int

  def main(arg: Array[String]): Unit = {
		println("hello")
  }
}
```

**Comment by b-studios** [comment]
Thanks @MasseGuillaume for following up on the issue! Minor, probably unimportant, remark: There is a typo in the issue title.

**Comment by xeno-by** [comment]
That'll be a great candidate for the upcoming Scala Center Open Source Spree: https://www.meetup.com/The-Copenhagen-Scala-Users-Group/events/239930806/.

**Comment by jonas** [comment]
Will take a look at support for this.

**Comment by jonas** [comment]
This should probably be added to the 1.9.0 milestone.

**Comment by olafurpg** [comment]
Good catch @jonas
