### ISSUE TITLE
Add support for Dotty enums

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#901]
https://github.com/lampepfl/dotty/blob/master/docs/docs/reference/adts.md

**Comment by jonas** [comment]
Docs was moved to https://github.com/lampepfl/dotty/blob/master/docs/docs/reference/enums/adts.md

**Comment by olafurpg** [comment]
After brainstorming with @allanrenucci on this ticket, here is our proposal.

- New token: `Token.Enum() extends Keyword`
- New Defn tree nodes:
```scala
Defn.Case(Name, Template) extends Stat with Member.Type
Defn.Enum(Mods, name: Name, Ctor.Primary, parents: Seq[Ctor.Call], Seq[Defn.Case]) extends Defn with Member.Type
```

- Defn.Enum is used for plain `enum` (not `enum class`) like here

```scala
@annot enum Foo(x: Int) extends Bar {
  case Baz, Qux
  case Mux extends Foo() {
    def bar
  }
  // any other statement than Defn.Case is not allowed.
  def foo = 2 // ERROR
}
```

- A new modifier, `Mod.Enum()`, which is used for "enum class", are regular `Defn.Class`

```scala
// enum class is a Defn.Class just like case classes
enum class Foo(x: Int) // Defn.Class(List(Mod.Enum()), Foo, ...)
```

- Up for debate: should the parser validate Defn.Case in these cases?

```scala
// 1.
// case in companion of enum class must "extends"
enum class Foo
object Foo {
  case Bar extends Foo // OK
  case Buz // Error
}

// 2.
// comma separated cases cannot have templates or ctors
enum Foo {
  case Bar(x: Int), Buz           // Error
  case Muz[T], Buz                // Error
  case Baz extends Maan, Buz      // Error
  case Baz { def hello = 1 }, Buz // Error
  case Baz { def hello = 1 }      // OK
}
```

**Comment by xeno-by** [comment]
1) How does one model a template for an enum class, e.g. in `enum Option[+T] { case Some[+T](x: T); case None }`? This doesn't seem to be included in the proposed data model.

2) I don't think we can validate `extends Foo` in the parser. This requires name resolution, right?

3) `comma separated cases cannot have templates or ctors`. This looks validatable, so I'd prefer we handled this early.

**Comment by olafurpg** [comment]
1. plain enums don't have templates, early initializers are not supported, self annotations and non-Defn.Enum statements are not allowed in the template body. 
2. I was thinking of requiring at least one parent inside the companion, no naming resolution required
3. sounds good

**Comment by xeno-by** [comment]
1. Oh wait, I just realized that you're proposing to have both `Defn.Enum` and `Mod.Enum`. Why's that?

**Comment by allanrenucci** [comment]
`Mod.Enum` is for `enum class` as they seem to parse like normal case classes. `Defn.Enum` however can only contain `Defn.Case`

**Comment by xeno-by** [comment]
Ah I see. This makes sense.

**Comment by xeno-by** [comment]
Please wait a little bit before working on this. I'd like to get https://github.com/scalameta/scalameta/pull/907 in first.

**Comment by allanrenucci** [comment]
I am not sure about the actual proposal for `Defn.Case`. `Defn.Case` are just like classes. They can have modifiers, type parameters and constructors.
Should we represent them as a modifier on `Defn.Class` (and `Defn.Object` when there is no constructor)?

**Comment by MasseGuillaume** [comment]
The syntax might change a bit: https://github.com/lampepfl/dotty/pull/4003

**Comment by olafurpg** [comment]
After discussions with @allanrenucci and @samuelchassot we came to this design for the current Dotty enums:

```scala
object Defn {
  // Identical to Defn.Class except `.templ.stats` can contain `Enum.Case` and `Enum.RepeatedCase`
  @ast class Enum(mods: List[Mod],
                  name: Type.Name,
                  tparams: List[Type.Param],
                  ctor: Ctor.Primary,
                  templ: Template) extends Defn with Member.Type
  object Enum {
    @ast class Name(value: Predef.String @nonEmpty)
      extends scala.meta.Name with Term.Ref with Member.Term
    // example:
    // enum Try {
    //   case Success(value: String)
    //   case Failure(e: Throwable)
    // }
    @ast class Case(mods: List[Mod],
                    name: Term.Name /* not Type.Name because only companion is visible */,
                    tparams: List[Type.Param],
                    ctor: Ctor.Primary,
                    inits: List[Init]) extends Defn with Member.Term {
      checkFields(
        parent.isEmpty || {
          val p = parent.get
          p.is[Template] && (p.parent.isEmpty || p.parent.get.is[Defn.Enum])
        }
      )
    }
    // example:
    // enum Color {
    //   case Red, Blue, Green
    // }
    @ast class RepeatedCase(mods: List[Mod], cases: List[Enum.Name]) extends Defn {
      checkFields(
        parent.isEmpty || {
          val p = parent.get
          p.is[Template] && (p.parent.isEmpty || p.parent.get.is[Defn.Enum])
        }
      )
    }
  }
}
```

@samuelchassot will work on this ticket over the coming weeks.

Currently, it's very un-ergonomic to extend the parser because every change requires recompiling semanticdb-scalac resulting in >1 minute turnaround times for tweaking the parser. 

To make it faster to iterate on parser changes I created a new repository https://github.com/scalameta/trees that contains only the syntactic APIs. The repo is a fork of the main repo and only removes the SemanticDB-related tests. All source files are located in the same location as in the main repository.
