### ISSUE TITLE
Add support for Dotty named type arguments

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#903]
https://github.com/dotty-staging/dotty/blob/e9d87e0dc3f270b3a603267c50b8d7ca66272263/docs/docs/reference/named-typeargs.md

**Comment by olafurpg** [comment]
Push this back one milestone?

**Comment by kpbochenek** [comment]
As explained by dotty guys this feature won't be done in scala3
https://dotty.epfl.ch/docs/reference/other-new-features/named-typeargs.html
