### ISSUE TITLE
DOS-style line endings

### ISSUE THREAD

**Issue by raboof** [scalameta/scalameta#911]
When running sbt-scalahost 1.8.0 on akka I get:
```
[error] failed to generate semanticdb for /home/aengelen/dev/akka/ak
ka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala:
[error] java.lang.IllegalArgumentException: [705..704) in Input.Labe
ledString("akka-stream/src/main/scala/akka/stream/impl/FanoutProcess
or.scala",
```

This seems to be caused by the fact that this file for some reason has DOS-style line endings (CRLF) instead of unix-style (LF). I'll try and create a minimal reproduction on scalameta master, but wanted to record this already in case I don't get to it any time soon.

**Comment by xeno-by** [comment]
Looks related: https://github.com/scalameta/scalameta/issues/443

**Comment by xeno-by** [comment]
Closed in favor of https://github.com/scalameta/scalameta/issues/443.
