### ISSUE TITLE
Persist ResolvedName for Importee.Wildcard

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#925]
See https://github.com/scalameta/scalameta/blob/a3b8b1f8c7fc7b75d6ea0663e5f3a39555fa574e/scalameta/semantic/shared/src/main/scala/scala/meta/semantic/Api.scala#L33

I would be nice if it returned instead a Symbol.Multi with all the symbols behind that import. For extra credit, it would be nice if it only returned *used* symbols in the compilation unit (cc/ https://github.com/scalacenter/scalafix/issues/182)

**Comment by xeno-by** [comment]
Is there an easy way to find out the used symbols without doing `-Ywarn-unused-import`?

**Comment by olafurpg** [comment]
I think it's fine to require users to enable `-Ywarn-unused-import`, like we do with RemoveUnusedImports https://scalacenter.github.io/scalafix/#RemoveUnusedImports

It seems only import selectors are tracked https://github.com/scala/scala/blob/ff57fa8cfaa54dd2493cdddc277cc43fcab09c88/src/compiler/scala/tools/nsc/typechecker/Contexts.scala#L58 not individual used symbols. Is there another way to see which symbols are used in a compilation unit?

**Comment by xeno-by** [comment]
I think we can just traverse the AST of the entire unit, taking note of symbols that are used there.

**Comment by olafurpg** [comment]
I think that approach won't handle macros, unless you have some magic trick up your sleeve to track used symbols in macros :) I also recall that special care needs to be take for annotations and some type tree nodes.

**Comment by xeno-by** [comment]
Of course, there is a trick :) Every macro expansion has a special attachment that holds a reference to a typechecked expandee.

**Comment by olafurpg** [comment]
Sounds like a deal. This would make it possible to expand wildcard imports into explicit imports, which could have a good impact on compiler performance.

**Comment by xeno-by** [comment]
@olafurpg Is this still relevant?

**Comment by olafurpg** [comment]
Nope
