### ISSUE TITLE
Publish testkit for scala.js

### ISSUE THREAD

**Issue by LMnet** [scalameta/scalameta#938]
At the moment there is no testkit for scala.js. As a temporary workaround I just copypasted classes from testkit project to my scala.js project, but it would be convenient to have testkit cross-published.

**Comment by olafurpg** [comment]
Thank you for reporting! This should be doable. Testkit uses some JVM specific code to download and unzip. However, it should be possible to move that to the `jvm/` directory. Would you be interested in contributing this fix @LMnet ?

**Comment by LMnet** [comment]
I can try, but I'm playing with scalameta only with my pet project in free time, so I can't promise anything.
About implementation: as far as I understand, `AnyDiff`, `Observation`, `Phase`, `StructurallyEqual` and `SyntaxAnalysis` could be cross-published. `Corpus`, `CorpusFile`, `FileOps` should be moved to the jvm-specific folder. Am I right?

**Comment by olafurpg** [comment]
That sounds about right @LMnet .

**Comment by xeno-by** [comment]
@olafurpg @LMnet Guys, is this ticket still relevant?

**Comment by LMnet** [comment]
@xeno-by I'm not sure I will have time for this issue in the near future.

About relevance - in my project, I still have a copy-pasted testkit. I'm not sure how many scala.js projects uses scalameta, but overall it looks like this task is pretty useful.

**Comment by olafurpg** [comment]
This is a several minute effort to separate out the JVM-only parts in to the `jvm/` directory so I propose we keep this issue and I will complete it once I have some time to kill
