### ISSUE TITLE
Add Database to semanticdb.proto

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#943]
Currently, the top-level message in semanticdb.proto is `Attributes`. This makes it complicated to represent a `Database(entries: Seq[Attribute])` as `Array[Byte]`. It would be nice if there was a Database message
```proto
message Database {
  repeated Attributes entries = 1;
}
```

to match `scala.meta.Database`.

**Comment by xeno-by** [comment]
Following the introduction of `s.Attributes.filename` and fat databases, this suggestion further highlights the fact that our storage layer is torn between partially incompatible use cases. 

I don't mind any of these use cases per se (in fact, I was quite enthusiastic about fat databases, suggesting that they become a default), but I think it would be useful to document these use cases somewhere to see whether we can make our schema and/or implementation more consistent.

**Comment by olafurpg** [comment]
The use-case I had here was for sbt-messagehost, where the messages don't necessarily come in the correct order per compilation unit. There are two phases, one phase where we get callback when the compiler reports diagnostics and one final "printSummary" phase where we aggregate the collected messages and build a single Database. It would be nice to be able to persist that database somewhere as a single Array[Byte] blob (e.g., `META-INF/semanticdb/messagehost.database` )

This brings me to another idea I had today, should we perhaps use `.attributes` as a suffix instead of `.semanticdb`? Just an idea, haven't thought it out much.

**Comment by xeno-by** [comment]
Would it be possible to split the `messagehost.database` into a bunch of per-compilation unit `.semanticdb` files?

Re the file extension: I like it primarily because of branding reasons (though the name "semantic db" itself is used in several software projects already). In comparison, `.attributes` feels generic. If we're talking about alternatives, we could start saying `.scalametadb` (results of googling are very favorable to us).

**Comment by olafurpg** [comment]
Re: file extension. I'm in favor of `.scalametadb` and I think those files should contain `s.Database` bytes instead of `s.Attributes`. Then we avoid the need for multiple file extensions, and I believe we pay only a single byte extra to represent them as `List[s.Attributes]` instead of `s.Attributes`.

**Comment by olafurpg** [comment]
It turns out this will be useful for sbthost because of how sbt encodes .sbt files. A single .sbt file is split into multiple compilation units. A protobuf s.Database would allow us to persist s.Attributes for all those compilation units in a single .semanticdb file.
