### ISSUE TITLE
Include Mirror.sourcepath and Mirror.classpath.

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#944]
It's necessary to provide a sourcepath and classpath to load a Mirror. However, once loaded, the sourcepath and classpath are not accessible from a `Mirror` instance. It would be helpful in scalafix to be able to get the original classpath from a `Mirror`. The particular use-case I have in mind is to be able to compile the Mirror sources with Dotty.

**Comment by olafurpg** [comment]
To elaborate, semantic scalafix rewrites take `Mirror` as an argument. Inside my rewrite, I would like to be able to query that `Mirror` for the dependency classpath that was used to compile `Mirror.sources`. It would be nice to also have scalac options (although compiler plugins will be tricky). I would use the dependency classpath to programmatically re-compile `Mirror.sources` with the Dotty compiler.

**Comment by olafurpg** [comment]
It seems what I'm asking for is to regain some of the old `online.Mirror` capabilities. The use-case is not for typechecking quasiquotes but instead to programmatically create new mirrors with parameters like

- sources: Sourcepath
- dependencyClasspath: Classpath
- compilerArgs: List[String]

This would be very powerful for scalafix in order to re-run the compilation on the fixed output.

**Comment by xeno-by** [comment]
After today's chat, the consensus is to experiment with saving Scalac compiler settings to `META-INF/semanticdb/whatever`. Since this feature may leak private info, it should be an opt-in.

**Comment by olafurpg** [comment]
Mirror.sourcepath would be useful for sbthost. It would be helpful when finding the original Input.File from Input.LabeledString.

**Comment by xeno-by** [comment]
Closed in favor of https://github.com/scalameta/scalameta/issues/880.
