### ISSUE TITLE
Add productFields on Trees

### ISSUE THREAD

**Issue by gabro** [scalameta/scalameta#948]
As discussed on gitter, it would be really cool to access all the fields of a tree.

We already have `productPrefix` which enumerates the values, but there's no way of enumerating the names of the fields.

Ultimately the idea would be to have enough pieces to expose a `toMap` that returns a `Map[String, Tree | Seq[Tree]]` (yeah, I know, no unions in Scala yet, but clarity). For example, given

```scala
1 + 2
```

the resulting tree would be

```scala
Term.ApplyInfix(
  lhs = Lit.Int(
    value = 1
  ),
  op = Term.Name(
    name = "+"
  ),
  targs = Seq(),
  args = Seq(
    Lit.Int(
      value = 2
    )
  )
)
```

then the `toMap` function applied to the top-level Tree would return

```scala
Map(
  "lhs" -> Lit.Int(1),
  "op" -> Term.Name("+"),
  "targs" -> Seq(),
  "args" -> Seq(Lit.Int(2))
)
```

With that, one could recursively apply `toMap` to the structure and add more metadata (e.g. the `type`), ending up with a serializable representation of a tree.

```scala
Map(
  "type" -> "Term.ApplyInfix",
  "lhs" -> Map(
     "type" -> "Lit.Int",
    "value" -> 1
  ),
  "op" -> Map(
    "type" -> "Term.Name",
    "name" -> "+"
  ),
  "targs" -> Seq(),
  "args" -> Seq(
    Map(
      "type": "Lit.Int",
      "value": 2
    )
  )
)
```

As I'm writing this, I think it would probably be cool to have a `serialize` method that does this, perhaps provided by `contrib`.

Thoughts?

**Comment by DavidDudson** [comment]
We could also use this to generate prettyStructure from this.

**Comment by xeno-by** [comment]
@gabro How has your prototype evolved? Have your requirements changed in the last few days?

**Comment by gabro** [comment]
no, they're essentially the same. It would still be very useful to access the names of the fields of a Tree, so to zip them with the values.

**Comment by xeno-by** [comment]
Would you consider contributing this functionality? I'm quite overwhelmed at the moment by the end-of-quarter stuff.

Here's where I'd add synthesis of the `productFields` method: https://github.com/scalameta/scalameta/blob/master/scalameta/common/shared/src/main/scala/scala/meta/internal/ast/ast.scala#L168. I'd obtain the labels for `productFields` from `fieldParamss`.

**Comment by gabro** [comment]
Yup, I tried something like that today, but I had an hard time debugging it and I couldn't get very far. I'll try again and see what I can do :)

**Comment by xeno-by** [comment]
Please let me know where you get stuck. I'll be happy to help.

**Comment by gabro** [comment]
Yay, I have something that appears to be working :) @xeno-by as soon as you have time: https://github.com/scalameta/scalameta/pull/956
