### ISSUE TITLE
Database.map/filter/collect

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#964]
I experience regularly that I want to slightly modify a Database. Currently, you need to do something like `db.copy(entries = db.entries.map/filter/collect)`. It would be nice if filter/map/collect were methods on Database to do the same.

```scala
// before
db.copy(entries = db.entries.map(_._2.copy(denotations = Nil)))
// after
db.map(_._2.copy(denotations = Nil))
```

**Comment by olafurpg** [comment]
I opened #998 making Database extend Seq[Attributes], feedback is welcome.

**Comment by xeno-by** [comment]
Closed in favor of https://github.com/scalameta/scalameta/issues/880.
