### ISSUE TITLE
Add new logo to the website

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#969]
Here's some initial work recently done by @olafurpg: https://github.com/scalameta/scalameta/pull/916.

**Comment by olafurpg** [comment]
http://scalameta.org/ doesn't use the scalatex-readme side panel so we can switch to any basic landing pages css/html template. Scalatex is just nice syntax for scalatags that generates plain vanilla html. I think this landing page is really slick http://frees.io/ We could try to do something similar with bootstrap.

**Comment by olafurpg** [comment]
Our landing page now has the logo :)
