### ISSUE TITLE
Rename the scalahost plugin

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#971]
The name "scalahost" has repeatedly proven to be confusing to newcomers. We should call our compiler plugin "semanticdb", since that is much clearer.

**Comment by olafurpg** [comment]
I'm not convinced this is a good idea. What should sbthost, dottyhost and intellijhost be named then?

I agree it appears to be confusing for new users, but that should be solvable with better docs http://scalameta.org/tutorial/#Scalahost

**Comment by ShaneDelmore** [comment]
How about sbtSemanticdb, dottySemanticdb, and intellijSemanticdb?

**Comment by olafurpg** [comment]
I think we should postpone this discussion for after 1.9.

**Comment by xeno-by** [comment]
Fair enough.

**Comment by xeno-by** [comment]
@olafurpg I suggest we revisit this. Since the beginning of the previous week, I'm repeatedly explaining people what scalahost is, and it's getting fairly old. 

I think that by sticking to the old name we increase the number of concepts we need to introduce to people without getting any value in return. We're getting more and more users, so it would be helpful if our onboarding process was easier.

**Comment by ShaneDelmore** [comment]
Agreed.  I looked at the doc link @olafurpg to see if reading the docs would answer the question.  Reading the name Scalahost I parse it as two words, “scala” and “host”.  Is it hosting scala?  Is scala hosting something?  I just can’t pull any meaning out of it.  Reading the docs doesn’t give me much more, but beyond that if someone is reading a list of dependencies I don’t want them to have to google each name to understand if it is even related to what they are searching for.  

Even a name like semanticHost or metaHost would at leave give an idea of what it is for, but the word scala adds no meaning as anyone looking at a scala plugin already knows scala is involved, so they are left with the word host alone to convey meaning which just doesn’t seem like enough.

When I see sbt-docker I immediately know this plugin must help sbt interact with docker, and if I am not investigating sbt to docker interaction I will immediately disregard it, which I think is valuable.

How could we do the same for Scalahost?

**Comment by olafurpg** [comment]
Just upgraded to 2.0.0-M2 in scalafix and wanted to report that I like `semanticdb-scalac`, despite it being quite verbose. Fixed in #1055
