### ISSUE TITLE
Shorthands for certain ASTs

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#972]
Certain ASTs that stand for simple syntactic constructs are annoyingly verbose. Examples:
  * `Self(Name.Anonymous(), None)`
  * `Ctor.Primary(Nil, Name.Anonymous(), Nil)`
  * `Template(Nil, Nil, Self(Name.Anonymous(), None), Nil)`
  * `Init(tpe, Name.Anonymous(), Nil)`
  * `Name("")`

It may be beneficial to provide shorthands for such ASTs, so that they are less annoying to write, e.g. `Ctor.Primary()` or `Template()`. 

On the flip side, these shorthands are only going to work for construction, not for deconstruction, which is unsatisfying.

@olafurpg @DavidDudson Please discuss.

**Comment by ShaneDelmore** [comment]
What about using named parameters to make the constructs less annnoying to write by having defaults for the files that are commonly unused?

**Comment by xeno-by** [comment]
Unfortunately, this is also unsymmetric, because we can't use default arguments in patterns.

**Comment by olafurpg** [comment]
Named pattern matching would be awesome, with other fields becoming `_`. I'm in favor of simplifying the ctors with default values, even if it means asymmetry with patterns. In patterns, it's still possible to `t: Template` match.

**Comment by olafurpg** [comment]
I have changed my mind. I think symmetric apply/unapply is fantastic guideline for designing a consistent tree api. I'm OK with closing this ticket.
