### ISSUE TITLE
Scalahost and scalameta/paradise are incompatible

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#979]
I tried to run scalahost on the scalafix codebase which uses scalameta/paradise and I got many errors like this

```scala
org.scalameta.paradise.typechecker.HijackAnalyzer$$anon$2
[error] failed to generate semanticdb for /home/geirsson/scalafix/scalafix-core/shared/src/main/scala/scalafix/util/package.scala:
[error] java.lang.RuntimeException: the compiler instance must use a hijacked analyzer
```

Scalahost managed to persist semanticdbs for several files in the core module, but then started crashing. I suspect it's caused by incompatibility with scalameta/paradise.

**Comment by xeno-by** [comment]
@olafurpg Is this still relevant for you?

**Comment by olafurpg** [comment]
It's not, I don't use paradise in scalafix anymore.
