### ISSUE TITLE
Fix checkCLA

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#993]
Our checkCLA.sh script is broken, but the fix is actually pretty easy: https://github.com/xeno-by/scalamacros/blob/master/bin/checkCLA.sh.

**Comment by xeno-by** [comment]
@olafurpg Since you were looking into our build recently, can you take care of this one too, please?

**Comment by olafurpg** [comment]
Here you go @xeno-by https://github.com/scalameta/scalameta/pull/1019 I borrowed the script from Scala Native and it seems to do the check now.

**Comment by olafurpg** [comment]
Fixed in #1019
